### ISSUE TITLE
Windows 11 22H2 Dualscreen not supported

### ISSUE THREAD

**Issue by xShinChanx** [ChrisAnd1998/TaskbarX#1004]
**Describe the bug**
When I start my laptop I get a pop-up message saying taskbarx may not support this version of windows. This started happening after I updated to Windows 22H2. When I'm using my laptop with a dual screen and click on the start button the taskbar changes back to default

**To Reproduce**
1. Update to the latest version of windows (Windows 11 22H2)
2. Restart your device.
3. Use a dual-screen setup
4. Click on the start icon. you will see the taskbar changing to windows default taskbar

**Expected behavior**
When I click on the windows icon I expect my taskbar to remain with the same settings as what I've chosen in taskbarx configurator.

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Version [22H2]

**Additional context**

**Comment by ifelixculpa** [comment]
following this issue on 22H2 , hope dev fixes it soon

**Comment by chucktheviking** [comment]
Can confirm issue with Win11 22H2

**Comment by jakethesnake2004** [comment]
Can confirm, updated last night to Win 11 Pro 22H2 and same issue as op w/ latest version of TaskbarX as of today.

**Comment by api-was-taken** [comment]
Please fix

**Comment by ChrisAnd1998** [comment]
I have noticed the issue and will try to fix it asap.

**Comment by Caluminac** [comment]
Since updating to Windows 11 22H2, taskbarx doesn't work anymore, it doesn't go transparent. I have downloaded the latest version of the rainmeter skin 1.7.8.0 but everytime i check it on rainmeter is says 1.7.6.0
