### ISSUE TITLE
Startup icon scale issue

### ISSUE THREAD

**Issue by D-Maxwell** [ChrisAnd1998/TaskbarX#1022]
**Describe the bug**
The startup icon in the top right corner of the startup tab has its light dots unevenly centered. Indeed, the rightmost one is off by a single pixel.

**Screenshots**
![image](https://user-images.githubusercontent.com/98100481/204888093-1e51c345-30d4-4849-8367-20ae68815efc.png)
![image](https://user-images.githubusercontent.com/98100481/204888438-5dde104b-9d2f-4898-a237-42c24b935b82.png)

**Comment by unrealest** [comment]
I'm pretty sure this is a problem on Microsoft's end, they made the emoji font. Correct me if I'm wrong
