### ISSUE TITLE
Clicking the "Show Desktop" button at the very right of the screen does nothing.

### ISSUE THREAD

**Issue by SoCuul** [ChrisAnd1998/TaskbarX#1023]
**Describe the bug**
Whenever the "Show Desktop" button is clicked at the furthest point on the right, it does nothing. If I move slightly to the left, the action happens as usual.

**To Reproduce**
1. Click the "Show Desktop" button at the very edge of the screen.

**Expected behavior**
It should show the desktop, but this only ends up happening if I click slightly a little to the left.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 21H2

**Comment by SoCuul** [comment]
Bump

**Comment by dominsights** [comment]
Last fix in this repository was 1 year ago. I think you can assume it is dead.

**Comment by SoCuul** [comment]
Bump
