### ISSUE TITLE
Windows Defender blocking TaskbarX

### ISSUE THREAD

**Issue by DevVali** [ChrisAnd1998/TaskbarX#1040]
Hi, I tried to install TaskbarX thru the ZIP folder, however, Defender did not allow me to, since it blocked from opening TaskbarX. Is TaskbarX a secure app I can install without putting my device to any risks? @ChrisAnd1998

**Comment by KalphosZeromar** [comment]
Been a taskbarX user for quite a while now and it has been nothing but gold I can assure you that as long as you install from an official source it should be safe
