### ISSUE TITLE
Paid?

### ISSUE THREAD

**Issue by Nou4r** [ChrisAnd1998/TaskbarX#1078]
Why is it paid on the Microsoft Store but its open source / freeware on here?

**Comment by haruki-taka8** [comment]
Copied directly from the [FAQ section](https://github.com/ChrisAnd1998/TaskbarX/blob/master/README.md):

> **Whats the difference between the normal version and the store version?** The store version is exactly the same as the normal/free version. It's a donation sytem. The store version does give you the benefit of automatic updates and easy installing.
