### ISSUE TITLE
📌 | Please avoid opening duplicate issues, thanks 😁

### ISSUE THREAD

**Issue by ChrisAnd1998** [ChrisAnd1998/TaskbarX#108]

**Comment by yashpalgoyal1304** [comment]
How to search for existing issues:
- go to https://github.com/ChrisAnd1998/TaskbarX/issues?q=is:issue+
- use the search field as shown below
- try searching with 2-4 times with different terms if u dont find the issue

![avoid duplicates I1tr5QmqiR](https://user-images.githubusercontent.com/19423063/132117501-c2b1f97d-88b1-4518-a75d-d6b845594e6a.png)

**Comment by yashpalgoyal1304** [comment]
hi @ChrisAnd1998 can u please add the above instruction set in the description/first comment of this issue to aid with its reference in https://github.com/ChrisAnd1998/TaskbarX/pull/789/ ??
