### ISSUE TITLE
Error message on startup after uninstall

### ISSUE THREAD

**Issue by B2TheMonkey** [ChrisAnd1998/TaskbarX#1087]
Hello I am having an issue where I get an error on startup "get an app to open this taskbarxi link. I originally installed it via the Microsoft store. Uninstalled through the configurator as the instructions showed. Restarted my PC after and get this error. I did a quick search and found that there is a schedule that is usually left behind. Searched through task scheduler and found nothing. Any help would be appreciated.

**Comment by floriandevo** [comment]
Same problem.
Reinstall from Microsoft Store. Into configurator panel remove schedule. Uninstall from configurator. Wait few minute. Restart the computer. Work for me (W11) !

**Comment by B2TheMonkey** [comment]
Your meaning the remove startup button at the bottom of the configurator?

**Comment by B2TheMonkey** [comment]
Thanks for the help. Seems obvious now. Seems to have worked.

**Comment by B2TheMonkey** [comment]
Thanks. Seems to have worked
