### ISSUE TITLE
Active window icon has dark background

### ISSUE THREAD

**Issue by Martin5001** [ChrisAnd1998/TaskbarX#118]
![taskbar](https://user-images.githubusercontent.com/35201200/71115266-d6921200-21d1-11ea-80f6-99b960551c6d.png)

**App version:** 1.3.5.0 (but I think it occured on some older version (1.3.x.x) too.)
**Possible cause:** Tablet mode - taskbar autohide
(I thing this bug sometimes occured even in the desktop when the tablet mode was not involved, but I am not 100% sure about this.)

**How to reproduce:**
1. detach the keyboard so the tablet mode is toggled on
2. set taskbar to auto hide in tablet mode
3. pull on form the bottom to show now hidden taskbar and then white for it to hide automatically again
4. turn off taskbar autohide
5. attach the keyboard back

**Comment by Cabola** [comment]
I have this and have always had this in normal mode. No matter which monitor it is, the active windowses taskbars icon has a dark background. I've just learned to live with it, because I never could find any way to get rid of it and only keep the bottom border.

**Comment by ChrisAnd1998** [comment]
What happens if you enable transparancy in Windows Settings?

Search for "color settings" in Settings and then under "more options" enable "transparency effects"
