### ISSUE TITLE
Feature Request - Hide taskbar labels without combining icons

### ISSUE THREAD

**Issue by AzimsTech** [ChrisAnd1998/TaskbarX#124]
I'd love to see this feature implemented. 

![img](https://i.imgur.com/4U4vLUB.png)

**Comment by Martin5001** [comment]
By the way, I noticed that source code of the app @AzimsTech mentioned is on [GitHub](https://github.com/m417z/7-Taskbar-Tweaker) . But I haven't looked at it any further, just to let you know.
