### ISSUE TITLE
Settings UI Concept

### ISSUE THREAD

**Issue by Martin5001** [ChrisAnd1998/TaskbarX#131]
Maybe now when Settings are separate, it might be a good opportunity to make some improvements.
I just made a quick mockup using Fluent design guidelines to fit into Windows 10 design. (I didn´t finish the top section with the logo, but imagine it´s there.)

![falconx-fluent](https://user-images.githubusercontent.com/35201200/71527911-b3581880-28dd-11ea-80e6-6943f14d448a.png)
(The "Stop" dropdown contains the "Restart" option. The "Secondary position offset" would grey out when "Use only on primary taskbar" is toggled on - and thus the secondary settings is not used or needed. By using the dropdown for "Taskbar style" options you make one dropdown out of four buttons - so more free space. Also I´ve change "Save" to "Save settings" because it sounds better to me but that´s only my opinion.)

(Controls are taken from [XAML Controls Gallery - Windows Store](https://www.microsoft.com/cs-cz/p/xaml-controls-gallery/9msvh128x2zt#activetab=pivot:overviewtab))

This could be achieved using:

- UWP with these controls built-in (probably not the best option)
- ~XAML islands to host UWP controls inside current WinForms window (requires Windows 10 1903)~ .NET Core only
- 3rd party / custom WinForms controls
- React/Electron - (#50 - now CPU usage shouldn´t be a problem as settings would not run with the main process and every PC capable of running Windows 10 will have enough resources to run it.)
- maybe there is some other option I don´t know about

**Comment by ChrisAnd1998** [comment]
Yep, i totally agree. I have coincidentally been trying FluentXAML yesterday but, didn't come to far because, i am totally new to XAML and WPF. XD

**Comment by ChrisAnd1998** [comment]
As you can see i changed the layout in 1.4.0.0 to get more space. Eventually when Win-UI comes to winforms i will make it look like the concept. Currently WPF is a big pain compared to winforms so currently i want to stay with that.

**Comment by Martin5001** [comment]
I understand that. I also tried to learn WPF once but went away from it. I don´t know anything about WinUI should be on WinForms too. But maybe you have found some information on that? (I always thought it is either on UWP or XAML Islands only, but not as a native part of WinForms or WPF.)

(Also there is a small bug that tab controls are visible (partially) on top of the window. So I guess you used tab controls for the navigation but did not hide/replace it with the left buttons entirely.)

**Comment by ChrisAnd1998** [comment]
@Martin5001  Yeah, the new Windows UI is not yet available for winforms but, i read that they are working on it.

I left the tabcontrol visible because, it's a testing build i will patch it up when i release it.
I need it, to switch tabs in the form designer.
