### ISSUE TITLE
[Petition] Taskbar Over maximized window

### ISSUE THREAD

**Issue by johnnydement** [ChrisAnd1998/TaskbarX#136]
FalconX works superb, congratulations!

I've got a petition, would be possible to get taskbar to appear over maximized windows?

That way we could have a proper dock, even mimic elementary OS top bar appearance ;)

Best regards

**Comment by ChrisAnd1998** [comment]
I'll look into it. I think it would be possible to force the taskbar to be "topmost" making it on top of everything.
