### ISSUE TITLE
Two suggestions and a bugreport

### ISSUE THREAD

**Issue by swsegdan** [ChrisAnd1998/TaskbarX#141]
1. Add a button to start FalconX from the settings tool. At the moment, if you start the settings tool before the actual app, there is no way to launch FalconX without using Explorer.

* Also: If you press "Restart" when FalconX is not started, you get an error.

2. Add a tray Icon

**Comment by ChrisAnd1998** [comment]
I'll look into it. I finally got rid of the tray icon in update 1.3.6.0 though 🙄

**Comment by swsegdan** [comment]
I liked having the tray icon available for convenience when it came to quickly opening settings. Make it toggable with a "Show tray icon" flag?

**Comment by ChrisAnd1998** [comment]
I think it would be possible to have an option that if it's enabled FalconX will host a tray icon. And just launch the settings window with that.

Basically making the tray icon a optional feature because, it's 50/50 that people prefer a tray icon or just completely hidden.

**Comment by Cabola** [comment]
FYI when you start the "falconx settings.exe" the "falconx.exe" is also launched, it's just running under the settings process, once you hit the close button "falconx.exe" moves out as it's own process and "awakens". You can see this by having the task manager running at same time and look at the background processes

I'd also love to have the tray icon back, make it easier to see when the program is actually still running.

**Comment by user00101010** [comment]
I love the current implementation with tray hidden and the settings menu in start

**Comment by ChrisAnd1998** [comment]
@user00101010  Yes, i am very happy i made the change 👌😁
