### ISSUE TITLE
App promotion possibility

### ISSUE THREAD

**Issue by Martin5001** [ChrisAnd1998/TaskbarX#142]
I recently came across this article on  [onmsft.com](https://www.onmsft.com/news/microsoft-launches-new-bing-pages-for-businesses-and-personalities) talking about Microsoft currently testing an option for brands to show their "profiles" in Bing search. More on that can be found at MS website here: https://www.bing.com/bp/gettingstarted
This could bring some new users, and it is free (Afaik, I haven´t tried it myself but it looks there are no requirements except the twitter account they mention.)

**Comment by ChrisAnd1998** [comment]
Could be interesting :) I'll look into it tomorrow.
