### ISSUE TITLE
Important feature suggestion

### ISSUE THREAD

**Issue by neoOpus** [ChrisAnd1998/TaskbarX#145]
Hi Chris,

Finally, I found someone who is focusing on Taskbar... I was looking for a solution to the major annoyance that dates back to Windows 95 which is the auto hide feature that is unreliable... I've found few years ago a pseudo-fix but unfortunately this was developed in the 90s and the developer passed away... 

Taskbar Activate (http://pmdevigne.free.fr/TaskbarActivate.html) is the name of the software and what it does is quite simple, it allows to show the taskbar when needed (mostly when you have full screen apps the auto hide feature is by default broken) and it also allows forcing hiding the taskbar (properly via windows API) when it is stuck and you just want to get rid of it to be able to see what is behind it like photoshop systray... 

I also found a solution about how to make the blue line created by Taskbar Active hidden once of all that I can provide the detail about if required later (it is a sort of hack but a lucky one)...

I hope this makes sense and I invite you to test the software... this makes the taskbar controllable in all different scenarios but it would be great if you get it reverse engineered and implanted into FalconX or maybe create another software that can do the same but more elegantly...

Thank you.

**Comment by Martin5001** [comment]
Related: #122

**Comment by Martin5001** [comment]
I know Microsoft has terrible approach on user feedback, but maybe if we wrote a detailed report to them they could (and should) fix it finally. Do you think there is a way to contact them directly?

**Comment by ChrisAnd1998** [comment]
Sorry for the late response! I will have to do some testing on this.

**Comment by neoOpus** [comment]
I can provide more details about how I sort of solved this annoying issue.... but I think you are the best to find an elegant fix for it, since MS knew about it decades ago and didn't manage to provide any solutions, that's why most users opt to keep the taskbar on screen all the time even if it consumes some real estate (pixels)... I see that you have the set of tools that are needed to reverse engineer that nice piece of software...

I also used Process Hacker (task manager) to make the blue line disappear completely as stated already and what is wonderful is that it stick and work seamlessly without any further intervention later... still I wish if I have your skills to develop something that is more neat and do some more features... 

I did contact MS and some other taskbar related projects' dev but none really managed to come to help while this for sure can be the best thing to do for Taskbar for a broad range of users (gamers, designer, browsers, ...)

**Comment by ChrisAnd1998** [comment]
@neoOpus Currently having a very busy week due to the new year but, i will defenitly look into this in a couple hours or tomorrow ;)

**Comment by ChrisAnd1998** [comment]
@neoOpus So what you basically want is the functionality of "Taskbar Activate" but, then without the blue bar at the bottom?

**Comment by neoOpus** [comment]
Hi,

Sorry for the delay, I didn't see the updates and your last question, yes actually I am using TaskbarActivate and I managed via a hack (discovered by myself) to make it work without the blue line nor taking any pixel on the screen which make full-screen experiences work fine without any difference... but I was trying to find someone who is working on a taskbar utility to suggest him this to implant the same features as TaskbarActivate in their utility... it is working great for me and I have zero trouble with the taskbar auto-hide which is a major annoyance for many users which make them decide to keep it on the screen and lose some real estate (pixels)... I was about to do some reverse engineering and learn programming myself, but it would take some time, so I am asking good programmers like you to do it if they are interested... feel free to keep this closed
