### ISSUE TITLE
Transparent taskbar only when no maximized window

### ISSUE THREAD

**Issue by stephtr** [ChrisAnd1998/TaskbarX#149]
It would be nice if the taskbar with transparent styling enabled would loose it's transparency, if there's a window maximized on the current monitor. (In that case the taskbar doesn't blend in the background anyway, it would also fix #49 in that case.)

**Comment by watermarkhu** [comment]
I second this. 
It would be nice if the same options would be available as from TranslucentTB. 
Now I'm using both programs to get my preferred look.
