### ISSUE TITLE
Blur option is not working in real time sometimes. 

### ISSUE THREAD

**Issue by maharshi-b** [ChrisAnd1998/TaskbarX#154]
Sometimes blur is not updating. When i click on windows icon, it is updating. After that it is not changing.

**Comment by ChrisAnd1998** [comment]
Yep, transparent seems to work fine but, those effects have to be applied in a loop. Just like every tool that changes the taskbar appearance. Like translucentTB. I hope to find a way to lock the appearance or stop it from updating.
