### ISSUE TITLE
Feature Request: Fake transparency?

### ISSUE THREAD

**Issue by Spagoot420** [ChrisAnd1998/TaskbarX#155]
I really fell in love with the look of the transparent task bar, but sometimes when windows overlap the task bar, stuff gets difficult to read.
In this case it's the white highlighting in the bottom of the icons that mark that it is not only a link, but there is an actual open window:

Window above task bar:
![image](https://user-images.githubusercontent.com/49160836/72909944-1485d700-3d38-11ea-9324-a161e9bf8fee.png)

Window overlapping task bar:
![image](https://user-images.githubusercontent.com/49160836/72909968-210a2f80-3d38-11ea-9567-8bc6b4497095.png)

My solution would be an option, that provides something like this:
![image](https://user-images.githubusercontent.com/49160836/72910697-303dad00-3d39-11ea-9513-cdfe7bc05b9c.png)

In fact the task bar is not really transparent, it just shows the desktop wallpaper.
Do you think there is a way to implement something like that?

**Comment by Martin5001** [comment]
(Note: There could be one problem with this which is that users would probably notice that the transparency is not real when they would drag a window beneath the taskbar.)

**Comment by Spagoot420** [comment]
Yeah, please don't change the existing functionality of the transparent option. If this gets implemented, this should be a dedicated option with probably a better name than "fake transparenty" :/
