### ISSUE TITLE
Blur "kinda" broken on a 1280x1024 screen

### ISSUE THREAD

**Issue by Hubza** [ChrisAnd1998/TaskbarX#159]
Hello! I'm using this app with the "Blur" style option, and i've found a problem.

On my main, 1920x1080 monitor, it works great (amazing app, thanks), but on my 1280x1024 secondary display, the blur stops at the bottom. As you can see in this screenshot.

![image](https://user-images.githubusercontent.com/33783503/73026388-39a64280-3e29-11ea-8c77-e57f80625328.png)
(Blur slowly gets less transparent, to the point where the wallpaper, or whatever is behind it, is completely visible)
![image](https://user-images.githubusercontent.com/33783503/73026556-85f18280-3e29-11ea-9ba9-02f3176ce3cb.png)
As you can see, this doesn't happen on my main 1080p monitor.

It'd be nice to get this fixed, as it's slightly infuriating.

![image](https://user-images.githubusercontent.com/33783503/73026426-4aef4f00-3e29-11ea-9764-afc99aaa4a30.png)

Thanks!

**Comment by ChrisAnd1998** [comment]
Yes, taskbar styling is not fully stable. I am trying to find a better solution to change the taskbar style. And also try to lock it so it will stay in that state. And then the loop can be removed.

Do you have this issue with other taskbar tools too? Like [TranslucentTB](https://github.com/TranslucentTB/TranslucentTB) and [TaskbarTools](https://github.com/Elestriel/TaskbarTools).

**Comment by Hubza** [comment]
TranslucentTB has the same issue, yes. But it's a lot less apparent.

**Comment by ChrisAnd1998** [comment]
Does this still happen in 1.5.3.0? There have been lots of changes.
