### ISSUE TITLE
2nd Monitor: After restart/wake up, 2nd monitor not centered.

### ISSUE THREAD

**Issue by vaisas** [ChrisAnd1998/TaskbarX#162]
After a restart, wake up the second monitor is not centered and i have to open settings for it to fix it self. Main monitor stays centered.

This is on the payed Microsoft Version, this didnt happen on the free zip version i had until 2 days ago. It only happens to me on the paid version.

**Comment by shayvaturi** [comment]
@ChrisAnd1998 - I think you need to refresh the position after connecting or disconnecting another monitor.

**Comment by ChrisAnd1998** [comment]
@shayvaturi That's what i tried but, it doesn't work. The UIAutomation API does not recognize a new taskbar without restarting the application.
