### ISSUE TITLE
The app icons are not centered when the display rotates

### ISSUE THREAD

**Issue by isohal** [ChrisAnd1998/TaskbarX#168]
The app icons lose their center alignment when I rotate the display to portrait mode. I have to tap on FalconX app icon, which then initiates the center alignment but when I rotate the display back to landscape mode, it loses center alignment again. It seems like the app stops responding after rotation event and needs to opened again.

**Comment by ChrisAnd1998** [comment]
Well, it simply doesn't detect that the display has been rotated i think. I'll look into it.

What happens if you rotate your display and then launch any application to trigger FalconX?

**Comment by isohal** [comment]
So, actually I was slightly wrong in describing the behavior. The app icons do get centered after rotating the display to portrait mode but it takes a good 20 seconds for that to happen. If you trigger it by opening FaconX, it happens immediately but if you don’t do anything, it takes a solid 20 seconds.

**Comment by ChrisAnd1998** [comment]
Does this still happen in 1.5.0.0? As TaskbarX now restarts on DISPLAY_CHANGE event.

**Comment by isohal** [comment]
Hi Chris,
The icons are recentered on display rotation now. However, it takes a while to happen – probably 10 sec. Is it possible to make it happen instantly?

**Comment by ChrisAnd1998** [comment]
Well, it has no reason to take that long as the refresh rate is set to 400 milliseconds by default. So i don't think it will get any faster. I will do some testing on that.

**Comment by isohal** [comment]
Also, has the name changed from FalconX to TaskbarX? Just curious.

**Comment by ChrisAnd1998** [comment]
Yep, i think TaskbarX is a much better name ;)

**Comment by isohal** [comment]
I like it! 👍 Good luck!

________________________________
