### ISSUE TITLE
Add more detail to settings

### ISSUE THREAD

**Issue by QkeleQ10** [ChrisAnd1998/TaskbarX#169]
It would be greatly appreciated if you add some more details to the options in the Settings. Like adding tooltips for what an option does (especially Acrylic), and maybe animation previews.

**Comment by Cabola** [comment]
The animations has a link you can go to, to view them.

**Comment by QkeleQ10** [comment]
Oh oops, didn't realise. But more details would be nice though.

[Quinten Althues](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=dtf0j)	[dtf0j]

Met vriendelijke groet,
Quinten Althues

On February 17, 2020 at 7:09 GMT, Carsten Larsen <notifications@github.com> wrote:

The animations has a link you can go to, to view them.
