### ISSUE TITLE
Settings app doesn't works properly with scaling

### ISSUE THREAD

**Issue by Dubzer** [ChrisAnd1998/TaskbarX#170]
Settings app looks blurry on my system. I'm using dual screen setup.
Main monitor: 3840x2160 175% of scaling 
Second monitor: 1680x1050 100% scaling
![screenshot](https://user-images.githubusercontent.com/18244287/74586938-f1300e00-4ffd-11ea-9482-318e612b45f9.png)

**Comment by ChrisAnd1998** [comment]
Fixed in 1.5.4.0
