### ISSUE TITLE
Taskbar Color

### ISSUE THREAD

**Issue by SkyrenOfficial** [ChrisAnd1998/TaskbarX#172]
![image](https://user-images.githubusercontent.com/22105222/74638178-acc28080-516b-11ea-83e2-697a75de731c.png)
Any solution?
I'd like to make everything more visible. Perhaps even to change font/effect color not to be white.

**Comment by ChrisAnd1998** [comment]
Currently i don't know if it's possible but, i will mark it as a "feature request" for now.
