### ISSUE TITLE
transparency setting not taking effect (in 1709 and lower)

### ISSUE THREAD

**Issue by mcoblefias** [ChrisAnd1998/TaskbarX#176]
Every time I set my styling to transparent, it only makes it blur, no matter how many times I set it to transparent. I also tried restarting my machine but still the same.

![K00mjl0KOs](https://user-images.githubusercontent.com/24319318/75094971-ff1bfb00-55ca-11ea-8443-910c9cbdc401.gif)

**Comment by ChrisAnd1998** [comment]
What if you go to %appdata% in explorer open up FalconX.cfg and change the number 2 to 1?

**Comment by Darthagnon** [comment]
I'm having similar issues with transparency, etc. options not working, or looking kinda glitchy when I have (Winaero Tweaker's)[https://winaero.com/comment.php?comment.news.1836] "increase Taskbar Transparency level" enabled (Win10 v1709) (the tweak works like this: https://winaero.com/blog/increase-taskbar-transparency-level-in-windows-10/).

**Comment by diegopovalz** [comment]
Having the same probleme here; blur and acrylic work fine, but transparency doesn't take effect

**Comment by mcoblefias** [comment]
This is already how it looks like. No value 2.

![notepad++_4enibs5ACf](https://user-images.githubusercontent.com/24319318/75103005-b5193080-562f-11ea-9217-edc325ffab80.png)

**Comment by ChrisAnd1998** [comment]
@diegopovalz @mcoblefias @Darthagnon 
Is your Windows 10 installation maintained by someone else? Like an organisation.
What build of Windows 10 is it? 

> @Darthagnon **1709**

What edition (Home, Pro etc..)?
Any Antivirus software installed?

I am asking this so i may be able to reproduce your situation.

**Comment by Darthagnon** [comment]
@ChrisAnd1998 
Win10 v1709 Home, Antivirus: (Panda Dome)[https://www.pandasecurity.com/en/homeusers/solutions/free-antivirus/], Settings (blurs, etc. disabled atm; will post screenshots asap):

    CubicEaseInOut
    500
    0
    False
    True
    False
    3
    0
    False
    0

**Comment by ChrisAnd1998** [comment]
I just installed 1709 and 1909 in a virtual machine and tested both the store and regular version.
1909 worked on both just fine no issues. In 1709 i noticed the settings only got saved 1 time. After that it keeps resetting itself. Also none of the taskbar styles worked.

So the conclusion is that 1709 does not work. I will try to find a fix but, the chance will be little.

**Comment by Darthagnon** [comment]
@ChrisAnd1998 Here's my screenshots. On my PC, custom settings seem to work, they just do the wrong thing... 

https://imgur.com/a/0KcJQXl

**Comment by ChrisAnd1998** [comment]
No problem :) it's fun to do.

Can you try this?
[1.4.3.0_Test.zip](https://github.com/ChrisAnd1998/FalconX-Center-Taskbar/files/4241238/1.4.3.0_Test.zip)

**Comment by Darthagnon** [comment]
I tried v1.4.3.0_Test; the outcome is identical to before, the screenshots still apply. I also installed the latest version of TranslucentTB and compared its behaviour with FalconX (also tried disabling and reenabling WinaeroTweaker's transparency tweak - no difference, except to "normal taskbar" mode)

Conclusions reached (applicable to Win10 v1709 Home, FalconX test version and latest release version):

 - Transparent Taskbar is shown with FalconX: Acrylic enabled [Unexpected] or TranslucentTB: Clear enabled [Expected]
 - [Expected] Normal, slightly transparent taskbar (transparency can be adjusted with Winaero Tweaker) is show with FalconX: Styling disabled or TranslucentTB: Normal enabled
 - [Expected] Blurry Taskbar is shown with FalconX: Blur enabled or TranslucentTB: Blur enabled
 - Opaque Taskbar is shown with FalconX: Transparent enabled [Unexpected] or TranslucentTB: Opaque enabled [Expected]
 - Acrylic is not offered by TranslucentTB (I think that Acrylic was not offered in Win10 v1709)

Simplest fix suggestion I can think of: check for Win10 v1709, and change the options offered to "Opaque" (current "Transparent" code), Blur (leave as-is), and "Transparent" (current "Acrylic" code). Thus, all the options would do what they say they do, in a compatible manner for v1709 (I can't comment on other Win10 versions, though if it currently works, then it works).

**Comment by Cabola** [comment]
I know this is a bit off topic but you really odd to update your windows! Why use such an old version? So many holes been patches since v1709, "hackers" would just love to take advantage of your open market machine! I hope no one finds a way to you, because then you're screwed..

**Comment by AndiTails** [comment]
> I know this is a bit off topic but you really odd to update your windows! Why use such an old version? So many holes been patches since v1709, "hackers" would just love to take advantage of your open market machine! I hope no one finds a way to you, because then you're screwed..

If it's the Education or Enterprise version, 1709 is actually still being patched by Microsoft until April 14, 2020 - so is perfectly safe. Home/Pro need to be on 1809 as a minimum now, however. Details [here](https://support.microsoft.com/en-gb/help/13853/windows-lifecycle-fact-sheet).

**Comment by Darthagnon** [comment]
@Cabola I know I should update Windows. Just that I figure I'm not a target for hackers; my important stuff is also (mostly) backed up or encrypted. I don't like the design direction Win10 is taking (e.g. Task View, coloured icons) and don't fancy making my machine slower over time with endless updates (see: iOS, similar update policy). So I keep updates off, and as a bonus don't have to deal with M$'s PC-breaking bugs lol. Had no trouble yet.
