### ISSUE TITLE
Eartrumpet animation stutters and disables blur

### ISSUE THREAD

**Issue by lilbud** [ChrisAnd1998/TaskbarX#178]
I have EarTrumpet installed on Windows 10. When I have FalconX installed, if I try to open EarTrumpet, the animation stutters and actually disables the blur for a split second.

Attaching a video
https://photos.app.goo.gl/m4em4B2HsZ29uMhQ9

**Comment by ChrisAnd1998** [comment]
Interesting, i will take a look when i get back at my PC ;)

**Comment by ChrisAnd1998** [comment]
It can take some time i have to reproduce this on a different pc or in a vm. As i can't reproduce it at my own pc.

**Comment by andresandiah** [comment]
i can confirm this happens to me too.

**Comment by ChrisAnd1998** [comment]
Does this still happen in 1.5.5.0? TaskbarX now uses MSAA instead of the UIAutomation Api.

**Comment by lilbud** [comment]
Unfortunately, yes. Problem still happens in 1.5.5.0. Uninstalled both FalconX and Eartrumpet and reinstalled both.
