### ISSUE TITLE
Autohide taskbar on maximized windows

### ISSUE THREAD

**Issue by kapitanluffy** [ChrisAnd1998/TaskbarX#180]
Awesome work!

It would be great if  we can autohide the task bar only when a window is maximied similar to:
https://github.com/ChanpleCai/SmartTaskbar

**Comment by ChrisAnd1998** [comment]
Thanks!

**Comment by watermarkhu** [comment]
It would be great of this could be optionally taskbar specific. 
If a window is maximized on the second monitor, only the second taskbar is hidden.
