### ISSUE TITLE
STOP dose not run

### ISSUE THREAD

**Issue by leminsc8er** [ChrisAnd1998/TaskbarX#183]
after clicking STOP and save, the chnage does not run instantly

**Comment by ChrisAnd1998** [comment]
What doe you mean exactly? If i understand you correctly you want it to apply the settings instantly.
FalconX has to be restarted to read the new settings. I may be able to make that faster.

**Comment by prediscover** [comment]
Stop does not reset the taskbar to default windows 10 behavior.
