### ISSUE TITLE
Disable or move item to left in Vertical Display

### ISSUE THREAD

**Issue by vsnst** [ChrisAnd1998/TaskbarX#186]
I use Surface Pro and switch to vertical mode frequently but Falcon will center icons by calculating vertical width, which will make it show less items on the taskbar.

Can I have an option to disable Falcon when in vertical mode or auto detect it?

thank you for developing this app making my windows looks beautiful
![Show less icons in vertical mod](https://user-images.githubusercontent.com/36701269/75342368-465b0200-58d1-11ea-8af5-5cc26134dde6.jpg)

**Comment by ChrisAnd1998** [comment]
Hmm, don't know if i can detect that. I think what i can do is to have an option where you can set a width that would be skipped. Like if your resolution 1920x1080 holding it in landscape mode will be 1920 pixels wide and when you hold your screen in vertical mode it will be 1080 pixels wide. So if you put 1080 in that option and your resolution becomes 1080 pixels wide it will just stop centering.
And as soon it changes to anything else in this case 1920 pixels wide it will continue centering.

Conclusion:
Add option "Do not center when resolution equals ... pixels wide"

**Comment by vsnst** [comment]
> Hmm, don't know if i can detect that. I think what i can do is to have an option where you can set a width that would be skipped. Like if your resolution 1920x1080 holding it in landscape mode will be 1920 pixels wide and when you hold your screen in vertical mode it will be 1080 pixels wide. So if you put 1080 in that option and your resolution becomes 1080 pixels wide it will just stop centering.
> And as soon it changes to anything else in this case 1920 pixels wide it will continue centering.
> 
> Conclusion:
> Add option "Do not center when resolution equals ... pixels wide"
GENIUS IDEA
once again, thank you for providing us a solution.

**Comment by ChrisAnd1998** [comment]
@vsnst Added it to the 1.5.5.0 pre-release. Can you test it out?
https://github.com/ChrisAnd1998/TaskbarX/releases/tag/1.5.5.0

**Comment by vsnst** [comment]
> @vsnst Added it to the 1.5.5.0 pre-release. Can you test it out?
> https://github.com/ChrisAnd1998/TaskbarX/releases/tag/1.5.5.0

It works on my New Surface Pro (Runing 2004 Build19608.1006), but it took 23sec to update in both landscape and portrait mode.

**How it happened?**
I set the "Skip Resolution" to 1824 which is the width when the display switch to vertical mode. Once I thought it didn't work, all the icons disappear. 
After 20sec those icons finally move to the left. Then, I rotated my Surface Pro switching to landscape mode, it takes the same 23sec to recover to center.

**How to improved?**
I hope when I switch to vertical(/portrait) mode, icons immediately appear on the left.

**What has been improved?**
In this build, CPU usage is surprisingly better than my current build(about 1.5%) on average. Good work
And I love the new UI, looks clean. Hope to see Fluent Design in TaskbarX as well.

**Question**
Does animation speed shorter or longer would consume lesser CPU, battery?
![Annotation 2020-04-22 085534-medium](https://user-images.githubusercontent.com/36701269/79929208-ae643980-8477-11ea-8e02-edc37c6e45ca.png)

Thank you @Chris for taking time on my features request.

**Comment by ChrisAnd1998** [comment]
@vsnst Thx for testing! I'll look into this.
The use of animations don't make a difference on battery life but, someone requested it so i added it.

**Comment by ChrisAnd1998** [comment]
@vsnst Allright, i updated the pre-release 1.5.5.0 with the
Automation.ConnectionTimeout set to 1 second | default is 2 seconds
Automation.TransactionTimeout set to 1 second | default is 20 seconds

**Comment by ChrisAnd1998** [comment]
@vsnst Did you try it out already? I need to know so i can work on the next update. Sorry for pushing you ;)

**Comment by vsnst** [comment]
> @vsnst Did you try it out already? I need to know so i can work on the next update. Sorry for pushing you ;)

Sorry, I did not think you would be that fast fixing it.

I just tested, i can't feel the difference. I don't know if I had downloaded the wrong version, the about page said it is version 1.5.4.0.

**Comment by ChrisAnd1998** [comment]
Oh XD, no you need the 1.5.5.0 pre-release 😉
https://github.com/ChrisAnd1998/TaskbarX/releases/tag/1.5.5.0

**Comment by ChrisAnd1998** [comment]
@vsnst Oh XD, no you need the 1.5.5.0 pre-release 😉
https://github.com/ChrisAnd1998/TaskbarX/releases/tag/1.5.5.0

**Comment by vsnst** [comment]
> @vsnst Oh XD, no you need the 1.5.5.0 pre-release 😉
> https://github.com/ChrisAnd1998/TaskbarX/releases/tag/1.5.5.0
> 
> Or i might have forgotten to change it to 1.5.5.0.
> What i hoped was that this fixed it 😓

that's the one I downloaded, yeah, similar issue, about 15~20sec update.

maybe I need to clean the cache or something before I tested the pre-release?

**Comment by ChrisAnd1998** [comment]
@vsnst Nah, if you replaced the exe file and then re-run it then it should do what it's coded to. There is no cache. The weird thing is that if the display changes it should restart it's self after 1 second. This clearly doesn't happen or it's stuck on the beginning after the restart. Now i have no idea why it's waiting so long 😩.

**Comment by vsnst** [comment]
> @vsnst Nah, if you replaced the exe file and then re-run it then it should do what it's coded to. There is no cache. The weird thing is that if the display changes it should restart it's self after 1 second. This clearly doesn't happen or it's stuck on the beginning after the restart. Now i have no idea why it's waiting so long 😩.

that's alright, don't push yourself too hard on that.

It's already so much more useful to me.

**Comment by ChrisAnd1998** [comment]
@vsnst But, it's not perfect XD
Here is another try
[Release.zip](https://github.com/ChrisAnd1998/TaskbarX/files/4524814/Release.zip)

Instead of finding all taskbars using the UIAutomation API it now finds it using EnumWindows Pinvoke Message

**Comment by vsnst** [comment]
> @vsnst But, it's not perfect XD
> Here is another try
> [Release.zip](https://github.com/ChrisAnd1998/TaskbarX/files/4524814/Release.zip)
> 
> Instead of finding all taskbars using the UIAutomation API it now finds it using EnumWindows Pinvoke Message

This time much better, totally usable.
Vertical mode immediate move to left, except switching back takes 15sec, but this time icons won't disappear, I could live with that.

Thank you

**Comment by vsnst** [comment]
Opps

seems Windows autorotation uses different dethod. 
This time, if I rotate the Display, icons won't move.

But If I manually rotate the screen in the settings/ Intel graphics command center to switch it, it works

**Comment by vsnst** [comment]
I did another test on surface pro. It didn't work well on Surface Book 2.

It actually work like above two on SP, no big issue.
It's weird ,I'll make another test when I get home.
Thank you

**Comment by notuxius** [comment]
I have position of taskbar vertically on the left side and external monitor
look of the taskbar on ext 24' 1440 monitor:
![07 09 58 17 983](https://user-images.githubusercontent.com/2657014/81264079-7fd68900-9049-11ea-9ad8-679720320716.png)
look of the taskbar on internal laptop 14' monitor 1080:
![07 09 53 28 496](https://user-images.githubusercontent.com/2657014/81264141-97ae0d00-9049-11ea-848a-92a5324cc15b.png)
don't know if i should start new bug or comment on this one
thank you for great work
