### ISSUE TITLE
FalconX freezes with Windows Key + Space command

### ISSUE THREAD

**Issue by hashtagSELFIE** [ChrisAnd1998/TaskbarX#188]
Hi, I ran in tho this problem a lot lately since I'm a bilingual. I loved Windows+Space command a lot. I notice that the program will freeze a while after I type for minutes, so I speculate that it from that. It also kills my Windows key too. I found that restarting FalconX fixes the problem. Please look in to this if you had time. Thanks

PS. It never freezes before. I just start noticing in recent days.

**Comment by iHaired** [comment]
Same here. Russian+English user.
