### ISSUE TITLE
A problem in urgent need of repair

### ISSUE THREAD

**Issue by paranoia721** [ChrisAnd1998/TaskbarX#190]
Whenever there is an icon increase or decrease in the notification area, the centered icon will return to the beginning, and then center again, which greatly affects the experience. I hope it can be repaired as soon as possible. Thank you

![20200228_233015](https://user-images.githubusercontent.com/59696607/75562272-4438a500-5a83-11ea-8fd3-b82bcf22d629.gif)

**Comment by ChrisAnd1998** [comment]
I had that fixed a long time ago. Any other applications installed that alter the taskbar?
I also can't reproduce it on any of my testing systems.

**Comment by vsnst** [comment]
I don't have this issue either.

**Comment by Cabola** [comment]
could it be the cpu monitor task bar object that could be interfering here?
