### ISSUE TITLE
Taskbar styling settings not working

### ISSUE THREAD

**Issue by Dark5lalom** [ChrisAnd1998/TaskbarX#195]
On my laptop (MSI) changing the taskbar effects doesn't change the styling at all. It works well on my desktop. Have tried reinstalling etc. on 1.4.3.0

**Comment by TechBrule** [comment]
I have the same issue on an HP Z2 mini workstation, Windows 10 pro 1909. Setting any styling has no effect and after a reboot the enable taskbar styling button is unchecked. My set up has 3 monitors, and having the taskbar displayed on all 3 or only the center one does not seem to make any difference. On version 1.4.5.0

**Comment by ChrisAnd1998** [comment]
Does it make a difference if you enable "Transparency effects" in  (Windows Settings > Personalization > Colors) ?

**Comment by TechBrule** [comment]
it does not seem to matter if that is set to off or on, as a note none of the style options seem to do anything for me on this one computer but works fine on 2 other computers, this computer and one of the ones that works are windows 10 pro, the only difference I can think of is that this computer is domain joined and also uses folder redirection but not roaming profiles. I am an admin on all machines. I wonder if Dark5lalom's computer is domain joined?

**Comment by rmaclean** [comment]
Similar issue for me. Used to work on this machine, not sure version but was pre-the new settings app. Everything is centred but no animation and no effects

> Does it make a difference if you enable "Transparency effects"  

Makes no difference

> I can think of is that this computer is domain joined

I am not domain-joined

Other info
- Got it through the store (not the zip)
- On 1903 Windows Build
- The current version of the app is 1.4.5.0

**Comment by rmaclean** [comment]
Had a feeling it was crashing, spotted this in the event viewer

```
Application: FalconX.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at FalconX4.Taskbar.RefreshWindowsExplorer()
   at FalconX4.Taskbar.ResetTaskbarStyle()
   at FalconX4.Taskbar.Main()

```

**Comment by ChrisAnd1998** [comment]
Well the System.NullReferenceException always have been an issue. It shows up on every loop when it's checking for the position of the last icon in the taskbar but, FalconX should be ignoring it. It's caused somewhere in the UIAutomation API. I hope to get rid of this depency and go with plain window messages but, i didn't find out how yet.

**Comment by rmaclean** [comment]
Updated to 1909 build of Windows and ... it is working now 🤷‍♂

**Comment by ChrisAnd1998** [comment]
🧙‍♂️

**Comment by Dark5lalom** [comment]
Hi again still having issues with this. Sometimes on this machine it will also say about the vbs file not being there on startup (Have had the logon task schedule enabled). Taskbar styling still doesn't seem to be working, i've tried reinstalling (windows store version) and i am running up to date windows 10 pro 1909. the machine is also not domain joined.

**Comment by TechBrule** [comment]
After reading these comments it seems like everyone was running the windows store version (as was I) so i uninstalled it and downloaded the zip file, now it works fine.

**Comment by ChrisAnd1998** [comment]
The Store version had lots of issues with saving to a file. I fixed that by using powershell to write to the settings file. This method seems to work fine on my side but, is a very clunky fix. The store version has all permissions but, doesn't recognize that :/
The same problem appears when i try to write to the registry (Current User).

It seems like i have to find a different method as it doesn't work for some.
