### ISSUE TITLE
Possible memory leak ? 

### ISSUE THREAD

**Issue by anilit99** [ChrisAnd1998/TaskbarX#198]
After a day or two or couple of hibernation/wake up cycles, windows explorer is taking upto half a gig of memory. Usually on my laptop explorer takes 50mb. Only way to fix this is to restart the explorer process and stopping the falconX process. 
Config - win 10. 1909 (Build - 18363.720)

**Comment by ChrisAnd1998** [comment]
Hmm, this is not happening on any of the pc's i test FalconX on.

**Comment by Dansel** [comment]
Pretty sure this is happening to me. Whenever I leave TaskbarX on Windows Explorer has a constans 0.5%-1% CPU usage and slowly accumulates memory.

![image](https://user-images.githubusercontent.com/2886387/80924552-e594ed80-8d89-11ea-9023-e246d1a299bb.png)

This is after a couple of hours. If I leave it be it can approach 1.5GB after a couple of days without restarting Explorer.

I'm going to see if I can attach a debugger to it and see what happens, but I'm a newb at it and it might not help any.

**Comment by swsegdan** [comment]
So did some debugging and:

              HEAP_ENTRY Size Prev Flags            UserPtr UserSize - state
        0000000021e6e1d0 0024 0000  [00]   0000000021e6e1e0    00230 - (busy)
          UIAutomationCore!MsaaProxy::`vftable'

              HEAP_ENTRY Size Prev Flags            UserPtr UserSize - state
        0000000006c93d50 0013 0000  [00]   0000000006c93d60    00128 - (busy)
          UIAutomationCore!UiaNode::`vftable'

Those calls are leaking memory for me.

Don't know if it helps.

**Comment by ChrisAnd1998** [comment]
Well, now i moved away from UIAutomation does it still happen?
TaskbarX now uses MSAA. 

https://github.com/ChrisAnd1998/TaskbarX/releases/tag/1.5.7.0

**Comment by swsegdan** [comment]
It is better. I've not really used my computer enough these past days to see if there would be any leaks after longer use, but the CPU usage is down. I'll keep an eye on it and let you know if anything happens.
