### ISSUE TITLE
Task Schedule doesn't work, can't find script "FalconX.vbs"

### ISSUE THREAD

**Issue by BonomDenej** [ChrisAnd1998/TaskbarX#201]
Whenever I boot Windows after enabling the task schedule I have this message from a "Windows Script Host" window: (I'm translating) Failed to find the script file : "C:\Users\Bonom Denej\AppData\Roaming\FalconX.vbs"

Disabling the task schedule works fine, FalconX still launches, albeit a bit slow. But from what I read the task schedule would make it boot faster so I was hoping it would work.

**Comment by cybercatgurrl** [comment]
I have the same issue.
