### ISSUE TITLE
Secondary monitor icon positions only update when primary icons change

### ISSUE THREAD

**Issue by dambler** [ChrisAnd1998/TaskbarX#203]
I have a dual monitor setup and the following taskbar settings enabled:

- Always hide labels 
- Show taskbar on all displays
- Show taskbar buttons on _Taskbar where window is open_
- Combine buttons on other taskbars _Always hide labels_

With these settings, the secondary screen will only update the position of its icons when the primary screens icons change.

To reproduce:
**With several windows open on both screens**
1. Open a new window on the **secondary** screen.
2. The icons will _not_ update their position.
3. On the primary screen, close an open window.
4. Both taskbars will now update the positioning of the icons.

**Comment by ChrisAnd1998** [comment]
Yep, it's nit actually coded to do so. So i will mark it as a feature request.
