### ISSUE TITLE
[Feature Request]Genie minimization effect

### ISSUE THREAD

**Issue by onlytanmoy** [ChrisAnd1998/TaskbarX#207]
Chris- as requested please implement the 'Genie minimization effect' as one of the included animations in the app.
As you might know the Genie effect is what all Macs do by default. Whenever you minimize a window, the window gets skinny at the bottom and gets 'sucked into' the dock.

**Comment by Darthagnon** [comment]
You can already get this effect by using Stardock WindowFX. I'm not sure theming this particular type of animation is the point of TaskbarX.

**Comment by onlytanmoy** [comment]
@Darthagnon I am conscious of Stardock product :)
Since I am using TaskbarX only hence approached Chris to implement the genie effect. Don't want to install WindowFX just for that.

**Comment by Darthagnon** [comment]
I'm with you there, buddy. I'm currently wanting to uninstall Stardock Fences, but can't live without the "double-click to hide desktop mess" feature (already found an AHK script, just need to tidy my desktop first). Would be nice to have ~~FalconX~~ TaskbarX be the perfect Windows Dock software. (I've used RocketDock, NexusDock, ObjectDock, and they're all lacking, and use too many workarounds to replace Windows taskbar features).
