### ISSUE TITLE
📌 | Currently rewriting the whole project with smarter code and unlimited monitor support (Can take some time ⌛). Testing builds are in the 1.5.0.0 pre-release ;)

### ISSUE THREAD

**Issue by ChrisAnd1998** [ChrisAnd1998/TaskbarX#209]
https://github.com/ChrisAnd1998/FalconX-Center-Taskbar/releases/tag/1.5.0.0

**Comment by CuraeL** [comment]
WOW!

**Comment by Cabola** [comment]
holy scrapbooks!

**Comment by robindrost** [comment]
Testing latest release, feels really smooth!

**Comment by ChrisAnd1998** [comment]
Iam thinking of making a configurator. It will allow you to setup and test your settings. When you like the settings you can apply and the configurator will create the taskschedule with all the needed parameters. This will make FalconX not depending on a settings file that could be blocked by permissions or cause other issues. The configurator will have an export and import function for your settings. So if you want to change the settings at a later time you can import your exported settings file.

**Comment by Cabola** [comment]
that'd be cool!

**Comment by solariz** [comment]
Using the new dev build now v6 just updated to v10 - running smooth! Thanks for the great tool.

**Comment by ChrisAnd1998** [comment]
@solariz Great! thanks for testing and letting me know! :)

**Comment by iamthekings5** [comment]
Tried v6 and v12, when swapping monitors with DisplayFusion sometimes new main display doesn't align properly and half the taskbar is missing (goes into the tray).

**Comment by ChrisAnd1998** [comment]
@iamthekings5 Allright, i will look into it in the comming days 😉👍

**Comment by ChrisAnd1998** [comment]
@iamthekings5 does v13 fix it already?

**Comment by iamthekings5** [comment]
> @iamthekings5 Does v14 fix it already?

It works great now! Only problem is this. Thanks a lot!

![image](https://user-images.githubusercontent.com/58262947/78468330-ec8afa80-770e-11ea-8c2c-c810b9a1ea0d.png)

**Comment by ChrisAnd1998** [comment]
😆🤯 wow! I will dig into that right away. I will let you know when it's fixed 😉

**Comment by solariz** [comment]
>but, i can't get it to act like this... 😅

Can't see that behavior too. Having the V14 running without any problem so far.
Microsoft Windows [Version 10.0.18363.752]

![screenshot_20200406-113844](https://user-images.githubusercontent.com/4168339/78544954-3a7d2c80-77fb-11ea-863c-52c81e98277d.png)

**Comment by shayvaturi** [comment]
@ChrisAnd1998 - any chance to move to c#?

**Comment by ChrisAnd1998** [comment]
@shayvaturi Nope, VB.NET and C# are both equal languages. And i am so used to VB.NET that i don't felt the necessity to move.

**Comment by shayvaturi** [comment]
The benefit is that it will be easier to contribute 😉
Like you said VB.net is the same, but it's very rare to see projects written in VB.net.

**Comment by iamthekings5** [comment]
> @iamthekings5 😆🤯 wow! I will dig into that right away. I will let you know when it's fixed 😉
> 
> Edit: I tried to reproduce it in many ways but, i can't get it to act like this... 😅

I will do some more extensive testing and use to try and reproduce the issue and get back to you!

**Comment by shayvaturi** [comment]
@ChrisAnd1998 - I added a pull request with gitignore and nuget reference.

**Comment by ChrisAnd1998** [comment]
@shayvaturi Oh.. I clearly missed that. It's merged now. Thanks!
