### ISSUE TITLE
[Request / Idea] Pause animation while hovering over the taskbar

### ISSUE THREAD

**Issue by Robzyy** [ChrisAnd1998/TaskbarX#217]
Hello, Chris! 
I often find myself dragging the apps while just trying to click on them because they are moving, trying to recenter. 

Weak recreation here: https://gyazo.com/dd5fdfa74166db63d7105d20032abb09 

I want to know if it is possible to pause the animation while the mouse is over the taskbar so something like this doesn't happen. (It's not something that really needs implemented, it's just an idea)

I don't mind if you don't agree with this.

Edit: I prefer "FalconX" over "TaskbarX" lol.

**Comment by ChrisAnd1998** [comment]
I think that would be possible. I have to see if the animator keeps moving smoothly while checking for a value.

**Comment by Martin5001** [comment]
> "FalconX" seems to be the name of a rocket.

Also it's a name of some other company

**Comment by Danita** [comment]
I was about to post this same feature request. I think it's the only thing missing that would make TaskbarX perfect!

**Comment by nicekiwi** [comment]
I find myself accidently opening, or minimizing the wrong app many times as the animation seems to take place just as my mouse gets there after closing another pinned app.

**Comment by ginqus** [comment]
Any updates? I haven't found anything in the settings related to this, so I assume that this feature wasn't implemented yet.
