### ISSUE TITLE
[Feature Request]Wavy effect on hovering over icons

### ISSUE THREAD

**Issue by onlytanmoy** [ChrisAnd1998/TaskbarX#218]
Hey Chris- hope all well at your end. So I was watching this video https://youtu.be/_9_8021P1Zg
towards 4:45 timeline you will see the nice wavy effect it produces when you hover the mouse cursor over the icons on the taskbar. Don't want to install Nexus Dock just for it so was thinking out loud if it will be possible to have this feature in FalconX :) Do let me know. Thanks.

**Comment by ChrisAnd1998** [comment]
Everything Ok :)
That would be a hard one idk if it is even possible. I will take a look at it ;)

**Comment by onlytanmoy** [comment]
It matters to me that you considered giving this idea a thought rather than rejecting it outright. So, even if you are not able to implement it I still thank you my friend.

**Comment by onlytanmoy** [comment]
@ChrisAnd1998 Hey Chris, something like this will be possible - the icons will enlarge on mouseover? Pls see below link to get the idea I am proposing
https://www.deviantart.com/mazinlabib10/art/Circle-Icons-856101455
