### ISSUE TITLE
Compatibility with PowerToys

### ISSUE THREAD

**Issue by yokhoe** [ChrisAnd1998/TaskbarX#219]
I believe the FalconX may have a conflict with PowerToys, but I can't pin-point exactly how to provide this data/log for you, other than this warning notification often popping up.  It causes the taskbar centering to stop working until restarted.

I will address this to the PowerToys team as well.  Just wondering if anybody else utilize both tools and if they're experiencing the same issue.  Please let me know if there's antyhing I can do to gather the data/log for the devs.

![image](https://user-images.githubusercontent.com/22972701/79080040-47f15580-7cd8-11ea-9dd1-340706364899.png)

**Comment by ChrisAnd1998** [comment]
But, FalconX doesn't run as Admin. I also have PowerToys installed and don't get this message.
I think it could be something else...

**Comment by vsnst** [comment]
I also have PowerToys installed and no issue so far.

The Administrator privileges message is a new features in PowerToys, You can find the settings under the general setting page.
[https://github.com/microsoft/PowerToys/blob/master/doc/devdocs/run-as-admin-detection.md](url)
