### ISSUE TITLE
Configurator Doesn't Remember Settings or Add to Startup.

### ISSUE THREAD

**Issue by UtopiaOpera** [ChrisAnd1998/TaskbarX#220]
I set the options for transparency and no animation in the configurator, and they apply, but they don't save if I restart the .exe or restart computer. It worked fine in the final version of 'FalconX'.

As a side note, when pressing apply, it doesn't add the app to Startup. I added it myself manually in the end.

**Comment by ChrisAnd1998** [comment]
When you click apply a taskschedule will be created with all required parameters. The configurator has the options File -> Import and Export you can use that to save your settings and later import it to make some changes. The configurator will not save the settings somewhere automatically as it was giving problems for a lot of people. 

![Untitled](https://user-images.githubusercontent.com/50437199/79231393-448bd480-7e66-11ea-9757-e479b26407c3.png)
