### ISSUE TITLE
New update removed the ability to set "launch at startup" and also settings are no longer persistent.

### ISSUE THREAD

**Issue by BitGrub** [ChrisAnd1998/TaskbarX#221]
Love the name change, but settings are no longer remembered; Every time the new (uglier) configurator is opened, all the default settings are reselected, which is extremely frustrating.

The uglier (new) configurator also lacks the option to make TaskbarX launch at startup, whether as program or as task, which the old version already had.

I'm using the free portable version of TaskbarX 1.5.0.0

**Comment by ChrisAnd1998** [comment]
Hi, having the settings saved somewhere caused issues for lots of people thats why i removed that. The configurator has an option to import and export the settings so if you want to change your settings at a later time you will have to import the settings you exported. It has to work this way to prevent all kinds of issues. 

Also the configurators UI is temporary. I wanted to put it out for testing and if it works fine i can focus on designing it. Sorry about that XD

When you click the "Apply" button a task schedule will be created containing all the parameters you have setup using the configurator. Here is a screenshot

![Untitled](https://user-images.githubusercontent.com/50437199/79245021-d4864a00-7e77-11ea-9c4d-367b271b3e91.png)

![Untitled2](https://user-images.githubusercontent.com/50437199/79245284-321a9680-7e78-11ea-8a56-5e4117ead250.png)

**Comment by BitGrub** [comment]
Huh, that’s strange. My startup task isn’t working for some reason, then.

And sorry for being a bit of a prick, it was just a lot of unexpected changes

**Comment by ChrisAnd1998** [comment]
No problem i get it 😉

What if your right click on TaskbarX in the taskschedule and hit run? Does that work?

**Comment by ChrisAnd1998** [comment]
Oh well i think i found a way to get the settings again by just reading the existing taskschedule's values XD

**Comment by ChrisAnd1998** [comment]
@BitGrub Yep, that worked. it's in update 1.5.2.0. I also added the option to set the delay of the task schedule which may fix your startup issue by increasing the value.
