### ISSUE TITLE
📌 | About TaskbarX and the new Configurator

### ISSUE THREAD

**Issue by ChrisAnd1998** [ChrisAnd1998/TaskbarX#222]
You may have noticed that the project is now renamed to TaskbarX and that the settings works differently now.

In the previous versions your settings where automatically saved to your appdata as a txt/cfg file.
However this was causing issues for some people so the new configurator works very differently.
TaskbarX now gets its settings through it's commandline parameters which can be found [here](https://github.com/ChrisAnd1998/TaskbarX/blob/master/README.md). The configurator lets you choose your settings and when clicked on "**Apply**" it will show you the new settings you had chosen. In the background the configurator will create a **logon/startup taskschedule** with all the needed parameters (_This will not be visible in taskmanger but, in the taskscheduler "**taskschd.msc**"_). This way TaskbarX doesn't depend on a settings file stored in your **appdata** that may cause issues with permissions, writing to it because it's in use or even when it runs from the Microsoft Store not able to read the settings. 

The configurator may look bad now but, thats temporary. When i'm sure it's stable then i will focus on redesigning it. If you want to change your settings at later time then you can use **File -> Import and Export** options to export the settings anywhere you like and import them when you want to change something.

![Untitled](https://user-images.githubusercontent.com/50437199/79249026-f3d3a600-7e7c-11ea-9af8-d2796833a2c6.png)

**Comment by Cabola** [comment]
**1)** When installing you're not allowed to place icons on desktop, this option is disabled and uncheck able. You're only allowed to add them to the start menu. - Now this could be my own windows/anti software settings fault for causing it, so don't know if it's an issue..

**2)** The start menu folder is your name ("Chris Andriesen") and not TaskbarX. That could be confusing to some people..

Other than that, seems to be working better than before! Good job.

**Comment by ChrisAnd1998** [comment]
I actually disabled the option to put the icons on your desktop as i thought it was not needed XD.

Didn't notice the name of the start menu folder so i will definitely change that too.

Thanks 😁

**Comment by krtpowa** [comment]
I was just looking for the application and could not find it installed, I see that it changed its name! :)
Why do notices appear on virustotal.com?

**Comment by ChrisAnd1998** [comment]
@krtpowa FalconX had that issue too it's needs time for virus total to see that it's a false positive.
I'm still not sure why it happens but, i think its the UIAutomation Api from Microsoft.

**Comment by andresandiah** [comment]
I dont know what may be the problem, but at least for me, the "create task scheduler" option never worked. Do i need to enable or do something to my machine?
I always had to enable FalconX and now TaskbarX trough task manager/startup option: and when that option got dumped i had to add a shortcut to shell:startup in order for it to launch

**Comment by ChrisAnd1998** [comment]
@andresandiah Mostly the only reason that the task schedule won't work is the delay of the task. 
In update 1.5.2.0 i added an option in the configurator to change it. Try setting it on 20 seconds and if it works, work down the value to what does work. If this fixes it i would like to know your delay.

**Comment by andresandiah** [comment]
I have been trying for the last hour random values all the way from 1 to 300. None worked, what could be preventing taskbarX to create a task schedule?

**Comment by ChrisAnd1998** [comment]
@andresandiah I have no idea. Can you check if the taskschedule is even created? In your Start menu just search for Taskscheduler and open it up. On the left panel go to "Task Scheduler Library". A list with schedules will appear. Can you see if a schedule called TaskbarX is there? And if it is what happens if you right click on it and select "Run".

**Comment by Cabola** [comment]
Technically mine haven't worked "correctly" since beginning of v1.4. I have 3 monitors and they're setup like this
![Untitled-1](https://user-images.githubusercontent.com/19853946/79460606-5a7bcf80-7ff5-11ea-91c1-8d760d624893.png)
My task bar doesn't center on any of them after startup till I have a program open on monitor 2 and 3. Now it's not that big a deal because I have my mail open on monitor 2 and Discord on monitor 3. So when they startup and open up, the icons on each taskbars on all 3 monitors move to the center.

But if I don't open my mail program or any other program on monitor 2 then all 3 taskbars icons will remain in the left side. Mind you I only have icons showing on monitor 1 (primary) and then any open programs icons will display on their respective monitors taskbar. This is where I think the bug is to be found. Because when my windows boot up and FalconX/TaskbarX is ran there's no icons to move on monitor 2 and 3 so therefor it doesn't execute anything even tho there's icons on the primary monitors taskbar. Well that's my theory anyways...

**Comment by andresandiah** [comment]
No task schedule created. That option didnt work either in FalconX so i had to use the regular Startup method. I guess I'll have to go back to FalconX.

**Comment by ChrisAnd1998** [comment]
@andresandiah Can you try to create a new basic task manually? doesn't matter what you fill in. If you can't then the only thing i can think of is that you are not allowed to create a taskschedule. and then i have to following question.
Is your pc maintained by an organisation like school or work? 

I can just bring back to shortcuts next update as an alternative to the taskschedule.

**Comment by andresandiah** [comment]
I can create new basic tasks on my own, I have a few like ThrottleStop and even others created by different programs like Process Lasso. I am on windows 10 Pro, and I activated some policies to avoid Windows Update Driver installation and to disable Windows Defender completely.

(In other words, the pc is NOT maintained by and organization, it is maintained by me lol)

Thanks in advance for the shortcuts alternative in the next update. And thanks for your hard work bro!

**Comment by ChrisAnd1998** [comment]
@andresandiah Allright, i added it to the pre-release ;)
https://github.com/ChrisAnd1998/TaskbarX/releases/tag/1.5.3.0

**Comment by andresandiah** [comment]
@ChrisAnd1998 Thanks Bro! Its working great now thanks a lot!

**Comment by ChrisAnd1998** [comment]
Nice 😁, the issue i ran into with the 259 character limit in the shortcut can be fixed by just creating a registry startup key however when running from the store, the application is not able to access the registry. What i am hoping is that it does work in WPF or UWP but, i have to some testing on that. If nothing works then i will have to shorten the command line arguments to fit in however if i add more and more options over time i will reach the limit again. 

So i might need you later to test an application written in WPF or something else that will make a Taskschedule and see if that works. It may also be possible to let cmd create a schedule instead of the application itself as you explained other software is able to do so.

Can you try one more thing? Running the configurator as Admin and let it create a Taskschedule... If that does not work there must be something wrong in the Taskscheduler library for Winforms.

**Comment by andresandiah** [comment]
@ChrisAnd1998 I did try giving administrator rights and didn't work either 😥. Hit me up when you have those new versions working in order to test if everything works out with task scheduler.
thanks!

**Comment by ChrisAnd1998** [comment]
@andresandiah Thanks for your help! :)

Here is a WPF application it should create a taskschedule with the "-taskbarstyle=1" parameter.

[WpfApp1.zip](https://github.com/ChrisAnd1998/TaskbarX/files/4496158/WpfApp1.zip)

You need to place the **WpfApp1.exe** inside the TaskbarX directory.
Lets see if that works...

_I will be trying to create more possible solutions_

**Comment by andresandiah** [comment]
Hi @ChrisAnd1998 The WPF application worked! It created the task schedule just as you described.
The configurator returned this message when trying to create (and failing) a task schedule:

![image](https://user-images.githubusercontent.com/45172029/79641098-f246fe00-815a-11ea-953c-e2e82ccca4a5.png)

**Comment by ChrisAnd1998** [comment]
There is the issue! **(11,28):UserId:** Shouldn't be in there.  🎉🎉🎉

I have just released update 1.5.3.0 
and replaced Environment.UserName with System.Security.Principal.WindowsIdentity.GetCurrent().Name

So if you got the second WpfApp1 then the existing configurator should work.

**Comment by andresandiah** [comment]
Yeah!, I just installed latest version and is working perfectly with the configurator ╰(*°▽°*)╯
Thanks for your work Chris

**Comment by ChrisAnd1998** [comment]
Damn i'm so happy it's fixed now!!
no problem :)

**Comment by CVFireDragon** [comment]
I haven't seen anything about this so... 

Basically, when TaskbarX is running and you try to uninstall it, it uninstalls everything except for TaskbarX and a few DLLs, and the uninstaller says "Successfully Uninstalled!". So maybe add a check for if the program is running, and then kill it if you try to uninstall. 

Also, love your work <3 great job! What inspired you to make this?

**Comment by ChrisAnd1998** [comment]
Thx! I will add a check to the uninstaller. However the store version is not capabable of doing that but, i will look into that for if there is a way around ;)

**Comment by Cabola** [comment]
Might also note that the installer still calls the start menu folder your name. Further more when selecting where you want to install it to, if you don't use the default and want to select a folder your self (ex. "C:\TaskbarX"), then after selecting the folder it'll say the path to install to should be "C:\TaskbarX\Your name\TaskbarX\". Of course you can then just delete the part you don't want "Your name\TaskbarX\"..

**Comment by ChrisAnd1998** [comment]
@Cabola Huh, it's configured to only list it under TaskbarX. Did you uninstall the older versions before installing the new versions?

**Comment by Cabola** [comment]
Yea, there's only a your name folder in my start menu, not a taskbarx folder.

**Comment by swsegdan** [comment]
Two things: 

The number of DLLs included is approaching the number where you might want to move them to subfolders for the sake of neatness. It's getting cluttered.

Have you looked into something like NSSM? ( https://nssm.cc/ ) It's just about the easiest way I know of to take a normal application and run it as a service. And this is the kind of software I can easily see benefiting from being run that way.

**Comment by ChrisAnd1998** [comment]
@swsegdan Not looked into that so i will when i get back home ;) I have included all DLL's it needs to run including the DLL's from .NET Framework which you normally need to install to run the application. I can reduce it to 4 DLL's but, then you will require to install .NET Framework 4.8. I just did it so it will always run.

**Comment by swsegdan** [comment]
@ChrisAnd1998 Oh, I don't mind the DLLs being included, I just mean that you should create a subfolder named "Dependencies" or whatever, instead of having them in the root folder.

**Comment by Cabola** [comment]
That reminds me, when I uninstalled TaskbarX a bunch of DLL's were left behind in the install folder (which weren't deleted either because the DLL's remained), and as stated before the "Chris Andriesen" folder in the start menu also remained with the 2 shortcuts, tho not executable..

**Comment by ChrisAnd1998** [comment]
@Cabola Currently i use InstallForge to create the installer and uninstaller but, it lacks some options to properly uninstall it. So i will find another installer creator that has more options.

**Comment by Darthagnon** [comment]
Does the new ModernWPF settings mean it won't work with Win7 any more? :'(

**Comment by ChrisAnd1998** [comment]
@Darthagnon The ModernWPF UI will probably just work on Windows 7 however i'm not planning to support Windows 7 anymore as the OS is now (End Of Life). Sorry for the to the point answer...

**Comment by Darthagnon** [comment]
I use it basically just for taskbar centering, and it works great for that still, on outdated Windows. Transparency is a bit different, but it's workable. Thank you for your hard work!

**Comment by Cabola** [comment]
hmm I just launched twitch app on my desktop and that made my anti protection system mark the configure with a false positive for ransomware :S Weird part is, I wasn't even using the configure, but it also killed taskbarx.exe and closed some other programs I had running at same time :S Never had that happen before lol

**Comment by ChrisAnd1998** [comment]
@cabola ohh! thx for letting me know! What AV do you use?

**Comment by NicoASMB** [comment]
@ChrisAnd1998 

I'm having the same issue. My Bitdefender Total Security 2020 is marking TaskbarX as Ransomware when the programm is running. I've already contacted their support and also found this old GitHub ticket:

https://github.com/ChrisAnd1998/TaskbarX/issues/105

**Comment by Cabola** [comment]
Oh sorry @ChrisAnd1998 , forgot all about replying back to this. My AV is Bitdefender Total Security 2020

**Comment by stephenjmcmahon** [comment]
Win10 Store version removed itself from launching on start-up ~2 weeks ago
Experienced same thing on desktop and laptop
See no option on the configurator anymore either

Fixed it on my side:
Win + R to open the Run dialog and type shell:AppsFolder in the run box.
Hit the Enter key to open the Applications folder.
Drag and drop the shortcut of the TaskbarX to the Desktop.
