### ISSUE TITLE
1.5.1.0 requires different version of .NET framework?

### ISSUE THREAD

**Issue by Skrell** [ChrisAnd1998/TaskbarX#223]
I had no issues with 1.5.0.0 (which worked great performance wise btw) but when I upgraded to the next release it said I needed to install the .net framework 4.8?  Windows 8.1 x64

**Comment by ChrisAnd1998** [comment]
Yes, i build it on top of 4.8 but, i can lower that if you prefer...

1.5.0.0 was also build on .Net Framework 4.8 though.

**Comment by Skrell** [comment]
hmm maybe this is an issue with my PC?  I'll try it again later today and confirm it's still a problem.  I did notice that the files in the release folders are drastically different between 1.5.0.0 and 1.5.1.0

**Comment by ChrisAnd1998** [comment]
Well, the dll files are the same but, i left the pdb and xml files in that get generated when compiling the application. You could try to remove those files to see if that fixes it. I can just set the target to .NET 4.7.2 next update.

**Comment by ChrisAnd1998** [comment]
1.5.2.0 is build just as 1.5.0.0 on .NET 4.8. As i explained above .NET 4.7.2 increased CPU Usage so i don't want to retarget the project of course.
