### ISSUE TITLE
Problem with added toolbars or bar plugins

### ISSUE THREAD

**Issue by krtpowa** [ChrisAnd1998/TaskbarX#225]
Hello, I recently bought this great program, because it is wonderful, it gives a great aesthetic to windows.
The problem on my pc is that I use a "folder called" _ "to host some shortcuts to the CPU governor
and older I have a speed meter app.
These 2 things are added to the bar, I never have a problem if I have the option to "lock the taskbar" unchecked (you see the stripes to move things etc) but if I leave it locked, as it should always be, every time I I open an app and it "readjusts" everything gets out of control

> working fine with the bar "unlocked"
![image](https://user-images.githubusercontent.com/5263460/79353083-e250d380-7f3a-11ea-8434-e1677c7cbe32.png)

> funcionando mal con la barra "bloqueada" como estaría siempre.
(bar locked, as it would always be in a normal mode)

![image](https://user-images.githubusercontent.com/5263460/79353186-01e7fc00-7f3b-11ea-953e-a29dd2fb0c5a.png)

![image](https://user-images.githubusercontent.com/5263460/79353356-3f4c8980-7f3b-11ea-924e-a9ec08aa01a3.png)

can you configure something to avoid this?
Thank you very much for your great application!

-- My current settings --

![image](https://user-images.githubusercontent.com/5263460/79353586-889cd900-7f3b-11ea-9a4c-a8ad80b7d2ac.png)
![image](https://user-images.githubusercontent.com/5263460/79353612-918daa80-7f3b-11ea-9712-5258181ddb79.png)

**Comment by ChrisAnd1998** [comment]
Hmm, FalconX should fix that automatically already...
Also TaskbarX has just been published you may want to try to update as it may fix it. It's a whole rewrite of the project and will overwrite your FalconX installation with the new update.

**Comment by krtpowa** [comment]
> Hmm, FalconX should fix that automatically already...
> Also TaskbarX has just been published you may want to try to update as it may fix it. It's a whole rewrite of the project and will overwrite your FalconX installation with the new update.

I just opened windows store and it was updated, seems to have corrected this problem! Thank you!

**Comment by ChrisAnd1998** [comment]
Great!
