### ISSUE TITLE
TaskbarX just not working at all after it was changed to TaskbarX 

### ISSUE THREAD

**Issue by andylmfao** [ChrisAnd1998/TaskbarX#227]
As you can see in the video, the farthest i got it do was make it transparent. But it doesn't center at all, and only actually does it when the program Isn't even running. And when i open TaskbarX after i click apply, it just goes solid again.

https://send.firefox.com/download/3d79c0f7a9fdb815/#wi8NtrHvkumcg7eVS9ulgQ here's the video, hope this can get resolved.

**Comment by ChrisAnd1998** [comment]
Can you replace the TaskbarX.exe with this one? This one will show a message box on any error.
[TaskbarX.zip](https://github.com/ChrisAnd1998/TaskbarX/files/4487239/TaskbarX.zip)

**Comment by andylmfao** [comment]
I'll try to do this tomorrow. For some reason, after a few hours, it centered itself. I didn't do anything at all in between those two. Very strange.

**Comment by ChrisAnd1998** [comment]
Allright XD, i'll wait.

**Comment by ChrisAnd1998** [comment]
@andylmfao Do you still have the issue?
