### ISSUE TITLE
After update not working properly

### ISSUE THREAD

**Issue by ThorstenWirth** [ChrisAnd1998/TaskbarX#228]
At startup i get the following error:
> shell:AppsFolder\40210ChrisAndriessen.FalconX_y1dazs5f5wq00!TaskbarX 
> Klasse nicht registriert

Changes to settings are not persistent.

**Comment by ChrisAnd1998** [comment]
What hapens if you open cmd.exe an run the following command

/c start shell:AppsFolder\40210ChrisAndriessen.FalconX_y1dazs5f5wq00!TaskbarX

**Comment by elajits** [comment]
hey having the same issue getting this message in PowerShell
![bild](https://user-images.githubusercontent.com/8584951/79537009-9ceaee00-8081-11ea-833c-eb0b018e6ac0.png)

**Comment by ChrisAnd1998** [comment]
@elajits Can you enter Get-AppxPackage in powershell? It should list all applications.
Scroll down and look for TaskbarX i think its the last one. I would like a screenshot of that. As that may explain this error.

**Comment by elajits** [comment]
@ChrisAnd1998 i getting this messages

![bild](https://user-images.githubusercontent.com/8584951/79538394-93af5080-8084-11ea-83e0-d75f1d4d6f8e.png)

**Comment by ChrisAnd1998** [comment]
Thx! currently looking...

**Comment by elajits** [comment]
but the problem starts for me when after i uninstalling it at every login i facing this message!
![bild](https://user-images.githubusercontent.com/8584951/79538699-20f2a500-8085-11ea-9513-5fa9e3b73611.png)

**Comment by ChrisAnd1998** [comment]
Can you execute this in powershell?
**cmd.exe /c start shell:AppsFolder\40210ChrisAndriessen.FalconX_y1dazs5f5wq00!TaskbarX -taskbarstyle=1**

**Comment by elajits** [comment]
@ChrisAnd1998 getting the same message as i get when i login to windows
![bild](https://user-images.githubusercontent.com/8584951/79539224-2f8d8c00-8086-11ea-9358-004bd5e12efa.png)

**Comment by ChrisAnd1998** [comment]
Wait your'e trying to uninstall...
If you uninstalled it then you should open taskscheduler and remove the TaskbarX.
![ddd](https://user-images.githubusercontent.com/50437199/79539391-85623400-8086-11ea-830e-ca643210583c.png)

I thought you where getting this error after installation according to this issue.

**Comment by elajits** [comment]
@ChrisAnd1998 Yea! okay ill try that! i just testing it on my school pc! :)
i did not have any problems whit it when it was installed! 👍 

thx for fast support and keep up the good work! 🥇

**Comment by ChrisAnd1998** [comment]
No problem! :)

**Comment by elajits** [comment]
@ChrisAnd1998 Yea! okay ill try that! i just testing it on my school pc! :)
i did not have any problems whit it when it was installed! 👍 
thx for fast support and keep up the good work! 🥇

**Comment by ChrisAnd1998** [comment]
@ThorstenWirth  i would like you to do the same thing.

**Comment by ThorstenWirth** [comment]
Removing the entry in taskschd.msc removed the error at startup, but no FalconX/TaskbarX at startup (obviously).
Running the TaskbarX Configurator and applying the settings reintroduced the error at startup.
Manually running  `cmd.exe /c start shell:AppsFolder\40210ChrisAndriessen.FalconX_y1dazs5f5wq00!TaskbarX -taskbarstyle=0 -animationstyle=elasticeaseinout -onbatteryanimationstyle=bounceeaseinout -animationspeed=100 -centerinbetween=1 -looprefreshrate=400 -onbatterylooprefreshrate=100 -fixtoolbarsontraychange=1`  started the application without error

**Comment by ChrisAnd1998** [comment]
Hmm, i don't understand why the taskscheduler does not work as it runs the exact same command.

**Comment by ChrisAnd1998** [comment]
@ThorstenWirth And setting a delay using the configurator also doesn't work? Try setting it to like 10 seconds instead of 3.

**Comment by ThorstenWirth** [comment]
> And setting a delay using the configurator also doesn't work? Try setting it to like 10 seconds instead of 3.

Where? There is no setting for that.
![Anmerkung 2020-04-17 193704hfjhfhgf](https://user-images.githubusercontent.com/31453908/79597807-38607b00-80e3-11ea-8457-f67982ba855b.png)

**Comment by ChrisAnd1998** [comment]
@ThorstenWirth Ohh XD you need update 1.5.2.0 for that.

**Comment by ThorstenWirth** [comment]
`powershell.exe Start-Process 'shell:AppsFolder\40210ChrisAndriessen.FalconX_y1dazs5f5wq00!TaskbarX' -Args '-taskbarstyle=0 -animationstyle=elasticeaseinout -onbatteryanimationstyle=bounceeaseinout -animationspeed=100 -centerinbetween=1 -looprefreshrate=400 -onbatterylooprefreshrate=100 -fixtoolbarsontraychange=1'` did nothing.

`cmd.exe powershell.exe Start-Process 'shell:AppsFolder\40210ChrisAndriessen.FalconX_y1dazs5f5wq00!TaskbarX' -Args '-taskbarstyle=0 -animationstyle=elasticeaseinout -onbatteryanimationstyle=bounceeaseinout -animationspeed=100 -centerinbetween=1 -looprefreshrate=400 -onbatterylooprefreshrate=100 -fixtoolbarsontraychange=1'` did nothing but open an empty commandline window.


Ok - the update has installed - the settings are persistent.
After applying the settings and reboot the same error
![Anmerkung 2020-04-17 000738](https://user-images.githubusercontent.com/31453908/79600332-47e1c300-80e7-11ea-88bf-b6f9013b0f92.png)

**Comment by ChrisAnd1998** [comment]
@ThorstenWirth I'am confused 😵. What build of Windows 10 is it?

**Comment by ThorstenWirth** [comment]
ok ... had to reboot windows because of something other - now TaskbarX works fine ...
_how?!?_

**Comment by ChrisAnd1998** [comment]
Wait what! Do you ever completely restart it or just put it in sleep mode?

**Comment by ThorstenWirth** [comment]
Complete and proper reboot every time

**Comment by ChrisAnd1998** [comment]
And you updated it through the store to 1.5.2.0?

**Comment by ThorstenWirth** [comment]
Yes

**Comment by ChrisAnd1998** [comment]
🤯

**Comment by ChrisAnd1998** [comment]
Well, i guess it's fixed now...

**Comment by ThorstenWirth** [comment]
Yes - and thanks.

**Comment by ChrisAnd1998** [comment]
No problem 😁
