### ISSUE TITLE
Error Message after i Unistall

### ISSUE THREAD

**Issue by elajits** [ChrisAnd1998/TaskbarX#229]
Heyi just got TaskbarX from MS store 
But after i Unistalled TaskbarX i keep getting these messages at every login into my windows!
how do i solve this?
Thx!

![2020-04-17](https://user-images.githubusercontent.com/8584951/79536075-6c09b980-807f-11ea-8909-737b424316ca.png)

**Comment by ChrisAnd1998** [comment]
Fix for this issue.

If you uninstalled it then you should open taskscheduler and remove the TaskbarX entry.
![ddd](https://user-images.githubusercontent.com/50437199/79539391-85623400-8086-11ea-830e-ca643210583c.png)

**Comment by WinObs** [comment]
Just filed a bug on the error and then found this and was able to remove the entry. Shouldn't this be cleaned out when the uninstall happens?

**Comment by ChrisAnd1998** [comment]
@WinObs I will be able to do this on the regular version. But the store version has no such option on uninstall. I can add an option in the configurator to remove the taskschedule.

**Comment by WinObs** [comment]
That would be a good option.

Thanks.

Sent from Outlook Mobile<https://aka.ms/blhgte>
________________________________
