### ISSUE TITLE
[TaskbarX v1.5.2.0 Portable] "Compensate for tray, clock" doesn't work; no startup task.

### ISSUE THREAD

**Issue by Darthagnon** [ChrisAnd1998/TaskbarX#230]
I'm using TaskbarX v1.5.2.0, extracted from the release ZIP on Win10 v1709.

Whenever I tick "compensate for tray, clock, etc.", nothing happens, and it resets the checkbox when I restart the configurator.

It also hasn't created a startup task with command-line args, as I understand it's supposed to.

Am I doing something wrong? Does it need installing (not portable-ish any more)?

**Comment by Darthagnon** [comment]
I looked through other open issues, and decided to test taskbar styling, too. This isn't working at all, either :'(

**Comment by ChrisAnd1998** [comment]
Just want to let you know i have seen your issue. Currently working on a different issue that might fix It 

> also hasn't created a startup task with command-line args, as I understand it's supposed to.

**Comment by Darthagnon** [comment]
Thank you! 
PS v1.5.3.0, compensate for tray, clock, etc. now crashes on the second click of Apply (e.g. tick the box, Apply, untick the box, Apply, configurator crash)
