### ISSUE TITLE
Error After Uninstall

### ISSUE THREAD

**Issue by WinObs** [ChrisAnd1998/TaskbarX#231]
Looks like something in startup process has been left behind after uninstalling TaskbarX. Upon reboot I get this error every time after uninstalling.

Have tried to reinstall (purchased via Windows Store) and stop the task again and then uninstall but get the same error.

![Annotation 2020-04-18 073509](https://user-images.githubusercontent.com/40800748/79636861-e2262300-8148-11ea-8efb-0d1679418a10.png)

**Comment by ChrisAnd1998** [comment]
I have added a button in 1.5.3.0 to remove the taskschedule.
The update is in submission to the store but will only be updated on a working day.
