### ISSUE TITLE
TaskbarX microsoft store version not working

### ISSUE THREAD

**Issue by ZeonKing** [ChrisAnd1998/TaskbarX#232]
Hi, sometimes when using taskbarx it doesn't work properly, sometimes it does not center the pinned apps (but it is transparent) and sometimes it does not work at all. And usually it doesn't work right when I boot my laptop instead it suddenly works in the middle

**Comment by ChrisAnd1998** [comment]
@ZeonKing Currently update 1.5.3.0 is in submission to the store which might fix the issues you're experiencing. I will get back to this issue when it's published.

**Comment by ChrisAnd1998** [comment]
@ZeonKing So even 1.5.4.0 is now published. Do you still have this issue?

**Comment by ZeonKing** [comment]
It still doesn't work right after start up but after a while it works(faster than before). And since 1.5.3.0 the task bar config does not respond for a while

**Comment by ChrisAnd1998** [comment]
@ZeonKing Allright, then i need more info about your PC to understand why it's behaving like that.

I would like to know:
Your build of Windows 10.
What software you have installed.
If you use any other taskbar tweaking tools.

Maybe even a video displaying the issue.

**Comment by ZeonKing** [comment]
I use Windows 10 pro build 18363.778
The only software I installed are steams and some games, wallpaper engine and rainmeter others are just Microsoft office stuff
I used transparent taskbar before but I have uninstalled it

**Comment by ChrisAnd1998** [comment]
Allright, thanks i will be trying to reproduce this tomorrow. You will hear from me.

**Comment by ChrisAnd1998** [comment]
@ZeonKing Wallpaper Engine doesn't show me any issues. Same goes for Steam and Rainmeter with default skins.

Can you give me a list with all the skins you are using in Rainmeter?
