### ISSUE TITLE
Taskbar flickers (or flashes) when the Acrylic style is on

### ISSUE THREAD

**Issue by misaeldry** [ChrisAnd1998/TaskbarX#233]
Hello!

I am using the Acrylic style. It makes me really happy. There's an issue, though. Whenever I click on the Windows logo and the start menu comes up, the taskbar flickers to dark (I guess because the system default color theme is Dark mode). The taskbar also flickers after closing the start menu clicking somewhere else.

Here's a video on Google Drive:
https://drive.google.com/file/d/1nDP-iQDfXSQWi6xUAJ3vG-2FWv7_zANd/view?usp=sharing

Is there a way to fix this?
There's another detail. When using the Blur style, it seems that the blur sharpens at the bottom of the taskbar. Here's also a pic of this.

![Taskbar X Blus style](https://user-images.githubusercontent.com/33500/79703581-47296800-8272-11ea-881b-3402c47f6b3b.JPG)

I'm thrilled with my icons in the middle of the taskbar.
Thank you.

**Comment by ChrisAnd1998** [comment]
TaskbarX/FalconX had this issue for a long time now and i haven't found a fix for it yet 😓. This only happens with Acrylic. While transparent and blur work in the exact same way as Acrylic the taskbar reacts differently to it. I am still trying to find another way.

Does TranslucentTB give you the same issues?

**Comment by misaeldry** [comment]
Yes. There's the same issue with TranslucentTB (it's called "Fluent" there). The rest of the effects are ok. Just that one flickers. I'm sure that answer will come to you soon! It is a great app already!

**Comment by softtama** [comment]
I'm on the latest stable 1.5.6.0 and also experienced the same issue.

The issue reproduction:
1. Click Start button to open Start menu -> flicker
2. Click Start button to close Start menu
3. Click Start button to open Start menu -> not flicker
4. Click on another area to close Start menu -> flicker
5. Click Start button to open Start menu -> flicker
