### ISSUE TITLE
Auto arrange function not working if no app is on laptop display.

### ISSUE THREAD

**Issue by baseband5** [ChrisAnd1998/TaskbarX#234]
Steps to reproduce:
Laptop with 2 extra monitors, one of them set as default (not the laptop screen)
If no icons on laptop display is present, no autoarrange is done.
After opening at least 1 app and move window to laptop display all magic happen immediately

**Comment by ChrisAnd1998** [comment]
What version are you using? The store version 1.5.3.0 has just been published which contains a fix for the Taskbar setting: show only icon on taskbar where window is open.

**Comment by baseband5** [comment]
1.5.3.0
I'm no longer in need to work on 3 screen setup. Strange but when I moved from install to portable build problem was present about 2 days but after I messed something with configurator It disapeared.
Still no clue if it was problem with old configuration still present somewhere in system.
