### ISSUE TITLE
Can't apply changes

### ISSUE THREAD

**Issue by 0neEyed** [ChrisAnd1998/TaskbarX#238]
I choosed transparent on style then apply when I reopen taskbarX it sets default. TaskbarX also doesn't run at startup. My ver is 1.5.4.0

**Comment by ChrisAnd1998** [comment]
@0neEyed You're on Win10 1709 right?

**Comment by 0neEyed** [comment]
I am on 1909. It didnt have any problems before, until I reinstall it.

**Comment by ChrisAnd1998** [comment]
Hmm, when upgrading to 1909 did you do a fresh install or did you just update it from the previous build. I need to find out whats going on here.

**Comment by 0neEyed** [comment]
I update it from previous which is 1809.

**Comment by ChrisAnd1998** [comment]
That weird, it doesn't need to be run as admin...
