### ISSUE TITLE
TaskbarX visibly resetting on wallpaper change

### ISSUE THREAD

**Issue by KevReillyUK** [ChrisAnd1998/TaskbarX#243]
I have an recently observed issue with TaskbarX that's left me wondering whether the _Don't move to the left on SystemEvents.UserPreferenceChanged while restarting_ feature introduced with 1.5.3.0 (Store version) is actually working.

A quick explanation:

I run a wallpaper slideshow program ([_Wallpaper Slideshow Pro_](https://www.gphotoshow.com/wallpaper-slideshow-pro.php)) that cycles through wallpapers on my secondary monitor every 30 seconds. When it cycles the following series of events is observed:

- The wallpaper on the secondary monitor changes.
- This effectively changes the wallpaper on the primary as well, because Windows treats multi-monitor wallpapers as one giant image.
- Half a second later, the mouse cursor changes _very_ briefly to the Busy mode, as though Windows is refreshing something.
- Half a second after that, TaskbarX jumps to the left then back to the centre.

I'm reasonably confident that all of these events have been consistent over the past few Windows Updates but the last one, with TaskbarX jumping around, is definitely new as of a day or so ago.

From the What's New for 1.5.3.0 these two struck me as possibly pertinent:

- _Restart on SystemEvents.UserPreferenceChanged_ 
- _Don't move to the left on SystemEvents.UserPreferenceChanged while restarting. Making the restart invisible._

I'm not a developer, but I know that changing wallpapers is one of the things that triggers _SystemEvents.UserPreferenceChanged_. To my untrained eye it almost looks as though the first of these changes has been applied but that the second isn't working.

Is there any chance I can have a confirmation that this is definitely not a bug in TaskbarX before I start looking elsewhere? Because there are a lot of other options to explore -- not least of which is a significant recent Windows update -- and I really don't want to go down the rabbit hole if I don't have to.

In the meantime I've reduced the frequency of the wallpaper change to stop TaskbarX doing an Irish jig every few seconds.

TIA for any assistance.

**Comment by KevReillyUK** [comment]
Just an FYI: I uninstalled the Store version and tried some of the standalone versions and I can confirm that 1.5.3.0 with the old-school configurator does **not** exhibit this behaviour, but 1.5.4.0 **does**. I guess it was the automatic TaskbarX update from the Store that broke things here, not Windows Update which is a relief.

I can't begin to guess why a changing the configuration UI would have introduced this bug, but I'll stick with the non-Store 1.5.3.0 for now until it's resolved.

Thanks for a great little utility. It tames the taskbar on my ultrawide monitor like no other. Before it the distance I was having to cover with the mouse just to switch apps was insane.

**Comment by ChrisAnd1998** [comment]
@KevReillyUK I actually disabled the feature that allowed TaskbarX to stay in the middle when SystemEvents.UserPreferenceChanged triggers. I did this because, it never happened randomly and only when you do change your settings by yourself. I'll try to filter out what changed (if possible). And just skip the wallpaper change. If that doesn't work i'll just enable it again ;)

**Comment by KevReillyUK** [comment]
Thanks. Don't change it back if there's a risk of it breaking anything else, but it would be useful to have it back.

I'm just glad I'm not going crazy. The problem is this system only gets rebooted once in a while (mostly it just sleeps and resumes) so programs that get updated in the background can have legacy versions running for ages before a forced reboot runs the newer versions all at once. It can make understanding new behaviours tricky. This one was relatively simple compared with some of the head-scratchers it's caused over the years.

**Comment by ChrisAnd1998** [comment]
XD, Well TaskbarX only allows 1 instance of itself. So replacing the exe will always work.
I just found the way to filter the **SystemEvents.UserPreferenceChanged** event.
It's now set to only restart on **UserPreferenceCategory.General** the wallpaper change is not a part of this category.

The Pre-Release is right here for if you want to test it out.
https://github.com/ChrisAnd1998/TaskbarX/releases/tag/1.5.5.0

**Comment by KevReillyUK** [comment]
That's working great, thanks. I put the latest standalone 1.5.4.0 on and made sure it was misbehaving, then overwrote it with the 1.5.5.0 .exe and everything's stable again. If only all tech support was this efficient.

I'm not sure what the GitHub etiquette is when it comes to closing reports but I'm tempted to leave this as it is for now (just in case by some bizarre coincidence there's someone else out there using a fast wallpaper changer and looking for answers), then mark it as closed once the Store version drops. But if you want to close it now please do so.

**Comment by ChrisAnd1998** [comment]
Allright! I'm happy it's fixed now. I'll leave it open until full release. There might be a little tiny chance someone is running into the same issue 😁

**Comment by hapiscalin** [comment]
I have the same issue. I brought the pro version from the store. I just have multiple backgrounds that change every 30 minutes but every time it changes it resets the TaskbarX

**Comment by ChrisAnd1998** [comment]
@hapiscalin Yes, it will fixed when i fully release 1.5.5.0.
