### ISSUE TITLE
[wish] Refresh Rate setting tooltip

### ISSUE THREAD

**Issue by JovialMockingbird** [ChrisAnd1998/TaskbarX#244]
Windows Store version of TaskbarX 1.5.4.0

Hi, 
As someone who likes to tinker with software at a user level but doesn't have programming experience the refresh rate setting has me confused. It wasn't immediately obvious to me if the setting was for a delay or some kind of polling rate. Through some trial and error I think it is for setting delay. 
I was wondering if there are any performance penalties for a lower or higher setting and if there is a recommended range? Additionally I'd like to suggest a rephrasing or some kind of tool tip for the setting to clarify what it does. 

![taskbarx configurator refresh rate](https://user-images.githubusercontent.com/30690488/80109513-de960000-857d-11ea-8bc9-6703b67f3c5f.jpg)

**Comment by Martin5001** [comment]
I think this kind of information is meant to be placed on the right side - look in Windows settings for reference. I think that would be a better solution than tooltips according to the Fluent Design guidelines.
