### ISSUE TITLE
TaskbarX just not working and closing, then i try to change settings

### ISSUE THREAD

**Issue by BevirAway** [ChrisAnd1998/TaskbarX#245]

**Comment by ChrisAnd1998** [comment]
Can you give me any information about your PC?
Any error messages?

I need a clue.

**Comment by BevirAway** [comment]
No error is shown. Windows version is 1909. I have Ryzen 5 1600x. gtx 1070.

**Comment by ChrisAnd1998** [comment]
Does this Pre-Release make a difference?
https://github.com/ChrisAnd1998/TaskbarX/releases/tag/1.5.5.0

**Comment by BevirAway** [comment]
No changes

**Comment by ChrisAnd1998** [comment]
Any older version that does work?
https://github.com/ChrisAnd1998/TaskbarX/releases

**Comment by BevirAway** [comment]
1.5.0.0 works great

**Comment by ChrisAnd1998** [comment]
Oh wow, then you're getting really close.
Can you try to go up and tell me what version breaks?
Then i can look through the update logs to see what might causes it to crash.
