### ISSUE TITLE
Icons missing in taskbar

### ISSUE THREAD

**Issue by higoorc** [ChrisAnd1998/TaskbarX#246]
![image](https://user-images.githubusercontent.com/42069752/80217556-d00c1f00-8637-11ea-9cac-45415f0a53e6.png)

The link still working to open all applications, but the icons is just missing, just Spotify still there. This happened after hybernate the Windows.

My folder C:\Users\USER-Admin\AppData\Roaming\Microsoft\Internet Explorer\Quick Launch\User Pinned\TaskBar was completed empty after that. And I figured out the Spotify stay there because Spotify never appears here, all the others applications do.

If I remove from taskbar and add it again of course It works, but it's really annoying.

(it was in the Windows Store paid version)

**Comment by ChrisAnd1998** [comment]
Weirdly enough i got this same issue in the insider preview fast ring 2004 one week ago. Yesterday it updated again and now it's fixed for me. I doubt it's TaskbarX doing this as it has no access at such level and only gets the bounding rectangle of the last item in the taskbar.
