### ISSUE TITLE
Not working properly in multi desktop

### ISSUE THREAD

**Issue by AndersonALAC** [ChrisAnd1998/TaskbarX#247]
![image](https://user-images.githubusercontent.com/43598111/80251665-9293aa00-86a8-11ea-990d-8d7baca64eb6.png)
Switching between multiple desktops causes this problem, the offset of one desktop is not changing after switching and cause the tabs go over the border. open or close tabs on this desktop is not updating the taskbar. 
it seems that only one desktop has this problem at the first time, but when i restarted taskbarx with the configurator, it fixed that desktop but all other desktops had the same problem.

I'm using 1.5.4.0 from ms store, on win10 1909 build 18363.778

**Comment by ChrisAnd1998** [comment]
@AndersonALAC How can i reproduce this in steps?
I can't get it to behave like that.

**Comment by AndersonALAC** [comment]
> @AndersonALAC How can i reproduce this in steps?
> I can't get it to behave like that.

- Use "When Taskbar is full" of "Combine taskbar buttons" option in windows settings
- close all other desktops
- open 9 or more windows on the desktop
- open taskview and drag a window on the "New Desktop" button
- switch between the desktops

my arguments are: -taskbarstyle=2 -animationstyle=quadeaseinout -onbatteryanimationstyle=quadeaseinout -animationspeed=200 -primarytaskbaroffset=0 -secondarytaskbaroffset=0 -centerinbetween=1 -looprefreshrate=150 -onbatterylooprefreshrate=200 -fixtoolbarsontraychange=1

**Comment by ion-elgreco** [comment]
I have the same issue. When you have on both virtual desktops multiple applications open. One of the desktops the taskbar applications will be off-center. Taskbarx should center all applications for each virtual desktop on the taskbar. I think it now sets the center for one virtual desktop and keeps it for the other one, even though everything will be off-center.

**Comment by prediscover** [comment]
Yea. When you restart Taskbar x on one desktop, it will center it for that taskbar but then when you switch back to another desktop with lesser/different # of windows, it stays at the same position. It should refresh when switching to another desktop

**Comment by wh1FF** [comment]
![2020-08-05 20 02 51](https://user-images.githubusercontent.com/69248771/89416080-f2ddc180-d756-11ea-8350-1facc1c2217c.png)
I have the same exact problem too. Screenshots of both virtual desktop included.

**Comment by AndersonALAC** [comment]
It now seems to be working just fine (1.6.1.0 on Windows 10 2004 19041,508), maybe this issue can be closed
