### ISSUE TITLE
[req] Help out windows terminal with persistant acrylic.

### ISSUE THREAD

**Issue by NicTanghe** [ChrisAnd1998/TaskbarX#248]
Hello not sure how similar both apps are but after starting to try and help people fix things i'm frustrated with in windows i got the idea to ask you to help out the windows terminal people to make acrylic persistent.  it seems they gave up for no good reason and just shoving of responsibility.

Could you have a look at this ticket ?
https://github.com/microsoft/terminal/issues/603

titl doesn't make sense but it's where they want it discussed i think.

**Comment by ChrisAnd1998** [comment]
It's written in C++ which is not a coding language i know. I kinda understand it but, i don't have the knowledge to write in it. This is something they need to do their selfes. TranslucentTB has a good demonstration in C++ on how to accomplish this. I think they can help better with this 😉
