### ISSUE TITLE
Move Start Button, Search, Cortana, and Task View to center too

### ISSUE THREAD

**Issue by ghost** [ChrisAnd1998/TaskbarX#25]
# #
Example

![image](https://user-images.githubusercontent.com/16917061/66089375-37358980-e5a9-11e9-9a4d-ee9e68a5abe7.png)

**Comment by ChrisAnd1998** [comment]
I can stick them to the icons so it's totally possible. The only problem is that i cant move to start menu itself so it would still popup on the left side.

Here an example video with the start button only.

[![Alt text](https://chrisandriessen.nl/web/img/2019-10-04-20-44-48.jpg)](https://chrisandriessen.nl/web/img/2019-10-04-20-44-48.mp4)

**Comment by Vulcanraven91** [comment]
Maybe try to hook the startmenu class?

**Comment by ChrisAnd1998** [comment]
I have tried that but, the startmenu is not responding to SetWindowPos. It's just locked.
Also AutoIt, Autohotkey and other gui inspect tools are unable to move it.

**Comment by jerryshaw12** [comment]
maybe you should make your own start menu haha /jk

**Comment by pc-v2** [comment]
would you add this? maybe useful for full-screen start-menu?

**Comment by adarshhegde** [comment]
it would be cool to move it to the right  and have it be user configurable on what should run when the user clicks it, like specifying an executable or batch file to be run, people could do cool stuff with it
