### ISSUE TITLE
Top Taskbar Issue

### ISSUE THREAD

**Issue by adhamsalama** [ChrisAnd1998/TaskbarX#250]
I have my taskbar at the top and the icons overlap the opened program.

This only happens when I'm using browsers (Firefox and Edge) and TaskbarX transparent style.

[Here's how it looks like with and without TaskbarX](https://imgur.com/a/JDixPzj)

**Comment by ChrisAnd1998** [comment]
Sadly this is something i can't fix. Because it's not caused by TaskbarX. This indeed only happens with browsers... Chrome does it too.
