### ISSUE TITLE
Feature Requested: Separate pinned apps and open apps, sort by name, and Folder as list

### ISSUE THREAD

**Issue by magi44ken** [ChrisAnd1998/TaskbarX#251]
Hi,

Please consider the following feature request.

1. Separate pinned apps and open apps into two sections. Add a setting to allow user to choose which layout to use.

2. Sort open apps by app name. This makes it easier to find an app. Add a setting so user can choose between sort by when it pinned orby app name.

3. Pin Folder and show it as list when mouse hover it. For example, I might create folder with all power shortcuts such shut down, sleep, logout, etc. and pin folder to taskbar. When I move the mouse over it display it as list to select.

**Comment by ChrisAnd1998** [comment]
Atm i have no position control over the icons them selves. I also don't know if it's possible at the level TaskbarX works. TaskbarX controls the taskbar from outside using MSAA. 

I will keep it here for if i find a way.

**Comment by teddy3501** [comment]
Enabling quick launch button in addition to using TaskbarX may be a good temporary solution.  
See steps here:
https://www.howtogeek.com/howto/windows-7/add-the-quick-launch-bar-to-the-taskbar-in-windows-7/
Works in Win 10.
