### ISSUE TITLE
Error at startup, even if TaskbarX is deleted

### ISSUE THREAD

**Issue by Domiking001** [ChrisAnd1998/TaskbarX#252]
![image](https://user-images.githubusercontent.com/64316364/80281462-9e648800-870b-11ea-8f3a-26b97e16a252.png)

This happens on every startup, i can easely lick it away but TaskbarX don't start automatically i need to turn it on manually.

Strangely after deleting TaskbarX, this issue still happens every time, and i don't know what to do

**Comment by hayderux** [comment]
me too ...

**Comment by ChrisAnd1998** [comment]
In your startmenu search for "**Task Scheduler**".
On the left menu click on "**Task Scheduler Library**". In the middle a list will appear.
Right click on the "**TaskbarX**" or "**FalconX**" entry and click "**Delete**". Problem solved ;)

**Comment by Domiking001** [comment]
Thank you :-)
