### ISSUE TITLE
(1.5.5.0 Preview) Taskbar positioned to the right instead of center

### ISSUE THREAD

**Issue by Martin5001** [ChrisAnd1998/TaskbarX#253]
Taskbar moves to the right like this:
![image](https://user-images.githubusercontent.com/35201200/80309811-822e1d00-87d7-11ea-9c10-25413a4f5792.png)
I tried toggling some of the new settings on and off (pause looper, maximized window) to see if it has something to do with it, but no change. EDIT: Position offset was set to default 0 px - changing it to about -400 centered it on my 1920x1200 screen. But that´s just a workaround.

**Comment by ChrisAnd1998** [comment]
Oww that should'nt happen XD. Have been working all day on this version. 
Tommorrow i am going to test it on some different PC's. So i hope i come across the same issue.

**Comment by ChrisAnd1998** [comment]
@Martin5001 Allright, i think it's fixed now. It was looking for the taskbar toolbar named "running applications" but that doesn't work if Windows is installed in another language. So now it's finding it by it's role which is **22** (toolbar).

**Comment by Martin5001** [comment]
@ChrisAnd1998 It works now. Thanks

**Comment by ChrisAnd1998** [comment]
Thanks for testing :)
