### ISSUE TITLE
UWP version doesn't work at startup, I need to close it and re-open it (v1.5.4.0 on W10 1909)

### ISSUE THREAD

**Issue by franubis** [ChrisAnd1998/TaskbarX#254]
Hello, acquired the software through the Windows Store, and while it works perfectly fine during the first time, problems arise when shutting down or rebooting the PC.

Upon turning back the PC or rebooting, the taskbar is as default with no settings from TaskbarX carrying over whatsoever, not even the icons location.

I open the task manager and I can see that TaskbarX is indeed open but nothing, and I open the Configurator and it shows the settings that were enabled before turning the PC off.

Reopening TaskbarX itself doesn't help either, neither does ending the process I've mentioned through the task manager.

The only thing that solves it is to open the Configuration, click on "Stop TaskbarX" and then click on the main program to have it run.
I don't have any software related to Windows customization installed, nothing like Wallpaper Engine or anything else that may affect either the taskbar or anything related to Windows.

**Comment by ChrisAnd1998** [comment]
In the configurator there is a **Delay** option for the **Taskschedule** which may fix it if you increase the value.

**Comment by franubis** [comment]
Thanks, something related to that worked. Setting the scheduled task's delay within Task Manager to zero actually did it.

**Comment by ChrisAnd1998** [comment]
Oh well thats surprising :) 0 sec doesn't work on my end XD but, i'm happy that fixed it.
