### ISSUE TITLE
Heuristic Virus report on Virustotal

### ISSUE THREAD

**Issue by aarya-agarwal** [ChrisAnd1998/TaskbarX#256]
When downloading TaskbarX from you website https://chrisandriessen.nl/taskbarx/ and checked the file on VirusTotal the file is flagged as a Heuristic Virus from 1/61 engines.

**Comment by ChrisAnd1998** [comment]
Yep, i saw it. Actually doing a rescan resulted in **2/72**. The 2 that are flagging TaskbarX are **SecureAge APEX** and **Sophos ML**. After a bit of research these 2 joined VirusTotal very recently and are both based on Artificial Intelligence. I will try to contact them about the false positives ;)

**Comment by ionut-botizan** [comment]
Any news on this issue?
Recently, my company switched to Sophos and today I had the "pleasure" of it cleaning up a threat on my machine...

> Generic ML PUA detected at C:\Users\botizani\Desktop\MouseWithoutBorders\Release\TaskbarX.exe

---

For now I just removed the code that was initializing the `TaskbarStyler` thread and the `ResetTaskbarStyle` function (I use Translucent TB for styling as it provides more options so I didn't need those) and recompiled the project and that seems to be enough for Sophos ML to leave the new TaskbarX executable alone.
This works for me at the moment, but I'd rather have it installed from the store, as it was before...
