### ISSUE TITLE
Uninstall Issue

### ISSUE THREAD

**Issue by raymond-dillon** [ChrisAnd1998/TaskbarX#257]
Hi, 

I have uninstalled the application but my icons remain centred.

How can I revert back completely?

Thank you!

**Comment by felincoli** [comment]
same issue 
https://i.imgur.com/GT8bO3f.png

**Comment by raymond-dillon** [comment]
My issue is slightly different - uninstall is fine - but changes to the positioning of the taskbar icons doesn't return to normal after the uninstall.

**Comment by LtCmdrKeene** [comment]
After uninstalling this from the MS App Store, I'm getting an error on every system boot up. I uninstalled it from the Start menu by simple right-click. I didn't even know there was a way a store app could uninstall un-cleanly, but apparently it happened. How do I fix this?

[Window Title]
shell:AppsFolder\40210ChrisAndriessen.FalconX_y1dazs5f5wq00!TaskbarX
Windows cannot find 'shell:AppsFolder\40210ChrisAndriessen.FalconX_y1dazs5f5wq00!TaskbarX'. Make sure you typed the name correctly, and then try again.

**Comment by ChrisAnd1998** [comment]
@LtCmdrKeene 
There is an explanation here:

https://chrisandriessen.nl/taskbarx

And here

https://github.com/ChrisAnd1998/TaskbarX

**Comment by LtCmdrKeene** [comment]
Thank! I had searched the issues tab, I definitely should have checked the full readme. Thanks again!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by ChrisAnd1998** [comment]
@LtCmdrKeene No problem 👍

**Comment by GittyMac** [comment]
I've got this issue too, it doesn't seem to fully uninstall, as TaskbarX.exe and some DLLs are still in the installation directory.
