### ISSUE TITLE
TaskbarX occasionally restarts (maybe?), icons go to the left, then back to the middle.

### ISSUE THREAD

**Issue by CVFireDragon** [ChrisAnd1998/TaskbarX#259]
Title, does this every few minutes or so.
Not sure if this was intended, though.
Also, translucent taskbar. Everything else is default.

There's a video of it happening [here](https://github.com/ChrisAnd1998/TaskbarX/files/4555284/taskbarxerror.zip)
Or [here](https://streamable.com/yveyzf) if you don't wanna download it.

**Comment by Martin5001** [comment]
Same for me

**Comment by ChrisAnd1998** [comment]
Will be fixed next update
