### ISSUE TITLE
Class Not Registered Error

### ISSUE THREAD

**Issue by ashrithr** [ChrisAnd1998/TaskbarX#262]
I am frequently running into this issue:

![image (1)](https://user-images.githubusercontent.com/1916107/80728948-114c7500-8af7-11ea-988a-63bbbe06fe85.png)

Any workaround?

**Comment by prediscover** [comment]
**Steps to reproduce**
> Start up computer or log off and log on again

**Current behaviour (bug)**

> Window (pictured in OP) appears, TaskbarX does not launch and run.

**Expected behaviour (correct)**

> No windows pop up upon login, Taskbar X starts

Getting this one too. It also opens a cmd window, blank. 

OS: Windows 10 build19619
TaskbarX Version 1.5.4.0 Microsoft Store Ver

**Comment by ChrisAnd1998** [comment]
Increasing the Taskschedule delay in the configurator might fix it.

**Comment by ashrithr** [comment]
Changing the Delay to 10 secs seems to have fixed it.
