### ISSUE TITLE
(1.5.5.0 Preview) Performance issues (?)

### ISSUE THREAD

**Issue by Martin5001** [ChrisAnd1998/TaskbarX#263]
The older of my two PCs is normally quite slow but now it hangs even more. Had to do a few hard shutdowns even. I suspect it could be my antivirus scanning the program everytime it runs but I can't confirm that. Interestingly it didn't slow down as much with earlier builds of 1.5.5.0 release – the first one or two builds (before the installer) were fine.
Should I test something specifically?

**Comment by ChrisAnd1998** [comment]
I noticed it getting laggy to... the new feature "Default taskbar on maximized window" was causing this. I made some changes and i think it's fixed now. Would be very happy if you want to test it again :)

**Comment by ChrisAnd1998** [comment]
@Martin5001 I have delayed that feature now for 1.5.6.0. It was a disaster. When a window was maximized TaskbarX was ok but, Explorer.exe will start eating CPU usage like crazy. So i have go with a different take. The command to set the taskbar style to default causes it.
