### ISSUE TITLE
Feature Request: Icons background

### ISSUE THREAD

**Issue by CypherPotato** [ChrisAnd1998/TaskbarX#264]
Background only behind the icons bar, not the entire taskbar, just like Mac.

Or make some shadow, idk. It's hard to see which apps is active in a white background.

**Comment by brunih** [comment]
Yes but also make it an option, and if possible also make an option to add background only in the right side (where there's clock, icons, etc...) and in the left side (start button)
If possible also add a way so we can use a round rectangle background, but only IF POSSIBLE
Thanks :)
