### ISSUE TITLE
Error on restart following uninstall

### ISSUE THREAD

**Issue by goldngreen** [ChrisAnd1998/TaskbarX#265]
Hi,

I installed TaskbarX. I then uninstalled it. Now every time I login I get a command prompt followed by a error message:

shell:AppsFolder\40210ChrisAndriessen.FalconX_y1dazs5f5wq00!TaskbarX. Make sure you've typed the name correctly, then try again.

![TaskbarX-issue-uninstall](https://user-images.githubusercontent.com/140815/80916050-2e2eb580-8d4e-11ea-9b80-a28f40f58d17.png)

**Comment by ChrisAnd1998** [comment]
In your startmenu search for "Task Scheduler".
On the left menu click on "Task Scheduler Library". In the middle a list will appear.
Right click on the "TaskbarX" or "FalconX" entry and click "Delete".

**Comment by goldngreen** [comment]
Thanks for the prompt response. It fixed the problem. Do you not think that the uninstall should remove this task entry?

**Comment by ChrisAnd1998** [comment]
The next update will do that ;)
Sadly the store version can't do this as it has no option to do something on uninstall. Like stopping the application and removing the taskschedule.

**Comment by goldngreen** [comment]
Ok. Shame it is not fixable for the store version. Thanks again.
