### ISSUE TITLE
Constant crashes and taskbar visual changes causes a freeze

### ISSUE THREAD

**Issue by ion-elgreco** [ChrisAnd1998/TaskbarX#266]
Great application, I even bought in Microsoft store, but it is constantly crashing lately and this is very distracting while I'm working. Because the taskbar will move to the left and bounce back and this happens quite a lot. Also when I try to change the taskbar to blur or something, the configurator app will freeze and do nothing.

**Comment by ChrisAnd1998** [comment]
Today i released 1.5.5.0. In the previous versions it restarted to much because, it catched any change in Windows. Now it only restarts on necessary setting changes.

**Comment by ion-elgreco** [comment]
> @ion-elgreco Today i released 1.5.5.0. In the previous versions it restarted to much because, it catched any change in Windows. So it was not crashing just restarting ;) Now it only restarts on necessary setting changes.

Ah ok! I'll try this version out!

**Comment by ion-elgreco** [comment]
You can close this issue! :) Seems to work as before again

**Comment by ChrisAnd1998** [comment]
Allright! Thanks testing it so quickly :)
