### ISSUE TITLE
Trojan Wacatac.dlml detected

### ISSUE THREAD

**Issue by cozyplanes** [ChrisAnd1998/TaskbarX#267]
windows defender says https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3aWin32%2fWacatac.D!ml&threatid=2147749373 is detected in the setup installer of version 1.5.5.0

**Comment by ChrisAnd1998** [comment]
Yes, this is a false positive. More .NET applications have this issue atm.
https://github.com/dotnet/runtime/issues/35167

**Comment by cozyplanes** [comment]
Thanks for the clarification!
