### ISSUE TITLE
Doesnt save the configuration. After restarting pc the configuration is rested and have to setup manually

### ISSUE THREAD

**Issue by paradox-sp** [ChrisAnd1998/TaskbarX#273]

**Comment by ChrisAnd1998** [comment]
Is it the Store version or regular?
So it does run on start-up but no settings?

**Comment by Spry-T** [comment]
It is regular version and yes it does start in startup but doesnt save the configs

**Comment by ChrisAnd1998** [comment]
Can you upload the Taskschedule?

In your startmenu search for "**Task Scheduler**".
On the left menu click on "**Task Scheduler Library**". In the middle a list will appear.
Right click on the "**TaskbarX**" entry and click "Export".

Mine looks like this:
```
<?xml version="1.0" encoding="UTF-16"?>
<Task version="1.2" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">
  <RegistrationInfo>
    <Date>2020-05-05T18:45:25.64+02:00</Date>
    <Author>Chris Andriessen</Author>
    <Description>Center taskbar icons</Description>
    <URI>\TaskbarX</URI>
  </RegistrationInfo>
  <Triggers>
    <LogonTrigger>
      <Enabled>true</Enabled>
      <UserId>PC-CHRIS\Chris</UserId>
      <Delay>PT3S</Delay>
    </LogonTrigger>
  </Triggers>
  <Principals>
    <Principal id="Author">
      <UserId>S-1-5-21-129630763-3270447136-501090987-1001</UserId>
      <LogonType>InteractiveToken</LogonType>
      <RunLevel>LeastPrivilege</RunLevel>
    </Principal>
  </Principals>
  <Settings>
    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>
    <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>
    <StopIfGoingOnBatteries>false</StopIfGoingOnBatteries>
    <AllowHardTerminate>true</AllowHardTerminate>
    <StartWhenAvailable>false</StartWhenAvailable>
    <RunOnlyIfNetworkAvailable>false</RunOnlyIfNetworkAvailable>
    <IdleSettings>
      <Duration>PT10M</Duration>
      <WaitTimeout>PT1H</WaitTimeout>
      <StopOnIdleEnd>false</StopOnIdleEnd>
      <RestartOnIdle>false</RestartOnIdle>
    </IdleSettings>
    <AllowStartOnDemand>true</AllowStartOnDemand>
    <Enabled>true</Enabled>
    <Hidden>true</Hidden>
    <RunOnlyIfIdle>false</RunOnlyIfIdle>
    <WakeToRun>false</WakeToRun>
    <ExecutionTimeLimit>PT0S</ExecutionTimeLimit>
    <Priority>7</Priority>
  </Settings>
  <Actions Context="Author">
    <Exec>
      <Command>D:\Visual Studio Projects\!TaskbarX\APPX\TaskbarX\Release\TaskbarX.exe</Command>
      <Arguments>-tbs=1 -as=elasticeaseout -obas=cubiceaseinout -asp=100 -ptbo=0 -stbo=0 -lr=400 -oblr=400 -sr=0 -ftotc=1 -cfsa=1</Arguments>
    </Exec>
  </Actions>
</Task>
```

**Comment by Spry-T** [comment]
<?xml version="1.0" encoding="UTF-16"?>
<Task version="1.2" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">
  <RegistrationInfo>
    <Date>2020-05-06T07:52:49.037+05:45</Date>
    <Author>Chris Andriessen</Author>
    <Description>Center taskbar icons</Description>
    <URI>\TaskbarX</URI>
  </RegistrationInfo>
  <Triggers>
    <LogonTrigger>
      <Enabled>true</Enabled>
      <UserId>DESKTOP-AL0J2SF\prasa</UserId>
      <Delay>PT3S</Delay>
    </LogonTrigger>
  </Triggers>
  <Principals>
    <Principal id="Author">
      <UserId>S-1-5-21-110203731-3989555822-3033479852-1001</UserId>
      <LogonType>InteractiveToken</LogonType>
      <RunLevel>LeastPrivilege</RunLevel>
    </Principal>
  </Principals>
  <Settings>
    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>
    <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>
    <StopIfGoingOnBatteries>false</StopIfGoingOnBatteries>
    <AllowHardTerminate>true</AllowHardTerminate>
    <StartWhenAvailable>false</StartWhenAvailable>
    <RunOnlyIfNetworkAvailable>false</RunOnlyIfNetworkAvailable>
    <IdleSettings>
      <Duration>PT10M</Duration>
      <WaitTimeout>PT1H</WaitTimeout>
      <StopOnIdleEnd>false</StopOnIdleEnd>
      <RestartOnIdle>false</RestartOnIdle>
    </IdleSettings>
    <AllowStartOnDemand>true</AllowStartOnDemand>
    <Enabled>true</Enabled>
    <Hidden>true</Hidden>
    <RunOnlyIfIdle>false</RunOnlyIfIdle>
    <WakeToRun>false</WakeToRun>
    <ExecutionTimeLimit>PT0S</ExecutionTimeLimit>
    <Priority>7</Priority>
  </Settings>
  <Actions Context="Author">
    <Exec>
      <Command>E:\TaskbarX_03.05.2020_1.5.5.0\TaskbarX.exe</Command>
      <Arguments>-tbs=0 -as=cubiceaseinout -obas=cubiceaseinout -asp=100 -ptbo=0 -stbo=0 -cib=1 -lr=400 -oblr=400 -sr=0 -ftotc=1</Arguments>
    </Exec>
  </Actions>
</Task>

**Comment by Spry-T** [comment]
[TaskbarX.txt](https://github.com/ChrisAnd1998/TaskbarX/files/4584573/TaskbarX.txt)

**Comment by Spry-T** [comment]
```
<?xml version="1.0" encoding="UTF-16"?>
<Task version="1.2" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">
  <RegistrationInfo>
    <Date>2020-05-06T07:52:49.037+05:45</Date>
    <Author>Chris Andriessen</Author>
    <Description>Center taskbar icons</Description>
    <URI>\TaskbarX</URI>
  </RegistrationInfo>
  <Triggers>
    <LogonTrigger>
      <Enabled>true</Enabled>
      <UserId>DESKTOP-AL0J2SF\prasa</UserId>
      <Delay>PT3S</Delay>
    </LogonTrigger>
  </Triggers>
  <Principals>
    <Principal id="Author">
      <UserId>S-1-5-21-110203731-3989555822-3033479852-1001</UserId>
      <LogonType>InteractiveToken</LogonType>
      <RunLevel>LeastPrivilege</RunLevel>
    </Principal>
  </Principals>
  <Settings>
    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>
    <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>
    <StopIfGoingOnBatteries>false</StopIfGoingOnBatteries>
    <AllowHardTerminate>true</AllowHardTerminate>
    <StartWhenAvailable>false</StartWhenAvailable>
    <RunOnlyIfNetworkAvailable>false</RunOnlyIfNetworkAvailable>
    <IdleSettings>
      <Duration>PT10M</Duration>
      <WaitTimeout>PT1H</WaitTimeout>
      <StopOnIdleEnd>false</StopOnIdleEnd>
      <RestartOnIdle>false</RestartOnIdle>
    </IdleSettings>
    <AllowStartOnDemand>true</AllowStartOnDemand>
    <Enabled>true</Enabled>
    <Hidden>true</Hidden>
    <RunOnlyIfIdle>false</RunOnlyIfIdle>
    <WakeToRun>false</WakeToRun>
    <ExecutionTimeLimit>PT0S</ExecutionTimeLimit>
    <Priority>7</Priority>
  </Settings>
  <Actions Context="Author">
    <Exec>
      <Command>E:\TaskbarX_03.05.2020_1.5.5.0\TaskbarX.exe</Command>
      <Arguments>-tbs=0 -as=cubiceaseinout -obas=cubiceaseinout -asp=100 -ptbo=0 -stbo=0 -cib=1 -lr=400 -oblr=400 -sr=0 -ftotc=1</Arguments>
    </Exec>
  </Actions>
</Task>

**Comment by fooorch** [comment]
I was able to reproduce this. I added the TaskbarX in the Startup folder aside from creating the TaskSchedule from the configurator, which caused the conflict.

**Comment by softtama** [comment]
My workaround is to manually remove the TaskbarX's Task Scheduler item from the Task Scheduler and re-adding it from the TaskbarX Configurator with my preferences currently active.
