### ISSUE TITLE
TaskbarX Doesn't Appear to Run Correctly

### ISSUE THREAD

**Issue by Mattophobia** [ChrisAnd1998/TaskbarX#275]
Seemingly after installing the newest Windows 10 update (1909), TaskbarX has stopped working. I've confirmed the issue to occur on the most recent version of TaskbarX (Both the Store version and the Regular version), regardless of the application settings.

When TaskbarX is running, it doesn't actually centre the taskbar, and instead causes a regular loading icon to appear on the mouse cursor until TaskbarX is stopped. I've included a [video to demonstrate](https://youtu.be/E_1hJjXNHAQ). 

Not entirely sure how to recommend duplicating the issue since it happens no matter what for me.

**Comment by ChrisAnd1998** [comment]
In the video i can see you have made a toolbar with the recycle bin. Can you remove that and try again? It's the only thing i can see that is not tested.

**Comment by cmputerboom** [comment]
@Mattophobia I was running taskbarx on 1909 and now on 2004 and it was working (of course with some glitches). But how did you add that toolbar with the recycle bin? Im curious

**Comment by Mattophobia** [comment]
> 
> 
> @Mattophobia In the video i can see you have made a toolbar with the recycle bin. Can you remove that and try again? It's the only thing i can see that is not tested.

I've tested it without it and it still does it - it's just the quick launch toolbar option that I've finagled a recycle bin into.

I will say the more I've tested it, I've noticed the issue is more intermittent. Sometimes it actually centres for up to a minute, breaks, comes back, THEN does the issue I recorded. It wouldn't surprise me if this was just one of those random nonsensical Windows based issues that's fixed with a Windows reinstall, but TaskbarX is currently the only app with an issue.

**Comment by Mattophobia** [comment]
> 
> 
> @Mattophobia I was running taskbarx on 1909 and now on 2004 and it was working (of course with some glitches). But how did you add that toolbar with the recycle bin? Im curious

Here's a link to a guide of the Quick Launch menu if you're interested: https://www.tenforums.com/tutorials/4624-add-remove-quick-launch-toolbar-windows-10-a.html

I use macOS primarily so I like layout parity between devices, it's one of the reasons I grabbed TaskbarX.

**Comment by ChrisAnd1998** [comment]
@Mattophobia Sorry for the late response.. Can you give the latest 1.6.3.0 a try or the pre-release 1.6.4.0.
I have now included separate builds for x86 and x64. It's seems to have fixed a ton of issues lately.

**Comment by nikorue** [comment]
unsubscribe
-------- Original message --------From: Chris Andriessen ***@***.***> Date: 3/21/21  13:30  (GMT+03:00) To: ChrisAnd1998/TaskbarX ***@***.***> Cc: Subscribed ***@***.***> Subject: Re: [ChrisAnd1998/TaskbarX] TaskbarX Doesn't Appear to Run Correctly
  (#275) 
Closed #275.
