### ISSUE TITLE
Issues on startup even after multiple clean reinstall

### ISSUE THREAD

**Issue by SnailMango** [ChrisAnd1998/TaskbarX#276]
FalconX used to work very well, but now with TaskbarX I'm only having problems with my Win10 multiple monitor setup.
Everytime I install it it works pretty well before rebooting the PC (even if it doesn't let me delete the original folder with the setup before the reboot). After rebooting, the icons of my secondary vertical monitor are centered but the taskbar isn't transparent like I configured after installation, and on my primary monitor the icons appears in the middle between the center of the taskbar and the Start button, so an indefinite position even if in the settings the offset are both 0px.
If I try to change the settings in the configurator, after clicking Apply, it closes and when I reopen it the settings aren't changed like if it's not saving anything.
I'm still having these problems after doing a clean reinstall with Revo Uninstaller and deleting all the FalconX registry keys.

![Immagine](https://user-images.githubusercontent.com/64862343/81100765-616b7300-8f0d-11ea-9e3c-ebef9ce08447.jpg)

**Comment by ChrisAnd1998** [comment]
Hmm, thats weird.
You are on 1.5.5.0 right?
I would also like to know if it's the store version or regular version and what build of Windows 10 you are using.

What are the resolutions of both your monitors? So i can try to reproduce your setup.

**Comment by SnailMango** [comment]
> @SnailMango Hmm, thats weird.
> You are on 1.5.5.0 right?
> I would also like to know if it's the store version or regular version and what build of Windows 10 you are using.
> 
> What are the resolutions of both your monitors? So i can try to reproduce your setup.

Yes, 1.5.5.0 regular version and Win10 build 18363.815.
Monitors are both 1920x1080: one horizontal and one vertical (left one in the screenshot).

**Comment by MikelThief** [comment]
Same things happens on 3440x1440, 1.5.5.0 store version, Win10 2019 Fall update

**Comment by ChrisAnd1998** [comment]
Can you try the latest pre-release 1.5.7.0?

**Comment by MikelThief** [comment]
@ChrisAnd1998 in my case it works properly under new 1.5.7.0
