### ISSUE TITLE
[Query]File explorer not opening upon clicking

### ISSUE THREAD

**Issue by onlytanmoy** [ChrisAnd1998/TaskbarX#278]
Hey @ChrisAnd1998 Chris, hope all well at your end.
Just recently I observed that clicking on the file explorer icon in TaskbarX is not launching my win explorer as it did earlier :( is it just me?

**Comment by ChrisAnd1998** [comment]
I think it's just you XD. Maybe a bug in Windows... TaskbarX only knows the size of the first and last icon in the taskbar nothing else.

Everything is ok :) I have been working so much on TaskbarX lately that i just need a break for a couple days...

**Comment by onlytanmoy** [comment]
yeh, a restart of the windows seemed to fix it...lol..you know how Windows is and how reboot helps most of the times :) even in life if you ask, so yes go for that well deserved break and stay safe mate.
