### ISSUE TITLE
Taskbar Flickering.

### ISSUE THREAD

**Issue by cainy-a** [ChrisAnd1998/TaskbarX#279]
I know this is a duplicate of #216, however that issue stated that v16 and v17 fixed it, when i have been using the latest stable version (https://github.com/ChrisAnd1998/TaskbarX/releases/tag/1.5.5.0) and it has been occuring with programs open ***AND*** closed.

**Comment by ChrisAnd1998** [comment]
And 1.5.6.0?
https://github.com/ChrisAnd1998/TaskbarX/releases/tag/1.5.6.0

**Comment by cainy-a** [comment]
This issue still occurs on 1.5.6.0.
If it helps to have any additional info, my windows build is `Windows 10 Pro Build 18362.19h1_release.190318-1202`, and I the only other app that could be seen as modifying the taskbar is OpenShell, the start menu replacement.
I'll try that debugger that you linked in the pinned issue about bugs

**Comment by cainy-a** [comment]
I couldn't get dnSpy to output anything

**Comment by cainy-a** [comment]
Use of Process Hacker has confirmed that the same thing is happening as in issue #216, where it is contantly crashing and restarting

**Comment by cainy-a** [comment]
Okay it's fixed now
