### ISSUE TITLE
Are there any ways to speed up its startup process?

### ISSUE THREAD

**Issue by s0seji** [ChrisAnd1998/TaskbarX#280]

**Comment by ChrisAnd1998** [comment]
@s0seji At the moment it is already using a Taskschedule which is the fastest way. If you have Administrator access then you can try to modify the taskschedule using the "Task Scheduler" application in your start menu. I am not sure but, i think you can make it start before logging in. You will have to try it. I will also try to make it faster when i get back home and share the new settings you have to apply manually.

**Comment by s0seji** [comment]
i just read this like right now and i did what you said. i changed the task schedule to "start before logging in". will be giving you updates in a few days to observe if there are improvements. thank you so much chris. i really love this project you made. if i could be of help, i want to contribute to this as well (although i am a little scared because it would be my first time haha!). Again, thanks!
