### ISSUE TITLE
Taskbar wont go to middle

### ISSUE THREAD

**Issue by essakura** [ChrisAnd1998/TaskbarX#282]
When opened the task bar will go transparent but wont go to the middle, even when left open for a while. I found a way to fix this by opening taskbarx through the menu at the right side of the taskbar, but why doesn't it do this automatically?

**Comment by ChrisAnd1998** [comment]
@essakura Can you give the pre-release a try?
https://github.com/ChrisAnd1998/TaskbarX/releases/tag/1.5.6.0

**Comment by essakura** [comment]
Its perfect thank you!

**Comment by farhan2077** [comment]
I was also facing the same issue. Pre-release version 1.5.7.0 seemed to fix the problem.
