### ISSUE TITLE
Taskbar Icon flickering

### ISSUE THREAD

**Issue by ImranSefat** [ChrisAnd1998/TaskbarX#283]
The icons in the taskbar is shaking left and right just a little bit but it's visible to the eye

**Comment by ChrisAnd1998** [comment]
What version?

**Comment by ImranSefat** [comment]
V1.3.2.0 
It fixed automatically

**Comment by ChrisAnd1998** [comment]
Thats a very low version though... 1.5.6.0 is the latest.
