### ISSUE TITLE
taskbar icon not in center when monitor in portrait mode

### ISSUE THREAD

**Issue by junda15** [ChrisAnd1998/TaskbarX#287]
hi please see the attached. my taskbar icon are not in the center when in portrait mode. perhaps can add in a feature to automatic turn off this taskbarX when detect monitor is in portrait mode since portrait mode all the icons will fill up the taskbar space.

![Annotation 2020-05-14 104207](https://user-images.githubusercontent.com/65323849/81886574-9e033280-95cf-11ea-9412-e508cbd72698.jpg)

**Comment by ChrisAnd1998** [comment]
@junda15 It should still center it but, there is an option in the configurator to skip a resolution by it's width.
So if your res is 1920x1080 then in landscape your width is 1920 and when rotated your width is 1080.

**Comment by junda15** [comment]
my resolution is 3840x2400. do i need to enter any settings into the configurator ?

**Comment by ChrisAnd1998** [comment]
There should be an option under extra called skip resolution. Enter 2400 in there.

**Comment by junda15** [comment]
yes chris, i enter and it works now in portrait mode now. thank you !

**Comment by ChrisAnd1998** [comment]
great! :)
