### ISSUE TITLE
Taskbar wont go Transparent

### ISSUE THREAD

**Issue by OSbOoL** [ChrisAnd1998/TaskbarX#288]
No matter what I do, the Taskbar doesn't give me the expected Transparency.
The only thing is that the Symbols move to the middle...
Is there a bugfix on the road?
Thanks

**Comment by ChrisAnd1998** [comment]
Whats your W10 build?
If it's 1709 or lower then you need to update.

**Comment by OliverSchriever** [comment]
I have 1909 :)

**Comment by yeahalti** [comment]
Facing this issue as well!
1909 build

**Comment by OliverSchriever** [comment]
Taskbar runs on both PCS (1909). Only doesn't work on Notebook (1909)

**Comment by Inoki** [comment]
I have a similar issue. The taskbar is transparent, but after a while it goes back to being opaque. Happens randomly.

**Comment by chendijun527** [comment]
my laptop has the same problem,restart pc transparent works 2~5second, then being opaque.

**Comment by RazorScoot** [comment]
@chendijun527 can I ask how you did that, I have never used task scheduler before

**Comment by lilnut004** [comment]
I fixed mine by simply going to the GitHub link I got it from and downloading the newest version, when I ran the install it prompted me to update instead, I did and It now works fine.

This is where I got it:
https://falcon-x.en.softonic.com/download

**Comment by 83y** [comment]
> I fixed mine by simply going to the GitHub link I got it from and downloading the newest version, when I ran the install it prompted me to update instead, I did and It now works fine.
> 
> This is where I got it:
> https://falcon-x.en.softonic.com/download
This worked for me too, its funny how an older version works.

**Comment by ChrisAnd1998** [comment]
@83y Yeah.. there some weird things going on. FalconX supports the older way of taskbar styling which should not work on 1803 and above. In 1803 Microsoft made some changes to the SetWindowCompositionAttribute API so in TaskbarX i had to adapt to the changes. But according to some reports and your comments it seems to be all mixed up 😩. Maybe something is forgotten inside the Windows updates...
