### ISSUE TITLE
Acrylic style selection does not show windows behind taskbar

### ISSUE THREAD

**Issue by primes1022** [ChrisAnd1998/TaskbarX#291]
## Actual Behavior
Acrylic Style
![image](https://user-images.githubusercontent.com/33763931/82375627-dd29ed00-99ee-11ea-83c3-7372609f0b32.png)

## Expected Behavior
More like the Blur Style
![image](https://user-images.githubusercontent.com/33763931/82375551-c2577880-99ee-11ea-8cd5-da9c38a23334.png)

## Steps to Reproduce the Problem

  1. TaskbarX Configurator
  1. Style
  1. Acrylic
  1. Apply
  1. Move a window behind the taskbar

## Specifications

  - App Version: 1.5.5.0
  - Windows Version: 1909 - 18363.836

## Other

  - Tested between two different installs of Windows (same version and builds)
  - Tested with both AMD and NVIDIA gpus

**Comment by ChrisAnd1998** [comment]
@primes1022 Well sometimes it does and sometimes it doesn't. Sadly Acrylic is buggy and i can't fix that. The problem is that the taskbar itself reacts so different to it :/
