### ISSUE TITLE
TaskbarX is not working

### ISSUE THREAD

**Issue by h1314-z** [ChrisAnd1998/TaskbarX#292]
TaskbarX does not run correctly no matter how many times it is opened. Nothing has changed at all.The computer version number is 1903

**Comment by ChrisAnd1998** [comment]
Can you give the pre-release 1.5.6.0 a try?

**Comment by h1314-z** [comment]
@ChrisAnd1998 where can download the 1.5.6.0. But I use the Microsoft store version.Is also like this

**Comment by ChrisAnd1998** [comment]
@h1314-z You can get it from here:
https://github.com/ChrisAnd1998/TaskbarX/releases/tag/1.5.6.0

**Comment by h1314-z** [comment]
@ChrisAnd1998 The problem is still. Still can't open TaskbarX, but TaskbarX Configurator can be opened.

**Comment by h1314-z** [comment]
@ChrisAnd1998 The store version cannot be used. I tried. There was no response after opening.

**Comment by ChrisAnd1998** [comment]
@h1314-z Hmm, the best way to find the issue is to debug it on your system. You should install **Visualstudio Community 2019** but, will take a lot of gigs in space. I'am currently looking if there is a lightweight and portable way to debug .NET applications.

**Comment by h1314-z** [comment]
I tried again after restarting the computer. Found that it can be used. It is now running. thank you very much for your help. Thank you

**Comment by h1314-z** [comment]
@ChrisAnd1998 I tried again after restarting the computer. Found that it can be used. It is now running. thank you very much for your help. Thank you

**Comment by ChrisAnd1998** [comment]
allrig
