### ISSUE TITLE
Merge Settings

### ISSUE THREAD

**Issue by ncodee** [ChrisAnd1998/TaskbarX#293]
Hi,

Before these latest updates, the Settings panel was integrated into the app itself, is there any reason that this has changed recently? It's a bit cumbersome having to entries/panels for a single instance.

Thanks

**Comment by ChrisAnd1998** [comment]
@ncodee Don't really understand what you mean...

> the Settings panel was integrated into the app itself

^??

There is a Settings app and a background service.
Both separated from each other.

**Comment by ncodee** [comment]
Hi, sorry what I mean is there shouldn't be a separate entity just for 'TaskerX Configurator', it should only be accessible via right-clicking on the Taskbar shortcut. If that can't be done, then just have shortcut entry for ''TaskerX' which opens up the 'Configurator' and from there you can launch the TaskerX process.

Hope this makes sense, thanks.
