### ISSUE TITLE
[Bug] [With workaround] TaskbarX Configurator crashes if started from a shortcut with empty "Start in:" field

### ISSUE THREAD

**Issue by Darthagnon** [ChrisAnd1998/TaskbarX#294]
I discovered that TaskbarX Configurator will crash if started from a Shortcut.lnk created with nothing in the "Start in:" field. Run it, try to change any setting, click a button, and it will crash.

Workaround:
Put the path to the TaskbarX folder in the "Start in:" field.

**Comment by ChrisAnd1998** [comment]
I can't reproduce it but, i will add a start-in directory for the shortcuts the installer creates ;)

**Comment by fluoroom** [comment]
I had the problem that it would crash even when running the actual file (double-click) or running it from the start menu search (no shortcut, just typing the file name and finding it). So i created a real shorcut (with "start in:") on the start menu and now it works. Thanks!
