### ISSUE TITLE
Feature: Setting for active taskbar item transparency

### ISSUE THREAD

**Issue by MikaelPorttila** [ChrisAnd1998/TaskbarX#296]
It would be awesome if we could get an option to apply a transparent background color on active taskbar item.

![taskbar-active-item](https://user-images.githubusercontent.com/903468/82722441-0ab0b800-9cc7-11ea-8787-e30b81919e88.PNG)

**Comment by ChrisAnd1998** [comment]
Actually, this is a bug i can't fix :/ It's a reaction of the taskbar probably by some sort of setting in Windows. Normally the icon will also be transparent.

**Comment by MikaelPorttila** [comment]
Thank you for the info, it was easy to fix by changing this setting:
![image](https://user-images.githubusercontent.com/903468/82746896-f6d38780-9d94-11ea-83e5-0243807b7b1e.png)

**Comment by ChrisAnd1998** [comment]
Great! :)
