### ISSUE TITLE
Feature Request: Run on startup

### ISSUE THREAD

**Issue by KirbyTheStar9** [ChrisAnd1998/TaskbarX#297]
Hi, what happened to run on startup? The feature disappeared when the name changed to TaskbarX from FalconX and it was really useful

**Comment by KirbyTheStar9** [comment]
Wait, there's a task schedule option. I'll check it out

**Comment by ChrisAnd1998** [comment]
XD, once you click apply in the configurator a Taskschedule will be created. This is much better as it is way faster. 😉

**Comment by KirbyTheStar9** [comment]
Maybe just try renaming it so it's less confusing for new users and/or people that use the old versions that updated to taskbarx from falconx
