### ISSUE TITLE
Flickering taskbar

### ISSUE THREAD

**Issue by CAKyPA** [ChrisAnd1998/TaskbarX#298]
Having flickering, transparency issues like other people, but noticed no one mentioned their windows settings.
So does the TaskbarX is compatible with below Windows settings or do i need to set them specific to run smooth?

- Settings > Personalization > Colors > Start, Taskbar, and action center
- Settings > Personalization > Colors > Transparency Effects
- Settings > Ease of Access > Display > Show transparency in Windows
- Settings > Ease of Access > Display > Show animations in Windows

I'm on Windows 10 1909.

**Comment by jcamachott** [comment]
I am experiencing flickering as well, generally random like every 5 to 20 seconds. 

TaskbarX is set to Transparent or Blur. In default it seems to stop. 

Windows settings:
Transparency Effects: ON
Animations and Transparency ON

Im on Windows 10 2004

**Comment by yumekohina** [comment]
yeah, hihi, my taskbar flickers a lot whenever i open it, on any effect :<
windows 10!

**Comment by najab123** [comment]
hey guys does any one have a solution for this? i bought this app and my taskbar keep flickering on transparent.

Windows 10, 64 bit, transparent animation off (flickers on ON as well)
