### ISSUE TITLE
Autorun is missing?

### ISSUE THREAD

**Issue by Brummell67** [ChrisAnd1998/TaskbarX#300]
In version 1.5.6.0 , I don't see the option "for auto-activate at login".
Is it a choose?

**Comment by ChrisAnd1998** [comment]
It will create a logon Taskschedule when you hit apply in the configurator ;)

**Comment by Brummell67** [comment]
Sorry, I doesn't find:
![image](https://user-images.githubusercontent.com/5261273/82945476-47b5cc80-9f9d-11ea-9c24-ba9bbdadb9f0.png)
Maybe another section?

**Comment by ChrisAnd1998** [comment]
No XD, the blue "Apply" button in the right bottom corner will automatically create a logon Taskschedule.

**Comment by Brummell67** [comment]
Thank you and excuse me.
If I wanted to disable it? Is not possible?

**Comment by ChrisAnd1998** [comment]
In the tab called "Taskscheduler" you can remove it but, it will recreate when you hit apply again. So you can't really disable it. If you use TaskbarX you always need it to run at startup. There is not really a point for disabling it.
