### ISSUE TITLE
Flickering after opening a window(s)

### ISSUE THREAD

**Issue by riskirills66** [ChrisAnd1998/TaskbarX#302]
every time i open other application or tab to other application the taskbar turn back into left taskbar for a sec then turn to center again.

**Comment by Coupz** [comment]
I updated from 1.5.5.0 to 1.5.7.0 and have seen that too.

**Comment by Matutecp** [comment]
Happening in 1.5.5.0 too

**Comment by ChrisAnd1998** [comment]
What build of Windows?

**Comment by ChrisAnd1998** [comment]
To avoid duplicate issues i'll close this one.
https://github.com/ChrisAnd1998/TaskbarX/issues/298
