### ISSUE TITLE
Feature request: Center windows search

### ISSUE THREAD

**Issue by tmoerkerken** [ChrisAnd1998/TaskbarX#303]
Would this be possible:
![image](https://user-images.githubusercontent.com/6529496/83878769-eb8d3e00-a73c-11ea-8bcb-af0dad37c0ca.png)

**Comment by ChrisAnd1998** [comment]
Sadly getting it exactly centered is not possible as far as i know. It will always align with the search bar or icon.

The closest thing you can do to get this look is to enable immersive search in your Registry.
https://www.tenforums.com/tutorials/98610-enable-disable-floating-immersive-search-bar-windows-10-a.html
