### ISSUE TITLE
When I start my computer it does not startup, it does not apply Dark theme though

### ISSUE THREAD

**Issue by EvanDonoso** [ChrisAnd1998/TaskbarX#305]

**Comment by ChrisAnd1998** [comment]
Have you hit the apply button in the configurator yet? When the apply button is pressed it will create a startup taskschedule.

**Comment by b4imetu** [comment]
Hi @ChrisAnd1998! I have the same problem, that
- TaskbarX doesn't launch after system boots.
- And Configurator never remembers my config.
I mean every time I run TaskbarX manually, the taskbar will not be Transparent until I run Configurator to set it to Transparent and click Apply manually again.

**Comment by ChrisAnd1998** [comment]
@b4imetu Are you able to type in your startmenu "Taskscheduler" and open it?
Just want to make sure if you even have access to it. If you don't then your pc is probably owned by an organisation like a school or work. And they blocked access to it.

**Comment by b4imetu** [comment]
@ChrisAnd1998 Yes I have access to Taskscheduler and I didn't see anything about TaskBar in that.
By the way, I didn't install TaskbarX from Microsoft Store. I just extract TaskbarX_22.05.2020_1.5.6.0.zip and run TaskbarX.exe, but the program didn't seem installed on my computer. I can't find any shortcuts created on my desktop or startmenu. And Configurator never remembers my config as I mentioned.

**Comment by ChrisAnd1998** [comment]
@b4imetu Well something must be preventing TaskbarX from creating a Taskschedule. Maybe an antivirus software other than Windows defender... The settings are also stored in the taskschedule so that means both issues lead the same issue.
