### ISSUE TITLE
Taskbar items do not align when double height and window text is shown

### ISSUE THREAD

**Issue by Arlodotexe** [ChrisAnd1998/TaskbarX#306]
I've found a bug where the items in the taskbar do not center align

To reproduce:
1. In taskbar settings, change "Combine taskbar buttons" to "When taskbar is full"
2. Set the taskbar height to double
3. Open enough windows for the taskbar to overflow onto the second line

## Expected result:
![image](https://user-images.githubusercontent.com/9384894/84627473-9b387d80-aeac-11ea-8d2c-fa3b6e3f8f3c.png)

## Actual result:

![image](https://user-images.githubusercontent.com/9384894/84627290-4268e500-aeac-11ea-8071-b8fdb4c11cdb.png)

**Comment by ChrisAnd1998** [comment]
@Arlodotexe This will probably be unfixable. As TaskbarX looks for the first and last icon in the taskbar to know it's position. If TaskbarX looks for all icons then the performance will be unacceptable when you have so many icons in your taskbar.

I will keep this issue open as i may find a solution.
