### ISSUE TITLE
on Multiple displays same style can not be applied because of windows settings

### ISSUE THREAD

**Issue by Gideon-Felt** [ChrisAnd1998/TaskbarX#307]
When 'automatically hide the taskbar in desktop mode' is enabled in windows 10 settings the same TaskbarX style can not be applied to both taskbars on a multi-monitor set up at the same time, it will automatically set one to transparent and the other to the one I dictated, sometimes changing wich taskbar it's applied to but never both.

**Comment by ekx** [comment]
I have the same problem

**Comment by ekx** [comment]
Sometimes after rebooting both Taskbars will be set to the correct style for a short amount of time. Haven't been able to notice any specific action that breaks the style on the second taskbar
