### ISSUE TITLE
TaskbarX filled with software overload

### ISSUE THREAD

**Issue by junda15** [ChrisAnd1998/TaskbarX#311]
I am on the latest version of taskbarX 1.5.6.0. 
When i open app that overfilled the taskbar with taskbarX, there will be a small scroll bar by the side and i am unable to see any of the icon. I am able to see the icon when I can click on the small scrollbar up and down. However when i let go of the click, the taskbar jumps back to empty.
![TaskbarX overload with apps on tray](https://user-images.githubusercontent.com/65323849/86104353-8258da80-baf0-11ea-9c5d-f5bb774fe806.jpg)

When i turn taskbarX off, i see the icons and are able to control up and down using the small little scrollbar within taskbar.
![Without TaskbarX](https://user-images.githubusercontent.com/65323849/86104359-84229e00-baf0-11ea-8c23-bdb8ff169755.jpg)

**Comment by ChrisAnd1998** [comment]
I think this is just the Taskbar not TaskbarX. Try disabling TaskbarX and see if it still does it. If so i won't be able to fix that.

**Comment by junda15** [comment]
> I think this is just the Taskbar not TaskbarX. Try disabling TaskbarX and see if it still does it. If so i won't be able to fix that.

It is TaskbarX. I disabled TaskbarX and all the icons are working in order when Taskbar are filled with app. When i enable TaskbarX and Taskbar overfilled with app, the app icon jumps into empty and when i click on the scrollbar within the Taskbar, it will still jump to empty one. 

Give it a try by enabling TaskbarX and open a lot a lot of app that will fill more than your Taskbar space, you will understand what I am trying to say.

**Comment by ErwinSuwito** [comment]
Hi, I also have a similar problem:
![image](https://user-images.githubusercontent.com/30384397/88258271-f4849f80-cce9-11ea-96bd-b44f0d393b73.png)

Why not set a settings where taskbar icon centering is disabled when it reaches a set number of items?

**Comment by ChrisAnd1998** [comment]
@ErwinSuwito Well, this should not happen it clearly has enough space to center it. So i hope to find a proper fix for this not a workaround. Thanks for the idea 😄 but, that will be the last option if i won't be able to fix it.

**Comment by ErwinSuwito** [comment]
You're welcome.

But for me it happens when there's not enough space in the taskbar.

**Comment by junda15** [comment]
Yes when the taskbarX is enabled and icon reach a maximum number of icon, mine disappears as mine do not have enough space to center it anymore.

**Comment by junda15** [comment]
For me it happens to disappears when there is not enough space in the taskbar

**Comment by ChrisAnd1998** [comment]
@ErwinSuwito @junda15 I think i could get the maximum space for the taskbar automatically and when the icons total width exceeds it or comes very close disable TaskbarX and enable it again when there is enough space again. That would be better because, if you suddenly want to use small icons or taskbar labels then you need to re-enter the value and find out what the total icons count is. 

Just aiming for simplicity ;)

And make this an option (checkbox)

**Comment by junda15** [comment]
Can try it out
