### ISSUE TITLE
Feature Request: Hide peek line or disable peek

### ISSUE THREAD

**Issue by shivangswain** [ChrisAnd1998/TaskbarX#312]
Something like this would look super clean:

![image](https://user-images.githubusercontent.com/33395916/86464432-1fb04a80-bd4d-11ea-91d2-31ef402bf60c.png)

![image](https://user-images.githubusercontent.com/33395916/86464325-e546ad80-bd4c-11ea-9de6-1a25875f3bde.png)

**Comment by cmputerboom** [comment]
Which wallpaper is that?

**Comment by shivangswain** [comment]
> Which wallpaper is that?

It is from here: [Color Burst [3840 x 2160] : r/wallpaper](https://www.reddit.com/r/wallpaper/comments/hjflrk/color_burst_3840_x_2160/). Got it from [Reddit Wallpaper Changer](https://www.reddit.com/r/rwallpaperchanger).

**Comment by shivangswain** [comment]
I have currently removed it using this tool for Windows 7 called [ShowDesktop Remover](https://www.thewindowsclub.com/remove-and-restore-show-desktop-button-with-showdesktop-remover) but I would love if it was available included in TaskbarX.
