### ISSUE TITLE
Taskbar styles only applied after switching desktop

### ISSUE THREAD

**Issue by warpdesign** [ChrisAnd1998/TaskbarX#313]
When switching desktop using three fingers swipe, the taskbar from the new desktop first has default Windows styles with no TaskbarX styles. Only after screen has appeared, new styles are applied and icons are centered. So there is a 1-2sec delay before the taskbar gets the expected styles.

![taskbarx1](https://user-images.githubusercontent.com/199648/86492947-f0f79b80-bd6f-11ea-9129-b15eef077396.gif)

This is what I mean by switching desktops: https://www.youtube.com/watch?v=4tnmXFwLtK0

TaskbarX: 1.5.6.0
Windows: Microsoft Windows [version 10.0.19041.329]
Machine: Surface Book

**Comment by disisisid** [comment]
I only see this issue when switching desktop using three fingers swipe, when I use the Keyboard shortcut (Ctrl + Win + left/right arrow), it works fine.

**Comment by disisisid** [comment]
@warpdesign Did you find a fix yet?

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
