### ISSUE TITLE
After rebooting style is reset

### ISSUE THREAD

**Issue by Maracko** [ChrisAnd1998/TaskbarX#314]
After every PC reboot the stlye is reset to default (i use blur)

Every other setting is apllied correctly. After applying the style again with taskbarX configurator the style works as it should again

**Comment by Maracko** [comment]
This was not issue with the app itself, but that I added taskbarx to startup without knowing it automatically adds a scheduled task.

Closing issue

**Comment by nevedpaharia** [comment]
wait what I didn't understand can you please explain it so that it's easy to understand cuz I am facing the same issue.

**Comment by Maracko** [comment]
my problem was that I added taskbarx to startup folder manually but it's not needed and breaks the styling on reboot if you do it

**Comment by nevedpaharia** [comment]
Thank you, I did the same thing as you did.
