### ISSUE TITLE
TaskbarX won't uninstall

### ISSUE THREAD

**Issue by ahmedelaghil** [ChrisAnd1998/TaskbarX#317]
Hello. I am trying to uninstall TaskbarX (installer version) but I can't. Every time I try to uninstall it, I get this message.

![Annotation 2020-07-12 135026](https://user-images.githubusercontent.com/68185721/87244576-c29c4f00-c446-11ea-9b20-1b2ee1638797.png)

**Comment by DarkCreature97** [comment]
I'm currently having the same issue. When I try to uninstall it through the installer It throws an exception:

System.IO.FileLoadException: No se puede cargar el archivo o ensamblado 'Microsoft.Win32.TaskScheduler, Version=2.8.18.0, Culture=neutral, PublicKeyToken=DELETED' ni una de sus dependencias. La definición del manifiesto del ensamblado no coincide con la referencia al ensamblado. (Excepción de HRESULT: 0x80131040)
Nombre de archivo: 'Microsoft.Win32.TaskScheduler, Version=2.8.18.0, Culture=neutral, PublicKeyToken=DELETED'
   en TaskbarXInstaller.Form1.Button2_Click(Object sender, EventArgs e)
   en System.Windows.Forms.Control.OnClick(EventArgs e)
   en System.Windows.Forms.Button.OnClick(EventArgs e)
   en System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   en System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   en System.Windows.Forms.Control.WndProc(Message& m)
   en System.Windows.Forms.ButtonBase.WndProc(Message& m)
   en System.Windows.Forms.Button.WndProc(Message& m)
   en System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   en System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   en System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

AVS: El registro del enlace de ensamblado está desactivado.
Para habilitar el registro de errores del enlace de ensamblado, establezca el valor de Registro [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) como 1.
Nota: existe una disminución del rendimiento asociada registro de errores del enlace de ensamblado.
Para desactivar esta característica, elimine el valor de Registro [HKLM\Software\Microsoft\Fusion!EnableLog].

**Comment by NicTanghe** [comment]
I don't even have an uninstall anywhere not even in add or remove.
And it crashes when i try to change settings.

**Comment by hybridbyte** [comment]
I'm having the same issues... this is outrageous.

**Comment by ChrisAnd1998** [comment]
Sorry that i have not responded yet. I don't know how to fix it and where it comes from.

**Comment by NicTanghe** [comment]
Im pretty sure i fixed other issues i was having by just deleting the files
in folder and reinstalling.

Nic Tanghe


Op wo 15 jul. 2020 om 07:37 schreef Chris Andriessen <
notifications@github.com>:

**Comment by NicTanghe** [comment]
I**WORKAROUND just delete the files manually and reinstall the program. (dont remove it becouse the default taskbar is retarded.)**

Im pretty sure i fixed other issues i was having by just deleting the files

in folder and reinstalling.

(How is anything like this Outrageous No one instructed you to pay for this and if you dident pay for it HOW IS IT OUTRAGES?

**Comment by QuickasCovid** [comment]
Delete this registry key
Computer\HKEY_USERS\S-1-5-21-2495047022-3011468751-1535558934-1001\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\TaskbarX

Or simply search in the registry taskbarx and locate the one above

**Comment by QuickasCovid** [comment]
open registry editor and search taskbarx, you will find something like this 
Computer\HKEY_USERS\S-1-5-21-some number-\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\TaskbarX

delete that key

**Comment by ahmedelaghil** [comment]
> Sorry that i have not responded yet. I don't know how to fix it and where it comes from atm.

No worries. I managed to remove it and installed the Store version. Thank you for your work 👍

**Comment by DarkCreature97** [comment]
> No worries. I managed to remove it and installed the Store version. Thank you for your work 👍

At least you could have mentioned what exactly you did to get rid of it. 😑

**Comment by bx-sk** [comment]
> > No worries. I managed to remove it and installed the Store version. Thank you for your work 👍
> 
> At least you could have mentioned what exactly you did to get rid of it.

Click on TaskbarX configuration in the TaskbarX folder and you should be able to uninstall.

**Comment by Bharath21319** [comment]
how to uninstall taskbarX . TaskbarX configurator is not opening

**Comment by krishchvn** [comment]
Even if it's uninstalling, taskbar takes this messed up form 
![taskbar](https://user-images.githubusercontent.com/58606754/137598810-5f69ead2-03d8-44ba-bf1d-2086c3c49cc0.jpg)
