### ISSUE TITLE
taskbar automatically turns opaque even if I have enabled blur option 

### ISSUE THREAD

**Issue by aarish21** [ChrisAnd1998/TaskbarX#319]

**Comment by ChrisAnd1998** [comment]
@aarish21 Whats your build of Windows 10?

**Comment by dupr0n** [comment]
@ChrisAnd1998 Even I have a similar issue. No matter what theme I put, the taskbar is opaque. But when I select "Automatically hide taskbar" in the taskbar settings, it works normally. But the issue persists when I toggle that "Automatically hide taskbar" in windows settings. Running Windows 1903 here.

**Comment by ChrisAnd1998** [comment]
Do you have this enabled?

![Capture](https://user-images.githubusercontent.com/50437199/93015386-514d5980-f5b9-11ea-8c45-6883cb2c912c.PNG)

**Comment by Midnight1938** [comment]
facing the same problem

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
