### ISSUE TITLE
UWP Variant doesn't work on Insider Dev builds

### ISSUE THREAD

**Issue by VincentJoshuaET** [ChrisAnd1998/TaskbarX#324]
Currently running 20161, TaskbarX does nothing, no errors too. According to a Reddit post it seems that the non UWP program works.

**Comment by shivangswain** [comment]
I am currently using the UWP version on Insider Build v20161 and it is working perfectly fine for me.

![2020-07-16](https://user-images.githubusercontent.com/33395916/87641385-a4e02a00-c765-11ea-9fdf-4bf99609a6ab.png)
