### ISSUE TITLE
Secondary monitor taskbar position changing while changing wallpaper

### ISSUE THREAD

**Issue by drxwz** [ChrisAnd1998/TaskbarX#325]
Taskbar Version: 1.5.7.0 Pre-Release
Windows 10 PRO Version : 2004 build 19041.388.
Switching wallpapers will reposition the taskbar from the secondary monitor to default position and back; I'm running default options.
The wallpapers are changed every minute with Reddit Wallpaper Changer.
Other apps installed that may affect this:  T-Clock, Reddit Wallpaper Changer.

**Comment by ChrisAnd1998** [comment]
@drxwz What version of TaskbarX? I thought this was fixed in 1.5.6.0 ...

**Comment by drxwz** [comment]
I'm using the pre-release version: 1.5.7.0.

**Comment by ChrisAnd1998** [comment]
Can you try this? https://github.com/ChrisAnd1998/TaskbarX/releases/tag/1.6.8.0

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
