### ISSUE TITLE
Does not remember enabled toolbars

### ISSUE THREAD

**Issue by kaovilai** [ChrisAnd1998/TaskbarX#326]
On my HP laptop with TaskbarX 1.5.6.0, upon activation of the taskbar, it seems to always recall the default taskbar config regarding the toolbars. That is if I unticked the HP toolbar, the next restart it comes back. This behavior only affects TaskbarX toolbar, and not the default windows toolbar.
![image](https://user-images.githubusercontent.com/11228024/87632911-8b8aae00-c764-11ea-8d10-7d41ea9cfb36.png)

**Comment by ChrisAnd1998** [comment]
If you move the little tray icons around it will update. I have to find a better solution for this.

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
