### ISSUE TITLE
Hulu Full-Screen Issue (From Microsoft Store) [Windows 10]

### ISSUE THREAD

**Issue by Daemitrious** [ChrisAnd1998/TaskbarX#327]
When launching Hulu full-screen, the taskbar turns into the background color of the Hulu application just after returning back to the desktop background.  In the config file, I have it set to "Blur" for TaskbarX Configuration.

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
