### ISSUE TITLE
Task bar icons goes crazy

### ISSUE THREAD

**Issue by ImZary** [ChrisAnd1998/TaskbarX#328]
Hi i like the app & everything i think its cool except this weird bug that when an new app opens & its not pined on the task bar the icons on the task bar start dancing & bouncing around idk i hope this bugs fixed fast & ty

**Comment by kaovilai** [comment]
You probably have something wrong with your animations
See if setting the following animation styles to `none` helps. If so then that's your issue.
![image](https://user-images.githubusercontent.com/11228024/88029939-d17cb300-cb64-11ea-992f-e6f8eb05c61c.png)

**Comment by ChrisAnd1998** [comment]
@ImZary If it's 1.5.7.0 pre-release then this can happen as i disabled the wiggle blocker. Try 1.5.6.0 for now. For some people the icons wouldn't even move because of this block so iam finding a way to stop the wiggle and also make the icons always move.

**Comment by ImZary** [comment]
> @ImZary If it's 1.5.7.0 pre-release then this can happen as i disabled the wiggle blocker. Try 1.5.6.0 for now. For some people the icons wouldn't even move because of this block so iam finding a way to stop the wiggle and also make the icons always move.
ok but when i press uninstall it simply says you must be administrator but i am an admin on this account
so its kind of impossible to uninstall it to install the 1.5.6.0 version

**Comment by ImZary** [comment]
ok is seem like i manage to install version 1.5.6.0 ty so much for helpping
