### ISSUE TITLE
Feature Request: Add a Recycling Bin to the taskbar with the right-click menu options of the desktop icon

### ISSUE THREAD

**Issue by Rosmaninho** [ChrisAnd1998/TaskbarX#33]
Since I have an objective of having a desktop without icons I also wanted to move the Recycling Bin icon to the Taskbar (while maintaining the "Empty Recycling Bin" in the right-click menu). 
There's a work-around to do that (create a new toolbar and add a shortcut to the Recycling Bin icon over there) but the icon does not center with the other icons of the taskbar using Falcon X.

Would like to ask if it's possible to create an option to add a shortcut to the recycling bin in Falcon X.

**Comment by johnnydement** [comment]
Isn't it enough having it anchored to file explorer?
