### ISSUE TITLE
Malwarebytes detects a malware in the main application

### ISSUE THREAD

**Issue by B-eelzebub** [ChrisAnd1998/TaskbarX#331]
I have been using Taskbarx for some time now but suddenly today, Malwarebytes detected malware in the main application (it was some kind of malware.generic file) and quarantines the file. I have included an image below.
![image](https://user-images.githubusercontent.com/68503639/87875058-2f7b9000-c9d7-11ea-8dc3-8a62000bce91.png)
Is this an issue in the application or is Malwarebytes just being stupid?

**Comment by JosephInn** [comment]
The Exact same thing happened to me this morning.

**Comment by ChrisAnd1998** [comment]
I have to contact them about this. Without TaskbarX.exe TaskbarX won't work XD ofc. Just a false positive.

**Comment by ejrgithub** [comment]
Same thing - Virus total - 4 engines detecting.
