### ISSUE TITLE
How do I uninstall TaskbarX

### ISSUE THREAD

**Issue by nevedpaharia** [ChrisAnd1998/TaskbarX#332]
hey I wanted to know how to uninstall taskbarx because I am then going to install it from the Microsoft store

**Comment by ChrisAnd1998** [comment]
@nevedpaharia 

Open the "TaskbarX Configurator" and hit the "Stop TaskbarX" button. This will stop the TaskbarX process and put your icons back to the left. After that you can simply remove the files where you installed TaskbarX.

Thanks for willing to support the project 😄

**Comment by nednedsudo** [comment]
hello i need help bc im stupid and i didnt look how to uninstal taskbarx and i delete and the othere files and the left file is the taskbarx and i cant delete it help pls!.

**Comment by HamzaMasood1** [comment]
The uninstall button should not have been removed. This is a roundabout way of uninstalling this program.

**Comment by nesch52** [comment]
Hi, I am getting these Error messages from TaskbarX:
Waiting for Shell_TrayWnd
@Calculator | Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
@Calculator | Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
@Calculator | Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
@Calculator | Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
@Calculator | Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
@Calculator | Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
@Looper1 | Mitglied nicht gefunden. (Ausnahme von HRESULT: 0x80020003 (DISP_E_MEMBERNOTFOUND))
@Calculator | Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
@Calculator | Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
@Calculator | Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
@Calculator | Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
@Calculator | Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
@Calculator | Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
@Calculator | Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
@Calculator | Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
@Calculator | Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
@Calculator | Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
@Calculator | Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
@Looper1 | Mitglied nicht gefunden. (Ausnahme von HRESULT: 0x80020003 (DISP_E_MEMBERNOTFOUND))
@Calculator | Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
@Calculator | Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
@Calculator | Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.

Both programs are installed ,Looper is working in backgrnd Win10(latest )prof de X64 on Lenovo Laptop P15t (24GB-RAM i7 CPU) 
the message constantly appears.  Is there any UnInstall.exe for Taskbar X 
with clearing facility for remaining registry artefacts?

**Comment by rashmip2408** [comment]
Please help me to delete this. File isn't delete why

**Comment by rashmip2408** [comment]
![IMG20231019191722](https://github.com/ChrisAnd1998/TaskbarX/assets/119780744/72243ccd-ec69-4504-92ad-6e7628129485)
You have to correct this I don't how will you do but do this

**Comment by nesch52** [comment]
> Hi, I am getting these Error messages from TaskbarX: Waiting for Shell_TrayWnd @calculator | Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt. @calculator | Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt. @calculator | Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt. @calculator | Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt. @calculator | Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt. @calculator | Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt. @Looper1 | Mitglied nicht gefunden. (Ausnahme von HRESULT: 0x80020003 (DISP_E_MEMBERNOTFOUND)) @calculator | Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt. @calculator | Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt. @calculator | Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt. @calculator | Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt. @calculator | Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt. @calculator | Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt. @calculator | Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt. @calculator | Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt. @calculator | Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt. @calculator | Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt. @calculator | Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt. @Looper1 | Mitglied nicht gefunden. (Ausnahme von HRESULT: 0x80020003 (DISP_E_MEMBERNOTFOUND)) @calculator | Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt. @calculator | Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt. @calculator | Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
> 
> Both programs are installed ,Looper is working in backgrnd Win10(latest )prof de X64 on Lenovo Laptop P15t (24GB-RAM i7 CPU) the message constantly appears. Is there any UnInstall.exe for Taskbar X with clearing facility for remaining registry artefacts?

Since several Updates after Uninstalling with REVO UNINSTALLER (Cleans nearly everything correctly ,since i own it),
and a clean reinstall from here, i never got this issue back!     So for me the problem is solved so far! (sorry for late response,due to hospital.
