### ISSUE TITLE
[Feature] Enable different positioning on secondary monitors 

### ISSUE THREAD

**Issue by Osyx** [ChrisAnd1998/TaskbarX#333]
When you have one (or several) extra monitor(s), it would be awesome to be able to place the icons to the right and left individually.

A scenario would be when e.g. the user has three monitors, the left monitor could have the icons to the right, the middle in the middle and the right monitor would have them to the left, so that one would easily see the icons on the area closest to the user.

This request might fit better as two separate issues, one for being able to have the taskbar icon to the right and another for being able to have different on different screens.

**Comment by ChrisAnd1998** [comment]
@Osyx When you unlock the taskbar you can drag them any where you like.

**Comment by kaovilai** [comment]
@ChrisAnd1998 I think @Osyx meant three different taskbarX settings per monitor.
Here's a markdown representation.
```
left monitor | main monitor | right monitor
      [][][]      [][][]      [][]][]
____________________________________________
```

where each monitor has a different align settings.

**Comment by Osyx** [comment]
Yes exactly, thank you for making it clearer @kaovilai! 
Should have made an illustration as well, my explanation wasn't the best 😅

**Comment by rsunde** [comment]
This functionality becomes a little weird depending on situation, 

for me, I move between different environments with different number of screens and their positions. at Home I have huge screen to the left, laptop to the right, at work I have two screens on the desk, and laptop to the right. Also at work I might go to a presentation room and .... well you get the idea.

**Comment by Cabola** [comment]
@rsunde no one forces you to use features you know ;)
