### ISSUE TITLE
When Style is set to blur, a small line of unblurred taskbar shows on primary monitor when using two monitors

### ISSUE THREAD

**Issue by Alexander-69** [ChrisAnd1998/TaskbarX#334]
How it looks with only one monitor:
![image](https://user-images.githubusercontent.com/52092039/88005237-c7ec4000-cabd-11ea-8eed-0734c54f66a2.png)

How it looks with two:
Notice the unblurred section at the bottom
![image](https://user-images.githubusercontent.com/52092039/88005246-cf134e00-cabd-11ea-951b-fd3bd6cc9ae7.png)

**Comment by rsunde** [comment]
Its much more obvious when using different wallpapers on each screen

![image](https://user-images.githubusercontent.com/3204741/88162641-dea3ab80-cc11-11ea-939a-5ef764732778.png)

**Comment by MiguelGuthridge** [comment]
Same here
