### ISSUE TITLE
When disconnecting a display, the accrylic background on the taskbar is not updated

### ISSUE THREAD

**Issue by Alexander-69** [ChrisAnd1998/TaskbarX#335]
What it is supposed to look like 
![image](https://user-images.githubusercontent.com/52092039/88005626-a9d30f80-cabe-11ea-82d2-2316f2ef650b.png)

When the display is disconnected, it seems that the background acrylic of the other display is used on the other display where the backgound image is not in the same place
![image](https://user-images.githubusercontent.com/52092039/88005699-cf601900-cabe-11ea-96df-7f23ebae2a94.png)

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
