### ISSUE TITLE
[moonshot] Migrate from MSAA

### ISSUE THREAD

**Issue by kaovilai** [ChrisAnd1998/TaskbarX#339]
[Microsoft suggests to deprecate use of MSAA if possible](https://docs.microsoft.com/en-us/windows/win32/winauto/microsoft-active-accessibility-and-ui-automation-compared#transitioning-from-msaa)

Just something to think about if and when there's nothing else to do :P

**Comment by ChrisAnd1998** [comment]
@kaovilai Since 1.5.0.0 i migrated from UIAutomation to MSAA to get a little bit better performance and responsiveness. MSAA also feels more straight to the point and plain while coding. I think i have to stick with MSAA as there is no other option than UIAutomation which increases CPU Usage.

**Comment by kaovilai** [comment]
I didn't know about performance issues. Thought Microsoft advertised it as better in every way.

**Comment by ChrisAnd1998** [comment]
@kaovilai I also thought it was better as it is newer but, after running some tests with MSAA i was able to update the taskbar a little bit quicker after an icon gets added or removed. I also experienced better performance when i needed TaskbarX to work with unlimited monitors.

**Comment by kaovilai** [comment]
How did you test unlimited monitors?

**Comment by ChrisAnd1998** [comment]
@kaovilai XD, I just wrote it to detect the taskbars so if it worked on 2 monitors it already works. I ended up hooking 6 monitors and then you can really notice the performance difference between UIA and MSAA. UIA took almost twice as much CPU Usage. Tested on multiple different environments. Maybe if they make it better i can switch back to UIA in the future but, it will take a lot of time as it is a very drastic change.

**Comment by kaovilai** [comment]
Modularization will save us

**Comment by kaovilai** [comment]
Tbh I think there should be some kind of event listeners so that taskbar itself can report change instead of using looper to do the work. But then again, the taskbar wasn't designed to be listened to.
But then there are these shell replacements programs so you can essentially make the taskbar code yourself. Maybe I should snoop at OpenShell see if they're using event listeners for start menu press.

**Comment by ChrisAnd1998** [comment]
I hoped that would work but, the item removed event works while item added doesn't for the taskbar :(. Found that out some time ago.

It also needs to stay working so that I don't need to update TaskbarX when a new update for Windows gets released. So i don't really want to hook into the shell.

I can add event listeners for programs opening and closing but, thats not perfect. As icons can get added and removed in multiple ways.

**Comment by kaovilai** [comment]
> I can add event listeners for programs opening and closing but, thats not perfect. As icons can get added and removed in multiple ways. For example unpinning and pinning.

Could just run the current looper when you detect program close/open for maybe a minute. Then you can safely pause the looper to save power until next event.

**Comment by ChrisAnd1998** [comment]
But then it won't center in other situations. Only when a program opened or closed.

**Comment by kaovilai** [comment]
I thought it gets off centered only when new programs are launched and closed? What else shifts the taskbar? I thought the code set icons to offset to center and only need update when program open/close.

**Comment by ChrisAnd1998** [comment]
Whenever the icons change in size or position it will move. If you have the taskbar set to show labels then when you click an icon it will get wider to show the label text so then it's nice to have it adjusted. So many things can change the taskbar's size. I want it centered in any case.

**Comment by kaovilai** [comment]
Gotcha. A plausible feature for laptop users. Use detect events instead of
always centered.
