### ISSUE TITLE
Uninstalling issue

### ISSUE THREAD

**Issue by hapatapa** [ChrisAnd1998/TaskbarX#343]
when i try to uninstall taskbarx microsoft .net say the function is not working and if i try to uninstall it with control panel it say cannot because i'm not an administrator but i'm an administrator because its the local account help me!

**Comment by hapatapa** [comment]
oups i have closed that😂

**Comment by NicTanghe** [comment]
This ticket or form of it is already existing i think.

**Comment by hapatapa** [comment]
can you give me the link of the ticket or form?

**Comment by hapatapa** [comment]
it's because the installation have bugged so the uninstallation don't work.
but its ok i formatted my pc, so taskbarx was uninstalled
