### ISSUE TITLE
Unable to use TaskbarX Configurator

### ISSUE THREAD

**Issue by solarunderscore** [ChrisAnd1998/TaskbarX#344]
You can open the program, but none of the changes get applied. Only way to fix this is to uninstall, reboot computer, and reinstall. It is quite tedious and it happens pretty often for me. To reproduce this you need to select a taskbar theme like acrylic then change it back to default. Then exit and voila TaskbarX Configurator stops working and TaskbarX stops registering updates to the taskbar.

**Comment by solarunderscore** [comment]
https://youtu.be/0inkU0cj2Iw video of the problem.

**Comment by rsunde** [comment]
not sure what the author have in mind, but maybe you could try and set is as a service which will restart itself, or maybe a task ?

**Comment by rsunde** [comment]
> https://youtu.be/0inkU0cj2Iw video of the problem.

I am curious of your live wallpaper 👍

**Comment by rsunde** [comment]
> _not sure what the author have in mind, but maybe you could try and set is as a service which will restart itself, or maybe a task ?_
> 
> _Sorry, I didnt read your error description well enough._
> 
> **try launching it from commandline and then see what console messages it writes as it crashes.**

Sorry, I have tried myself, didnt work.
