### ISSUE TITLE
Not centering properly when changing modes (tablet mode and desktop)

### ISSUE THREAD

**Issue by ErwinSuwito** [ChrisAnd1998/TaskbarX#345]
When a users switches to tablet mode from desktop or desktop to tablet mode, taskbar icons are not being centered properly.

Original on desktop:
![Original](https://user-images.githubusercontent.com/30384397/88504175-16d63000-cffe-11ea-9dfb-a838a09332f1.png)

After enabling tablet mode:
![After](https://user-images.githubusercontent.com/30384397/88504185-1f2e6b00-cffe-11ea-994d-b729b24897df.png)

App will work properly again after restarting it.

**Comment by ChrisAnd1998** [comment]
@ErwinSuwito can you try the pre-release 1.5.7.0 to see if that works?

**Comment by ErwinSuwito** [comment]
@ChrisAnd1998 Yes it does work with pre-release 15.7.0.

Thanks!
