### ISSUE TITLE
Taskbar isn't transparent after reboot or restart

### ISSUE THREAD

**Issue by nevedpaharia** [ChrisAnd1998/TaskbarX#346]
Hey every time I start up my laptop the taskbar is in its default condition I mean it is not transparent but after I run the configurator and then click on apply it becomes transparent.

**Comment by cpe342** [comment]
Had same problem, managed to fix it by going into Configurator and clicking "Restart TaskbarX" a few times, then tried applying Blur, then apply Transparent. Hope this helps!

**Comment by YJJ982** [comment]
Restart the computer, the taskbar is not transparent

**Comment by YJJ982** [comment]
It would be great if there is an option to start with the computer

**Comment by ChrisAnd1998** [comment]
@YJJ982 There is but, it seems like something is preventing it from starting up or creating the Taskschedule. Any antivirus installed other than Windows Defender?

**Comment by alfredovaldes** [comment]
I have the same issue. TaskbarX does start, but the transparency doesn't get applied until i go into configurator and reapply manually.

**Comment by ChrisAnd1998** [comment]
Maybe the Taskschedule delay is to short?.. Inside the Configurator under the taskschedule tab.

**Comment by alfredovaldes** [comment]
Had delay at 3 seconds. Changed it to 10 and rebooted, it looked transparent like i wanted it to, but after opening any program it reverts to the windows default style, altough the icons in the taskbar do appear at the center like configured.

**Comment by ChrisAnd1998** [comment]
Do the icons move when you open any application?

**Comment by YJJ982** [comment]
no，When the application window is full screen, the taskbar will be opaque------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Chris&amp;nbsp;Andriessen&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年8月18日(星期二) 中午12:18
收件人:&nbsp;&quot;ChrisAnd1998/TaskbarX&quot;<TaskbarX@noreply.github.com&gt;;
抄送:&nbsp;&quot;YJJ982&quot;<1479284652@qq.com&gt;;&quot;Mention&quot;<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [ChrisAnd1998/TaskbarX] Taskbar isn&#39;t transparent after reboot or restart (#346)

**Comment by YJJ982** [comment]
When the machine is booted up, it cannot be started by itself and must be manually configured again------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Chris&amp;nbsp;Andriessen&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年8月17日(星期一) 中午12:43
收件人:&nbsp;&quot;ChrisAnd1998/TaskbarX&quot;<TaskbarX@noreply.github.com&gt;;
抄送:&nbsp;&quot;YJJ982&quot;<1479284652@qq.com&gt;;&quot;Mention&quot;<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [ChrisAnd1998/TaskbarX] Taskbar isn&#39;t transparent after reboot or restart (#346)

**Comment by alfredovaldes** [comment]
> Do the icons move when you open any application?

Sometimes they do, sometimes they dont. I had noticed that the moving occurs whenever i open a GPU intensive app. My GFX card is a GTX1050Ti at 4GB. Processor is Ryzen 5 1600, 16 GB DDR4 2666MHZ and im running windows 10 2004 update on an M.2 SSD. I do not think it is a performance issue on my hardware side.

**Comment by ChrisAnd1998** [comment]
@alfredovaldes Hardware doesn't really matter. I test TaskbarX on really old machines too but, this is just really weird behavior.

**Comment by volia1** [comment]
@ChrisAnd1998 I also experienced the same thing.
> Do the icons move when you open any application?

It does get centred and move when any app opens where task scheduler delay is 3 secs. I'll update after changing the delay to 6 secs.

**Comment by volia1** [comment]
@ChrisAnd1998 I experienced the same thing as him @alfredovaldes.
Change the delay to 10 secs, and it keeps transparent until I open any app.

**Comment by alfredovaldes** [comment]
I have been using it on my laptop as well, an old thinkpad with integrated graphics and the issue never appeared. Still occurs on my main PC every boot.

**Comment by loyalOrange503** [comment]
crazy to think a year later this is still a issue lol... will this get fixed at some point?

What I've done, 
Win+r
Shell:startup
put 'TaskbarX Configurator' shortcut here.

then every time I start the PC, the configurator window starts as well. All I have to do is press 'apply' and the transparency effects gets applied. still frustrating it doesn't do this from the get go, but happy it at least works somehow.

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
