### ISSUE TITLE
Feature Request | Have option to disable center taskbar all together.

### ISSUE THREAD

**Issue by AM9327** [ChrisAnd1998/TaskbarX#347]
Without position (vanilla win10 taskbar) https://prnt.sc/tq6i0c

With position https://prnt.sc/tq6hjz

Basically what I am saying I want to keep using the style tab but I don't want to use the center taskbar. I already did -300 to put it back to normal but the downside is if I open a new program it will mess it up. So I want the option to disable center taskbar all together and just use the style tab (transparent taskbar)

**Comment by ChrisAnd1998** [comment]
TaskbarX's main purpose is to move the taskbar so an option to disable it won't be comming. If you want to give the taskbar a style only then i would recommend using TranslucentTB.

**Comment by Danita** [comment]
Ah, I should've read this before buying. Thanks.

**Comment by AM9327** [comment]
> TaskbarX's main purpose is to move the taskbar so an option to disable it won't be comming. If you want to give the taskbar a style only then i would recommend using TranslucentTB.

Ah ok well thanks anyways, it's a great program but it would be cool if you did add that in a future update.

**Comment by ChrisAnd1998** [comment]
@Danita @AM9327 Allright, the option will be added next update ;)
