### ISSUE TITLE
Centering not working when having horizontal and vertical taskbar simultaneously

### ISSUE THREAD

**Issue by Spagoot420** [ChrisAnd1998/TaskbarX#348]
I have a multi-monitor setup.
On one monitor i have a vertical taskbar, on the other one it is horizontal.

Unfortunately, the icons are only being centered on one of them, in this case the vertical one:
![example](https://user-images.githubusercontent.com/49160836/88780736-ba088000-d18b-11ea-9c12-526769e31fe7.png)

Keep up the good work!

**Comment by ChrisAnd1998** [comment]
It looks like you're using an older version... Which is not capable of doing that.
