### ISSUE TITLE
Taskbar dosen't hide in fullscreen youtube video

### ISSUE THREAD

**Issue by umerbinsalman** [ChrisAnd1998/TaskbarX#349]
I have set taskbar x style to blur and when I load a youtube video and toggle the fullscreen the taskbar doesn't hide.
![Screenshot (9)](https://user-images.githubusercontent.com/24528025/89054431-365cb800-d372-11ea-8f4e-2828436e70f6.png)

**Comment by umerbinsalman** [comment]
the problem was from my end. so, closing this issue

**Comment by saraselis** [comment]
How did you fix that?

**Comment by Baryczka** [comment]
IT happening to me as well. I was just restarting explorer.exe from task manager to fix it. Would be good to know if there is other option @umerbinsalman @saraselis
