### ISSUE TITLE
Microsoft Store version installed under two accounts - only autostarts under 1

### ISSUE THREAD

**Issue by umern** [ChrisAnd1998/TaskbarX#350]
Hi,
I purchased the MS Store version using my two different accounts - and installed on the same PC - both accounts are Admin users.
Only the first account autostarts TaskBarX on reboot and remembers the settings.
The 2nd account it does not autostart and if I manually start it, it does not remember the settings.
Any ideas how to fix this?
Thanks.

**Comment by ChrisAnd1998** [comment]
@umern Maybe an Antivirus blocking TaskbarX from starting?

**Comment by umernalla** [comment]
I will check the logs, but the same Norton AV is installed under both accounts.

**Comment by ChrisAnd1998** [comment]
@umernalla There must be something blocking it...

**Comment by umern** [comment]
It seems to startup sometimes - but does not apply the settings - I set it to transparent but it does not start as transparent.
If I check the configurator it shows the Transparent option is selected and if I click apply then it changes to transparent.
Also, today I got the following popup message:
[Window Title]
shell:AppsFolder\40210ChrisAndriessen.FalconX_y1dazs5f5wq00!TaskbarX
[Content]
shell:AppsFolder\40210ChrisAndriessen.FalconX_y1dazs5f5wq00!TaskbarX
Class not registered
[OK]
Hope that helps

**Comment by ChrisAnd1998** [comment]
@umern Can you try increasing the Taskschedule delay to like 10 or so inside the Configurator?
