### ISSUE TITLE
Centering creeps from left to right over time

### ISSUE THREAD

**Issue by surfarri** [ChrisAnd1998/TaskbarX#351]
The icons start out not centered, and gradually shift from left to right.  Also, they disappear entirely for a few seconds and then eventually come back.
<img width="1891" alt="taskbar" src="https://user-images.githubusercontent.com/22309847/89110900-a6744800-d41d-11ea-9159-475f56311eb4.PNG">

**Comment by surfarri** [comment]
Trying to reproduce it again myself.  It may have been when switching from a game back to windows desktop.  Haven't come across it, but will update if/when it happens.

**Comment by ChrisAnd1998** [comment]
@surfarri 👍
