### ISSUE TITLE
Show/Hide items in File Explorer reloads TaskbarX

### ISSUE THREAD

**Issue by arthurjosse** [ChrisAnd1998/TaskbarX#353]
Windows 10
TaskbarX 1.5.4.0

In File Explorer, toggling Hidden items to show the files or folders that are marked as hidden reload TaskbarX. Would be less distracting if that wasn't the case.

**Comment by ChrisAnd1998** [comment]
@arthurjosse You need to update TaskbarX to **1.5.6.0** ;)

**Comment by arthurjosse** [comment]
Will do, thanks
