### ISSUE TITLE
Command line arguments for Windows Store version?

### ISSUE THREAD

**Issue by danperks** [ChrisAnd1998/TaskbarX#354]
Very simple. Is this possible and if so, how?

**Comment by ChrisAnd1998** [comment]
@danperks 
Commandline Arguments
-stop will stop TaskbarX, puts all icons back to the left and resets the taskbar style.
-tbs=1 will make the taskbar transparent. 2 blur, 3 acrylic and 0 is disabled.
-ptbo=0 will set the offset of the primary taskbar based on the center.
-stbo=0 will set the offset of the primary taskbar based on the center.
-cpo=1 will only center the primary taskbar. 0 is disabled.
-cso=1 will only center the secondary taskbar(s). 0 is disabled.
-as=backeaseout will set the animation style to BackEaseOut. "none" is instant.
-asp=500 will set the speed of the animation.
-lr=400 will set the refresh rate of the looper/taskbar checker.
-cib=1 will set the primary taskbar position in between start, search etc.. and the tray.
-ftotc=1 will update any toolbar when a tray icon gets added or removed.
-sr=1920 will put the icons to the left when screen width becomes 1920px.
-cfsa=1 will pause TaskbarX if a fullscreen app is running.
-obas=backeaseout will set the animation style to BackEaseOut when on battery mode.
-oblr=400 will set the refresh rate of the looper/taskbar checker when on battery mode.

cmd.exe /c start shell:AppsFolder\40210ChrisAndriessen.FalconX_y1dazs5f5wq00!TaskbarX -tbs=1 -as=cubiceaseinout
