### ISSUE TITLE
App gets disabled after entering a negative value to the Primary Taskbar Offset

### ISSUE THREAD

**Issue by alfawal** [ChrisAnd1998/TaskbarX#355]
just tried to position the icons to the left side by entering a negative value

**Comment by ChrisAnd1998** [comment]
Weird, i can't reproduce it. What did you enter exactly?

**Comment by alfawal** [comment]
The app gets disabled at any negative value starting from -1, my purpose was to just use the transparent style without adjusting the icon's position to the center

**Comment by alfawal** [comment]
Just downloaded the latest version now and looks like it's fixed! I don't know if you meant to fix it. LOL
