### ISSUE TITLE
Folders pinned to taskbar

### ISSUE THREAD

**Issue by retiredfields** [ChrisAnd1998/TaskbarX#357]
I have two folders added to the taskbar. Without TaskbarX the ">>" buttons, next to the folder name, highlight when the mouse cursor passes over them. With TaskbarX running, the ">>" buttons no longer highlight. 

![image](https://user-images.githubusercontent.com/69468376/89789979-8cea9480-dade-11ea-9909-bd4585ab3ae5.png)

**Comment by ChrisAnd1998** [comment]
Currently i don't know how to fix this. I know whats causing it... The taskbar's place holder is frozen to prevent the taskbar from flickering.
