### ISSUE TITLE
Set the taskbarx from microsoft store run in the windows start

### ISSUE THREAD

**Issue by walberth** [ChrisAnd1998/TaskbarX#359]
When i turn on my computer, by default the app is not running. I achieve this downlaod de compiled files from github and copy paste the shortuct in startup folder. But recently i buy the microsoft store app in a way to support you and your develop. But can't successfully configurate this behavior. I'ts not pretty have to start the prograrm every time i turn on the computer. Thanks for your time.

**Comment by ChrisAnd1998** [comment]
@walberth Once you click apply inside the Configurator then a Taskschedule should be created. If you already did this you can try to set the delay option inside the Configurator under the taskschedule tab to 10 seconds. If it still doesn't work then there may be an Antivirus that prevents the Configurator from creating a Taskschedule.

**Comment by walberth** [comment]
Hello, sorry for the delay you have absolutly right. Thanks for you support.
