### ISSUE TITLE
Icons not centered in touch friendly mode

### ISSUE THREAD

**Issue by michalhudecek** [ChrisAnd1998/TaskbarX#360]
The recent [touch-friendly mode ](https://www.windowscentral.com/microsofts-improving-touch-desktop-mode-right-approach)in Windows 10 increases the spacing between icons on the taskbar when keyboard is removed (I am using Surface Pro 7). Do not mistake it with Tablet mode which does something else.

TaskbarX does not compensate for that. The icons are hidden on the right even though there is a lot of space on the left.

![image](https://user-images.githubusercontent.com/1215304/90102144-47c59d00-dd40-11ea-8c48-c4a2f2eaf8fb.png)

**Comment by ChrisAnd1998** [comment]
@michalhudecek TaskbarX looks for the taskbars size by itself so it will notice the spacing. If you look closely you can see that the icons are centered but, the tray area is overlapping it. Have you enabled the "Compensate clock, tray, start etc.." option enabled inside the Configurator?

**Comment by michalhudecek** [comment]
I see. I would prefer real center on large screens (like external monitors) and compensating for clock etc. on small screens then. That is a separate issue though. I am closing this one.
