### ISSUE TITLE
Windows Security Threats Warning

### ISSUE THREAD

**Issue by arslanmuhsin** [ChrisAnd1998/TaskbarX#361]
Windows Security Anti-virus gives warning; Threats found: Trojan:Win32/Wacatac.B!ml

![Annotation 2020-08-13 190716](https://user-images.githubusercontent.com/43956680/90158853-390ad480-dd98-11ea-902b-caedbd99d673.png)

**Comment by Wibbbs** [comment]
Also seeing this from virus total.

![image](https://user-images.githubusercontent.com/24574428/90198733-8b4ff380-dda0-11ea-815a-19526cdc7933.png)

**Comment by vMambaaa** [comment]
I also received this warning from my Firewall yesterday.
![ApplicationFrameHost_aO8QfKIqHt](https://user-images.githubusercontent.com/39503573/90282772-905e8280-de34-11ea-826f-f368ccd9f649.png)

**Comment by ChrisAnd1998** [comment]
Weird, it seems like it targets the TaskbarX.exe on @arslanmuhsin and the Taskschedule on @vMambaaa .
It's clear that it's an automatic detection not specifically TaskbarX targeted. It may not like MSAA. I can try to contact Microsoft about this but, that won't fix it for a next update.

**Comment by halkliff** [comment]
> Weird, it seems like it targets the TaskbarX.exe on @arslanmuhsin and the Taskschedule on @vMambaaa .
> It's clear that it's an automatic detection not specifically TaskbarX targeted. It may not like MSAA. I can try to contact Microsoft about this but, that won't fix it for a next update.

Had the same issue as well. So, can we just tell the antivirus to ignore it?

**Comment by ChrisAnd1998** [comment]
@halkliff Add the TaskbarX.exe or just it's whole directory to Windows Defenders exclusions.

**Comment by PhantomX165** [comment]
![TaskbarX_1 6 1 0 9_2_2020 8_39_47 AM](https://user-images.githubusercontent.com/70643389/91982376-2aa93c00-ecf8-11ea-9193-adc9d24aeeef.png)

This is what it says when I open the configurator

![TaskbarX_1 6 1 0 9_2_2020 8_39_34 AM](https://user-images.githubusercontent.com/70643389/91982439-3c8adf00-ecf8-11ea-9047-5c4ca0b8706c.png)
 This is what it says when I open taskbarX.exe

i extracted the zip file and opened these applications
if that's the problem i can't find the setup for taskbarx as it was not in the zip file

**Comment by PhantomX165** [comment]
i run windows 10 home edition

**Comment by PhantomX165** [comment]
it also says the same thing about the win32 trojan virus on my windows defender

**Comment by spupuz** [comment]
got virus error on defender Trojan:Win32/Emali.A!cl for version 1.6.1.0

**Comment by PhantomX165** [comment]
so what do we do about this

**Comment by ChrisAnd1998** [comment]
@PhantomX165 The best thing to do is to submit a **false positive** sample to Microsoft or for the AV your'e using.
I already did this for couple including Defender. Or just add TaskbarX to your exclusions.
