### ISSUE TITLE
Rainmeter TaskbarX does not center all the time

### ISSUE THREAD

**Issue by sean7130** [ChrisAnd1998/TaskbarX#362]
Sometimes when I switch in between different tabs, the icon is uncentered. It proceeds to stay this way until I either refresh it in rainmeter or just snaps back itself after ~30 seconds or so. 

I set the center checker looper to 400 ms, and also tried toggling in "pause during full screen" option but neither seem to make a good difference.

This is my current configuration

```
as=backeaseout
;will set the animation style to BackEaseOut. "none" is instant. <-- Only lower case is alowed.

obas=backeaseout
;will set the animation style to BackEaseOut when on battery mode. "none" is instant. <-- Only lower case is alowed.

tbs=2
;will make the taskbar transparent. 2 blur, 3 acrylic and 0 is disabled.

ptbo=0
;will set the offset of the primary taskbar based on the center. Use - for negative numbers like 350 or -350.

stbo=0
;will set the offset of the primary taskbar based on the center. Use - for negative numbers like 350 or -350.

cpo=0
;will only center the primary taskbar. 0 is disabled and 1 is enabled.

cso=0
;will only center the secondary taskbar(s). 0 is disabled and 1 is enabled.

asp=1000
;will set the speed of the animation in milliseconds.

lr=400
;will set the refresh rate of the looper/taskbar checker in milliseconds.

oblr=400
;will set the refresh rate of the looper/taskbar checker when on battery mode in milliseconds.

cib=0
;will set the primary taskbar position in between start, search etc.. and the tray. 0 is disabled and 1 is enabled.

ftotc=1
;will update any toolbar when a tray icon gets added or removed. 0 is disabled and 1 is enabled.

sr=500
;will put the icons to the left when screen width becomes 500px.

cfsa=0
;will pause TaskbarX if a fullscreen app is running. 0 is disabled and 1 is enabled.
```

![bug](https://user-images.githubusercontent.com/46799877/90195925-b0406880-dd98-11ea-8afd-f481b44e7fa2.png)

You can see from my screenshot that all my icons are somehow stuck to the left. In some other times it will stuck to the right.

**Comment by ChrisAnd1998** [comment]
@sean7130 It could be just stuck there due to a function that prevents to large movements to prevent a swing bug. I am currently working on 1.5.7.0 and have improved it by a lot. It could be possible this is fixed next update as it allows large movements and also keeps the big swing bug fixed.

**Comment by sean7130** [comment]
Okay that makes sense, if a function that prevents large swing is the issue, then do you expect changing the animation style to "none" resolve the problem as there should be no more swing? Regardless I'll give it a try soon.
