### ISSUE TITLE
TaskbarX applied, but not appearing as the customized taskbar.

### ISSUE THREAD

**Issue by barnoii** [ChrisAnd1998/TaskbarX#365]
I set my setting and hit apply, but it doesn't do a thing. Thanks in advance.

**Comment by ChrisAnd1998** [comment]
@barnoii Any antivirus running that may prevent TaskbarX from staring?..

**Comment by barnoii** [comment]
I don't think so. I haven't received a notification from Windows Defender. I added an exclusion for TaskbarX though, just in case.

**Comment by barnoii** [comment]
And here's what shows in dnSpy if this helps in anyway. I'm not the much familiar with code 😅. 
![image](https://user-images.githubusercontent.com/65990582/90427055-001c7980-e090-11ea-9432-1737bb7a7e19.png)

**Comment by barnoii** [comment]
I also tried the Rainmeter skin and that didn't work also. For both, it just shows the loading symbol cursor and does nothing.

**Comment by ChrisAnd1998** [comment]
It's just stopping instantly. So i have no clue where the issue is. What happens if you enable the services you disabled again?

**Comment by barnoii** [comment]
Disabling the services I disabled was because of the 100 disk bug that occurred. I don't think enabling it won't do a thing. The SysMain service and Windows Search service disabled does not effect the computer. Disabling it only slows the search a little bit. I'll try hough.

**Comment by ChrisAnd1998** [comment]
Actually no, but as that's a thing you changed i needed to know for sure. I have been thinking but, still no idea what could be the issue...

**Comment by barnoii** [comment]
Thanks for trying. I'll try to think as well as why this is becoming a problem.

**Comment by barnoii** [comment]
Sorry but the solution is so dumb.  A software update made it work.
