### ISSUE TITLE
Taskbarx keeps flickering and crashing

### ISSUE THREAD

**Issue by danknight03** [ChrisAnd1998/TaskbarX#369]
So as soon as i reboot the pc its all well until i click once and then the taskbar keeps flickering and im unable to click anything and evertime i boot it up also it gets a command promt thing that pops up... i can't use the pc at all please help

**Comment by ChrisAnd1998** [comment]
Seems like you have more tools modifying the taskbar?
On startup quickly open cmd.exe
And enter this command: **SCHTASKS /DELETE /TN "TaskbarX"**
Then restart PC

**Comment by qthang** [comment]
i have same problem. How fix?

**Comment by bearoxo** [comment]
I tried SCHTASKS /DELETE /TN but my TaskName somehow was "TaskbarX DESKTOP-JOHNJohn" (e.g. My PC name is Desktop-John), but it didn't worked. 

I still have FalconX but I stopped the app and remove the logon task already.
But the taskbar still flickers like it has Tourette's.

**Comment by ChrisAnd1998** [comment]
@bearoxo It's right that it's called "TaskbarX DESKTOP-JOHNJohn" Because it should be TaskbarX + Pc name + User name. You can use the Configurator to remove the taskschedule under the Taskschedule tab and stop the TaskbarX process. If that's done and the Taskbar is still flickering then i'm not sure if the issue is caused by TaskbarX as it is completely portable.

**Comment by bearoxo** [comment]
Yeahhh, turns out the flickering problem wasn't from TaskbarX. It was from an older version of Stardock Fences. Updated it and no more flickering.

**Comment by qthang** [comment]
How do I know if something is causing the TaskbarX to crash?

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
