### ISSUE TITLE
No "TaskbarX.exe" executive file

### ISSUE THREAD

**Issue by Daemitrious** [ChrisAnd1998/TaskbarX#370]
[TaskbarX-master.zip](https://github.com/ChrisAnd1998/TaskbarX/files/5112898/TaskbarX-master.zip)
I've tried cloning it but I couldn't find the executive for the main application.  The file above is the zipped file of TaskbarX but I couldn't find out how to launch it either.

**Comment by ChrisAnd1998** [comment]
What's the issue here exactly? 

You compiled the source but did not find the exe?
If so you have to enter the right build path.

Or looking for the compiled version?
https://github.com/ChrisAnd1998/TaskbarX/releases

**Comment by Daemitrious** [comment]
Ok thanks, 1.5.8 worked for me!
