### ISSUE TITLE
Request: Turn taskbar transparency back to normal when maximising a window

### ISSUE THREAD

**Issue by leonscm** [ChrisAnd1998/TaskbarX#371]
Would be nice if you had the option to make the taskbar turn back to normal or opaque when a window is maximised, similar to the "translucentTB" app.

**Comment by barnoii** [comment]
Pretty sure this was already a feature, but it seems to be removed in the latest updates.

**Comment by barnoii** [comment]
Nope, it still a feature, just tested right now. When a window is maximized, it turns dark.

**Comment by ChrisAnd1998** [comment]
It's there but, completely disabled as it caused high CPU usage. When i have the time i will dig into this.

**Comment by ChrisAnd1998** [comment]
It's in the pre-release now ;) you can check it out. I also added the option to set a color and transparency of the taskbar(s).

**Comment by Manu99it** [comment]
Could be that being triggered also when opening "start", "search", "Cortana", "calendar" (on the right), "notification" and the other buttons that show menus just upon the taskbar? Would be awesome also an option to choose or not that behavior. So one could completely get rid of taskbartb (I'm using that in combination for now)
