### ISSUE TITLE
Taskbar looks different on the 2nd display against primary display

### ISSUE THREAD

**Issue by happybaby8882** [ChrisAnd1998/TaskbarX#372]
when i set "acrylic" style in the configurator, on the primary display, it looks fine, but on the 2nd display, the taskbar is still Transparent.

**Comment by ChrisAnd1998** [comment]
Yeah.. i'm not a fan of the styling. You can better try this for now.

HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced
**TaskbarAcrylicOpacity** <-- DWORD
0 = Transparent and 1 > 255 is Acrylic

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
