### ISSUE TITLE
Default style when maximized does not work for UWP apps

### ISSUE THREAD

**Issue by Martin5001** [ChrisAnd1998/TaskbarX#374]
In version 1.6.0.0 the option to revert default style when maximized app is running doesn´t work for UWP apps (tried Windows settings, MS Store) but it works for Win32 apps (File explorer, Chredge)

**Comment by ChrisAnd1998** [comment]
Oh! thanks i feel so dumb that i didn't test it on UWP apps.

**Comment by ChrisAnd1998** [comment]
Should be fixed now ;)
