### ISSUE TITLE
Last build transparent taskbar doesn't work.

### ISSUE THREAD

**Issue by felipemartau** [ChrisAnd1998/TaskbarX#375]
Today I had an issue with taskbarx and had to re-download it. When I selected transparent with 0 alpha, it glitched out and wasn't transparent, but when you set it to 1% alpha it works, so I guess there might be some bug with the 0% alpha.

**Comment by samuelrafo** [comment]
Exact same bug here. 1% transparency works very well but 0% make taskbar gray.

**Comment by GrosBourrin** [comment]
oh i came here to talk about that ! so this is an issue of taskbarx ! same issue here ! 1.5.9 tbx

**Comment by ChrisAnd1998** [comment]
**ACCENT_ENABLE_TRANSPARENT** is the one that should be used for full transparent.
I tried to do it with **ACCENT_ENABLE_TRANSPARENTGRADIENT** which works fine on my end with 0%.

I have added them as sepperate options in the **1.6.0.0 pre-release** https://github.com/ChrisAnd1998/TaskbarX/releases/tag/1.6.0.0

-tbs=1 (Full transparent)
-tbs=2 (Blur)
-tbs=3 (Acrylic)
-tbs=4 (Transparent Gradient)
-tbs=5 (Opaque)

![prev](https://user-images.githubusercontent.com/50437199/91536767-84cf8900-e915-11ea-8d44-2bab9a5c293f.png)

**Comment by samuelrafo** [comment]
Thanks, 1.6.0.0 with transparent gradient and alpha 0% working very well!
