### ISSUE TITLE
Dual monitors turn off display sleep issue

### ISSUE THREAD

**Issue by burt-ie** [ChrisAnd1998/TaskbarX#376]
I'm not sure if this has been reported yet, but I have a dual monitor setup, and every time my monitors go off with power saving/sleep mode the taskbar on my second monitor is no longer centered or transparent.

This happens with both the Windows store version and the download from github but strangely the Rainmeter version does not seem affected by this.

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
