### ISSUE TITLE
Cannot complete the compressed folder extraction wizard.

### ISSUE THREAD

**Issue by MattPeterUK** [ChrisAnd1998/TaskbarX#377]
"The compressed folder is empty. 

Before you can extract files, you must copy files to this compressed folder. "

That's the message I get if I try to unzip version 1.6.0.0. folder. 

Is it just my device (Surface Pro X)  or did you forget to upload the files? 

Cheers

**Comment by barnoii** [comment]
**+1** The same thing happened to me with 7zip.

**Comment by RoboticToast** [comment]
Yeah the same thing is happening to me. I would just download the previous version until the problem is fixed. :)

**Comment by ChrisAnd1998** [comment]
Woops, yep i made a mistake 😆. I will fix it asap when i get back to my PC.
