### ISSUE TITLE
Bug: Switch to Default Taskbar on Maximized Window Not Working

### ISSUE THREAD

**Issue by akhilesh-balaji** [ChrisAnd1998/TaskbarX#378]
Hi,
My favorite feature in Taskbar X is the "Switch to Default Taskbar on Maximized Window" feature. I use this along with the blurred taskbar style. However, on the latest version of TaskbarX, when I turn on this feature, the taskbar permanently switches to the default style. I have tried this with the other styles as well, and it still doesn't work. I'm on Windows 10 version 2004.

**Comment by barnoii** [comment]
Also happens to me. I'll just use 1.5.9.0 for now.

**Comment by ChrisAnd1998** [comment]
In 1.5.9.0 it looked if a window has **WM_MAXIMIZE** style. This works fine however doesn't work with Windows apps and some other applications. in 1.6.0.0 it uses PInvoke **GetWindowPlacement**  to ask if the window is maximized or not. I'll try to cook up a mix of them both.

**Comment by akhilesh-balaji** [comment]
@ChrisAnd1998 Sure, Waiting for the update. I am using TaskbarX is combination with TransparentTB Till then.

**Comment by ChrisAnd1998** [comment]
Allright i came up with this:
https://github.com/ChrisAnd1998/TaskbarX/releases/tag/1.6.1.0

Does this fix the issue?

**Comment by barnoii** [comment]
For me, the pre-release did not fix the issue. I tried all styles and still nothing. Maybe @akhilesh-balaji can tell us what is going on on his end.

**Comment by ChrisAnd1998** [comment]
Thx @barnoii. I'll just keep trying different things as I'm trying to solve this blind folded.
I also included a **v2** https://github.com/ChrisAnd1998/TaskbarX/releases/tag/1.6.1.0

**Comment by barnoii** [comment]
All versions did not work for the "Switch back to Default on maximized" feature, but the feature where it just turns black when a maximized window is open is fine.

**Comment by ChrisAnd1998** [comment]
@barnoii Hmm, strange. Tommorow i will try some different things. Thanks for testing :)

**Comment by barnoii** [comment]
@ChrisAnd1998  No problem, thanks for this program, too.

**Comment by barnoii** [comment]
Oh, I'm sorry! The comment where I said it turns black is only because my live wallpaper system pauses when a window is maximized and it made my taskbar look black. I thought it was a feature of yours!

**Comment by ChrisAnd1998** [comment]
Haha, i thought so to but, after reading it a couple times i thought you may have meant that the part that turns it to default only works when you maximize a window...

**Comment by akhilesh-balaji** [comment]
@ChrisAnd1998 Thank you. I tried it on v3, and I had the same issue. Maybe it has something to do with an external factor?

**Comment by akhilesh-balaji** [comment]
@ChrisAnd1998 Every time I enable that option, and hit apply, it briefly changes to the blur effect before becoming default again. I started having this issue, just before I got version 1.6.0.0. For reference, here's a recording of the issue:
https://we.tl/t-RMvl6tbzdA

**Comment by ChrisAnd1998** [comment]
@akhilesh-balaji Thanks for makking the video at least i can see whats happening :). I think it detects another application that is not visible.

**Comment by ChrisAnd1998** [comment]
@akhilesh-balaji @barnoii I've added a **v4**
https://github.com/ChrisAnd1998/TaskbarX/releases/tag/1.6.1.0

Next to the _Restart, Stop, Close and Apply buttons_ you can enable "Show Console".
The console will output all the windows it thinks are maximized.
So use this without having any window maximized. Maybe it will output the invisible window that's causing the issue.

**Comment by akhilesh-balaji** [comment]
@ChrisAnd1998 I tried it, and this is what it kept on giving as an output until I closed the Window:
![image](https://user-images.githubusercontent.com/69246693/91653989-f862c900-eac2-11ea-9b6a-0e5ea8833d1f.png)

**Comment by akhilesh-balaji** [comment]
I tried it, and this is what it said:
![image](https://user-images.githubusercontent.com/69246693/91654007-35c75680-eac3-11ea-9d59-f066af3b6ef1.png)

**Comment by ChrisAnd1998** [comment]
It's doing exactly i was thinking...

Here's how it should behave:
https://streamable.com/fubsw7

Thanks for testing!

**Comment by akhilesh-balaji** [comment]
@ChrisAnd1998 👍

**Comment by akhilesh-balaji** [comment]
@ChrisAnd1998 I have a suggestion...
TranslucentTB is an open source app that resets the taskbar to default when a window in maximized, or when the start menu is opened. How about taking a look at what they have done? This is the link: https://github.com/TranslucentTB/TranslucentTB

**Comment by ChrisAnd1998** [comment]
@akhilesh-balaji Yep, there's also https://github.com/Elestriel/TaskbarTools ... The fun part is to solve this without looking in someone else's code but, there's no other option than taking a little peek i guess.

**Comment by ChrisAnd1998** [comment]
@akhilesh-balaji In TranslucentTB it also looks if the window is not Cloaked
`if (window.visible() && window.state() == SW_MAXIMIZE && **!**window.get_attribute<BOOL>(**DWMWA_CLOAKED**)`

I'm not sure if i did this the right way.. but, maybe it already works.

I've added a v5
https://github.com/ChrisAnd1998/TaskbarX/releases/tag/1.6.1.0

**Comment by akhilesh-balaji** [comment]
@ChrisAnd1998 Nope, still the same...

**Comment by ChrisAnd1998** [comment]
@akhilesh-balaji I don't see what i'm missing here :/
Can you see what the console outputs in **v6**?
https://github.com/ChrisAnd1998/TaskbarX/releases/tag/1.6.1.0

**Comment by akhilesh-balaji** [comment]
@ChrisAnd1998 This is what it gave me:
![image](https://user-images.githubusercontent.com/69246693/91656399-0ec65000-ead6-11ea-9eb0-587ddf870cc0.png)

**Comment by akhilesh-balaji** [comment]
@ChrisAnd1998 
💡 I'm using Microsoft PowerToys as well. I enabled all the features. Maybe something to do with that...?

**Comment by ChrisAnd1998** [comment]
@akhilesh-balaji Please give it a try :) I'm a bit lost...
What build of Windows 10 do you use? Maybe i can reproduce it.

**Comment by akhilesh-balaji** [comment]
@ChrisAnd1998 I tried disabling all the PowerToy features. it didn't work. I am on Windows version 2004.

**Comment by ChrisAnd1998** [comment]
@akhilesh-balaji 1.5.9.0 looks for the window style **WS_MAXIMIZE** but this only works with win32 apps. So i can't do anything with that to make uwp apps work as they work completely differently. 1.6.0.0 uses the GetWindowPlacement Api which works on both win32 and uwp apps. On your end TaskbarX has to deal with **phantom windows** those windows are invisible frames holding uwp apps and seem to be in a maximized state. Currently i am finding out how to properly detect them but, having a hard time doing so as i'm unable to reproduce this issue :(

**Comment by ChrisAnd1998** [comment]
@akhilesh-balaji **v7** ignores windows that have no title.
The console now outputs the current window title for uwp apps instead of **ApplicationFrameWindow**
This will indicate what specific uwp app is causing this...

https://github.com/ChrisAnd1998/TaskbarX/releases/tag/1.6.1.0

**Comment by akhilesh-balaji** [comment]
@ChrisAnd1998 Hope this helps:
![image](https://user-images.githubusercontent.com/69246693/91659522-cca90880-eaed-11ea-96e0-0b4041832c8d.png)

**Comment by ChrisAnd1998** [comment]
Maybe instead of stopping those apps close "**Application Frame Host**" in taskmanager.

**Comment by akhilesh-balaji** [comment]
Ok, sure. I'll do that if it happens again. But, I switched to the 1.6.0.0, and it's working perfectly fine.

**Comment by akhilesh-balaji** [comment]
> If that works i can make TaskbarX just kill that on start.
Yeah, I think that might work. But, the issue is resolved (temporarily, at least). If it happens again, I'll kill "Application frame host", and tell you if it worked.

**Comment by ChrisAnd1998** [comment]
Allright 👍

**Comment by akhilesh-balaji** [comment]
Closing the issue for now. Will re-open if it happens again.

**Comment by ChrisAnd1998** [comment]
You can also test **v8** first if it happens again..
That one properly detects cloaked/phantom windows like TranslucentTB does.

**Comment by barnoii** [comment]
I can also confirm that **v*** works! Sorry for being late in this conversation, but thanks for fixing this issue! 🙏

**Comment by akhilesh-balaji** [comment]
The problem came back. Testing with v8 now.

**Comment by akhilesh-balaji** [comment]
@ChrisAnd1998 v8 works for me, too!

**Comment by ChrisAnd1998** [comment]
GREAT!!! I want to make some more changes but, you can safely use v8 for now.

**Comment by barnoii** [comment]
I'm not sure if this only is me, but the taskbar has been flickering recently. It does it sometimes and stops randomly.

**Comment by akhilesh-balaji** [comment]
@barnoii I've noticed that this happens when an app with Administrator rights is running. Maybe you should open a new issue about this.

**Comment by akhilesh-balaji** [comment]
@ChrisAnd1998 A similar thing happened again today. Every thing was working perfectly, except when I maximize a windows, the taskbar turns transparent. This is a recording of the issue:
https://we.tl/t-xAtofdOMQF

**Comment by barnoii** [comment]
Before I open an issue, I'll try to find a solution for myself first. I'll see if a restart works.
