### ISSUE TITLE
Transparency stopped and crashed computer

### ISSUE THREAD

**Issue by AyyarliesSoul** [ChrisAnd1998/TaskbarX#379]
The taskbar lost its transparency so when I opened Taskbar configuration anything I clicked and it would crash and open a report to Microsoft.

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
