### ISSUE TITLE
Won't work in my laptop.

### ISSUE THREAD

**Issue by brynhales** [ChrisAnd1998/TaskbarX#382]
I already watch a ton of Youtube videos on how to setup TaskbarX, but it still won't work. I know it's as simple as clicking that TaskbarX application. But it won't work in my pc, it just keeps that loading icon. 
![Screenshot (64)](https://user-images.githubusercontent.com/70501501/91682999-e85fed80-eb85-11ea-89f1-93536ab15cfc.png)

**Comment by ChrisAnd1998** [comment]
@brynhales Allright, let's see whats the issue here...

Can you try to follow this? To begin with.
https://github.com/ChrisAnd1998/TaskbarX/issues/274
