### ISSUE TITLE
After disconnecting an external screen from laptop an error appears

### ISSUE THREAD

**Issue by shayvt** [ChrisAnd1998/TaskbarX#383]
After disconnecting an external screen from the laptop an error appears and TaskbarX crashes.

![image](https://user-images.githubusercontent.com/6310671/91837784-57c6f300-ec01-11ea-90b2-bbfc3c9b5494.png)

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
