### ISSUE TITLE
Unpinning an app leaves a gap that is only fixed after a reboot

### ISSUE THREAD

**Issue by EmilYoung2004** [ChrisAnd1998/TaskbarX#384]
Does not get fixed by restarting TaskbarX
![image](https://user-images.githubusercontent.com/64395220/91881984-3eae5880-ec7a-11ea-9bc9-f8252ef3ed0c.png)
Gap is on right of image

**Comment by ChrisAnd1998** [comment]
@EmilYoung2004 Are you sure it only happens with TaskbarX? Not just a windows bug?
