### ISSUE TITLE
App icons on taskbar goes behind toolbars (Image attached)

### ISSUE THREAD

**Issue by LaruYan** [ChrisAnd1998/TaskbarX#386]
### Screenshot showing problem
![taskbar img](https://user-images.githubusercontent.com/13941966/92060381-9362e800-edce-11ea-8c5b-7b3be2a3e380.jpg)

### Description
- Some of app icons on taskbar goes behind toolbars.
- Checking `Compensate Tray Clock etc...` option in Position on configurator doesn't affects. (still app icons are behind toolbars) 
- Turning some of tray icons on and off doesn't affects. (icons re-positions, however, app icons are still behind toolbars)

### Store or Regular version?
- Regular Zip version 1.6.1.0 on Release section

### What's your Build of Windows 10?
- Windows 10 version 2004. build number 19041.450 

### .NET Framework 4.8 installed?
- Checked registry, `Version` value on `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Client` says 4.8.04084

### Any Antivirus software?
- Kaspersky Internet Security 2021 21.1.15.500(a)

### Any other third-party taskbar tweakers?
- some of my computers have [BatteryBar](https://batterybarpro.com/) installed

### Is there a way i can reproduce?
- put a toolbar on to Taskbar (try **Address**, it can widen its size)

### What are your taskbar settings?
- ON / Lock the taskbar
- OFF / Automatically hide the taskbar in desktop mode
- OFF / Automatically hide the taskbar in tablet mode
- OFF / Use small taskbar buttons
- ON / Use peek to preview the desktop when you move your mouse to the Show desktop button at the end of the taskbar
- ON / Replace Command Prompt with Windows PowerShell in the menu when I right-click the start button or press Windows key+X
- ON / Show badges on taskbar buttons
- Bottom / Taskbar location on screen
- Always, hide labels / Combine taskbar buttons

### What says the error message if you got any?
- there was no error messages

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
