### ISSUE TITLE
version 1.6.10 deceted Trojan:Win32/Emali.A!cl

### ISSUE THREAD

**Issue by spupuz** [ChrisAnd1998/TaskbarX#387]
Hello there i was downloading taskbar 1.6.1.0 portable zip version and Windows Defender detectd Trojan:Win32/Emali.A!cl.

**Comment by ChrisAnd1998** [comment]
Yep, this seems to happen to some people. It looks like a automatic detection.

**Comment by PhantomX165** [comment]
thers already a same issue thread plz go to the other one
