### ISSUE TITLE
Taskbar X breaks after changing task bar

### ISSUE THREAD

**Issue by misaeldry** [ChrisAnd1998/TaskbarX#388]
Hello there, Chris!

Today I noticed that Taskbar X has been updated and I've checked out the new Configurator. The thing is that, if I choose a task bar style, say "Acrylic" my forever favorite, the app just breaks. The settings window is still open but the taskbar goes back to Windows default. I've unistalled the app and reintalled it. Right afer opening it, the icons go back to the middle of the task bar, but again, if I choose another style,the icons go back to their original position on the left, and the app stops working. It does not close, but it stops working.

Looking forward to try all this new features!!

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
