### ISSUE TITLE
Middle mouse clicks on the tray.

### ISSUE THREAD

**Issue by OneIPhy** [ChrisAnd1998/TaskbarX#390]
Make when you press the middle mouse button to open the TaskBarX settings

**Comment by TheClio69** [comment]
@OneIPhy, you can already do it yourself via applications allowing you to assign actions to a combination of keys (for example open the settings of Taskbar X). Here is the link for a tutorial on how to do it: https://www.trishtech.com/2019/10/easy-hot-key-assign-custom-actions-to-keyboard-keys/.

**Comment by TheClio69** [comment]
In addition, some applications already use the middle mouse button to make shortcuts, which would therefore cause problems between the different applications.

**Comment by ChrisAnd1998** [comment]
@TheClio69 I think @OneIPhy ment the tray icon you can enable inside the Configurator. Left click = restart, right click = stop, middle click = unassigned and can be linked to the Configurator.

**Comment by TheClio69** [comment]
> @TheClio69 I think @OneIPhy ment the tray icon you can enable inside the Configurator. Left click = restart, right click = stop, middle click = unassigned and can be linked to the Configurator.

Oh ok.

**Comment by pbakes** [comment]
When I middle-click on the tray icon the configurator never appears. I have to launch the configurator from the start menu.
Should I create a new ticket for the issue? Using version 1.6.6.0 on 19042.804.
