### ISSUE TITLE
Bug with the "hide primary tray" option in the extra category (version 1.6.10)

### ISSUE THREAD

**Issue by TheClio69** [ChrisAnd1998/TaskbarX#391]
Hello, after updating TaskbarX to the new version (version 1.6.10), I tested the option "hide primary tray", which had no problem, until the taskbar slides to the down to switch to full screen mode. After switching to full screen mode, I made it reappear, and a sort of gray rectangle appeared to the right of the taskbar, and could not be removed, look at the following gif :
![taskbarx](https://user-images.githubusercontent.com/36702003/92243737-35afc800-eec2-11ea-91c4-4525d2a77f23.gif). 
Each time the taskbar goes back to full screen, the "rectangle" appears. I hope my bug report will be understandable and as complete as possible. Sorry for my bad English, I'm French. If you need any further information, please let me know.

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
