### ISSUE TITLE
New style "Transparent Gradient" not supported on command line -tbs

### ISSUE THREAD

**Issue by JomaPT** [ChrisAnd1998/TaskbarX#392]
First of all, thank you very much for your excellent program. I have seen that with the latest update (1.6.1.0) the argument on the command line "-tbs" does not support the new "Transparent Gradient" mode (should it work with the value "4"?). The new mode also does not appear in the description of this command on the github page. I hope you can work it out. Thank you.

**Comment by ChrisAnd1998** [comment]
@JomaPT Thx :), Well it's working fine over here.. I have updated the Command line args section. Can you see if the **TaskbarX.exe** is 1.6.1.0? When hovering your mouse over it. If the Configurator works then the commandline args do also. The settings are basiclly stored inside the command line args in the Taskscheduler.

**Comment by JomaPT** [comment]
Thank you very much for the answer. I installed TaskbarX_1.6.1.0.rmskin. In the TaskbarX.ini file I change the values to the tbs variable. The values I have tested are 0, 1, 2, 3, 4 and 5.  The results after refreshing the skin are those seen in the screenshot. The problem is, I can't put the transparent-gradient style. If instead of making the changes in the .ini file I use TaskbarX Configurator I do manage to apply the style correctly.

![tbs](https://user-images.githubusercontent.com/70835817/93001522-dee46700-f52f-11ea-94ad-7470887bdb13.png)

**Comment by ChrisAnd1998** [comment]
@JomaPT The transparent gradient needs the color parameter to be set. 0,0,0,0 is the same as transparent.

**Comment by JomaPT** [comment]
Perfect. That's the solution. In color variable I have placed the values 0;0;0;50 and now it works perfectly. Thank you for teaching me how to choose the right values.

**Comment by ChrisAnd1998** [comment]
No problem :)
