### ISSUE TITLE
Sync on tool?

### ISSUE THREAD

**Issue by crutkas** [ChrisAnd1998/TaskbarX#394]
Hi Chris, i'm from PowerToys team, got time to sync?  would love to chat.  crutkas@microsoft.com

**Comment by Aaron-Junker** [comment]
Oh ok. Why Maybe later?

**Comment by ChrisAnd1998** [comment]
@Aaron-Junker Here's the the mail i sent to Clint why.

> I feel grateful that you would take TaskbarX in consideration for migrating with such an amazing project. However i'am not sure if i want to do this right now... I feel TaskbarX wouldn't be about me anymore... I have been developing TaskbarX for years and the people kept me motivated to keep going. I just really like that i can just do my thing and the way TaskbarX heading right now.  
> 
> Thanks for your offer :). Maybe i change my mind in the future.

**Comment by Aaron-Junker** [comment]
ok Thats understandable
