### ISSUE TITLE
Request: Compensate for XMeters app display in taskbar

### ISSUE THREAD

**Issue by stevemagruder** [ChrisAnd1998/TaskbarX#395]
XMeters (https://entropy6.com/xmeters/) shows system stats in the taskbar to the left of the tray.
I just installed TaskbarX and the taskbar is lopsided to the right and sometimes spills over the XMeters display (cpu and memory pie charts), unless I apply an offset, and I'm currently using -60px.
This is a request for TaskbarX to automatically compensate for horizontal space taken up by XMeters, if that's possible.

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
