### ISSUE TITLE
TaskbarX stopped centering icons

### ISSUE THREAD

**Issue by japkov** [ChrisAnd1998/TaskbarX#396]
Hello again

This is again puzzling

I was trying to figure out what some randomly appearing Windows process does - useroobebroker.exe, while updating the system at the same time; once updates were applied I did rebooted my machine. And when system was up, TaskbarX puked message that's its incompatible with my Windows version and at that point while it runs itself (can see both main and configurator processes), it doesn't center icons. That happen with 1.5.7.0 but then I quickly look up on github and tried the newest 1.6.1.0. - sadly, it behaves in same way.

The OS is Windows 10 x64 PLK build 2004 (19041.508)

I did launched the console option and here's what it shows:

![image](https://user-images.githubusercontent.com/69731550/92981431-0be63a80-f49a-11ea-9e1a-a0c3d2331b85.png)

Which as you probably figured translates into: _Error: no method from 'instance object (...) from 'System.Int32' class'._

The "funny" thing is that FalconX again runs without issues...

Could this issue be related to September Windows patches?

**Comment by ChrisAnd1998** [comment]
@japkov The error happens when MSAA can't get any information from the Taskbar i believe... 

Maybe a good old restart will fix it? Otherwise i will try to reproduce the error by really messing with the Taskbar.

**Comment by japkov** [comment]
I think I've tried everything - cold boot, clean boot, disabling fast startup and reenabling it again but nothing affected TaskbarX and it still doesn't center icons

**Comment by ChrisAnd1998** [comment]
Allright i'll try to find a fix.

The difference:
FalconX uses UIAutomation
TaskbarX uses MSAA

**Comment by Taka745** [comment]
I don't know if can help, but in 1.6.2.0 is happening the same thing to me.

**Comment by ChrisAnd1998** [comment]
Can you try using the 64bit version of TaskbarX?

**Comment by Taka745** [comment]
With the last update everything work fine. Thanks.
I forgot to update the GitHub comment.

Valentini Fabio

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
