### ISSUE TITLE
Feature Request: Support 3rd party Start Menus

### ISSUE THREAD

**Issue by PersonalProxy** [ChrisAnd1998/TaskbarX#397]
Hello, I just found the software and love it. It's beautiful, simple and functional.

I did notice that the Start button defaults to the Windows default even though I have [StartIsBack ](http://www.startisback.com)installed.
Not a huge deal as StartIsBack functions when I press the Windows key on my keyboard, but it would still be neat if it worked when clicking with the mouse as well.

I have not tested it with other options such as [OpenShell ](https://open-shell.github.io/Open-Shell-Menu/)or [Start10 ](https://www.stardock.com/products/start10/)but I assume it would be the same.
Thanks for your consideration!

**Comment by ChrisAnd1998** [comment]
@PersonalProxy Hmm, i have to test this again... I thought it worked just fine with 3rd party start menus. Last month i tested Open-Shell which worked fine.

**Comment by AlePini** [comment]
I have the same issues and it's still not fixed
The only way I can make both works is to open StartIsBack after TaskbarX

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
