### ISSUE TITLE
TaskbarX has constant disk usage of 2-3 MB/s

### ISSUE THREAD

**Issue by NoxAurea** [ChrisAnd1998/TaskbarX#398]
I'm not sure if this is actually a bug or expected behavior but this does not happen on my other laptop running TaskbarX. Here's what's going on.

TaskbarX is running and functioning as expected except for its disk usage.

TaskbarX.exe and its associated COM Surrogate (dllhost.exe) are constantly reading from MSO.DLL at ~2-3 MB/s (see Task Manager and Resource Monitor screenshots). As far as I can tell, MSO.DLL is only used by Microsoft Office. I can't imagine why TaskbarX would need to access an Office DLL at all, let alone at 2-3 MB/s constantly. It's mostly the COM Surrogate accessing the DLL but TaskbarX.exe is doing it as well to a lesser extent. In addition, on my other laptop the TaskbarX process does not have an associated COM Surrogate as far as I can tell.

This disk usage occurs regardless of if any Microsoft Office apps are running (or any apps at all).
I am running TaskbarX version 1.6.1.0 from the Microsoft Store. I tried the free portable version of TaskbarX as well and it exhibits the same behavior. The portable version was actually slightly worse and was reading from disk at about 5 MB/s.

I'm running Windows 10 version 2004 on a Dell XPS 15 9500. I do have a second monitor attached. Curiously, the disk usage drops by about half if I disconnect the external monitor. The laptop's internal screen is a 4K screen, if that matters.

Here's the paths to the files being accessed by TaskbarX and the COM Surrogate, respectively:

C:\Program Files\Microsoft Office\root\vfs\ProgramFilesCommonX86\Microsoft Shared\Office16\MSO.DLL
C:\Program Files\Microsoft Office\root\vfs\ProgramFilesCommonX64\Microsoft Shared\OFFICE16\MSO.DLL

System Info:
TaskbarX version 1.6.1.0 - Microsoft Store version
Dell XPS 15 9500 - Intel Core i7-10750H - 32 GB RAM - Display 3840x2400 60 Hz
External Monitor - Samsung CRG9 5120x1440 60 Hz
Disk - WD SN730 NVMe SSD
Windows 10 Pro Version 2004 Build 19041.508
.NET Framework Versions: 4.0.0.0 and 4.8.04084
No 3rd party antivirus, just built in Windows Security

TaskbarX Settings:
Style: Acrylic - RGBA (0,0,0,.25) - checkbox NOT checked
Animation: cubiceaseinout - 300 ms
Position: 0px for all boxes, checkboxes are NOT checked
Taskschedule: Delay 6 sec
Extra: Pause looper when fullscreen app is running - Refresh rates 1000ms

Taskbar Settings:
![image](https://user-images.githubusercontent.com/41928895/93005496-20b4e380-f517-11ea-9eac-f363465e45c2.png)
![image](https://user-images.githubusercontent.com/41928895/93005534-80ab8a00-f517-11ea-8ed7-f10a0c165bee.png)

Other programs that might (but shouldn't) impact the taskbar:
Wallpaper Engine
PowerToys version 0.21.1

Other Info:
I tried using the debugger following your instructions in your pinned post. I did not see anything in the output section referenced (it was blank). I did have the main function selected like you did in your screenshot.
The other laptop that doesn't show this behavior is a Surface Book 2 15 running Windows 10 Pro version 1909 build 18363.1082 and TaskbarX version 1.6.1.0 from the Microsoft Store with identical settings.

I've included a screenshot of Task Manager and Resource Monitor below.
![image](https://user-images.githubusercontent.com/41928895/93005071-0416ac80-f513-11ea-81ff-ca4d2cbe9dc4.png)
![image](https://user-images.githubusercontent.com/41928895/93005114-78e9e680-f513-11ea-82f4-7638c22b1f5f.png)

**Comment by Dansel** [comment]
I'm using the standalone version, release 1.6.0.0

I can't see the same behavior on my system. In fact, checking through Process Explorer, it has neither any child nor parent processes. With that said I did notice a steady 13.5 kb/s I/O activity and a surprising amount of CPU activity; a lot of context switching was going on. Checking through Process Monitor there is a lot of activity in the registry.

Over 15 000 events in less than 5 seconds.
[Logfile.zip](https://github.com/ChrisAnd1998/TaskbarX/files/5290770/Logfile.zip)
Attaching the Logfile. Notice the timestamps, and how the same ~150 events are repeating every few milliseconds.
(My refreshtime for TaskbarX is set to 500ms)
Is there some loop that isn't sleeping properly?

**Comment by ChrisAnd1998** [comment]
@NoxAurea Sorry for the late response and thanks for the details!! I will dive into this.

**Comment by Dansel** [comment]
@ChrisAnd1998 Do you want me to split the issue I pointed out into another ticket?

**Comment by ChrisAnd1998** [comment]
@Dansel That's not needed. Everything is sleeping fine though i think that it's a .NET thing as TaskbarX doesn't need the registry. I will inspect it too but, will take some time.

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
