### ISSUE TITLE
Taskschedule doesn't work for multiple users. 

### ISSUE THREAD

**Issue by SquirrelKiev** [ChrisAnd1998/TaskbarX#399]
If 2 or more users create a task schedule, it will overwrite the old one. After looking in task scheduler, my guess is it doesn't give a unique name. Could make it use the username as well?

**Comment by victorumn** [comment]
I have the same problem. Is it caused by the task scheduler? If so, will renaming it solve the problem?

**Comment by ChrisAnd1998** [comment]
@victorumn That could solve it. What i can do is let TaskbarX name the Taskschedule "TaskbarX-User" for example "TaskbarX-Chris". But i have to test that it won't run Taskschedule's that are created by different users.

**Comment by ChrisAnd1998** [comment]
Should be fixed in the pre-release 1.6.4.0. You will lose your current settings..
