### ISSUE TITLE
Symantec Endpoint Protection v. 14 (1168) recognizes TaskbarX as a threat

### ISSUE THREAD

**Issue by robtus** [ChrisAnd1998/TaskbarX#400]
Hi,

I've seen this before but topics were closed. I have downloaded and installed the latest version of TaskbarX which I really like a lot but Symantec is blocking this application, identifying it as a threat. Is there any chance to keep it working? Any advice would be much appreciated. 

All the best, Robert

**Comment by robtus** [comment]
![Screenshot 2020-09-20 112720](https://user-images.githubusercontent.com/71381061/93708178-72232b00-fb34-11ea-8142-b982eb9fc861.jpg)

**Comment by ChrisAnd1998** [comment]
@robtus For now you can just add TaskbarX to it's exclusions. I will contact Symantec about the false positive ;). Sorry for the late response.

**Comment by ChrisAnd1998** [comment]
Allright i just made a submission.. I hope they remove the false positive soon!

**Comment by robtus** [comment]
Hi Chris, many thanks for prompt reaction. I will verify in a few days as I'm not able to add any exclusions to Symantec - blocked by IT admin.

**Comment by ChrisAnd1998** [comment]
@robtus Allright, I just got a confirmation that the submission is closed. I should be fixed now but, can take upto 24 hours before you will see it fixed.

**Comment by robtus** [comment]
Hi Chris,

I have installed again yesterday and all was working really well until now - just before a moment this message arrived again...
![Screenshot 2020-09-21 113637](https://user-images.githubusercontent.com/71381061/93752285-bbd84800-fbfe-11ea-8aee-a5b2f65bb28b.jpg)
