### ISSUE TITLE
Request: Add TaskbarX to winget source.

### ISSUE THREAD

**Issue by AKharytonchyk** [ChrisAnd1998/TaskbarX#403]
Is it possible to add TaskbarX to Winget source to be able to easily manage installation and update process?

https://docs.microsoft.com/en-us/windows/package-manager/package/

**Comment by shayvt** [comment]
Can you package it as msix and add it to winget?

**Comment by RokeJulianLockhart** [comment]
> https://github.com/ChrisAnd1998/TaskbarX/issues/403#event-5814709768

@ChrisAnd1998, https://github.com/search?q=repo%3Amicrosoft%2Fwinget-pkgs+taskbarx&type=code doesn't return any manifests, nor does https://github.com/search?q=repo%3Amicrosoft%2Fwinget-pkgs+taskbarx&type=issues return a package request, so is this actually https://github.com/ChrisAnd1998/TaskbarX/issues?q=is%3Aissue+reason%3Acompleted? If not, reopen this or close it as unplanned, and I'll submit the request myself (https://github.com/microsoft/winget-pkgs/discussions/4086#discussioncomment-94626 doesn't apply anymore).

**Comment by RokeJulianLockhart** [comment]
> https://github.com/ChrisAnd1998/TaskbarX/issues/403#issuecomment-879041604

@shayvt, that's probably best filed as a separate issue, though I support it. If you file it, tag me and link it here for me, would you?
