### ISSUE TITLE
Right clicking on task bar doesn't work

### ISSUE THREAD

**Issue by CinnamonRage** [ChrisAnd1998/TaskbarX#405]
We I have the icons centred on the bottom, when I right click to get applications options like "New Window" on Chrome, no menu appears.

**Comment by ChrisAnd1998** [comment]
Not sure if this is caused by TaskbarX..

**Comment by CinnamonRage** [comment]
Looks like you are right. I think the timing was just coincidental. 

https://answers.microsoft.com/en-us/windows/forum/windows_10-start-win_taskbar/unable-to-right-click-task-bar-items-in-windows-10/8d392815-af3e-44c0-a0e6-341e84532baa

Sorry and thanks!
