### ISSUE TITLE
Every couple times I restart my computer, the taskbar resets, and the configurator no longer works.

### ISSUE THREAD

**Issue by MeatToboggan47** [ChrisAnd1998/TaskbarX#408]
The only way I can get it to work again is to go into the files, and run the configurator as Admin. It's slightly inconvenient since I don't want to have to go do that almost every time I start my computer.

**Comment by Rikopara** [comment]
I can confirm this issue. Every time I close-up and open TaskbarX it's resets all my configuration settings such a transparency.

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
