### ISSUE TITLE
My Taskbar Icons disaapered after installing TaskbarX

### ISSUE THREAD

**Issue by Harish795** [ChrisAnd1998/TaskbarX#409]
After when i download the taskbarx app when i opened the exe file.An animation was excecuted and my taskbar icons were going to center and they stopped and they just diaapeared

**Comment by ChrisAnd1998** [comment]
Can you try this? https://github.com/ChrisAnd1998/TaskbarX/releases/tag/1.6.8.0

**Comment by Harish795** [comment]
Yea @ChrisAnd1998 Now It Works Without Any Problem Thanks Buddy

**Comment by ChrisAnd1998** [comment]
Great! 😁👍
