### ISSUE TITLE
TaskbarX needs manual restart, about every 10 minutes to work

### ISSUE THREAD

**Issue by elementalmasterpotap** [ChrisAnd1998/TaskbarX#410]
TaskbarX needs manual restart, about every 10 minutes to work.

windows 10  2004

**Comment by GenericBleach** [comment]
same

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
