### ISSUE TITLE
Transparency not working in TaskView

### ISSUE THREAD

**Issue by chongyunxiang** [ChrisAnd1998/TaskbarX#411]
![Screenshot 2020-09-29 235352](https://user-images.githubusercontent.com/57867863/94582707-22b8c980-02af-11eb-8dee-3f578d4b2e96.jpg)

I set transparency but it's not transparent when it's in TaskView.

**Comment by ChrisAnd1998** [comment]
Actually it is working but Taskview makes your desktop go darker making it look like it doesn't work.
