### ISSUE TITLE
Blur issue and Acrylic Blur Intensity slider request

### ISSUE THREAD

**Issue by Kovadon** [ChrisAnd1998/TaskbarX#412]
Not sure why this is happening,:
![Screenshot 2020-09-29 145832](https://user-images.githubusercontent.com/15993426/94604081-27f12680-0265-11eb-9202-582e91692f4d.png)

Gonna have to use the Acrylic setting in the meantime until this is fixed, any chance we can get a slider to adjust the intensity of the blur?

**Comment by ChrisAnd1998** [comment]
@Kovadon Sadly i cant fix this as the blur effect is handled by user32.dll
