### ISSUE TITLE
I was looking for a way to make the start button go in the center and.....

### ISSUE THREAD

**Issue by cmputerboom** [ChrisAnd1998/TaskbarX#416]
I was looking for a way to make the start button go in the center and i found a screenshot of falconx  saying that it gave that option!

I had tried falconx and taskbarX in the past so I thought.. what? I must have missed something. So i just reinstalled taskbarX and I could not find that option. What gives? thankS!

here is the page with the screenshot https://www.ghacks.net/2018/06/20/center-windows-10-taskbar-icons-and-start-button-with-falcon/

**Comment by pc-v2** [comment]
@ChrisAnd1998 already tried this, the Start Menu is locked at left, maybe the workaround is to use custom start menu  #25

**Comment by ChrisAnd1998** [comment]
@cmputerboom It's possible but then the icons cant be in the center as the start button will overlay the icons. Secondly the start menu is locked and the way to give it another location is unknown like @pc-v2 just high lighted. Third issue i have is that i want to keep TaskbarX as light as possible and want to avoid creating custom docks or start menus (i want to use whats already there to make it look like it's supposed to be like that).

**Comment by bi11tacu1ar** [comment]
It is indeed possible. I know this thread is kinda old but I was searching for a solution and ran across this. Stardock's Start11 includes this feature. Just throwing that out there.
