### ISSUE TITLE
TaskbarX keeps restarting

### ISSUE THREAD

**Issue by MazinLabib10** [ChrisAnd1998/TaskbarX#417]
TaskbarX was working fine for me until yesterday. I had restarted my laptop and I noticed that the taskbar (automatically hidden in desktop mode) kept flickering and the icons would not center. I use one other software for the taskbar that is TranslucentTB but even with that turned off the issue was there. I enabled the tray icon and that's how I realized TaskbarX was restarting constantly as there were duplicate icons appearing for each flicker. When I enabled 'Only center primary taskbar', cmd windows started popping up for each flicker but they would close so fast that I could not read anything. Please look into this quickly as I am real fan of this software and I don't want to have to stop using it like this.

**EDIT:** I've found out that version 1.5.4.0 works on my laptop but none of the newer versions after that do. It's fine for now but of course I would rather be able to use the latest version.

**UPDATE (11 Dec 2020)**: This issue has stopped occurring in the latest version (1.6.3.0).

**Comment by qthang** [comment]
i have same problem

**Comment by shayvt** [comment]
Same issue here.
@ChrisAnd1998 do you have a log of TaskbarX that I can look into it?

**Comment by shayvt** [comment]
I found this error in the console, I think it's causing the crashes of TaskbarX:

![image](https://user-images.githubusercontent.com/6310671/97421411-26bf2200-1915-11eb-82cd-52383ea2e1e0.png)

**Comment by Liquidream** [comment]
I am having this exact issue (see it in the command window when I manually restart it due to crash loop).
Can't recall when it started, but has been an on/off problem for me for quite a while.
Even seems to happen soon after a Windows reboot. 🤷‍♂️

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
