### ISSUE TITLE
[wish] inivisble start button but open menü by click at area

### ISSUE THREAD

**Issue by leminsc8er** [ChrisAnd1998/TaskbarX#421]
Invisible start button don't show the button but at area you can click an open the menü via mous.

**Comment by Cyberdroid1** [comment]
I think this feature is there in 1.6.2.0

**Comment by Lumoo** [comment]
there is but only for hiding it.

**Comment by leminsc8er** [comment]
> 
> 
> I think this feature is there in 1.6.2.0
https://github.com/ChrisAnd1998/TaskbarX/issues/421#issuecomment-711414628
you cant open start by click on hidden area

**Comment by leminsc8er** [comment]
> 
> 
> I think this feature is there in 1.6.2.0



> 
> 
> there is but only for hiding it.

it does not run v1.6.8.0

**Comment by leminsc8er** [comment]
would be happy about an update soon <3
