### ISSUE TITLE
Windows Ink on second monitor should not be displayed

### ISSUE THREAD

**Issue by Manu99it** [ChrisAnd1998/TaskbarX#422]
Windows Ink in second monitor is displayed while it should not?
![image](https://user-images.githubusercontent.com/19348772/95113503-d6540a80-0742-11eb-912a-e6bbd723884c.png)

Actually #414 is related, would be awesome if we could choose what keep and what not

**Comment by Manu99it** [comment]
Windows Ink in second monitor is displayed while it should not?
![image](https://user-images.githubusercontent.com/19348772/95113385-ac024d00-0742-11eb-94a0-4329c3ae8513.png)

Actually #414 is related, would be awesome if we could choose what keep and what not

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
