### ISSUE TITLE
Taskbar icons move to the right when moving icons on tray

### ISSUE THREAD

**Issue by laonglaan100** [ChrisAnd1998/TaskbarX#423]
All the icons on the taskbar jump to the right and slide back to the place whenever I remove or move something from the tray.

[Short clip sample](https://i.imgur.com/GODI6LU.mp4)

**Comment by ChrisAnd1998** [comment]
@laonglaan100 It's happening due to the links next to your startbutton.

**Comment by laonglaan100** [comment]
I see. Is there anything I can do to fix it other than moving the links, or am I SOL?

**Comment by ChrisAnd1998** [comment]
Not for now. I have to come with something to make it possible to have links and other stuff on the left side without TaskbarX bugging out.

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
