### ISSUE TITLE
Line on bottom of top taskbar when transparent mode is set

### ISSUE THREAD

**Issue by VlaDosWOW** [ChrisAnd1998/TaskbarX#424]
### Appears when transparent mode is set and maximised window is open.

![TaskbarTransparentIssue](https://user-images.githubusercontent.com/49435083/95332129-aaa46200-08b3-11eb-86b2-0f0deab06789.png)

![image](https://user-images.githubusercontent.com/49435083/95333173-19ce8600-08b5-11eb-9f05-2306d023b38e.png)

**Comment by ChrisAnd1998** [comment]
@VlaDosWOW Yes, this a thing caused by chromium. I can't do anything about that.
