### ISSUE TITLE
TaskbarX has disabled system wide acrylic theme

### ISSUE THREAD

**Issue by trailbla7er** [ChrisAnd1998/TaskbarX#425]
This is the second time this has happened to me, I log in to my pc on a random day and taskbarx is no longer using the acrylic blur theme and it is also not working anywhere else on my pc, I then uninstall taskbarx from the microsoft store and reinstall and it works again, then repeat the process.

**Comment by Dansel** [comment]
I never had all that much luck with the acrylic (or fluent) style when set via TaskbarX, instead I use the inbuilt registry setting.

Create a DWORD32 "TaskbarAcrylicOpacity" with dec value 0 to 255 (0 fully transparent) at:
HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced

Then restart explorer for settings to take effect. Also, I don't remember which version of windows introduced this but I'm using v2004 and it's working here.

Actually @ChrisAnd1998 could TbX be updated to use this method instead? It removes the flickering I used to get.

**Comment by ChrisAnd1998** [comment]
@Dansel Yes, i know this existed for a couple months. I have been trying to send a message to the explorer to refresh the taskbar after the registry has been changed however this doesn't work for the "TaskbarAcrylicOpacity". So it requires the explorer/shell to be restarted every time you make a change. You also cant give it a accent color.

**Comment by yashpalgoyal1304** [comment]
hi, what is acrylic style? i tried this and i coulnd notice any difference - it looks exactly same as transparent to me.
