### ISSUE TITLE
Flickering when the taskbar style is set to acrylic.

### ISSUE THREAD

**Issue by icovelev** [ChrisAnd1998/TaskbarX#429]
It's so strange. If my taskbar is set to acrylic every time I open start menu or switch window my taskbar flickers. No problem on all other modes. Right now I'm on blur with 10% alpha  and it's pretty close to acrylic in looks, but i like the original acrylic style more. If I can be helpful with something I can send screenrecording of the bug.

**Comment by ChrisAnd1998** [comment]
Yep, this can't be fixed as this is kind of a feature when using the acrylic style.
