### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by tu-jw** [ChrisAnd1998/TaskbarX#431]
Hello and sorry in advance.

I'm new to this, how do I actually install this thing? I cloned the repo from github but I don't actually see any sort of executable. I want to make sure I do this correctly before actually installing it.

**Comment by ChrisAnd1998** [comment]
@tu-jw Hi, you can download the executables from here https://github.com/ChrisAnd1998/TaskbarX/releases/tag/1.6.2.0
or here https://chrisandriessen.nl/taskbarx

After that create a folder where you like and extract the files there. Then run the configurator exe and hit the apply button ;)
