### ISSUE TITLE
It is not working in window 10 now. Recently pop up message showing warning not to install this package it will harm the pc and there is only option to choose and that is Don't Run. What's the problem? 

### ISSUE THREAD

**Issue by Skipper1117** [ChrisAnd1998/TaskbarX#432]

**Comment by ChrisAnd1998** [comment]
@Skipper1117 Maybe "more details" and then "run anyway"?

**Comment by Skipper1117** [comment]
> @Skipper1117 Maybe "more details" and then "run anyway"?

Will it be okay to run the program?

**Comment by ChrisAnd1998** [comment]
@Skipper1117 Yes, that's just a UAC prompt. It pops up because i don't sign the executables. So Windows doesn't know if it should trust the application because the signature is unknown. A signature is way to expensive for me to even consider.

**Comment by Skipper1117** [comment]
> @Skipper1117 Yes, that's just a UAC prompt. It pops up because i don't sign the executables. So Windows doesn't know if it should trust the application because the signature is unknown. A signature is way to expensive for me to even consider.
> 
> It's a thing you have to do for a single time only.

Thanks for your time and big 👍 to your work.
