### ISSUE TITLE
Error message on windows start up

### ISSUE THREAD

**Issue by burt-ie** [ChrisAnd1998/TaskbarX#433]
I had the Windows store version installed which was a little buggy on dual monitors, so I unistalled it and switched to the rainmeter version, however I keep getting this message every time my PC now boots up

![image](https://user-images.githubusercontent.com/43120617/96145891-9852a580-0efd-11eb-8941-482d8c56cd8c.png)

**Comment by ChrisAnd1998** [comment]
@burt-ie You didn't properly uninstall TaskbarX but that no problem.
The fix is here: https://github.com/ChrisAnd1998/TaskbarX#errors
