### ISSUE TITLE
Need "Start with Windows" feature

### ISSUE THREAD

**Issue by evilprince2009** [ChrisAnd1998/TaskbarX#436]
I have launch TaskbarX manually after every turn on / system restart. This is tedious. Adding a "Start with Windows" functionality would be great.

**Comment by ChrisAnd1998** [comment]
@evilprince2009 It's already there... Have you clicked apply inside the Configurator? A Taskschedule should be created.

**Comment by takahatashun** [comment]
This feature is already exists
![image](https://user-images.githubusercontent.com/34259386/96731287-47e9b500-13e1-11eb-9a60-260f44b2e17a.png)

**Comment by voiceofvraja** [comment]
> @evilprince2009 It's already there... Have you clicked apply inside the Configurator? A Taskschedule should be created.

It does not work, I have tried a lot but have to re start on my own always

**Comment by voiceofvraja** [comment]
> @evilprince2009 It's already there... Have you clicked apply inside the Configurator? A Taskschedule should be created.

@ChrisAnd1998 It does not work, I have tried a lot but have to re start on my own always

**Comment by Axection** [comment]
me too. especially when you tried to restart the PC, it seems TaskbarX class wasn't available (declared) yet at startup, thus class not registered error (and I have to launch TaskbarX manually)

**Comment by ChrisAnd1998** [comment]
If it shows that class not registered error then you need to increase the delay of the taskschedule to like 10 sec or so.

**Comment by Axection** [comment]
I've tried increasing it to 30 sec and it still show same error. 
Specifically, when I do restart PC. "shutdown and turn on" did not face the problem, somehow.

**Comment by evilprince2009** [comment]
Somehow I solved it my own.

**Comment by Axection** [comment]
may you share your findings of solution @evilprince2009 ?

**Comment by evilprince2009** [comment]
> may you share your findings of solution @evilprince2009 ?

 Create shortcuts for `TaskbarX.exe` & `TaskbarX Configurator.exe`. Now Press Windows + R key , type `shell:startup` , hit enter & paste those shortcuts inside that directory.
