### ISSUE TITLE
taskbarx not working after sleep

### ISSUE THREAD

**Issue by proload99** [ChrisAnd1998/TaskbarX#438]
Recently after i put the pc to sleep and wake it up the taskbarx wont load up and it goes back to default. Or sometimes it will turn of transparancy like i had set and the icons will still be in the middle. I have to restart it to make it work

**Comment by MBlais13** [comment]
I have the same issue here as well. When I start TaskbarX (or after restart or sleep) even if the config had transparent taskbar enabled it won't show, I have to manually open the configurator and then click restart.

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
