### ISSUE TITLE
Position taskbar icons underneath windows they belong to

### ISSUE THREAD

**Issue by sid-6581** [ChrisAnd1998/TaskbarX#439]
I have an ultrawide monitor split into multiple horizontal zones, and I would love to have the taskbar icons positioned in the  same zone as the windows. So all the windows on the left side of the screen would have their icons on the left side of the taskbar, all the windows in the middle would have their icons in the middle, etc. Is it possible to have such fine grained control of taskbar icons?

**Comment by ChrisAnd1998** [comment]
@sid-6581 Sadly this is impossible as the icons can't be moved separately. There are stuck to the list box they are displayed in.
