### ISSUE TITLE
Transition is not smooth on wallpaper change with blur style

### ISSUE THREAD

**Issue by D3SOX** [ChrisAnd1998/TaskbarX#440]
Regular version (downloaded from GitHub)
What's your Build of Windows 10? 1903 (OS Build 18362.1082)
.NET Framework 4.8 installed? Yes
Any Antivirus software? No
Any other third-party taskbar tweakers? No
Is there a way I can reproduce? Set Style to Blur, set a slideshow as wallpaper, right click the desktop and click on "Next desktop background"
What are your taskbar settings? 
![taskbar_settings](https://user-images.githubusercontent.com/24937357/96932271-e861d700-14be-11eb-8d30-723a627d9c8f.png)

![taskbar](https://user-images.githubusercontent.com/24937357/96931561-ca47a700-14bd-11eb-8df8-a2d1f9896d60.gif)
Blur :arrow_up:

![taksbar_acrylic](https://user-images.githubusercontent.com/24937357/96931970-72f60680-14be-11eb-8371-48e3193dfe3c.gif)
However, with acrylic it looks good :arrow_up:

**Comment by ChrisAnd1998** [comment]
@D3SOX Sadly this can't be fixed as this some behavoir caused by SetWindowCompositionAttribute inside "user32.dll".
