### ISSUE TITLE
.msi or .exe instead of a zip

### ISSUE THREAD

**Issue by Rayne231** [ChrisAnd1998/TaskbarX#441]
Not a issue but a suggestion.

It is quite confusing for new users to figure out how to use your TaskbarX, so if you could please make a installer (.exe or .msi) file it would be easier to install and use. 😊

**Comment by RexGalilae** [comment]
I agree with you but as I understand it, the convenience is offered in exchange for a small donation. You can install this app directly from the Windows Store for $1.09 which will also take care of automatic updates.

**Comment by Rayne231** [comment]
I understand. Thank you. 👍
