### ISSUE TITLE
TaskbarX is breaking explorer.exe

### ISSUE THREAD

**Issue by helloplayer1** [ChrisAnd1998/TaskbarX#442]
So after updating to the newest version of the Software(1.6.2.0), my Computer started to have some problems with TaskbarX. When I start my PC and log into my user, explorer.exe falls into a crash loop and with every restart (about half a second) the screen flashes black. I have already tried removing the software (and Taskschedule) but that did not resolve my problem. I also tried to reset windows to an earlier version of windows with the windows restore point option (as I made a Windows Update before) but the issue still persists. 

In the beginning of the problem, there also showed up some errors from TaskbarX saying that the Taskbar could not be found and my operating system may be incompatible, but these do not show up anymore when starting the PC. Occasionally the Windows Explorer would show some Errors like: "The startup process was determined ...".

Useful Information:

Windows 10 Pro Version 2004, 
TaskbarX 1.6.2.0
No Taskschedule

**Comment by ChrisAnd1998** [comment]
Hi Julian, As you explained removing TaskbarX including the taskschedule didn't fix the issue then i'm not sure if this is related to TaskbarX. TaskbarX is portable, doesn't change your registry or your settings. It basically does everything when the application runs in realtime. If you managed to stop and remove TaskbarX and the issue still persists then something else is causing the issue for sure. I also have no reports of the explorer giving the error "The startup process was determined ...".

**Comment by helloplayer1** [comment]
Hi, thank you for your response. 

As for the explorer.exe error, this was just a rough translation of what the error said in german, I am not entirely sure what it said. It is totally possible, that the error has nothing to do with TaskbarX, but because of the initial error that TaskbarX gave me and the fact that the problem started again after I thought I had fixed it with the restore point and tried to remove the software again, made me assume that the issue is related to TaskbarX.

**Comment by ChrisAnd1998** [comment]
Do you know what it said in german exactly? Maybe i can find something.. I have tried searching your translation but, couldn't find any useful results.

**Comment by helloplayer1** [comment]
I will reply if I see it again, I will try to recreate it tomorrow.

**Comment by PaixD** [comment]
I'm experiencing the same issue, after the latest windows update, TaskbarX provides an error message saying "your OS maybe incompatible" while explorer.exe falls into a crash loop and with every restart (about half a second), however, the task bar is flashing while the screen is black, this resolves itself after a minute or two, with TaskbarX not active. However, if TaskbarX is turned on again, it works fine as intended, but every reboot the issue persists however, once taskbarX is uninstalled, this problem no longer occurs.

**Comment by ChrisAnd1998** [comment]
Are you both on the insider preview? I know there where some updates to the taskbar in 20H2 (October). I am updating to the latest insider preview to see if i can reproduce it.

**Comment by PaixD** [comment]
This is the recently installed update that seems to break TaskbarX
[windows-10-update-kb4579311](https://support.microsoft.com/en-us/help/4579311/windows-10-update-kb4579311)

**Comment by ChrisAnd1998** [comment]
Yep, i tested that one too. Currently running the latest insider preview. Can't reproduce the issue :/

**Comment by helloplayer1** [comment]
So I found out that for every explorer.exe crash I get an error in the Windows Event Viewer, this might help:
![Windows Event Viewer](https://user-images.githubusercontent.com/32032467/97081447-cffad500-1602-11eb-8428-8c6dee13662d.png)

**Comment by helloplayer1** [comment]
I gave it another try and sadly, I cannot solve the issue by properly uninstalling TaskbarX (Using the Configurator and then deleting all Files).

**Comment by PaixD** [comment]
![image](https://user-images.githubusercontent.com/24989002/97088908-ba0a0600-163c-11eb-9479-b84a548a9b85.png)

On my end, this is the error that is generated by TaskbarX after Windows somehow stops the explorer.exe crash loop

**Comment by gang-chun** [comment]
I too had the above error appear before a crash loop occurred. It takes a couple of minutes then everything loads up normally. TaskbarX doesn't run until I go start it. I'm running dnSpy now to see if I get any outputs.

**Comment by helloplayer1** [comment]
So usually when I startup and it goes into the crash loop, I open up Task manager and try to open up and close explorer.exe a few times (because I feel like that stops the crash faster), but occasionally I get these two error messages![20201025_000548.jpg](https://user-images.githubusercontent.com/32032467/97094609-7b814500-1656-11eb-9d1b-a708b7070e87.jpg)![20201025_000603.jpg](https://user-images.githubusercontent.com/32032467/97094610-81772600-1656-11eb-93bd-9f29de2fd147.jpg)

**Comment by ChrisAnd1998** [comment]
@helloplayer1
Take a look at this:
https://superuser.com/questions/720519/error-shell52205fd8-5dfb-447d-801a-d0b52f2e83e1-this-file-has-no-program

**Comment by helloplayer1** [comment]
@ChrisAnd1998 thank you, but I do not think that this is the same as my issue - my error is saying "The remote procedure call failed and was not executed." when translated to English. However, I gave the File Explorer Options solution a try and reset all to the default values, I will let you know if it helped.

**Comment by helloplayer1** [comment]
So it is a few days later and i still have the issue, even after resetting my File Explorer options. 😒

**Comment by ChrisAnd1998** [comment]
@helloplayer1 I'm still on it.. Have been debugging for days but, have not been able to reproduce the issue yet 😩.

**Comment by PaixD** [comment]
Got tired of explorer.exe crashing so I just rolled back the update, it's working fine now.

**Comment by helloplayer1** [comment]
> Got tired of explorer.exe crashing so I just rolled back the update, it's working fine now.

Do you mean the windows or the TaskbarX update?

**Comment by PaixD** [comment]
> > Got tired of explorer.exe crashing so I just rolled back the update, it's working fine now.
> 
> Do you mean the windows or the TaskbarX update?

The windows update

**Comment by ChrisAnd1998** [comment]
Can someone try this?
[Test.zip](https://github.com/ChrisAnd1998/TaskbarX/files/5470695/Test.zip)

**Comment by PaixD** [comment]
> Can someone try this?
> [Test.zip](https://github.com/ChrisAnd1998/TaskbarX/files/5470695/Test.zip)

Will do, on the new windows update right?

**Comment by ChrisAnd1998** [comment]
@PaixD Yes, but there is a chance it still doesn't work though.

**Comment by helloplayer1** [comment]
> @PaixD Yes, but there is a chance it still doesn't work though. So it could be possible you need to do a rollback again or wait for the others to test it first.

Still no luck for me :( 

Only thing it did is bringing back the errors:
![20201101_162427](https://user-images.githubusercontent.com/32032467/97811417-d92b1800-1c7a-11eb-8a78-71939c139187.jpg)
![20201101_162430](https://user-images.githubusercontent.com/32032467/97811418-d9c3ae80-1c7a-11eb-84f6-4132c2e69be9.jpg)
![20201101_162533](https://user-images.githubusercontent.com/32032467/97811420-da5c4500-1c7a-11eb-964d-5d30b95fd4c2.jpg)
![20201101_162539](https://user-images.githubusercontent.com/32032467/97811421-db8d7200-1c7a-11eb-92ea-e77afa3e90e3.jpg)

**Comment by ChrisAnd1998** [comment]
I would also like to know the version of Oleacc.dll in _C:\Windows\System32_
![oleacc](https://user-images.githubusercontent.com/50437199/97856608-cd803580-1cfc-11eb-9edf-ec7589e158b1.png)

**Comment by helloplayer1** [comment]
Here you go:

![image](https://user-images.githubusercontent.com/32032467/97866073-8188bd00-1d0b-11eb-9850-c63a6c8ed365.png)

**Comment by voltexes2** [comment]
I'm having the same issue as well, It started off as it crashlooping the explorer.exe and showing that my os may be incompatible, uninstalled it through windows safe mode but it's still occurring.

**Comment by ChrisAnd1998** [comment]
I have now added separated builds. 32bit and 64bit https://github.com/ChrisAnd1998/TaskbarX/releases/tag/1.6.3.0

**Comment by helloplayer1** [comment]
Any updates? Still getting the Issue, now also on my 2nd Device where uninstalling is also not a fix :/

**Comment by gang-chun** [comment]
Does anyone else by chance have Wallpaper Engine installed via Steam? I notice that breaks too when this issue occurs. Ending the wallpaper32.exe from it seems to break the explorer.exe crash loop, but TaskbarX still fails to load afterward.

**Comment by helloplayer1** [comment]
nope, however I did notice that it does not go into the crash loop sometimes, than the taskbar, the start menu and Windows Shortcuts just don't work until I manually restart explorer.exe via the Task Manager. This is also the case after breaking out of the crash loop in some cases.

**Comment by PaixD** [comment]
> Does anyone else by chance have Wallpaper Engine installed via Steam? I notice that breaks too when this issue occurs. Ending the wallpaper32.exe from it seems to break the explorer.exe crash loop, but TaskbarX still fails to load afterward.

Yeah, I have Wallpaper Engine installed from Steam. I suspected that maybe it was causing the crash loop but after disabling it from startup the crash loop still occurred, not sure if this is an issue directly related to Microsoft or TaskbarX.

**Comment by PaixD** [comment]
I have seemed to find a solution to the crash loop.
Strangely enough, I had Halo MCC installed from the Xbox app and uninstalling it has completely stopped the crash loop.

If you do have Halo MCC installed from the Xbox app try uninstalling it, I will re-install Taskbar X and check if it will bootup correctly.

**Comment by helloplayer1** [comment]
> I have seemed to find a solution to the crash loop.
> Strangely enough, I had Halo MCC installed from the Xbox app and uninstalling it has completely stopped the crash loop.
> 
> If you do have Halo MCC installed from the Xbox app try uninstalling it, I will re-install Taskbar X and check if it will bootup correctly.

So while the crash loop problem stopped on my Desktop a while ago (might be since I uninstalled Halo MCC), the issue still occurred on my laptop. So after you commented yesterday, I uninstalled it on my laptop too and strangely enough, this really fixed it!

I am really thankful for you finding the problem @PaixD, and maybe @ChrisAnd1998 now has a chance to do smth about it!

**Comment by PaixD** [comment]
> > I have seemed to find a solution to the crash loop.
> > Strangely enough, I had Halo MCC installed from the Xbox app and uninstalling it has completely stopped the crash loop.
> > If you do have Halo MCC installed from the Xbox app try uninstalling it, I will re-install Taskbar X and check if it will bootup correctly.
> 
> So while the crash loop problem stopped on my Desktop a while ago (might be since I uninstalled Halo MCC), the issue still occurred on my laptop. So after you commented yesterday, I uninstalled it on my laptop too and strangely enough, this really fixed it!
> 
> I am really thankful for you finding the problem @PaixD, and maybe @ChrisAnd1998 now has a chance to do smth about it!

I'm glad it worked out fine for you, I'm frankly quite surprised that one game could cause such a headache.

I think this issue has something to do with Windows itself, that's probably why @ChrisAnd1998 couldn't reproduce the issue.

**Comment by helloplayer1** [comment]
I have bad news: I just restarted my Laptop and for no reason at all, this issue was back again. Having no Halo MCC installed, this is a bit frustrating - I have no idea what to do now :(.

**Comment by herbertnicolas** [comment]
I having the same issue... I have some games installed from Xbox app but never installed Halo... Maybe this bug is related to Xbox app?

**Comment by PaixD** [comment]
> I have bad news: I just restarted my Laptop and for no reason at all, this issue was back again. Having no Halo MCC installed, this is a bit frustrating - I have no idea what to do now :(

> I'm having the same issue... I have some games installed from Xbox app but never installed Halo... Maybe this bug is related to Xbox app?

I think this issue is related to the Xbox Store Apps, I recently installed Train Sim World 2 and this issue was being produced again, so uninstalling the culprit apps completely stopped this issue, so I would suggest uninstalling the last app you installed prior to the issue occuring.

**Comment by Myriad-git** [comment]
For what it’s worth, upgrading to the Windows 11 Insider Preview seems to have solved the issue for me. Not sure if there’s a difference between how apps are handled.

**Comment by helloplayer1** [comment]
I do not think this issue is even related to TaskbarX. If you have it, uninstalling TaskbarX does not resolve it. Its just a Bug of the Xbox App for Windows and I think it occurs if your game pass subscription has run out but you still have some games installed, as it tries to update these games but than crashes. I for my part have solved it multiple times in the past by just uninstalling some game pass games.
