### ISSUE TITLE
Suggestion 

### ISSUE THREAD

**Issue by usama-rao** [ChrisAnd1998/TaskbarX#443]
I have been using taskbarx for 2 weeks now it's great. the transparent and acrylic effects are lovely but these effects don't apply to the start menu if they did that would be awesome.

**Comment by laonglaan100** [comment]
You'll need a separate program for that. Try Open-shell, also open-source.

**Comment by Eenna** [comment]
> 
> 
> I have been using taskbarx for 2 weeks now it's great. the transparent and acrylic effects are lovely but these effects don't apply to the start menu if they did that would be awesome.

I agree, it'd be awesome to apply those transparent and acrylic effects to the start menu without needing an extra program for it. I've been wishing for this feature as well.
