### ISSUE TITLE
incorrect display of icons when taskbar is full

### ISSUE THREAD

**Issue by MrrrLuiigii** [ChrisAnd1998/TaskbarX#444]
With taskbar center on some of the icons will not display at all if the taskbar is full and gets a scrollbar. TaskbarX attempts to center the items, but some of them get hidden behind the scrollbar.

**Comment by CallumCarmicheal** [comment]
I have this issue as I have many applications open frequently and have to switch between 1080p and 4k frequently. When I change the resolution to 1080, I have to temporarily go into TaskbarX and disable centering and then re-enable it after. 

Possible solution, disable TBX centering automatically when it detects if the taskbar is overflowing.

**Comment by etokarew** [comment]
Hello! Seems feature do not work on Windows 10 Pro 22H2 (`19045.4894`).
Version of TBX is latest, `1.7.8.0`.
