### ISSUE TITLE
dose not pause or stop wallpaper in background 

### ISSUE THREAD

**Issue by HellishHD** [ChrisAnd1998/TaskbarX#446]
love this app but it does not pause or stop wallpaper in background even when i playing games which means i'm using more ram im using wallpaper engine i also made a custom rule that when not focused to to pause/stop the app but it does not work

**Comment by ChrisAnd1998** [comment]
But TaskbarX hasn't anything to do with your wallpaper :/ You can enable "Pause TaskbarX in fullscreen mode" option inside the configurator... to pause the application while gaming.
