### ISSUE TITLE
Transparency effect gone when waking pc from sleep

### ISSUE THREAD

**Issue by proload99** [ChrisAnd1998/TaskbarX#447]
The transparency effect is applied however if i wake the pc from sleep it starts in default. i have to go into configurator and restart taskbarx to get it again

**Comment by hollowshiroyuki** [comment]
Same issue with Hibernation on Windows 10 20H2 and TaskbarX 1.7.1.0.

**Comment by EliasGagnef** [comment]
Same on Windows 11 21H2, hibernation also loses the transparency

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
