### ISSUE TITLE
[BUG] TaskbarX Changes the default position of the Icon, when launching a new application.

### ISSUE THREAD

**Issue by ghost** [ChrisAnd1998/TaskbarX#448]
When I open a new application, with the taskbar  empty (no Applications in Backround), the icon is moved to the right. Same thing happens with Big Taskbar Buttons.

![Annotation 2020-10-29 065132](https://user-images.githubusercontent.com/52204908/97536660-cc2dd080-19bd-11eb-8dc1-597cf6200de2.png)

 **Is this a know bug? Is there a fix for it? Thanks!**

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
