### ISSUE TITLE
Taskbar X not running on startup after latest windows update

### ISSUE THREAD

**Issue by chongyunxiang** [ChrisAnd1998/TaskbarX#451]
I've updated my windows 10 to the latest update and Taskbar X is not automatically running on startup. I even reset Taskbar X and set the Taskscheduler, but it still does not auto run on startup.

**Comment by Nicras** [comment]
The same for me...the task ends with error 0x80070005 which is "access denied". Seems to be the task scheduler running an instance of cmd.exe.

**Comment by ChrisAnd1998** [comment]
@chongyunxiang Have you tried increasing the delay of the Taskschedule inside the configurator?

**Comment by chongyunxiang** [comment]
I've just found the problem and that when it's installed from the Microsoft Store, the Task Scheduler does not locate the application, which is why it's not running.

**Comment by Ganidhu** [comment]
Same happening to me
