### ISSUE TITLE
Taskbar icons move to the right when Windows10 make a scroll bar for taskbar icons that can not place in just one line

### ISSUE THREAD

**Issue by Dealtz** [ChrisAnd1998/TaskbarX#452]
Taskbar icons move to the right when a scroll bar showed up.
I have tried FalconX_1.3.2.0 to FalconX_1.4.5.0 and TaskbarX_1.6.2.0, all of this versions has same problem.
![screenshot](https://user-images.githubusercontent.com/38786580/98099387-75972980-1eca-11eb-984d-fdaca1ebf091.png)
When it happened, I even can not switch to second line. After click the button of next line, it will be back to the first line as the screenshot shows. I have to close some windows at that time. I want to know why it happened. Maybe depend on how you implement the center function?
Best wishes!

**Comment by ChrisAnd1998** [comment]
@Dealtz I don't know if this is fixable. As this is some behaviour from the taskbar itself. TaskbarX disables drawing for the taskbar while it's not moving to prevent very annoying flickering issues. This probably prevents you from going to the second and first row.

**Comment by Dealtz** [comment]
> @Dealtz I don't know if this is fixable. As this is some behaviour from the taskbar itself. TaskbarX disables drawing for the taskbar while it's not moving to prevent very annoying flickering issues. This probably prevents you from going to the second and first row.

@ChrisAnd1998 I guess that when there is too many icons to place in just one row,  TaskbarX will always get the right-side location of taskbar in second row instead of the first. So after calculate the center, TaskbarX thought the taskbar should move to such location. 

When I click the next button in the scroll bar, TaskbarX will refresh the taskbar as the refresh rate set. The drawing for the taskbar will make taskbar return to first row and then draw the animation. This action prevents me from going to the second row. 

You can reproduce it by opening more applications to help you locate the real reason.
Best regard.
