### ISSUE TITLE
Where is my TaskbarX configurator?

### ISSUE THREAD

**Issue by snaildos** [ChrisAnd1998/TaskbarX#453]
Where the heck is it? It's not on my desktop;
It's NOT on my start bar,
WHERE IS IT?

**Comment by snaildos** [comment]
And no, There is no tray icon as well. my life is so interesting....

**Comment by ChrisAnd1998** [comment]
Startmenu?

**Comment by snaildos** [comment]
It's not here. AT ALL. But it works?

**Comment by ChrisAnd1998** [comment]
Do you use the free or store version?

**Comment by ChrisAnd1998** [comment]
Do you use the Free version or store version?

**Comment by snaildos** [comment]
Free version.

**Comment by cristiangerardo** [comment]
I use Windows Search box to find it.
![TaskbarX](https://user-images.githubusercontent.com/61348910/98283306-404c1380-1f7e-11eb-81ee-94cd67045516.png)

**Comment by cristiangerardo** [comment]
However with the latest versions it is possible to put an icon on the bar
![TaskbarX2](https://user-images.githubusercontent.com/61348910/98283538-8bfebd00-1f7e-11eb-9770-818d39e6f84c.png)

**Comment by snaildos** [comment]
Where is the executable? For the configuration?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ChrisAnd1998** [comment]
@snaildos It's inside the folder where you extracted TaskbarX.

**Comment by snaildos** [comment]
I used the installer.

**Comment by snaildos** [comment]
It seems like the installer doesn't pack the Configurator?

**Comment by ChrisAnd1998** [comment]
@snaildos It's in there...

**Comment by snaildos** [comment]
I even looked where TaskBarX.exe is, it's not there.

**Comment by cristiangerardo** [comment]
Make a screen copy of where you have TaskBar.exe so we can see it better.

**Comment by snaildos** [comment]
![image](https://user-images.githubusercontent.com/46210117/98616610-1c9b1b80-2338-11eb-9529-82770f436230.png)
I installed with the rmskin actually.

**Comment by ChrisAnd1998** [comment]
Uninstall TaskbarX and use the portable zip.

**Comment by snaildos** [comment]
Alrightio, sounds good. I'll try that. Why is this not added to the RMskin???
Will there also be a installer?

**Comment by snaildos** [comment]
Solved.
Still don't understand why the rmskin doesn't have the config, But alright.
