### ISSUE TITLE
Maximize Brower, weird effect in the top taskbar

### ISSUE THREAD

**Issue by santos-pardos** [ChrisAnd1998/TaskbarX#454]
When a use tasbarX in transparent mode i have a problem with the brower
When i maximize the browser the taskbar make an strange effect -i attache the effect in this picture
![image](https://user-images.githubusercontent.com/66181446/98439162-3cd89980-20f0-11eb-8b92-a01a2ceea2ea.png)
<img width="1272" alt="2020-11-07_11h55_32" src="https://user-images.githubusercontent.com/66181446/98439179-57127780-20f0-11eb-89ce-ff8937f8e3db.png">

**Comment by ChrisAnd1998** [comment]
@santos-pardos Sadly this can't be fixed as this is an issue caused by chromium itself. So this happens in chrome and Edge as well.
