### ISSUE TITLE
The icons in the start menu are strange.

### ISSUE THREAD

**Issue by fxzxmicah** [ChrisAnd1998/TaskbarX#455]
Here are some screenshots:
![image](https://user-images.githubusercontent.com/48860358/98462864-4b0ede80-21f2-11eb-99ea-e31d0c2e9031.png)
![image](https://user-images.githubusercontent.com/48860358/98462879-5e21ae80-21f2-11eb-80ac-e13e251b4b84.png)

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
