### ISSUE TITLE
Center taskbar - Dell XPS13 with Ultrawide Monitor

### ISSUE THREAD

**Issue by Hasekinio** [ChrisAnd1998/TaskbarX#456]
Hi Chris.
I tested today the Taskbar X on a Dell XPS13 connected with a ultrawide montior.
I don't want to center the taskbar on the Dell XPS 13 montior as it is too small. Also a part of the centered taskbar is "cut".
Is there a way that I see the whole taskbar on the XPS13 montior when it is centered?

When I close the monitor on the XPS13 the external ultrawide montior is set to the primary taskbar, so I can't use the setting "only center secondary taskbar".

I hope I could explain my problem.

Thanks,

Andreas

**Comment by Jimmy2004** [comment]
Open configuration exe, and go to "position". tick on "compensate tray clock". For the other question, it is the repository owner's work.

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
