### ISSUE TITLE
Can't Uninstall

### ISSUE THREAD

**Issue by LeelaShyam** [ChrisAnd1998/TaskbarX#457]
I tried to uninstall because I don't need it anymore. Please help.
It says 
![Screenshot_1](https://user-images.githubusercontent.com/74194638/98555020-6d266080-22c7-11eb-802c-4d9c7afbe44d.png)

**Comment by ChrisAnd1998** [comment]
@LeelaShyam You have to manually delete it. Open the "TaskbarX Configurator" and hit the "Stop TaskbarX" button. This will stop the TaskbarX process and put your icons back to the left. Then go to the "Taskschedule" tab and hit the "Remove" button. After that you can simply remove the files where you installed TaskbarX.

**Comment by chigggsy** [comment]
@ChrisAnd1998 I just followed your method: stop taskbarX, then remove the taskschedule, and then uninstall from the app. However I'm still getting this pop up window when my computer starts. 
![image](https://user-images.githubusercontent.com/54223023/112918622-022fd600-9151-11eb-813b-3cdeb2477eb1.png)

**Comment by ChrisAnd1998** [comment]
@chigggsy The error comes from the Taskschedule so te Taskschedule is still there.

**Comment by chigggsy** [comment]
@ChrisAnd1998 I just reinstalled it, then Removed the taskschedule and then uninstalled it again, and restarted my computer. But the pop up is still coming up. I've got the Windows App Store version if that helps? Is there anything else I'm missing?
