### ISSUE TITLE
Stopped working after some time.

### ISSUE THREAD

**Issue by mohakdev** [ChrisAnd1998/TaskbarX#458]
Hey i was using Taskbarx for sometime. Now it just stopped working if i open taskbar configuration and apply some new changes they just dont  work.
Please fix it.
My device=Lenovo idea pad s40 with ryzen 5.

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
