### ISSUE TITLE
[Feature Request] Add the ability to center the start button

### ISSUE THREAD

**Issue by TheXamlGuy** [ChrisAnd1998/TaskbarX#460]
Something similar to what we've seen from Windows 10x. Centering of the search and task view buttons would be a bonus too.

![image](https://user-images.githubusercontent.com/14894973/98742108-c1a00d80-23a5-11eb-8bb1-cfdb872f3756.png)
![image](https://user-images.githubusercontent.com/14894973/98742151-d11f5680-23a5-11eb-8257-ceda41660078.png)

**Comment by Jimmy2004** [comment]
Agree. Leaving the Windows start button alone is not a good idea. It seems so lonely. I want this feature too.

**Comment by BakoBitz** [comment]
Just wanted to bump up this feature request. We'd really love to see this on TaskbarX.
