### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by valdev-fs** [ChrisAnd1998/TaskbarX#461]
Hi dev, recently I got a laptop from my office and I downloaded TaskbarX, after I open the configuration then apply, my taskbar won't be centered, but any option on Style is working fine, the only thing doesn't work is center taskbar, what happend ? Can you tell me how to fix this. Thx

**Comment by ChrisAnd1998** [comment]
Yes, a small percentage has this issue. Currently iam working to find a fix for it. You can try the latest pre-release 1.6.3.0. It now has a 32bit and 64bit version. You probably need the 64bit version.

**Comment by valdev-fs** [comment]
Hi dev, thx the 1.6.30 version is working fine (at least now can be centered)
But I got new issue, now it wont be stay on the middle, I mean on the first refresh, it was on center, but next second/next refresh the taskbar keep moving to the right (I think it feels like the taskbar keep refreshing even the taskbar already on middle) so the program keep think it's not centered yet, so it keep move the taskbar to the right. (I dont click anything after click Apply and the taskbar keep moving automatically)

![Screenshot (1)](https://user-images.githubusercontent.com/29377445/99208653-aa24b280-27f3-11eb-9b4b-7c9384bfe7d7.png)
![Screenshot (2)](https://user-images.githubusercontent.com/29377445/99208669-b9a3fb80-27f3-11eb-900a-03effcd99958.png)
![Screenshot (3)](https://user-images.githubusercontent.com/29377445/99208672-bdd01900-27f3-11eb-9f70-d17dab6407cd.png)

**Comment by marroux** [comment]
hello, i have got the same issue, except, mine was never centered, it keeps moving to the right and refreshing.
running x64, windows 10 home edition, version 20h2, OS build 19042.630.
taskbar settings: automatic hide taskbar in desktop mode, use peek to preview.
running .net framework 4.8, no other taskbar tweakers.
tried to debug using dnSpy, there is no output.

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
