### ISSUE TITLE
Transparent makes my taskbar black.

### ISSUE THREAD

**Issue by marlonrandle** [ChrisAnd1998/TaskbarX#462]
Each of the other taskbar settings works, but when I use the transparent taskbar or the opaque taskbar, it simply makes my entire taskbar black.

**Comment by ChrisAnd1998** [comment]
@marlonrandle This happens when you're on a older build of windows 10.

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
