### ISSUE TITLE
Triple monitor setup question

### ISSUE THREAD

**Issue by AWildGamer** [ChrisAnd1998/TaskbarX#463]
I've downloaded both the Rainmeter skin and Windows Store version, but cannot figure out how to setup a triple-monitor setup like the pictures on your website. Am I missing something? Or was that an idea that cannot be done yet?

**Comment by ChrisAnd1998** [comment]
You can right click on the taskbar and then unlock them. After that you can drag the taskbars individually to any position. When you're done lock the taskbars again.

**Comment by AWildGamer** [comment]
Oh wow I'm dumb lol. Thank you!
