### ISSUE TITLE
making taskbarx as a rainmeter skin is *chef's kiss*

### ISSUE THREAD

**Issue by s0seji** [ChrisAnd1998/TaskbarX#465]
minor issue was when on acrylic mode and then opening the start menu/showing hidden icons, taskbar sometimes flicker.

**Comment by ChrisAnd1998** [comment]
@s0seji This is a hard one.. As this is more like a feature that comes with the Acrylic style. This is something caused in SetWindowCompositionAttribute Lib "user32.dll".

**Comment by s0seji** [comment]
surprisingly, it happens with transparent mode as well. but i'm glad to know the cause. thanks, chris!

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
