### ISSUE TITLE
Taskbar appearance on Startup

### ISSUE THREAD

**Issue by vrindavan** [ChrisAnd1998/TaskbarX#467]
I have applied transparent mode on but I have to open configurator after every boot to enable it, the centre position for icons just work fine but the transparent and other styles need to be applied again and again after every start

**Comment by Anequit** [comment]
Can confirm this is an issue with the transparent gradient as well

**Comment by mjw72652** [comment]
I have the exact same problem on two different HP laptops running Win 10 home 64 bit 2004

**Comment by mjw72652** [comment]
On one of my laptops, running 20H2, sometimes TaskbarX now goes transparent at first, then as startup proceeds to open up things like the Microsoft Newsbar and Gadgets, it goes to dark transparent gray. Sometimes, however, it does turn completely transparent again and doesn't need to be reconfigured. The other one never does this. Also, occasionally, on both laptops, I get an error message shell:AppsFolder\40210ChrisAndriessen.FalconX_y1dazs5F5wq00!TaskbarX, that I need to manually close.

**Comment by voiceofvraja** [comment]
I stopped using the app now, :/

**Comment by mjw72652** [comment]
I fixed the problem by adding a new key in my registry to revise my startup delay. If you do a Google search for "How to revise Windows 10 Startup Delay to possibly speed up starting your computer"  located at https://www.onmsft.com/how-to/how-to-revise-windows-10-startup-delay-to-possibly-speed-up-starting-your-computer you will find the step-by-step instructions on how to do this.

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
