### ISSUE TITLE
My taskbar dances and icons fly

### ISSUE THREAD

**Issue by thegamerx1** [ChrisAnd1998/TaskbarX#468]
if you open and close 2 windows very fast it dances D:
also sometimes the taskbar icons move to random positions after opening/closing windows
this didnt happen in older versions where the ui looked bad like windows 98 (i might be confusing it with falconX)
![ezgif com-gif-maker](https://user-images.githubusercontent.com/34986564/99882274-785e8200-2c1f-11eb-8aaa-ff8d56f7ad05.gif)

![ezgif com-gif-maker](https://user-images.githubusercontent.com/34986564/99882185-e9ea0080-2c1e-11eb-9aec-338295851190.gif)

**Comment by ChrisAnd1998** [comment]
Should be fixed in 1.6.3.0
