### ISSUE TITLE
[BUG] Taskbar icons overlap Tray

### ISSUE THREAD

**Issue by DTS233** [ChrisAnd1998/TaskbarX#470]
The icons in my tray overlaping the icons in my taskbar
![SharedScreenshot](https://user-images.githubusercontent.com/74960522/100078161-f2487280-2e8e-11eb-89a5-a0d4a4e5ac44.jpg)

**Comment by CallumCarmicheal** [comment]
Have you checked the "Compensate for tray area" option inside the configurator ?

**Comment by DTS233** [comment]
yes but every time i try nothing happens
