### ISSUE TITLE
TaskbarX animation stuttering when the first icon on the taskbar appears

### ISSUE THREAD

**Issue by SnailMango** [ChrisAnd1998/TaskbarX#471]
Hello! I just installed the TaskbarX skin with Rainmeter after a lot of months using FalconX. I've just done a clean install of Windows 10 Pro (now on latest 20H2 build) so I'm sure the issue should not be about old files making conflict.
The problem is that when I open the first app/software and it appears on the taskbar, it makes a strange cutted copy of itself when doing the moving animation from left to the center of the taskbar. This only happens on my 3440x1440 144Hz monitor. My secondary monitor is a 1920x1080 120Hz in portrait mode and the animation is fine.
I'm attaching a screenshot of my desktops took during the animation so you can see.
![TaskbarX_bug](https://user-images.githubusercontent.com/64862343/100381943-73804080-301a-11eb-9611-d6aae618ebf5.jpg)

**Comment by SnailMango** [comment]
Hello, any news about this issue?

**Comment by ChrisAnd1998** [comment]
@SnailMango Hi, i have been trying to find a fix for this but sadly no luck yet... I am able to reproduce it.

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
