### ISSUE TITLE
Start & tray

### ISSUE THREAD

**Issue by uvazhaemiydenisvitaljevich** [ChrisAnd1998/TaskbarX#473]
Привет! Можно ли сделать так, чтобы кнопка пуск (start) и трей (tray) появлялись при наведении курсора? В остальном все работает! Лучшая программа! Спасибо за труд!

**Comment by ChrisAnd1998** [comment]
> Translation: Hello! Is it possible to make the start button and the tray appear when the cursor is hovering? The rest of it works! Best program! Thank you for your hard work!‎
