### ISSUE TITLE
Primary tray area ui/display bug

### ISSUE THREAD

**Issue by Tyluur** [ChrisAnd1998/TaskbarX#479]
See the bottom right part.

https://i.imgur.com/2M3NCaO.png

Configurations -> Extra:

https://i.imgur.com/4rbagsy.png

**Comment by Tyluur** [comment]
Glad to see this being looked into. I'm using ubuntu 20.04 for home use now instead.

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
