### ISSUE TITLE
Installer for non Store version

### ISSUE THREAD

**Issue by Martin5001** [ChrisAnd1998/TaskbarX#48]
I think having some basic (un)installer would be really good, especially when installing new versions. Now I had to manually clean up the registry to get rid of the Startup task from the previous version and I think some settings left from the previous version may also be causing issue #47, but I don´t know.

**Comment by ChrisAnd1998** [comment]
Allright, i can do that.

The settings are completely replaced since they are now saved in the Appdata. 
So there can't be an issue there.

**Comment by Martin5001** [comment]
Thank you a lot for making improvements to the project :) Falcon is great tool for me.

**Comment by ChrisAnd1998** [comment]
I have finally included it now ;)
