### ISSUE TITLE
Botón de Inicio en la Barra de Tareas.

### ISSUE THREAD

**Issue by pianistadc** [ChrisAnd1998/TaskbarX#480]
**Describe the bug**
When I run "TaskbarX.exe" v1.6.3.0, my taskbar shows 2 start buttons. This happens in all versions of TaskbarX except "TaskbarX v1.5.6.0".

**To Reproduce**
Just run "TaskbarX.exe" v1.6.3.0 and the error happens.

**Expected behavior**
Icons centered with a single Start button.

**Screenshots**
Without running "TaskbarX.exe" v1.6.3.0:
https://drive.google.com/file/d/1FuNyb4_Ama1K4l2NA_aaG-tlhyPO9krx/view?usp=sharing
Running "TaskbarX.exe" v1.6.3.0:
https://drive.google.com/file/d/1dVoALmvhPzUdOjH-POxzOvBFg6BwkRZc/view?usp=sharing
Running old version "TaskbarX.exe" v1.5.6.0:
https://drive.google.com/file/d/1egSwg0pTSP1WACNu0wPGcpt1-fg7waap/view?usp=sharing

**Desktop (please complete the following information):**
 - OS: Windows 10 LTSC Delta OS (Modified Windows. This is the web: https://windowsminios.org/).
 - Browser: Chrome.
 - Version: v87.0.4280.88 (Build oficial) (64 bits)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
