### ISSUE TITLE
[Feature Request] Add the ability to show/hide search icon windows 10 on each screen

### ISSUE THREAD

**Issue by pietou-pietou** [ChrisAnd1998/TaskbarX#482]
show/hide the search icon on each screen would be a great bonus !
<img width="146" alt="Capture d’écran 2020-12-09 125156" src="https://user-images.githubusercontent.com/75731227/101626505-5d608000-3a1d-11eb-9121-48d216f4212e.png">

**Comment by ChrisAnd1998** [comment]
You can right click the taskbar and then hide search ;)
