### ISSUE TITLE
Opening and closing windows causes TaskbarX to behave erratically while centring the task bar when refresh rate is high

### ISSUE THREAD

**Issue by NathanielJS1541** [ChrisAnd1998/TaskbarX#485]
**Describe the bug**
Opening and closing windows will sometimes cause the "centre" feature of TaskbarX to behave very erratically when the refresh rate is set to below 100ms. My animations are set to "linear" and I have enabled compensation for the tray and clock.

**To Reproduce**
1. Set animation style to "linear" with 400ms animation speed
2. Centre taskbar with compensation for the clock
3. Set the Refresh rate to anywhere below about 100ms (My screenshots below are at 50ms)
4. Opening and closing windows will now cause the taskbar to "jitter" unexpectedly.

**Expected behavior**
I would expect that with an increased refresh rate the animation would simply happen sooner after a new window is opened. Maybe it could be implemented so that the software will disallow refresh rates high enough that it causes undesirable effects?

**Screenshots**
Here I simply open the "Settings" menu:
![example_1](https://user-images.githubusercontent.com/33491104/101914303-09d86880-3bbc-11eb-9245-4628f2e8b0ea.gif)
And here I close two explorer windows:
![example_2](https://user-images.githubusercontent.com/33491104/101914306-0ba22c00-3bbc-11eb-8c0a-d9224cc1a5bd.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 10.0.19042 Build 19042

**Additional context**
I feel this is not an urgent bug as the default refresh rate is set much higher than the ones I have found to cause problems, but I feel that given the behaviour when this does occur is such that I feel it should be brought up. Maybe the fix could be as simple as a warning on the help pop-up about the typical values below which problems begin to occur?

**Comment by ChrisAnd1998** [comment]
Can you try this? https://github.com/ChrisAnd1998/TaskbarX/releases/tag/1.6.8.0

**Comment by NathanielJS1541** [comment]
I've been using the pre-release for a day or so and I haven't been able to reproduce the behaviour I was seeing. Thanks very much.

**Comment by ChrisAnd1998** [comment]
@NathanielJS1541 Great! Thanks for letting me know. I found some issues with combined taskbar buttons and taskbar labels though.. So the full release can take some time. I'm really glad this issue is almost fixed 😁. I'm also getting more confirmations from other people that it's fixed.

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
