### ISSUE TITLE
Request... PLEASE can you add a way to move the startbutton in the center too??

### ISSUE THREAD

**Issue by cmputerboom** [ChrisAnd1998/TaskbarX#486]
PLEASE can you add a way to move the startbutton in the center too??
I have a 4k 55 inch screen and its annoying to have to reach all the way to the left to reach that. 
I know i can press the windows key on my keyboard.. but still.
OR if someone knows of a way to PIN a startbutton that will open the start menu that would help.. then i can HIDE the start button 

it seems like an old version of this program did have that ability? 
see here https://www.ghacks.net/2018/06/20/center-windows-10-taskbar-icons-and-start-button-with-falcon/

thanks in advance!

**Comment by myusrn** [comment]
Also see https://github.com/ChrisAnd1998/TaskbarX/issues/492 where I believe i've detailed this and related set of feature asks for the same reason you are asking.
