### ISSUE TITLE
Not Working for Third Monitor

### ISSUE THREAD

**Issue by chrisface1112** [ChrisAnd1998/TaskbarX#487]
I have a three monitor setup, my primary being my laptop, second being an ultrawide for productivity and a third 4K for gaming and media consumption, this program just doesn't work on the third monitor, it is like it doesn't exist but the first two it works just fine.

It just happens on the third monitor, not doing anything specific except booting the computer up.
![Second Monitor Taskbar](https://user-images.githubusercontent.com/75998856/102103244-bd2ea080-3dfa-11eb-9ce7-0bd6509d5e8f.jpg)
![Third Monitor Taskbar](https://user-images.githubusercontent.com/75998856/102103256-c1f35480-3dfa-11eb-99c6-2e55ab131356.jpg)

A quick fix as to how I can get it to work.

Windows 10 Pro 19042

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
