### ISSUE TITLE
Taskbar randomly flashing/restarting

### ISSUE THREAD

**Issue by huds0nx** [ChrisAnd1998/TaskbarX#488]
**Describe the bug**
Heya! Today I simply turned on my computer, and noticed my taskbar kept flashing, while the icons move left and right, as if it were restarting, which is odd. It usually does this when installing an app, which I did, but it has continued even after the installation is finished.

**To Reproduce**
1. Start up your computer
2. Install almost any program
3. You will notice that your taskbar is flashing and "restarting"

**Expected behavior**
I expected my taskbar to simply stay where it is without flashing and moving.

**Screenshots**
![aA4Ypa](https://user-images.githubusercontent.com/39014019/102137704-9fc8f900-3e31-11eb-8f85-ba007c96cf25.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 20H2 (os build 19042.572)

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
