### ISSUE TITLE
TaskbarX not working properly after restart

### ISSUE THREAD

**Issue by xultraalphax** [ChrisAnd1998/TaskbarX#489]
So my problem is that after I restart my pc taskbarx wont work properly even if I disable it in task scheduler and open it manually. The only way I can make it work again is by pressing uninstall inside the configurator so it resets my configuration and reopening taskbarx.

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
