### ISSUE TITLE
TaskbarX does not work and center my icons.

### ISSUE THREAD

**Issue by aenesks** [ChrisAnd1998/TaskbarX#493]
I can configurate my taskbar (transparent etc.) but it does not center my icons. My icons are going through right side of taskbar and i cant see or access them until restart the taskbarx and check "dont center my icons" option.

 - OS: Windows 10
 - Version 1.6.3.0

![Ekran Görüntüsü (80)](https://user-images.githubusercontent.com/76035709/102474951-544d5f80-406a-11eb-81ae-1b035c6ff001.png)
![Ekran Görüntüsü (81)](https://user-images.githubusercontent.com/76035709/102474972-58797d00-406a-11eb-9e39-183ae4c734b4.png)
![Ekran Görüntüsü (82)](https://user-images.githubusercontent.com/76035709/102474980-5ca59a80-406a-11eb-8f0a-3880e8a1272d.png)
![Ekran Görüntüsü (83)](https://user-images.githubusercontent.com/76035709/102474995-60d1b800-406a-11eb-8790-09147ed0238e.png)
![Ekran Görüntüsü (84)](https://user-images.githubusercontent.com/76035709/102475007-64653f00-406a-11eb-83f5-ae6cb60ea75d.png)
![Ekran Görüntüsü (85)](https://user-images.githubusercontent.com/76035709/102475022-67f8c600-406a-11eb-9708-55ee522c691c.png)
![Ekran Görüntüsü (86)](https://user-images.githubusercontent.com/76035709/102475038-6c24e380-406a-11eb-8603-29aa10e5213f.png)
![Ekran Görüntüsü (76)](https://user-images.githubusercontent.com/76035709/102475052-70e99780-406a-11eb-92f4-46d592185067.png)
![Ekran Görüntüsü (77)](https://user-images.githubusercontent.com/76035709/102475070-7515b500-406a-11eb-8f81-ad461d33685e.png)
![Ekran Görüntüsü (78)](https://user-images.githubusercontent.com/76035709/102475081-7941d280-406a-11eb-9c53-0844f4d195bb.png)
![Ekran Görüntüsü (79)](https://user-images.githubusercontent.com/76035709/102475090-7cd55980-406a-11eb-9bbf-60664e6573af.png)

**Comment by younkyumkim** [comment]
This problem is not being resolved
Help me solve it

**Comment by ChrisAnd1998** [comment]
@younkyumkim I'm sorry but, i can't give a solution until i am able to reproduce the issue or know what is causing this behavior.. 😩

**Comment by RavenScarto** [comment]
I have the same problem. I just bought your program on Microsoft Store but doesn´t work.

**Comment by RavenScarto** [comment]
> @younkyumkim I'm sorry but, i can't give a solution until i am able to reproduce the issue or know what is causing this behavior.. 😩

I have the same problem. I just bought your program on Microsoft Store but doesn´t work.

**Comment by AddictRacoon** [comment]
Just click on ¨Dont center taskbar :D

**Comment by aenesks** [comment]
> Just click on ¨Dont center taskbar :D

Why? I want my taskbar to be centered

**Comment by AddictRacoon** [comment]
I clicked in here and the space disapeared

**Comment by aenesks** [comment]
> I clicked in here and the space disapeared

It doesnt work on my pc

**Comment by ChrisAnd1998** [comment]
@aenesks Have you used different tools to manipulate the Taskbar? Also the trick that allows you to move the icons manually can cause miscalculations if you didn't remove that properly.

**Comment by aenesks** [comment]
> @aenesks Have you used different tools to manipulate the Taskbar? Also the trick that allows you to move the icons manually can cause miscalculations if you didn't remove that properly.

No, i have never used any tools but taskbarx. How can i remove the thing you mentioned properly? I am new at this configuration tools.

**Comment by ChrisAnd1998** [comment]
Just disable any toolbar just like in the screenshot. However i forgot this doesn't matter anymore as i fixed it a while ago.

![Untitled](https://user-images.githubusercontent.com/50437199/103552720-a1c02e00-4eac-11eb-8781-83f69fb47084.png)

This is how you can position them manually... http://www.wisecleaner.com/how-to/111-how-to-center-the-taskbar-icons-in-windows-10.html

**Comment by aenesks** [comment]
@ChrisAnd1998 I'll give it a try tonight. Also just updated to W10 20H2

**Comment by mc-milo** [comment]
I had the same issue its easy to resolve
1. stop TaskbarX 
2. delete all its files
3. restart 
4. redownload
5. you are done 

that's what fixed for me at least

**Comment by aenesks** [comment]
I updated the last version. And another bug appeared. The icons are going throght right step by step when i open a new application. (I have dual monitors)

**Comment by BarisBayraktar** [comment]
I can't centered either.

**Comment by Vanilla-Minazuki** [comment]
TaskBarX not centering my icons but i can make taskbar transparent etc.
![image](https://user-images.githubusercontent.com/87177969/125058584-1752c400-e0b3-11eb-9b7c-c17d6ea3a7bd.png)

**Comment by TheOnlyIlona** [comment]
I have the same problem, I can put it in invisible but not center it :v if anyone has a solution i'm interested

**Comment by asvpjair** [comment]
it did the same thing for me lol i just spent $2 for something that doesn't even work.

**Comment by emopedia** [comment]
I have the same problem. Transparency works but it doesn't center icons.

**Comment by d4ve02** [comment]
I have a dual monitor setup, with Display 1 as my side monitor and Display 2 as my main monitor. The windows taskbar is enabled only on the main monitor (Display 2), and I'm experiencing the same issue (transparency works but icon centering doesn't).

I tried enabling the taskbar for both monitors (Taskbar Settings > Show taskbar on all displays), and the result is that TaskbarX is centering icons on the taskbar that's not main. Icons of Display 1 are being centered and those of Display 2 are not.

If I try switching my main monitor to Display 1, the same thing happens: icons now are centered for Display 2 but not for Display 1.

I think the issue might be that TaskbarX is centering the icons of the taskbar that's not the main one, even if it's disabled.

**Comment by MoistTortilla** [comment]
> I have a dual monitor setup, with Display 1 as my side monitor and Display 2 as my main monitor. The windows taskbar is enabled only on the main monitor (Display 2), and I'm experiencing the same issue (transparency works but icon centering doesn't).
> 
> I tried enabling the taskbar for both monitors (Taskbar Settings > Show taskbar on all displays), and the result is that TaskbarX is centering icons on the taskbar that's not main. Icons of Display 1 are being centered and those of Display 2 are not.
> 
> If I try switching my main monitor to Display 1, the same thing happens: icons now are centered for Display 2 but not for Display 1.
> 
> I think the issue might be that TaskbarX is centering the icons of the taskbar that's not the main one, even if it's disabled.

I am having this same issue. I am going to try a few things and I will let you know. So far I haven't heard of any fix. I might try and revert to an older model of taskbarx.

**Comment by kkanekii** [comment]
howdyu make the thingy green on the bottom

**Comment by Zerrylicious** [comment]
replacing TaskbarX.exe from 1.6.8.0 version to 1.7.1.0 works for me

**Comment by Zayde05** [comment]
I have recently purchased this app yesterday to give my computer a more aesthetic and pleasing look. The taskbar wouldn't centre. I tried this on my other laptop and the same thing happened again. I don't want to have to refund this app because I have heard great reviews, but i may have to if there is no solution to this problem. Does anyone have a possible fix to this?

**Comment by dpaulsoria** [comment]
Hey, the same for me. I've purchased this app in microsoft store TODAY and at the beggining I had that problema (only transparency for the taskbar and the icons don't get center) but now I uninstalled and installed again and ANYTHING works, no transparency and nothing :)

**Comment by dpaulsoria** [comment]
![image](https://user-images.githubusercontent.com/72895299/127598497-f9395c24-74b4-44d5-8248-cbb9b6d11204.png)
Even the extra options doesn't work

**Comment by Robbie-Campbell** [comment]
Just quickly opening the console reveals this message, i wonder if this helps at all? 
![image](https://user-images.githubusercontent.com/56073739/127695044-710b192e-f3d5-46fa-82d7-173fdb7d33bf.png)

**Comment by s0mmer** [comment]
Have anyone found a fix yet? I've tried different versions, and the icons just wont center

**Comment by plankford** [comment]
Found it in another issue thread.

Uninstall the current version and install 1.6.9.0. Unzip that version and run. This fixed my not-centering issue.

**Comment by kkanekii** [comment]
@plankford that worked for me as well, I forgot to post it here, but thank you!

**Comment by erfanpaslar** [comment]
> Found it in another issue thread.
> 
> Uninstall the current version and install 1.6.9.0. Unzip that version and run. This fixed my not-centering issue.

You are a GOD! Thanks.

**Comment by MDARH** [comment]
Uninstall the current version and try some old version. Unzip that version and run. This fixed my not-centering issue. My not- Centering problem fix by 1.6.8.0 version.

**Comment by DarkPixelWolf** [comment]
I got the same issue after buying it today.

**Comment by veegishx** [comment]
> Found it in another issue thread.
> 
> Uninstall the current version and install 1.6.9.0. Unzip that version and run. This fixed my not-centering issue.

This worked for me, thanks!

**Comment by littlooo** [comment]
try installing taskbar x 1.06
[TaskbarX_1.6.2.0.zip](https://github.com/ChrisAnd1998/TaskbarX/files/7171225/TaskbarX_1.6.2.0.zip)

**Comment by littlooo** [comment]
> I got the same issue after buying it today.

try installing taskbar x 1.06
[TaskbarX_1.6.2.0.zip](https://github.com/ChrisAnd1998/TaskbarX/files/7171241/TaskbarX_1.6.2.0.zip)

**Comment by littlooo** [comment]
> @younkyumkim I'm sorry but, i can't give a solution until i am able to reproduce the issue or know what is causing this behavior.. 😩

well it's problem in new version,  it got fixed when i installed old version of taskbar x

**Comment by psyducktech** [comment]
Managed to fix this by downgrading to Version 1.6.9.0

Issue occurred on Windows 10 Home 1809.

![image](https://user-images.githubusercontent.com/89639839/133920938-41f45a37-0f4a-458f-95a5-f28c856b0dad.png)

![image](https://user-images.githubusercontent.com/89639839/133920947-77b4e5b7-047c-4478-b046-441eaff88703.png)

![image](https://user-images.githubusercontent.com/89639839/133920968-6f3f8d78-5e93-4414-8430-d4cfd2dd4415.png)

**Comment by pronovic** [comment]
I've been using TaskbarX v1.6.3 for about a year with no problems on Windows 10 Pro.  I have a single monitor running at 2560x1440 resolution.  

Yesterday, I pulled in the 21H1 feature update (taking me to build 19043.1237).  After reboot, the taskbar disappeared completely. I upgraded to TaskbarX v1.7.2, which fixed that problem, but then the taskbar wasn't centered.  I also tested with TaskbarX v1.6.9, but got the same behavior.  

After playing with this for a while, I've concluded that the problem seems to have a timing component and also seems to be related to the tray.   If TaskbarX starts before the tray is fully populated, then it seems to get confused about the width of the screen and incorrectly centers the taskbar.  So, part of the solution is to delay the start of TaskbarX until after everything in the tray has fully started.  However, even with that delay, the taskbar still is not entirely centered.  I fixed that using a negative offset that pulls the taskbar back to the left, and the result looks basically like it did before I patched Windows.  So, this is a good enough solution for me right now.

Below are the specific changes I made to get things working again.

Previously, I was starting TaskbarX with a shortcut in the `shell:startup` folder.  I got rid of that shortcut and switched to using the scheduled task on the **Startup** tab:

- _Delay:_ `20` seconds, then click **Remove** and **Create** to recreate the task

Then, I made the following changes on the **Position** tab, to pull the taskbar into the right place:

- _Primary Taskbar Offset:_ `-350` px
- _Compensate Tray Clock etc..._: checked
- _Revert to zero beyond Tray_: checked

I'm sure whether this will help anyone else, but it does seem to be behaving consistently for me right now, through multiple logout, sleep, and reboot cycles.

**Comment by Sergij-SApcPro** [comment]
Fixed it by using version 1.6.9.0, the developer should fix the problem as soon as possible.

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️

**Comment by Qeron** [comment]
Try to run as administrator, thats works for me

**Comment by kkhvled** [comment]
I have this problem rn and used 1.6.9.0 version and still have it
any other solutions?

**Comment by DishankRane** [comment]
The problem persists on any version of taskbarx please help
