### ISSUE TITLE
Multiple Instances

### ISSUE THREAD

**Issue by ABongoCat** [ChrisAnd1998/TaskbarX#494]
![x bug](https://user-images.githubusercontent.com/45139479/102528459-e53e2e00-409e-11eb-8201-06eea17dfa1c.png)
This what it looks like after I play League of Legends. I mostly use Ctrl + Esc to "tab out" and after the game I look down there and I see that. What happens often too when I tab out is that my taskbar is starting to glitch midways.

**Comment by albarlow** [comment]
I also get this after Windows goes to sleep and then wakes up.

I'm running a Windows 10 laptop with a 2nd hdmi monitor running off a USB-C hub.

Sometimes I get so many system tray icons it generates a system error.

**Comment by tedog123456789** [comment]
I'm also having this, after closing skyrim I looked in the tray and there were maybe 6 different instances appearing and then they all closed one by one as I watched. Very strange, makes me wonder if it's leaching off my resources for bitcoin mining or something

**Comment by TheRaikoz** [comment]
Same issue, very annoying.

**Comment by ChrisAnd1998** [comment]
Currently i have not found a solution for this yet. The icon in the tray is not refreshing causing the duplicates. To be clear for @tedog123456789 I would never do such things.. You can look through the source code here. TaskbarX can only have 1 instance running it will make sure of that. For now you can disable the tray icon inside the Configurator.
