### ISSUE TITLE
Taskbar Configuration Resetting on Startup

### ISSUE THREAD

**Issue by Shadowe1551** [ChrisAnd1998/TaskbarX#497]
I got the taskbarX program to launch with my system startup, it centers the icons and makes the taskbar transparent, the setting I applied, but a few seconds later, the transparency goes away, and the taskbar changes to a transparent gradient. How do I get it to stay transparent?

**Comment by InukaAsith** [comment]
I have the same problem too

**Comment by bakeluco** [comment]
Hey, try setting the shell:startup shortcut to "**Run as administrator**". 

**NOT** the .exe!! Just the shortcut

**Comment by Shadowe1551** [comment]
That did not seem to work.

**Comment by Shadowe1551** [comment]
> Hey, try setting the shell:startup shortcut to "**Run as administrator**".
> 
> **NOT** the .exe!! Just the shortcut

That did not seem to work.

**Comment by ChrisAnd1998** [comment]
@Shadowe1551 Are you running a older build of Windows 10? Below 1909

**Comment by Shadowe1551** [comment]
@ChrisAnd1998 Oh yes, I am on build 19042.685.

**Comment by ronilaukkarinen** [comment]
Noticed this too. Very frustrating. Using build 20H2.

**Comment by softtama** [comment]
I'm having the same issue as yours. Currently on 20H2 (build 19042.804).

**Comment by softtama** [comment]
My workaround is this:
https://github.com/ChrisAnd1998/TaskbarX/issues/273#issuecomment-778856097

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
