### ISSUE TITLE
Taskbarx causes laptop screen to glitch

### ISSUE THREAD

**Issue by SeveralP** [ChrisAnd1998/TaskbarX#500]
**Describe the bug**
Whenever you turn your device on it will cause the laptop screen to show multicolor lines, flashing, black screen, and just glitch out.
**To Reproduce**
1. Download taskbarx and turn your laptop on

**Expected behavior**
You should see a black screen and glitching
**Screenshots**
https://streamable.com/grljhf

**Desktop (please complete the following information):**
 - Windows 10
 - Latest

**Additional context**
You will have to reboot your laptop to have the issue fixed

**Comment by SeveralP** [comment]
I am 100% sure taskbarX is causing this, as whenever taskbarX is downloaded this issue happens and when it is not on my system this does not happen.

If you had this same issue please comment saying so

**Comment by Klokki** [comment]
Had a similar issue on my Surface Laptop 3, though when opening my browser instead of booting up
