### ISSUE TITLE
Hide Primary Tray Area bug

### ISSUE THREAD

**Issue by lefterispg** [ChrisAnd1998/TaskbarX#501]
**Describe the bug**
As you can see in the photo below, when I have both **"hide primary start button"** and **"hide primary tray area"** turned on, it doesn't exactly hiding the tray area but it is showing its borders. 

**To Reproduce**
1. Go to 'extra'
2. Click on 'Hide Primary Start Button' & 'Hide Primary Tray Area'
3. Click on 'Apply'

**Expected behavior**
It should hide the tray area without showing the borders.

**Screenshots**
![image](https://user-images.githubusercontent.com/45579527/103047441-36b15600-4594-11eb-989b-a46f88934ce7.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 pro
 - Version 1909

**Additional context**
Sometimes it does it even when  **"hide primary start button"** is off but not always.

**Comment by Everun2** [comment]
![Screenshot 2021-01-29 164306](https://user-images.githubusercontent.com/64978236/106334841-1f2f5200-6251-11eb-9eeb-219734b902a7.png)

Same issue. And thank you, Chris, just got TaskbarX and Aerial today, very happy!

**Comment by ChrisAnd1998** [comment]
@Everun2 @lefterispg I think I've got it now. You can try out the Pre-Release ;)
https://github.com/ChrisAnd1998/TaskbarX/releases/tag/1.6.5.0

**Comment by PhoenixCODE2322** [comment]
@lefterispg , can you please tell after hiding the tray area is there a way to access it. i just discovered hiding start menu and tray, but sometimes i need to access the tray. is there a way ?

**Comment by heitorcr84** [comment]
> @lefterispg , can you please tell after hiding the tray area is there a way to access it. i just discovered hiding start menu and tray, but sometimes i need to access the tray. is there a way ?

I'd also like this a lot. 
Something similar to the checkbox - **Switch back to default on maximized window**

It is possible?
