### ISSUE TITLE
can you pls add it auto restart after the explorer restarts pls pls pls pls pls 

### ISSUE THREAD

**Issue by Prakrit-170807** [ChrisAnd1998/TaskbarX#502]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ChrisAnd1998** [comment]
@Prakrit-170807 Ohh, it seems to have been broken after some updates. It's there but, needs some fixing i'll look into it ;)

**Comment by DanDon** [comment]
Not sure if this is related to the transparency not showing after waking the computer from sleep?? TaskbarX just needs to be opened manually and apply clicked to get the transparency back.
Mostly annoying as I sleep and wake the computer multiple times a day.
Not sure if this is explorer related as I presume explorer has to restart when sleeping then waking?

**Comment by Prakrit-170807** [comment]
No thanks Chris I am a app developer for windows and I do a lot of heavy stuff that some how brakes my file explores and it restarts my explorer and it doesn’t automatically start that bugs me so that was just a suggestion and I am very happy to use you program also I was look for this kind of program for ages and I was like mind blow to find it finally so it was just a quick suggestion. Also I am a customization king so this program is so reliable more than I expected honestly    Sent from Mail for Windows 10 From: Chris AndriessenSent: Thursday, December 24, 2020 4:51 PMTo: ChrisAnd1998/TaskbarXCc: Prakrit-170807; MentionSubject: Re: [ChrisAnd1998/TaskbarX] can you pls add it auto restart after the explorer restarts pls pls pls pls pls (#502) @Prakrit-170807 Ohh, it seems to have been broken after some updates. It's there but, needs some fixing i'll look into it ;)—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by stevemagruder** [comment]
I noticed this issue today when I had to restart Windows Explorer after making a registry change for an unrelated problem with other software. When I restarted Explorer, TaskbarX didn't restart. I had to launch the Config and restart it from there.

**Comment by BluePhoenix** [comment]
Found this issue after encountering the same thing. I was closing explorer.exe to refresh some other things that are not refreshing properly, but then TaskbarX does not restart until I manually open the Config window and press restart (or click restart in the taskbar icon).

Was trying to find how I could script it but no luck yet on finding that.

**Steps to reproduce**
1. Have TaskbarX running
2. Force quit explorer, it will automatically restart (i.e. powershell Stop-Process -name explorer)
3. TaskbarX no longer centers icons
4. The console output of TaskbarX says: 
```Looper1 | Error: Missing method 'instance object [TaskbarX] Accessibility.IAccessible::get_accRole(object)' from class 'System.Int32'.``` 
(Which sounds like a similar issue to #437 )
5. Open Taskbar X configurator, press `Restart TaskbarX` and everything works as expected.
