### ISSUE TITLE
TaskbarX doesn't work on Windows 7

### ISSUE THREAD

**Issue by sadordev** [ChrisAnd1998/TaskbarX#503]
When you run TaskbarX as administrator, nothing happens, however TaskbarX Configurator works

System: Windows 7
Version: Service Pack 1
.NET Framework: newest

**Comment by YuujiNana** [comment]
"What versions of Windows does TaskbarX support? TaskbarX only supports Windows 10. Version 1709 and lower will have issues with the "taskbar styling" option but, the centering will work fine. Windows 7 does not work and is not supported. It could be working on Windows 8 but, is not officially tested and is also not supported."
