### ISSUE TITLE
Audio in Windows 10 stops working from headphones after TaskbarX launches

### ISSUE THREAD

**Issue by noobishply** [ChrisAnd1998/TaskbarX#504]
**When TaskbarX launches at startup, the audio from my headphones stop working**
I tested my audio before taskbarx started, and it was fine, but when taskbarx opened up after a few seconds, the audio from my headphones wouldn't work at all. The settings I had for the animation was expoeseaseinout.

**To Reproduce**
1. Set TaskbarX to open at startup
2. Set the animation to expoeaseinout at set the time to 1000 ms and the style to transparent and switch back to default on maximized window
3. Click apply and restart your computer
4. Wait for TaskbarX to open up
5. Once opened up, test your audio from your headphones when connected

**Expected behavior**
Audio from headphones works fine and nothing goes wrong

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 20H2 (OS Build 19042.685)

**Additional context**
1) This problem only persisted after I set up a dual boot with Linux Mint.
2) On recording, you can hear the audio
3) I can hear the audio on my laptop only, not from my headphones

**Comment by ChrisAnd1998** [comment]
@noobishply There is no reason for TaskbarX to affect your audio. Have you tried completely uninstalling TaskbarX? to make sure.
