### ISSUE TITLE
Configurator not working :(

### ISSUE THREAD

**Issue by RafaeloxMC** [ChrisAnd1998/TaskbarX#506]
Hello! I tried to start my TaskbarX Configurator.exe but everytime i try to start it, nothing happens. More Information in the Video

RafaeloxMC

https://user-images.githubusercontent.com/53903394/103415569-09ac0700-4b83-11eb-96ee-1a23ce63bc84.mp4

**Comment by ChrisAnd1998** [comment]
@RafaeloxMC What version of TaskbarX? And what version of Windows 10?

**Comment by RafaeloxMC** [comment]
> @RafaeloxMC What version of TaskbarX? And what version of Windows 10?

Version "1.3.6.0 x64" and Windows Version "2004"

**Comment by ChrisAnd1998** [comment]
@RafaeloxMC I see! **Emoji.Wpf.dll** is missing. You need to download TaskbarX again and make sure you extract everything ;)

**Comment by LJINFINITY** [comment]
i have every thing extracted and still it doesnt work for me

**Comment by unboundss** [comment]
> 
> 
> @RafaeloxMC I see! **Emoji.Wpf.dll** is missing. You need to download TaskbarX again and make sure you extract everything ;)

I have everything installed im pretty sure 
![taskbarx](https://user-images.githubusercontent.com/86064080/122416377-98b9a980-cf80-11eb-88c6-c32354156f18.png)
