### ISSUE TITLE
the settings in TaskbarX Configurator keep Changed  

### ISSUE THREAD

**Issue by Bernard512** [ChrisAnd1998/TaskbarX#507]
Every time i restart or reboot my PC, the settings in TaskbarX configurator keep changed. Even though I have click "apply" in TaskbarX Configurator. 

Please help me to fix this

**Comment by Maruthi18** [comment]
Same here

**Comment by TheOddHacker** [comment]
Same

**Comment by TheOddHacker** [comment]
> Every time i restart or reboot my PC, the settings in TaskbarX configurator keep changed. Even though I have click "apply" in TaskbarX Configurator.
> 
> Please help me to fix this

so i was messing around with the command prompt and i think i fixed it

First of all go to TaskbarX configurator and uninstall it
Then you need to go to command prompt with admin access (press win+s and type cmd then open it with admin rights)
In cmd type `SCHTASKS` an a list will appear, go to the beginning of it an look for a task like "TaskbarX [pcname][username]"
Copy it and then type `SCHTASKS /DELETE /TN "TaskbarX [pcname][username]"` the quotations marks need to be there
Then open up TaskbarX configurator and the settings should be back to default and wen you set it up againd press aply and it should be fixed
Good luck :)

**Comment by Maruthi18** [comment]
translucent from microsoft store

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
