### ISSUE TITLE
TaskbarX causing taskbar to not work properly after booting

### ISSUE THREAD

**Issue by TheCyberDragon7** [ChrisAnd1998/TaskbarX#508]
Describe the bug:
Recent versions of TaskbarX seem to cause the taskbar to not work properly for several minutes after booting. During this time, my web browser, Opera, also doesn't work properly. However, everything else seems to work properly.

To Reproduce:
Power off your computer with TaskbarX installed, and then power your computer back on. (I'm not sure if this issue is unique to me, so you might not be able to replicate it)

Expected behavior:
The taskbar should function within a few seconds after booting.

Desktop:
 - OS: Windows 10
 - Version: 1909

Additional context:
One time, when I booted my computer, TaskbarX failed to run due to being outdated. This caused the Taskbar to operate normally.

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
