### ISSUE TITLE
Option to make the taskbar blur/acrylic or any of the others when apps are open that are fullscreen.

### ISSUE THREAD

**Issue by LiamAmsdorf** [ChrisAnd1998/TaskbarX#509]
I don't really like how I can have the taskbar transparent when I have apps open that are fullscreen like discord and google chrome it just kinda annoying.

Can u make an option on the settings page that allows users to set the taskbar to acrylic/blur or opaque when they have fullscreen apps open.

**Comment by ChrisAnd1998** [comment]
@LiamAmsdorf Currently you can use the option "Switch back to default on maximized window" option. This will turn the taskbar style back to normal when a windows maximized. I am planning to add the other styles too later.
![Untitled](https://user-images.githubusercontent.com/50437199/103748257-1d80be80-5004-11eb-8c12-3168ca1bcb54.png)

**Comment by LiamAmsdorf** [comment]
@ChrisAnd1998 oh i didnt realise that kk that's perfect for me thanks
