### ISSUE TITLE
Taskbarx very laggy when using multiple monitors.

### ISSUE THREAD

**Issue by Jusp3** [ChrisAnd1998/TaskbarX#510]
**Describe the bug**
When i open a game in fullscreen the taskbar goes crazy on second and primary monitor like in the video that i linked.
Even if the fullscreen game is same resolution with the desktop.

**Expected behavior**

**Screenshots**
Video about it.   v
https://user-images.githubusercontent.com/75336354/103819697-9703c580-5073-11eb-8d4d-ef4965977c83.mp4

**Desktop:**
 - OS: Windows 10
 - Version 20h2

**Comment by ChrisAnd1998** [comment]
Some games like to reset the taskbar and i have no idea why. This one seems to do it constantly... However under the "Extra" tab inside the Configurator there is an option "pause looper on fullscreen app". You can use that for now until i find out a better solution..
