### ISSUE TITLE
Icons scrolling out of the screen

### ISSUE THREAD

**Issue by luciferismyothername** [ChrisAnd1998/TaskbarX#511]
**Describe the bug**
The icons on taskbar scroll to then center and then they scroll out of the screen to the right to the point that they are invisible.

**To Reproduce**
1. Turn on TaskbarX 
2. The icons scroll off the screen.

**Expected behavior**
The icons are supposed to be centered

**Screenshots**
![image](https://user-images.githubusercontent.com/37019745/103908918-13a4ab80-5129-11eb-8866-c5456c593767.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Version: 20H2

**Additional context**

https://user-images.githubusercontent.com/37019745/103909988-574be500-512a-11eb-9433-835734bfe032.mp4

**Comment by ChrisAnd1998** [comment]
Can you try this? https://github.com/ChrisAnd1998/TaskbarX/releases/tag/1.6.8.0

**Comment by Yawhou** [comment]
Hi, I'm having the same issue, until yesterday everything was fine, then this problem suddenly occurs on my Windows10 pc as well today, tried other older versions of TaskbarX, same problem occurs, suspecting that it is something to do with Windows10? But I have no idea how to fix it, tried using offset, to bring the icons back to center, but after that the icons won't automatically recenter when new icons are added to the taskbar.

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
