### ISSUE TITLE
Flickering After closing window

### ISSUE THREAD

**Issue by Avni2000** [ChrisAnd1998/TaskbarX#512]
**Describe the bug**
Basically whenever I close a window that isn't pinned to the taskbar, all my windows (on the taskbar) "move around back and forth quickly" for lack of a better word

**Expected behavior**
Not flicker and just align normally I suppose

**Desktop (please complete the following information):**
 Windows 10 Home

**Comment by ManuDevil** [comment]
Same problem here.

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
