### ISSUE TITLE
Problem starting windows

### ISSUE THREAD

**Issue by ericksantiago2001** [ChrisAnd1998/TaskbarX#514]
When I installed the program everything was fine, after a few days the problem of the image appeared, so I used the uninstall button of the application and restarted, even without the program installed the error continued to appear. I reinstalled it and the error still persists. Any solution?

I have windows 10

![136949827_734718150482037_1288785849839406698_n](https://user-images.githubusercontent.com/77167075/104046508-cfa3bc00-51a5-11eb-9380-a507259b5295.jpg)

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
