### ISSUE TITLE
Custom order of icons lost on changing virtual desktop and back

### ISSUE THREAD

**Issue by MikeWeiZhou** [ChrisAnd1998/TaskbarX#515]
**Describe the bug**
The custom order of icons (manually dragging icons into their position - so I can use hotkeys WIN+1, WIN+2, ...) are lost when I change to another virtual desktop (CTRL + SHIFT + ARROW) and back.

**To Reproduce**
1. Create a new virtual desktop (WIN + TAB, then click "New Desktop" on top left of monitor)
2. You should now have two virtual desktops, can be switched with hotkeys CTRL + SHIFT + LEFT or RIGHT
3. Open three different applications (so three icons will show in taskbar) in desktop 1
4. Manually re-order the icons by dragging them in the taskbar
5. Remember the current icon order
6. Switch to desktop 2, and then back to desktop 1 (CTRL + SHIFT + LEFT or RIGHT)
7. Notice the icon order has been reset

**Expected behavior**
The icon order should have remained the same before and after switching virtual desktops.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 19042.685

**Additional Context**
I use and rely on hot keys heavily, so the order of icons would make or break my workflow.

Thanks very much for this tool, helps a lot when you have a 43" TV as a monitor. =)

**Comment by MikeWeiZhou** [comment]
Sorry, I made a mistake.

Default behavior in windows when changing desktops is like this. Arrggggg....

Please close this issue.

**Comment by ChrisAnd1998** [comment]
@MikeWeiZhou Allright 👍
