### ISSUE TITLE
Console popped up after booting

### ISSUE THREAD

**Issue by WZ-Tong** [ChrisAnd1998/TaskbarX#516]
**Describe the bug**
A cmd console popped up after booting. Showing software log and need to be closed manually.

**To Reproduce**
**Version:** 1.6.4.0, Microsoft Store
**OSVer:** Windows 10 Insider Preview (Dev) 2004 **Build** 21286.1000
**Steps:** Have it installed and just boot

**Comment by WZ-Tong** [comment]
![QQ截图20210109233706](https://user-images.githubusercontent.com/77199564/104095794-be83a980-5290-11eb-872f-9bcf11e3dd6e.png)

**Comment by WZ-Tong** [comment]
**Reason I found**
On Task Scheduler, the command includes **-console**
But I can't remove it manually for an alert **One or more specified arguments not valid**

**Comment by ChrisAnd1998** [comment]
@WZ-Tong you can turn of the console under the "About" tab inside the Configurator.

**Comment by WZ-Tong** [comment]
> @WZ-Tong you can turn of the console under the "About" tab inside the Configurator.

Problem Solved, thanks!

**Comment by ChrisAnd1998** [comment]
Allright 👍, no problem 😁
