### ISSUE TITLE
Changes the way its settings store

### ISSUE THREAD

**Issue by WZ-Tong** [ChrisAnd1998/TaskbarX#517]
Save settings in files and if there are not additional command when starting, load the saved file.
So we can open it directly from windows search or other quick start app

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
