### ISSUE TITLE
apps shirnk down to scrollbar leaving space upside when taskbar is on left or right of desktop

### ISSUE THREAD

**Issue by sujeet-agrahari** [ChrisAnd1998/TaskbarX#518]
When I place taskbar to the right or left, It shrinks down leaving space on top and a horizontal scroll bar appears.

It happens in below cases:

1. When I open any app from system tray icon
2.  When some notification pops on any opened app

https://user-images.githubusercontent.com/22151975/104114938-f4c43600-532f-11eb-9d4f-77da22dd19c2.mp4

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
