### ISSUE TITLE
Can't Open TaskbarX Configurator application, stuck on middle app icon taskbar

### ISSUE THREAD

**Issue by DoniJR96** [ChrisAnd1998/TaskbarX#520]
**Describe the bug**
I can't open TaskbarX Configurator.exe (both X86 and X64 version). It just stuck like nothing happening, but the taskbar app icon is on middle.

I use the latest version of TaskbarX (1.6.4.0)
My device is Surface Pro 4 (Core i5/8/256)
Please help me to fix this issue. Thanks

**Comment by byuhtu** [comment]
yeah i got the same problem

**Comment by Leidenschaftlich** [comment]
I brought it from the store hoping it would fix the issue - which it didn't - it keeps opening for 2 - 3 seconds and is blurry and crashes

**Comment by ChrisAnd1998** [comment]
This could be fixed now in 1.6.7.0.

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
