### ISSUE TITLE
Hide Start Menu logo

### ISSUE THREAD

**Issue by mattiasghodsian** [ChrisAnd1998/TaskbarX#521]
Am using PowerToys Run as a replacement for the Win start menu and would like to get an option to hide the Win logo in the taskbar.

![PowerToy](https://i.gyazo.com/14a2a2587556fcceba59539b79315f21.png)

**Comment by ChrisAnd1998** [comment]
@mattiasghodsian You can already hide the start button. The setting is under the "Extra" tab inside the Configurator.

**Comment by mattiasghodsian** [comment]
> @mattiasghodsian You can already hide the start button. The setting is under the "Extra" tab inside the Configurator.

Oh great, thanks :)
