### ISSUE TITLE
Transparent style not working as intended.

### ISSUE THREAD

**Issue by Snowiseverything** [ChrisAnd1998/TaskbarX#522]
**Description:**
after setting up TaskbarX for the first time, everything works fine except for Style, I can't change it nor they make any difference after I change the Style.

**To Reproduce**
There are no steps to reproduce except for checking **Styles**

**Expected behavior**
I expected the Style to change from default to transparent (show the desktop background) but none of the Style options work for me.

**Screenshots**
Here are some images on the desktop, as I don't know if the transparency is in apps or on the desktop.
![image](https://user-images.githubusercontent.com/77357336/104363614-7aa9d200-5526-11eb-9a58-8f73111f286d.png)
![image](https://user-images.githubusercontent.com/77357336/104363666-957c4680-5526-11eb-88ac-ca83aa0460c6.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Version 20H2 (OS Build 1902.685)

**Additional context**
Would be grateful if you looked into the issue or tell me any fixes that are there, also describe some of the options like Animation options because you don't understand what do they do. Thank you.
Best regards, Snow.

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
