### ISSUE TITLE
Will not boot up after download

### ISSUE THREAD

**Issue by TeacherMartin** [ChrisAnd1998/TaskbarX#524]
I have downloaded it but it wont boot up

I found the app through tiktok, and i liked how clean it looked. I also saw that you could make it transparent. But now that I have baught it, it wont start, so I only have it on my computer now.

 - OS: Windows 10 Home
 - Version: 2004

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
