### ISSUE TITLE
Menu not working

### ISSUE THREAD

**Issue by bor12** [ChrisAnd1998/TaskbarX#525]
**TaskbarX works but menu cannot me opened**

**To Reproduce**
I don't know how to get it back

**Expected behavior**
in the task menu there is no TaskbarX settings icon
**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Version 20H2 Bootcamp edition

**Additional context**
not working at startup. maybe incorrect installation

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
