### ISSUE TITLE
Auto-hide taskbar issue.

### ISSUE THREAD

**Issue by Aharper9917** [ChrisAnd1998/TaskbarX#528]
I have my taskbar set to auto hide, and I have a secondary monitor that is above my primary monitor. When I connect my secondary monitor the taskbar hides as intended, but when it hide the transparent/blurred bar falls onto my primary monitor. This leaves a burred bar on the top part of the primary screen, covering things like Chrome tabs and the min, max, and close buttons on my windows. 
My work around has been to open TaskbarX and restart it. This issue occurs every time I reconnect my HDMI cable to my laptop.
![image](https://user-images.githubusercontent.com/53236834/104622435-7bd61e80-564e-11eb-9f67-36f77c0b80af.png)

**Comment by Osyx** [comment]
You should close your duplicated issues, #526 and #527 which are basically the same as this one (#528).

**Comment by Aharper9917** [comment]
Odd, I didn't realize this posted multiple times

**Comment by ChrisAnd1998** [comment]
@Aharper9917 No problem, i closed them for you. I get back to you when i have some time...

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
