### ISSUE TITLE
[Feature request] center startbutton (experimental)

### ISSUE THREAD

**Issue by leminsc8er** [ChrisAnd1998/TaskbarX#529]
**Is your feature request related to a problem? Please describe.**
alternative start button

**Describe the solution you'd like**
this alternativ startbutton can set as shortcut on startbar optional if you have hidden startbar.
if you set true you can center the shortcut between your apps and set owen icon if you want.
if you click on shorcut open a command the startmenü.
https://i.imgur.com/evHetQ3.pngalterantive to https://github.com/ChrisAnd1998/TaskbarX/issues/421

**Describe alternatives you've considered**
if you set true "hide startbutton" and replace as shortcut between your centered apps.
1. hide startbutton
2. select icon or use original
3. creat shortcut to start

**Additional context**
this will better than windows 10 x

**Comment by MattPeter97** [comment]
This would be amazing.

**Comment by NdR91** [comment]
Really cool!

**Comment by yusufekerdiker** [comment]
Changing the start button icon would be awesome!

**Comment by leminsc8er** [comment]
1. Creat "Windows"-Dialog command as Desktopshortcut. Optional add Favicon.
2. Pin it centered into Startmenü.

**Comment by BakoBitz** [comment]
Just wanted to bump up this feature request. I check back on this forum every week or two, hoping Chris will have taken up centering the Start button (and the Start menu, when it's launched). Would really be amazing not just to emulate Windows 11, but better than 11, to be able to move that button wherever you like among the centered taskbar icons. And have the Start menu appear in the right place. Hope it's on the to-do list, and thanks to Chris for considering it.
