### ISSUE TITLE
Task schedule is not working

### ISSUE THREAD

**Issue by marroux** [ChrisAnd1998/TaskbarX#532]
**Describe the bug**
not working on startup

**Desktop (please complete the following information):**
 - OS: Windows 10 home edition (20H2) x64
 - Version 19042.746

**Additional context**
I had previous bug which was fixed with the update 1.6.4.0 

- [ ] (https://github.com/ChrisAnd1998/TaskbarX/issues/461)

now the only problem i seem to have is that the task schedule is not starting up the taskbar.

**Comment by ChrisAnd1998** [comment]
@marroux You can try increasing the delay of the task schedule inside the Configurator. That may fix the issue.

**Comment by marroux** [comment]
thanks for the fast response, appreciate your work.
tried 30 seconds and 45 seconds, still didnt fix the issue.

**Comment by ChrisAnd1998** [comment]
No problem ;),
Can you see if it is even created?
In your startmenu search for "Task Scheduler". On the left menu click on "Task Scheduler Library". In the middle a list will appear. And see if a TaskbarX entry is there...

**Comment by marroux** [comment]
it wasn't even created, searched also in different folders in task scheduler library.
tried creating it now again, didnt find any new entry,

**Comment by ChrisAnd1998** [comment]
It should look like this:
![Untitled](https://user-images.githubusercontent.com/50437199/104927188-655afa80-59a1-11eb-9e27-5d773c53878f.png)

What happens if you run the Configurator as Adminstator and hit Apply?

**Comment by marroux** [comment]
i put the configurator to run as Administrator as default..
i found the entry in Task scheduler enabled, i restarted, still didn't start up.
checked the task scheduler again after restart, the entry was still there.

**Comment by ChrisAnd1998** [comment]
If you scroll to the right until "Last Run Result" what does that say?
![Untitled](https://user-images.githubusercontent.com/50437199/104929764-98eb5400-59a4-11eb-8cee-a8789e8a04e7.png)

**Comment by marroux** [comment]
the requested operation requires elevation. (0x800702E4)

**Comment by ChrisAnd1998** [comment]
So it seems to have issues with permissions. It want's to run as Admin.
Can you try again without running the Configurator as Admin. And give me the "Last Run Result" again?

**Comment by marroux** [comment]
these are the steps that i followed:
1) exported the xml file before making any change in case you need it.
2) tried to remove the task scheduler through the configurator, didnt remove, so i deleted it manually.
3) created it without running configurator as admin.
4) restarted, worked :)

**Comment by ChrisAnd1998** [comment]
Great! I think the one that gave the issue was also created using Administrator and so can only be overwritten or removed with Administrator... On logon it can't run elevated so it wouldn't allow the schedule to run. If you then use the Configurator without Admin the elevated schedule can't be overwritten. Anyway... I'm glad it's fixed! :)
