### ISSUE TITLE
my app icons disappear to the left

### ISSUE THREAD

**Issue by gordopijudo777** [ChrisAnd1998/TaskbarX#534]
**Describe the bug**
this is my first time using this app and after i launched it, i noticed that the apps on my taskbar moved to the left and i can't see them, i only see the first 3 apps and the rest are like "hidden".

**To Reproduce**

**Expected behavior**
use the taskbar centered with any problem

**Screenshots**
this is my normal taskbar [https://prnt.sc/xgshtm](url)

and this is my taskbar when i use TaskBarX [https://prnt.sc/xgsiuw](url)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro N
 - Version 20H2
 
**Additional context**
 I tried then moving the position of the taskbar, and i could see them, but if i do that the apps are not centered.

**Comment by ChrisAnd1998** [comment]
Can you try this? https://github.com/ChrisAnd1998/TaskbarX/releases/tag/1.6.8.0

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
