### ISSUE TITLE
i cant uninstall taskbarx

### ISSUE THREAD

**Issue by joey140** [ChrisAnd1998/TaskbarX#535]
When i open taskbarx configurator and i went to uninstall and clicked the button but it did not work and my taskbar icons are still in the middle

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
