### ISSUE TITLE
When I restart the computer for a few seconds, tarskbarx does not run normally

### ISSUE THREAD

**Issue by RainMz** [ChrisAnd1998/TaskbarX#541]
**Describe the bug**
After restart, log in to the desktop, and then you can see that tarskbarx is running normally: the taskbar icon lives, and the color is transparent; but after a while, the icon still lives, but the taskbar color becomes the default color instead of transparent

**To Reproduce**
1. Go to 'restart'

**Expected behavior**
Tarskbarx can be started normally after each restart, and the display is normal

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Version [e.g. 20H2]

**Additional context**

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
