### ISSUE TITLE
Animation?

### ISSUE THREAD

**Issue by Coding-Mole** [ChrisAnd1998/TaskbarX#545]
Just a question, what do the animations actually do? I have set it to quarteaseoutin but don't see any changes anywhere.
Can you please tell me what the animation animates and when it does that please!
Thanks!

**Comment by ChrisAnd1998** [comment]
It animates the taskbar icons to their new position.
https://streamable.com/x6npf2

**Comment by Coding-Mole** [comment]
Thank you
