### ISSUE TITLE
Suppress display of CMD window at startup

### ISSUE THREAD

**Issue by lty2008one** [ChrisAnd1998/TaskbarX#547]
The current startup mode is to use cmd.exe /C, this method will pop up a window lasting 0.2 seconds after boot.
Writing the command into a vbs script can effectively avoid this phenomenon, and almost no bugs.
This is the vbs script I used.
--------

> DIM objShell
> set objShell=wscript.createObject("wscript.shell")
> ret=objShell.Run("cmd.exe /C start shell:AppsFolder\40210ChrisAndriessen.FalconX_y1dazs5f5wq00!TaskbarX -tbs=2 -color=0;0;0;16 -tpop=100 -tsop=100 -as=cubiceaseinout -obas=cubiceaseinout -asp=300 -ptbo=0 -stbo=0 -lr=400 -oblr=400 -sr=0 -sr2=0 -sr3=0 -ftotc=1", 0, TRUE)

--------
Just generate a vbs script like this, then schedule this script file at user login could effectively clear that annoying black window.

**Comment by ChrisAnd1998** [comment]
You're right but the problem is that it requires TaskbarX to create a vbs file. This works however is problematic for the store version.

**Comment by ChrisAnd1998** [comment]
@lty2008one I found another way. store apps can enable a protocol which allows me to run taskbarx with an alias and parameters:
`explorer.exe taskbarx:"-tbs=0 -color=0;0;0;50 -tpop=100 -tsop=100 -as=cubiceaseinout -obas=cubiceaseinout -asp=300 -ptbo=0 -stbo=0 -lr=400 -oblr=400 -sr=0 -sr2=0 -sr3=0 -ftotc=1 -rzbt=1 "`
