### ISSUE TITLE
 Drag TaskbarX windows is really annoying (v1.6.6.0 animation)

### ISSUE THREAD

**Issue by chuwy2k** [ChrisAnd1998/TaskbarX#550]
To drag the TaskbarX Configuration windows causes a slow animation that is really annoying.

**To Reproduce**
1. Go to '%AppData%\TaskbarX' folder
2. Click on 'TaskbarX Configurator.exe'
3. Drag the TaskbarX Configuration window and move it.
4. Annoying, isn't?

**Expected behavior**
A typical MS-Windows animation of drag and drop should happen.

**Desktop (please complete the following information):**
 - OS: Windows 10 Home x64.
 - Version: 20H2
 - Notebook: Lenovo IdeaPad L340-15APITouch

**Additional context**
Windows default resolution (100% DPI) settings.

**Comment by ChrisAnd1998** [comment]
@chuwy2k Yep, firstly i couldn't reproduce on the latest insider preview. Then i installed the latest stable version of Windows 10 and now i see it's very laggy XD. I will have it fixed next update ;)

**Comment by tkielarbb** [comment]
I have never seen anything so cool 😆 When you move it a lot it's almost like a living creature 😛
