### ISSUE TITLE
Command prompt  window goes nuts when I apply or restart the app

### ISSUE THREAD

**Issue by senojp** [ChrisAnd1998/TaskbarX#551]
**Describe the bug**

**To Reproduce**
1. Go to 'TaskbarX Config' app
2. Click on 'apply or restart'
3. See error

**Expected behavior**
Normal restart or apply changes without crazy command line window

**Screenshots**
![image](https://user-images.githubusercontent.com/71344607/106928388-5cbc3100-66d0-11eb-9136-6f7b565828e5.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Build 21292.rs_prerelease.210108-1514

**Additional context**

**Comment by ChrisAnd1998** [comment]
@senojp Well, the output is normal. The console windows will only show if you enbaled the "Show Console" option inside the Configurator.

**Comment by senojp** [comment]
I see! Thanks for the quick response.

Best,

Ivan N.
