### ISSUE TITLE
This Error always appears after I  turn on the pc

### ISSUE THREAD

**Issue by Bernard512** [ChrisAnd1998/TaskbarX#552]
![image](https://user-images.githubusercontent.com/76986108/106985366-ab3efd80-67ac-11eb-8eca-c01a41b20cb8.png)
Why this error always appears after booting up the pc? How to fix this error please? .
 
error massage: 
The group or resource is not in the correct state to perform the requested operation

**Comment by weiguang0927** [comment]
Same question

**Comment by jasielrt95** [comment]
i have the same problem

**Comment by pjschulz3004** [comment]
I have the Same Problem has anyone found a solution?

**Comment by Bernard512** [comment]
Hi, i have the solution. Just run the taskbar configuration with "run with
administration"

**Comment by Bernard512** [comment]
Hi, i have the solution. Just run the taskbar configuration with
administrator.

**Comment by ChrisAnd1998** [comment]
You can try to increase the delay of the taskschedule to like 10 seconds or so... If that doesn't work use Administrator but that can cause writing issues with the settings :/
