### ISSUE TITLE
Peek option

### ISSUE THREAD

**Issue by lohith11** [ChrisAnd1998/TaskbarX#554]
Taskbar X is an great taskbar customization tool . I feel it would be amazing if the developer can add the peek option when we hover over the app in taskbar . That would be very helpful

**Comment by nicekiwi** [comment]
Doesn't Windows already support this via AeroPeek? 
![image](https://user-images.githubusercontent.com/738975/121848888-c7484200-cd3e-11eb-85b3-1daa3ede6e60.png)
