### ISSUE TITLE
Facing error related to transparency effect...

### ISSUE THREAD

**Issue by Moon4546X** [ChrisAnd1998/TaskbarX#555]
Whenever I Start my PC taskbarx runs but transparency effect doesn't apply automatically....

I want taskbarx to run properly on startup with all my saved settings.

I am attaching the screenshots of my settings

 - OS: Windows 10 Pro
 - Version 20H2

![Task Manager 11-02-2021 11_54_52 AM](https://user-images.githubusercontent.com/66619464/107607709-fdc26300-6c5f-11eb-8525-bd55e90b6bdb.png)
![TaskbarX Configurator 11-02-2021 11_54_10 AM](https://user-images.githubusercontent.com/66619464/107607712-fef39000-6c5f-11eb-9732-23dd1cb38172.png)
![TaskbarX Configurator 11-02-2021 11_54_17 AM](https://user-images.githubusercontent.com/66619464/107607713-ff8c2680-6c5f-11eb-9c17-cc5250d69b4d.png)
![TaskbarX Configurator 11-02-2021 11_54_22 AM](https://user-images.githubusercontent.com/66619464/107607714-ff8c2680-6c5f-11eb-8bbc-4b482f74b42e.png)

**Comment by AbdullahKhan25** [comment]
I've been having the same problem. My taskbar is set to transparent on fullscreen, but on startup always starts with the default opaque appearance. I have to then use the configurator and apply again.

**Comment by Emporioe** [comment]
I have the same problem thinking that having the app in my D disk was the problem but I moved it to C disk.
And present the same problem it is annoying to have to go and look for the application besides having to start one more application for this it is inconvenient otherwise fine fine

**Comment by ChrisAnd1998** [comment]
Does this happen with the latest version? You are running an older version...

**Comment by caris1st** [comment]
> Does this happen with the latest version? You are running an older version...

I'm using the latest version and I've been facing the same problem for months with the latest versions at all times. I always set the setting to transparent, but 50% of the time it starts with the default effect and I have to click restart TaskbarX to enable it.

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
