### ISSUE TITLE
Taskbar Icons disappear

### ISSUE THREAD

**Issue by PadPlay** [ChrisAnd1998/TaskbarX#559]
Mostly, when I (re-) start the computer, after 1-2 min all taskbar icons disappear on one monitor, on the other one they are still there. If I restart TaskbarX, they come back.

Thanks for your help

**Comment by ChrisAnd1998** [comment]
Can you try this? https://github.com/ChrisAnd1998/TaskbarX/releases/tag/1.6.8.0

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
