### ISSUE TITLE
Icon position reset after wake

### ISSUE THREAD

**Issue by CZonin** [ChrisAnd1998/TaskbarX#560]
**Describe the bug**
TaskbarX is set to center taskbar icons. After waking PC from sleep, taskbar icons will be left aligned and after some time or interaction, they will go back to being centered.

**To Reproduce**
1. TaskbarX settings shown in screenshots
2. Put PC to sleep
3. Wake PC
4. Icons will be left aligned.

**Expected behavior**
Taskbar icons will be centered after waking PC from sleep.

**Screenshots**
![Screenshot 2021-02-16 164301](https://user-images.githubusercontent.com/67965669/108125283-3efaae80-7076-11eb-8c60-7a6ab2d1065d.png)
![Screenshot 2021-02-16 164317](https://user-images.githubusercontent.com/67965669/108125284-3efaae80-7076-11eb-8c62-f6c704b0178a.png)
![Screenshot 2021-02-16 164330](https://user-images.githubusercontent.com/67965669/108125285-3efaae80-7076-11eb-9eb9-28291a345e18.png)
![Screenshot 2021-02-16 164343](https://user-images.githubusercontent.com/67965669/108125286-3f934500-7076-11eb-854c-6c99210a3034.png)
![Screenshot 2021-02-16 164355](https://user-images.githubusercontent.com/67965669/108125288-3f934500-7076-11eb-9df5-0464abd2b7e7.png)

**Desktop**
 - OS: Windows 10
 - Version: 20H2

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
