### ISSUE TITLE
Dragging configurator generates a major slowdown.

### ISSUE THREAD

**Issue by Potato22** [ChrisAnd1998/TaskbarX#563]
**Describe the bug**
Dragging the configurator window drastically slows down File Explorer

**To Reproduce**
1. Open TaskbarX configurator
2. Click on the top of the window then proceed to drag it along

**Expected behavior**
Dragging the configurator window should not impact or generate any slowdowns.

**Screenshots**
https://user-images.githubusercontent.com/39096741/108615910-3241d600-743b-11eb-9d50-6f384e403dc4.mp4
https://user-images.githubusercontent.com/39096741/108616047-7f727780-743c-11eb-8efb-56b283333cdd.mp4

**Desktop (please complete the following information):**
 - OS: Windows10 Pro for Workstations
 - Version 20H2

**Additional context**
Recently updating TaskbarX to the latest version which in the changelog mentioned some changes in the configurator UI, unfortunately, this appears to generate a bug.
[1.6.6.0]

**Comment by ChrisAnd1998** [comment]
Fixed in the latest pre-release ;)

**Comment by Potato22** [comment]
Ah, alright. Thank you!
