### ISSUE TITLE
Search Menu (Cortana) not appearing

### ISSUE THREAD

**Issue by kozloffj** [ChrisAnd1998/TaskbarX#566]
When I click the Start button and begin to type or hit the search/cortana icon, the dialog box does not appear. Let say I hit start, and type **Note** and hit enter, the Notepad application opens, so the dialog exists, but it is not appearing.

In my configuration, I have 3 screens, all 3 have Left position Taskbar, but all other configurations within TaskbarX is default configuration.

I am using the MS Store version of TaskbarX (1.6.6.0)

Thank you!
Jeff Kozloff

**Comment by ChrisAnd1998** [comment]
@kozloffj Sorry, but i don't think this is caused by TaskbarX

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
