### ISSUE TITLE
Icons going crazy every few minutes!

### ISSUE THREAD

**Issue by oOII-J4HN-IIOo** [ChrisAnd1998/TaskbarX#567]
**Describe the bug**
At random (it seems to be every 5-10 minutes), TBX seems to refresh/reset the icon positions. When that happens, the icons start in their default position (next to the start menu icon), FLY off the right side of the screen, FLY back to the start button and start 'oscillating' towards the center of the taskbar. 

It's quite annoying, especially since when this happens, there's a very short pause during which my open windows don't respond to anything (mouse clicks/drags, typing etc.). It's also a visual distraction from when I'm trying to focus!

I have my taskbar centered and "Blur" effect turned on. Everything else is default, I believe.

**To Reproduce**
I'm not exactly sure WHAT is producing this problem in the first place... If I were to guess, maybe opening the start menu? Or opening a new window? The only thing I'm sure of is that it's because my icons are centered.

**Expected behavior**
The taskbar icons wildly oscillate across the taskbar and eventually settle back down to the center. Sometimes it flickers, too...

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Version [e.g. 1909]

**Additional context**

**Comment by fireundubh** [comment]
I experience this issue, too. Might be a regression of #30 and #283.

**Comment by daniel-evans007** [comment]
> **Describe the bug**
> A clear and concise description of what the bug is.
> At random (it seems to be every 5-10 minutes), TBX seems to refresh/reset the icon positions. When that happens, the icons start in their default position (next to the start menu icon), FLY off the right side of the screen, FLY back to the start button and start 'oscillating' towards the center of the taskbar.
> 
> It's quite annoying, especially since when this happens, there's a very short pause during which my open windows don't respond to anything (mouse clicks/drags, typing etc.). It's also a visual distraction from when I'm trying to focus!
> 
> I have my taskbar centered and "Blur" effect turned on. Everything else is default, I believe.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> I'm not exactly sure WHAT is producing this problem in the first place... If I were to guess, maybe opening the start menu? Or opening a new window? The only thing I'm sure of is that it's because my icons are centered.
> 
> **Expected behavior**
> A clear and concise description of what you expected to happen.
> The taskbar icons wildly oscillate across the taskbar and eventually settle back down to the center. Sometimes it flickers, too...
> 
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> 
> **Desktop (please complete the following information):**
> 
> * OS: [e.g. Windows 10]
> * Version [e.g. 1909]
> 
> **Additional context**
> Add any other context about the problem here.

Yeah same here, it's annoying, but I love TaskbarX too much.

**Comment by ChrisAnd1998** [comment]
Can you try this? https://github.com/ChrisAnd1998/TaskbarX/releases/tag/1.6.8.0

**Comment by oOII-J4HN-IIOo** [comment]
> Can you try this? https://github.com/ChrisAnd1998/TaskbarX/releases/tag/1.6.8.0

I think my TBX is installed via the Microsoft Store. And I don't think the pre-release is available from there, so I'd rather wait until the next full release and see if it has been fixed.

I did notice that it happens almost never now that I don't use an additional monitor (I'm using a laptop).  So additional monitor taskbar refreshes must be the problem!

**Comment by ChrisAnd1998** [comment]
@oOII-J4HN-IIOo Allright, there are more reports about this issue and someone else just confirmed it's fixed. So we will see ;)

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
