### ISSUE TITLE
Option to let start button and tray area appear when needed

### ISSUE THREAD

**Issue by gaemarkus** [ChrisAnd1998/TaskbarX#568]
**Is your feature request related to a problem? Please describe.**
I really like the clean look of the taskbar when the start button and the tray area are hidden. Having nothing but the cantered icons looks very clean and reminds me of the macOS dock. It's not an option for me though to keep them hidden, as I regularly use the start button and most of the tray area stuff in my regular workflow.

**Describe the solution you'd like**
There could be an option to make both areas reappear when hovering your cursor over the areas or alternatively when the cursor is anywhere on the taskbar.

**Describe alternatives you've considered**
I guess you could make the icons invisible. They don't actually have to be gone like they are in the current hidden mode.
It would be cool though when they'd also have animations like coming in from the bottom or the sides.

**Comment by Kiejo3** [comment]
(did not mean to thumb down) - good suggestion
