### ISSUE TITLE
Animation style "none" is not instant

### ISSUE THREAD

**Issue by CAKyPA** [ChrisAnd1998/TaskbarX#569]
Current animation style "none" is not exactly same as default Windows animation/behaviour.

New icon appears in taskbar instantly, but issue is some delay later it re-positions. Same with any animation speed.

What I'm looking is when button appears that already re-positioned.

From my look disabling entire Animations will make perfect Taskbar X to me, but not sure if it's possible in code.

**Comment by ChrisAnd1998** [comment]
@CAKyPA Sadly there is a delay before icons get recognized... The none animation already bypasses the whole animation part of TaskbarX.

**Comment by CAKyPA** [comment]
Got it, maybe it's possible to implement the icons get recognized instantly?

Currently using StartIsBack++ and taskbar icons appearing/disappearing instant perfectly.
Wanted to change from StartIsBack++ (using default Start Menu) to Taskbar X.
But this issue is holding me back.

**Comment by ChrisAnd1998** [comment]
@CAKyPA I understand. The difference is that StartIsBack uses dll injection which i want to avoid using.

**Comment by CAKyPA** [comment]
Ah okay,
Good luck!
