### ISSUE TITLE
Taskbar disappear

### ISSUE THREAD

**Issue by fxzxmicah** [ChrisAnd1998/TaskbarX#570]
**Describe the bug**
In rare cases, the taskbar will disappear(including from the ALT + tab menu) directly after running the full screen application .

**To Reproduce**
1. Run a full screen app
2. Switch to another virtual desktop
3. The taskbar disappears

**Screenshots**
![image](https://user-images.githubusercontent.com/48860358/109493153-07a0ee80-7ac7-11eb-826a-39a5a14e1f53.png)
![image](https://user-images.githubusercontent.com/48860358/109493233-24d5bd00-7ac7-11eb-86e8-672964f79ce3.png)
![image](https://user-images.githubusercontent.com/48860358/109493269-315a1580-7ac7-11eb-94e2-5815e04561e1.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 20H2

**Additional context**
The probability of this bug is very low, and the full screen application I'm running is a game, which takes up a lot of computer resources.

**Comment by fxzxmicah** [comment]
My taskbar is on the top of the desktop.

**Comment by Alempsar** [comment]
Buen día, lo mismo me sucede desde hace unos días, se ejecuta la app, pero los iconos aparecen un momento y desaparecen, tuve que poner "No centrar en la barra de tareas" para que estén en una esquina.
Alguna solución?

**Comment by Alempsar** [comment]
No centrado
![image](https://user-images.githubusercontent.com/76707354/109500532-5ff2d480-7a64-11eb-8451-eaa4713a2449.png)
Centrado
![image](https://user-images.githubusercontent.com/76707354/109500637-7d27a300-7a64-11eb-9266-73b339be3ba3.png)

**Comment by fxzxmicah** [comment]
@Alempsar It's not the same as the problem on my computer.
@ChrisAnd1998 Do you have any status updates? It happened several times recently. Once it disappeared, I had to restart my computer to recover.

**Comment by ChrisAnd1998** [comment]
@fxzxmicah Sorry @fxzxmicah I have not been able to reproduce the issue :/

**Comment by fxzxmicah** [comment]
@ChrisAnd1998 Because it's rare, it doesn't often appear here too, but since the release of version 1.6.6.0, it has happened four to five times, all after switching virtual desktop when running high load tasks. The entire taskbar disappears directly from all virtual desktops, including the ALT + tab menu.

**Comment by Alempsar** [comment]
Hola

Tengo la ultima versión 1.6.6.0, desinstale y era un problema ya que mostraba un mensaje de que no encontraba la aplicación, tuve que restaurar Windows desde CERO y la aplicación funciona de nuevo.
Cuando le di reparar Windows, seguía el problema.
Pero ahora ya esta bien, solo que tengo que instalar de nuevo mis aplicaciones.

Alex Martin Pilco Saravia

De: Fxzx micah
Enviado: domingo, 14 de marzo de 2021 10:23
Para: ChrisAnd1998/TaskbarX
CC: Alempsar; Mention
Asunto: Re: [ChrisAnd1998/TaskbarX] Taskbar disappear (#570)

@Alempsar It's not the same as the problem on my computer.
@ChrisAnd1998 Do you have any status updates? It happened several times recently. Once it disappeared, I had to restart my computer to recover.

**Comment by mrgoodwin** [comment]
I run into this every day. I have to right-click the taskbar in Task View and select the option to "Show this window on all desktops" to get it to show up again.

**Comment by 8ryo** [comment]
I've got this issue too, seems to happen if you 1) have full screen apps running (for me I run the apps in a lower resolution), 2) if you have the taskbar on the top instead of the bottom and 3) Use virtual desktop.

**Comment by 8ryo** [comment]
Yep can confirm, lower resolution apps (i.e. running a game at lower resolution) + using Ctrl-Win-Left/RightArrow causes the taskbar to disappear.

Steps to reproduce:
1) Put Taskbar on top
2) In configurator, make sure taskbar has "blur" style on
3) Open up 2 or more Virtual desktops 
4) Put a lower resolution fullscreen app (e.g. Valorant at 1600x900) on one of them
4) Put a browser (e.g. Chrome) in another tab
5) Go into the full-screen app
6) Use Ctrl-Win-Left/RightArrow to change desktop
7) Taskbar disappears

(And for people wondering how to get it back, just hit Win on your keyboard, right click Windows Explorer and click restart :) )

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
