### ISSUE TITLE
The new acrylic used for configurator app is not acrylic

### ISSUE THREAD

**Issue by Cyberdroid1** [ChrisAnd1998/TaskbarX#573]
**Describe the bug**
The current acrylic used for side panel in Configurator app is not at all acrylic, but instead a blur.

**Expected behavior**
The previous acrylic was much much better than the current blur.

**Screenshots**

![image](https://user-images.githubusercontent.com/51435948/109780164-bdd21880-7c2c-11eb-8c03-94487eecfa91.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 20H2 19042.844
 - Version: TaskbarX 1.6.7.0

**Additional context**
Recently, the EarTrumpet dev fixed the issue of lag when moving the configurator window by disabling acrylic when the app window is moving, then turn on the acrylic when it has stopped moving.

**Comment by ChrisAnd1998** [comment]
@Cyberdroid1 That's a great solution! I indeed changed it to blur to stop the window lag. I will try Eartumpets solution.

**Comment by Pein1911** [comment]
where is v1.6.7.0 ? I'm getting windows lag :(

**Comment by ChrisAnd1998** [comment]
@Cyberdroid1 I actually decided to disable it completely.. Blur seems to have this issue too on different builds of Windows 10.

**Comment by Cyberdroid1** [comment]
Do try the EarTrumpet app's workaround :)

**Comment by ChrisAnd1998** [comment]
@Cyberdroid1 I did.. It's a nice solution however using blur   only lagged less.
