### ISSUE TITLE
Is slowing the explorer.exe(Desktop) when the configurator is opened 

### ISSUE THREAD

**Issue by Minecodes** [ChrisAnd1998/TaskbarX#574]
My system is an Windows 10 Pro with an AMD Radeon RX 560 Series and an Intel Core i5-9400 9-Generation.
When i move the window around, it's lagging(the window) and an second curser is visible.
The window itself is moving to the dragging possition and stops there and the second curser disappears.

[Video for the Window: https://youtu.be/-laM8Tk3-fc](https://youtu.be/-laM8Tk3-fc)

**Comment by ChrisAnd1998** [comment]
@Minecodes It's a bug that should be fixed in the pre-release 1.6.7.0.

**Comment by Minecodes** [comment]
Okay, try it

**Comment by Minecodes** [comment]
It works 👍
