### ISSUE TITLE
每次开机出现黑色窗口

### ISSUE THREAD

**Issue by Crush422** [ChrisAnd1998/TaskbarX#575]
![屏幕截图 2021-03-05 092526](https://user-images.githubusercontent.com/80078427/110053669-ce050780-7d94-11eb-9434-d35707ceb5c0.png)

Desktop
 - OS:  Windows 10
 - Version.20H2

**Comment by jruaaa** [comment]
你能关那个窗户，在Configurator里头，要把这个取消
![image](https://user-images.githubusercontent.com/32626650/110664296-1e58dc80-817c-11eb-97d3-0e2c617bc680.png)

对不起，我中文很差，还在学
