### ISSUE TITLE
TaskbarX Configurator Crash After Restart

### ISSUE THREAD

**Issue by cytsai1008** [ChrisAnd1998/TaskbarX#576]
**Describe the bug**
After I select Restart in TaskbarX Configurator, The TaskbarX was killed, but it didn't restart. And it also let TaskbarX Configurator crashed.

**To Reproduce**
1. Go to 'TaskbarX Configurator'
2. Click on 'Restart'
4. TaskbarX Configurator Crashed.

**Expected behavior**
TaskbarX should be restart and the icon on Taskbar should return to left and go center again. 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 20H2

**Additional context**
It's a little weird that the icon didn't return after I killed the TaskbarX.exe.

**Comment by jruaaa** [comment]
newest prerelease seems to fix this for me

**Comment by littlooo** [comment]
reinstall the old version
[
[TaskbarX 1.6.2.0.zip](https://github.com/ChrisAnd1998/TaskbarX/files/7174809/TaskbarX.1.6.2.0.zip)
](url)

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
