### ISSUE TITLE
[Feature request] Hide the taskbar when no window is maximized

### ISSUE THREAD

**Issue by SpacEagle17** [ChrisAnd1998/TaskbarX#577]
I use minimalistic wallpapers and the taskbar ruins the experience when I don't have any window maximized. I am suggesting to add a feature that let's the user decide to auto hide the taskbar (like in windows 10) but only when no window is maximized. People might ask: Why don't you enable the auto hide option from the windows settings? I use the taskbar for multiple things, such as showing my CPU and GPU temperature and usage (system tray icons) and it is useful for me to see that information when I am inside certain applications. But the taskbar ruins the minimalistic feel of my desktop background and when I don't have any application maximized, I don't need to see the taskbar or in my case, the CPU and GPU information.

**Comment by ErdeFB** [comment]
If you need an solution in the intermit, I use SmartTaskbar on my second computer to do what you described. Not sure if it works with TaskbarX, but doesn't hurt to try. It works with Start Is Back which interacts with the taskbar the very least. Hopefully mentioning this isn't against any rules here and if it is, my sincerest apologies. You can find the project right here on Github:

https://github.com/ChanpleCai/SmartTaskbar
