### ISSUE TITLE
Configurator crashes on attempting to restart TaskbarX

### ISSUE THREAD

**Issue by BoolCube** [ChrisAnd1998/TaskbarX#578]
I wanted the taskbar to be transparent, so I opened up the configurator. However, after setting Style to Transparent and clicking on Apple button, TaskbarX doesn't restart and the taskabr is stuck on acrylic. On attempting to restart the service after clicking Restart TaskbarX, the app freezes for a while and crashes. TaskbarX stops too, so the icons are stuck at the center.

OS version: Windows 10 Insider Preview 21327.1000

**Comment by jruaaa** [comment]
newest prerelease seems to fix this for me

**Comment by BoolCube** [comment]
yep it fixes the issue for me too
closing issue
