### ISSUE TITLE
1 of 2 Monitors Resets Taskbar after wake from "Hibernate"

### ISSUE THREAD

**Issue by PixelCrafterOS** [ChrisAnd1998/TaskbarX#579]
**Describe the bug**
When booting the computer out of hibernate with 2 monitors, only one of the monitors' taskbar seems to be effected by TaskbarX, the other appearing like the windows default. The icons on both monitors are centered, but only one of them has the customized background.

**To Reproduce**
1. Set Custom Appearance
2. Put Computer in Hibernate
3. Boot Computer
4. Log In
5. See Glitch

After Booting, to fix it I open TaskbarX configurator and hit "Apply", which seems to fix the issue.

**Expected behavior**
I expected both monitors to be set correctly after booting.

**Desktop (please complete the following information):**
 - Windows 10 Pro
 - 20H2

**Additional context**
I rarely shut down or restart my computer, I use "Hibernate" because it allows me to continue right where I left off. TaskbarX is set to launch with my computer.

**Comment by Collinormous** [comment]
I have 3 monitors, and experience the same behavior after the PC is woken from sleep. Only the monitor set as "main display" will retain the applied settings.

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
