### ISSUE TITLE
I have a black screen issue in bottom left side

### ISSUE THREAD

**Issue by Kushhu** [ChrisAnd1998/TaskbarX#581]
**Bug :** I Just Installed And when I set to transparent this block of black screen appears for all wallpapers No matter what I change to...

**Expected behavior**
I mean it should be perfect for all screen, Please help me with this

**Screenshots**
![Screenshot (202)](https://user-images.githubusercontent.com/80196960/111072313-0d9fc200-8500-11eb-8b1b-e6301c1bb4d2.png)
![Screenshot (203)](https://user-images.githubusercontent.com/80196960/111072489-d67de080-8500-11eb-8484-d9d4e2fb4c75.png)

**Comment by ChrisAnd1998** [comment]
@Kushhu Hmm, never seen that happen... Can you give more info about your Windows 10 installation?

**Comment by Kushhu** [comment]
**Windows 10 Home**
![image](https://user-images.githubusercontent.com/80196960/111113251-7c742e00-8587-11eb-9ddf-2c8f58c5efed.png)

**Comment by Kushhu** [comment]
I'm really sorry @ChrisAnd1998, I had Previously installed Lively Wallpaper so this was the reason.
Now its Fine
![image](https://user-images.githubusercontent.com/80196960/111268356-2e2c6100-8653-11eb-8994-bf2a1d2dcf04.png)

**Comment by ChrisAnd1998** [comment]
@Kushhu That makes sence.. thanks for letting me know :) I'll close this now.
