### ISSUE TITLE
Configurator does nothing

### ISSUE THREAD

**Issue by WagglyJupiter** [ChrisAnd1998/TaskbarX#582]
The configurator does absolutely nothing. Doesn't change color, position, animation, etc.

Nothing to reproduce. It simply doesn't work.

I expected it to work...

 - OS: Windows 10
 - Version 20H2 19042.867

Also extremely laggy and slow

**Comment by ChrisAnd1998** [comment]
@WagglyJupiter The window drag lag will be fixed next update. Are you able to run the TaskbarX.exe manually?
It should run with default settings.

**Comment by cpriyam49** [comment]
I am facing the same issue as stated by @WagglyJupiter , I try to make the taskbar transparent but it doesn't work...no setting in the configurator is getting reflected in the taskbar...
I have the exact same version of Windows 10 that is 20H2 19042.867 
Pls look into the matter.

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
