### ISSUE TITLE
Taskbar is not hidden in second monitor when using full screen app.

### ISSUE THREAD

**Issue by quyleanh** [ChrisAnd1998/TaskbarX#583]
**Describe the bug**
Taskbar is not hidden in second monitor when using full screen app.
The primary monitor is not affect. 

**To Reproduce**
1. Setup auto hide for taskbar
2. Run TaskbarX
3. Open an application with full screen mode on secondary monitor
4. Hover mouse to the place of taskbar

**Expected behavior**
Taskbar is not displayed

**Screenshots**
![image](https://user-images.githubusercontent.com/9365035/111273064-efec6d00-8665-11eb-82d3-1607ad4ad2ac.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 20H2 Build 19042.867

**Additional context**
N/A

**Comment by ChrisAnd1998** [comment]
I'm sorry @quyleanh but i think this is a bug in windows or the game itself.

**Comment by quyleanh** [comment]
I don't know. Because I have no issue like that before installing TaskbarX.

**Comment by ChrisAnd1998** [comment]
Can you try to turn off or uninstall TaskbarX to see if it still happens? I have been trying to reproduce it but iam unable to.

**Comment by quyleanh** [comment]
I checked. You're correct. It's seem the Windows bugs.
Could you implement feature to hide it in TaskbarX?

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
