### ISSUE TITLE
TaskbarX incorrectly centering or completely hiding all icons.

### ISSUE THREAD

**Issue by ghost** [ChrisAnd1998/TaskbarX#584]
![Issue](https://user-images.githubusercontent.com/80090253/111888624-52fa3e80-899b-11eb-9f3a-6fc503955a23.PNG)

This issue happens very often. Usually occurs when opening new applications and it needs to auto-center. Once you open the new application is will either not center and just default to original Windows location, or it will make all icons and opened programs completely disappear like it's been shoved off to the side.

Here is my system specifications, TaskbarX information, and other information that may be helpful:

**Version For TaskbarX: 1.6.7.0
Windows Edition: Home
Windows Info: Windows 10 v2004
RAM: 4GB
Processor: AMD Ryzen 3 3300U with Radeon Vega Mobile Gfx, 2100 Mhz, 4 Core(s), 4 Logical Processor(s)
Build Version: 10.0.19041 Build 19041
Type: x64-Based**

This has is a re-occuring problem that I run into when opening any application. Restarting TaskbarX does nothing. Restarting Windows results in the same auto-centering issue. Here is a few information on my TaskbarX configuration settings:

**Primary Taskbar Offset: 0px
Secondary Taskbar Offset: 0px
Skip Resolution: (0px, 0px, 0px)
Compensate Tray Clock: Disabled
Don't Center Taskbar: Disabled
Revert To Zero Beyond Tray: Enabled
Pause Loop When Fullscreen: Enabled
Update Taskbar Toolbars: Enabled
Refresh Rate: 400ms (Default?)**

Rest of the settings are default and haven't been touched in the "TaskbarX Configurator" program. Uninstalling and Re-Installing TaskbarX still results in the same problem after a few restarts. Here is a few more information for the guidelines you provided:

**Store or Regular Version: Regular
.NET Framework 4.8 Installed?: Yes.
Any Anti-Virus Software: Yes. Windows Defender, Malwarebytes. None which flag TaskbarX.
Third Party Tweakers?: No.
Reproduce?: Yes. Enable my settings and try opening some programs. Centering works but after a few opening programs it will start glitching out and failing to center properly.
Error Message?: None**

The priority for this issue is low. Most users may not run into this problem. It might be harder to reproduce for some users.

**Comment by ChrisAnd1998** [comment]
@noahhx1 for better performance TaskbarX calculates the width of the taskbar by looking for the first icon's left position and last icon's right position in the taskbar.
This can be tricky if the loopers refresh rate is set to fast. So let's try it the old way i did with FalconX. In 1.6.8.0 pre-release it goes through every icon inside the taskbar and add up the total width. This way taskbarX can just request the width of an icon instead of it's position which is more stable while the taskbar is moving or doing other stuff.

https://github.com/ChrisAnd1998/TaskbarX/releases/tag/1.6.8.0

**Comment by mlodytymus** [comment]
i have the same problem :((((((((((((((((((

**Comment by Vadimmercury** [comment]
Windows Pro 10 20H2 19042.867
Version For TaskbarX: 1.6.8.0

I have the same problem

**Comment by nauhygon** [comment]
I have the same problem. 

TaskbarX 1.6.8.0.

Windows 10 Pro (OS build 21354.1)

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
