### ISSUE TITLE
Taskbarx.exe "quarantined" by Panda Dome... 

### ISSUE THREAD

**Issue by peppeg** [ChrisAnd1998/TaskbarX#585]
**Describe the bug**
Cannot use the app. exe quarantined by PandaDome

![2021-03-21 15_58_33-Panda Dome](https://user-images.githubusercontent.com/12475181/111909657-776b1f00-8a5e-11eb-9ac6-ae1bfb534310.jpg)

How fix this?
Thanks in advance

**Comment by ChrisAnd1998** [comment]
I can send them a message about the false positive. For now just add it to the exclusions.
