### ISSUE TITLE
autoload does not work when Windows starts

### ISSUE THREAD

**Issue by suprunchuk** [ChrisAnd1998/TaskbarX#587]
**Describe the bug**
start WINDOWS 10

Выпуск	Windows 10 Pro
Версия	20H2
Сборка ОС	19042.868

autoload does not work when Windows starts

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
