### ISSUE TITLE
Transparency resets after restart.

### ISSUE THREAD

**Issue by Zare01** [ChrisAnd1998/TaskbarX#588]
TaskbarX does not apply transparency or blur effects on startup. Only puts the icons in the middle.

**To Reproduce**
I didn't do anything to cause this issue.

**Expected behavior**
On startup TaskbarX will center icons but wont apply "style" effects.

**Screenshots**
![Screenshot 2021-03-25 084005](https://user-images.githubusercontent.com/79867565/112435974-bd1d3580-8d45-11eb-8539-4cc8cce5d4e4.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10 Pro]
 - Version [20H2 (OS Build 19042.867)]

TaskbarX was downloaded thru the windows store but I got the same issue from the git hub version.

**Comment by haptiqblack** [comment]
I am also having the same issue. Today it just stopped working even uninstalled and reinstalled and still no success.

OS: [Windows 10 Pro]
Version: 10.0.19402 Build 19042

**Comment by haptiqblack** [comment]
> 
> 
> I am also having the same issue. Today it just stopped working even uninstalled and reinstalled and still no success.
> 
> OS: [Windows 10 Pro]
> Version: 10.0.19402 Build 19042

I ran remaining updates on my computer and it fixed the issue for me.

**Comment by CoolAbhi1290** [comment]
Can confirm this happens

**Comment by CoolAbhi1290** [comment]
Solution that worked for me:

Try restarting TaskbarX using theTaskbarX Settings (click the restart button). Do it a few times. I am not too sure what that does, but it seemed to fix my issue. And yes, it did work even after I restarted my computer.

**Comment by Tw3ak3rz** [comment]
I think you can fix this with my solution that worked for me and another individual, worth a shot.

https://github.com/ChrisAnd1998/TaskbarX/issues/651

I fixed my problem, in Task Schedular is a TaskbarX task that you can edit. Open Task Scheduler and locate the task "TaskbarX" and open/edit that task. Once opened click the Actions Tab then click Edit at the bottom. In the Arguments section, you will change the number -tbs=
Replace with whatever you prefer for the desired style you want, (see below).

Now it will remain as desired between restarts or shutdown.

In the event you want to change things, these are the settings.
-tbs=0 Default
-tbs=1 Transparent
-tbs=4 Transparent Gradient
-tbs=5 Opaque
-tbs=2 Blur
-tbs=3 Acrylic (can flicker)

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
