### ISSUE TITLE
TaskBarX doesn't starting after format

### ISSUE THREAD

**Issue by MichalMiotke** [ChrisAnd1998/TaskbarX#589]
Before format i have TaskBarX but then that was working but after Formating my computer i click TaskBarX configurator folder taskbarx doesn't starting

**Comment by ChrisAnd1998** [comment]
Maybe install .NET Framework 4.5 or 4.8

**Comment by MichalMiotke** [comment]
Where i can find it

**Comment by MichalMiotke** [comment]
I already have installed version 4.5

**Comment by MichalMiotke** [comment]
@ChrisAnd1998

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
