### ISSUE TITLE
Icon Position Constantly Resetting

### ISSUE THREAD

**Issue by CZonin** [ChrisAnd1998/TaskbarX#591]
**Describe the bug**
For awhile I've noticed that after waking my PC from sleep, my icon position would be left aligned instead of centered. I would have to interact with it in someway (ie. opening a program from the taskbar, opening start menu) or by just waiting 5-10 seconds to get the icons to center. After one of the recent updates though, I've noticed that the icon position is going back to left aligned any time I interact with something on the taskbar (opening start menu, opening tray, opening any program, etc).

**Expected behavior**
Icons will always be centered after waking from sleep, and will not left align after interacting with the taskbar in any way.

**Screenshots**
Can provide if needed.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 20H2

**Comment by CZonin** [comment]
Update: It seems to be related to having "Pause looper when fullscreen app is running" enabled.

**Comment by ChrisAnd1998** [comment]
Does this happen since version 1.6.8.0?

**Comment by Sachawech** [comment]
Still happens for me and I'm on 1.6.8.0.

I love this application by the way! Thank you so much for making it!

Cheers
;)

**Comment by sheauxdown** [comment]
Hi Chris! First off, just want to say I, too, love this software! It's such a beautiful aesthetic upgrade to Windows - thanks for developing it! In the same vein as @Sachawech , I've noticed that with build 1.6.8.0, the looper will pause when on battery if the focus shifts to the desktop aside from an open application and/or the taskbar/start menu. It does appear to be only linked to the "Pause while on fullscreen" option, but for me only appears to occur when I'm running on battery. I've uninstalled and reinstalled the software to account for a potentially bad update. To replicate, I just simply click on the desktop or use the show desktop shortcut (win+D), and the looper will pause. Hope this helps with any bug fixing!

**Comment by CZonin** [comment]
> Does this happen since version 1.6.8.0?

Ya I'm always on the latest version, but I was experiencing the wake from sleep issue for much longer. Both issues I described above (wake from sleep, and interacting with anything) seem to be related to that setting. Disabling the setting solves it. I haven't noticed any issues in games with it disabled so I'll just leave it off for now.

**Comment by ChrisAnd1998** [comment]
Allright, here is the first fix for the pause on fullscreen option. https://github.com/ChrisAnd1998/TaskbarX/releases/tag/1.6.9.0

**Comment by CZonin** [comment]
> Thx :)
> 
> @Sachawech @sheauxdown @CZonin
> Allright, here is the first fix for the pause on fullscreen option. https://github.com/ChrisAnd1998/TaskbarX/releases/tag/1.6.9.0

Working so far. I'll test it a bit more and report back.

**Comment by CZonin** [comment]
> Thx :)
> 
> @Sachawech @sheauxdown @CZonin
> Allright, here is the first fix for the pause on fullscreen option. https://github.com/ChrisAnd1998/TaskbarX/releases/tag/1.6.9.0

Okay so it seems to have completely solved the issue where the icon position resets when interacting with the taskbar. The other issue of the position being reset after waking from sleep is still there. After disabling "Pause looper when fullscreen app is running" the icons are centered after wake.

**Comment by krtpowa** [comment]
same here, version 1.6.8.0 ( Windows store ), fix on 1.6.9.0 ? wait for it, thanks ChisAnd1998

**Comment by Sachawech** [comment]
Hi!

The icons are still resetting here every time I switch desktop:

win + ctrl + →
---- & ----
win + ctrl + ←

**Comment by kirashi3** [comment]
I updated to 1.6.9.0 portable but still experience problems with the looper causing TaskbarX to repeatedly crash and restart over and over again to the point of causing my PC to slow to a crawl and File Explorer windows to have corrupt UI elements. This happened a day or 2 after updating to Windows 10 Version 20H2 (Build 19042.928).

Below is a screenshot of my system tray after TaskbarX repeatedly restarted itself. 😛 
![image](https://user-images.githubusercontent.com/5917227/115184314-6b40a480-a092-11eb-8e34-d68b7238dd56.png)

I did enable the **pause looper when fullscreen app is running** option, but no change. Went ahead and enabled the console to see if I could snag something useful for you @ChrisAnd1998, but if you've got a built-in method to output a logfile.txt let me know and I'll be happy to try getting an actual logfile over to you as soon as I can.
![image](https://user-images.githubusercontent.com/5917227/115184295-624fd300-a092-11eb-990d-eca1e269aea4.png)

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
