### ISSUE TITLE
Start icon comes back after Lock Screen

### ISSUE THREAD

**Issue by mertbakir** [ChrisAnd1998/TaskbarX#592]
**Describe the bug**

I hid the start (windows) icon on the task bar, and it works fine. App launches at start-up and apply the settings as I configured. Yet, when I use Win+L to lock screen. Not sleep, not log out, only lock screen.
After I unlock the session windows icon comes back.

**To Reproduce**
1. Go to "Extra" menu on the TaskbarX Configurator.
2. Mark "Hide Primary Start button"
3. And your other configurations. Apply.
4. The start button should be hidden.
5. Win+L to lock screen.
6. Sign back in.
7. You'll should see the start button.

**Expected behavior**

Start button configuration shouldn't be broken by the lock screen.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Version [e.g. 20H2 Build 19042]

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
