### ISSUE TITLE
Now i can't center my icons on taskbar D:

### ISSUE THREAD

**Issue by mlodytymus** [ChrisAnd1998/TaskbarX#594]
biblethump

**Comment by ChrisAnd1998** [comment]
Can you give me more info?
Did it happen after the latest version or are you a new user? 
Build of Windows 10?  

I need to understand what's going on to be able to fix it.

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
