### ISSUE TITLE
Monitor on and off turns off taskbarx

### ISSUE THREAD

**Issue by Lightje** [ChrisAnd1998/TaskbarX#595]
Hello, when using taskbarx i have 2 monitors. When the pc goes into sleep or i turn off the monitor manually and back on the primary monitor uses taskbarx settings like normal but the second monitor goes back to standard windows settings.

**To Reproduce**
1. Lets say you have transparent or blur task bar in the config and i apply it all works normally. On a two monitor setup
2.  Now turn off both monitors or the second monitor and turn them back on
3.  You will see that the second monitor isnt using taskbarx settings that you put in the config anymore but is using standard windows settings

**Expected behavior**
Okay so i'm using the blurry taskbar and have my icons centered on both monitors, but when i turn off the monitors and come back and turn them on i want to have the same settings  that i applied 

**Desktop (please complete the following information):**
 - OS:  Windows 10 Pro
 - Version 19042

**Comment by Lightje** [comment]
Fixed by unninstalling via configurator and reinstalling.

**Comment by prajmus** [comment]
I have the same exact issue. After monitors go to sleep from inactivity, taskbar on secondary monitor is reverted to standard Windows one.

OS: Windows 10 Pro
Version: 19044

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
