### ISSUE TITLE
Major problem in disabling TaskbarX

### ISSUE THREAD

**Issue by KrishnaThakar** [ChrisAnd1998/TaskbarX#596]
I deleted the taskbarX but forgot to disable it from taskbarX configurator. Now my icons stay in the middle :( please help me...

I tried reinstalling and disabling it but it is not working. alsothere are no TaskbarX files in my device

**Comment by pc-v2** [comment]
open File Explorer, then restart it from task manager

**Comment by pc-v2** [comment]
![image](https://user-images.githubusercontent.com/58063311/113461216-e4f75200-9445-11eb-80b9-e76c1e37e903.png)
also delete this task

**Comment by KrishnaThakar** [comment]
This solved my problem: I went to the task manager and opened the file location, the exe file was in Startup apps folder and I deleted them. If it fails to delete, make sure you have ended the task from the task manager...

Hope this helps :)
