### ISSUE TITLE
I can't open taskbarx configurator

### ISSUE THREAD

**Issue by Charlyputh** [ChrisAnd1998/TaskbarX#597]
When i try to open it, it just doesn't open

**Comment by MikaelPorttila** [comment]
TaskbarX version? 
Windows version?
Errors in the event log?
.Net version on the machine?
Installation source?
Anything?!

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
