### ISSUE TITLE
Second taskbar hides to the top of Monitor 1 (Stacked Monitors)

### ISSUE THREAD

**Issue by platinumgeo** [ChrisAnd1998/TaskbarX#598]
**Describe the bug**
On a stacked monitor setup, monitor 2's taskbar autohides to the top of monitor 1. This leaves the taskbar covering anything at the top of monitor 1.

**Screenshots**
Taskbar up
![image](https://user-images.githubusercontent.com/81707600/113189318-f9bfc400-9252-11eb-8146-70d5cb379183.png)

Taskbar down
![image](https://user-images.githubusercontent.com/81707600/113189336-017f6880-9253-11eb-8ef9-e92328e984ca.png)

**Desktop:**
 - OS: Windows 10
 - Version 20H2

**Comment by pyxelr** [comment]
I've got the same issue, and it seems that only the following styles cause this problem: _Gradient_, _Opaque_ and _Blur_.
Switching to _Default_, _Transparent_ or _Acrylic_ is a solution for the moment.

OS: Windows 10
Version: 20H2
TaskbarX version: 1.6.8.0

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
