### ISSUE TITLE
Toasters doesn't work when taskbarx is on

### ISSUE THREAD

**Issue by CUPZYY** [ChrisAnd1998/TaskbarX#599]
**Describe the bug**
Toastnotifications on win10 doesn't show when taskbarx is on with transparent taskbar

**To Reproduce**
do something that will make a toastnotification

**Expected behavior**
The notification actually showing

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 20H2

**Comment by ChrisAnd1998** [comment]
For now i disabled them as they where getting annoying..

**Comment by CUPZYY** [comment]
"It's not a bug, it's a feature" moment
