### ISSUE TITLE
Icons center to left and center after opening new app from the same group, with grouping disabled

### ISSUE THREAD

**Issue by ZuriPL** [ChrisAnd1998/TaskbarX#600]
**Issue**

I have icon grouping disabled. Whenever I open a new app from the same group that's already been opened all icons jump left w/o an animation and then go to the center with an animation. Doesn't happen with apps that weren't already present on the taskbar.

Video of the behaviour:
https://user-images.githubusercontent.com/56483363/113518916-8804b480-9589-11eb-8db0-bc8b63ac4d17.mp4

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
