### ISSUE TITLE
Whenever TaskbarX doesn't launch on startup, some other programs also don't launch on startup.

### ISSUE THREAD

**Issue by TheCyberDragon7** [ChrisAnd1998/TaskbarX#601]
If I remove the Taskschedule, or if TaskbarX has an error that prevents it from launching on startup, other programs such as Discord, WallpaperEngine, and iCUE will also fail to launch, despite launching on startup normally.

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
