### ISSUE TITLE
[wish] pause looper owen apps

### ISSUE THREAD

**Issue by leminsc8er** [ChrisAnd1998/TaskbarX#602]
**Is your feature request related to a problem? Please describe.**
Some Gamers Use Window-Mod. Pause Looper in Fullscreen does not work quick.

**Describe the solution you'd like**
 If you give optional a way to "pause looper for 1"h or give optional running apps.

**Describe alternatives you've considered**

**Additional context**
If you will ad "pause looper for 1h" in trayiconmenü it will be nice

**Comment by theFireProjet** [comment]
If TaskbarX creates some issues in combination with another program (a game or any other kind of full screen application), it would be useful if you could select that program in the configurator. TaskbarX could automatically disable centered taskbar icons while that specific program is running.

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
