### ISSUE TITLE
Taskbar X appearance Settings after every restart in Windows dark theme only.

### ISSUE THREAD

**Issue by AayushBoliya** [ChrisAnd1998/TaskbarX#603]
**Describe the bug**
The icon positions don't change, but the appearance settings change after every shut down. This didn't happen when I had Windows Light Theme, only after I enabled dark theme it started acting like this. 

**To Reproduce**
1. Go to TaskbarX configurator and set the appearance of your taskbar as you like. (1.6.8.0)
2. Set is as Startup Application.
3. Set Windows theme to Dark mode.
4. Shut Down or Restart your PC.
5. Taskbar icon settings don't change, but appearance change to (0,0,0,0) White.

**Expected behavior**
It should not reset it appearance and remain saved.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 20H2

**Comment by Mr-Anonymous75** [comment]
Acrylic turns to transparent in dark mode too.

**Comment by AayushBoliya** [comment]
Further discussion at #641
