### ISSUE TITLE
TaskbarX makes the pc completely frozen

### ISSUE THREAD

**Issue by M1lad7** [ChrisAnd1998/TaskbarX#604]
There is a weird bug in TaskbarX that causes my pc to completely freeze, I cannot do anything but completely shutting down my pc with the power button
I've only encountered this issue while playing games (league of legends)

The way it happens is that when I queue up and game launches (a new window starts) the window (the launched game) is not focused (the window is shown and it's full screen, it's just not focused), and when I click on it to focus on the window, boom the whole pc freezes

unfortunately my English isn't that great but I tried my best to explain it
btw I'm 100% sure TaskbarX is causing this issue, It only happens when TaskbarX is running

the only solution I found is that when the game launches, I alt tab, and then click the game icon on taskbar

I'm using windows 10

**Comment by NilsGke** [comment]
I have the same issue. My pc isn't that good so it happens when I open something like Chrome. When I stop taskbarx before opening something, everything is fine.

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
