### ISSUE TITLE
Add exceptions for browsers and custom list support for the "Pause looper when fullscreen" feature

### ISSUE THREAD

**Issue by siegmour** [ChrisAnd1998/TaskbarX#605]
**Is your feature request related to a problem? Please describe.**
The pause looper feature is great - it prevents issues while gaming or using other fullscreen applications. However, the problem is that it detects a browser in fullscreen mode, or even a fullscreen YouTube video as a fullscreen application. This causes the icons to very annoyingly constantly shift left to the start of the desktop when the looper is disabled if you click in the browser window or click on the video to pause it, and re-center when you click back in another window. I experience this scenario a lot on my dual monitors, where I often watch YouTube videos on my secondary screen.

**Describe the solution you'd like**
The simple solution would be to add an exception for most famous browsers - Firefox, Chrome, Edge, Opera and perhaps one-two more big ones. I think this should be done regardless if the optional solution below is implemented, since it affects the user-experience and the looper doesn't affect the browser performance, so there is no need to disable it while a browser is full-screen.

**Describe alternatives you've considered**
The optional solution is to as well implement a custom list of apps which the user can add and manage from the installed ones on his computer. It would be an amazing addition, since there are other apps which might run into the same scenario besides browsers.

The only alternative to this issue currently, is to disable the fullscreen looper. This is far from a good solution, since I also play a lot of games. You can as well keep the looper enabled, and manually exit TaskbarX before starting to game but this has two downfalls - often you might just forget and it is annoying.

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
