### ISSUE TITLE
Total Opacity does nothing

### ISSUE THREAD

**Issue by chrisbitmead** [ChrisAnd1998/TaskbarX#606]
Unless I'm missing something, the "Total Opacity" sliders do absolutely nothing.

I can change the opacity with the "Alpha" slider. I don't really get why there'd be an alpha slider AND an opacity slider, maybe I'm too dull to get it.

**To Reproduce**
Put in "Transparent Gradiant" mode, and play with Total Opacity Sliders.

**Expected behavior**
Something would change.

 - OS: Windows 10, latest patch level.
 - Version 10.0.19042 build 19042
 - Taskbarx 1.6.9.0

**Comment by konfuzius** [comment]
Hallo,
Same here.
After latest Windows 10 update and after starting **TaskbarX.exe** none of selected styles change the taskbar (but central position).
Only if you manually start **TaskbarX Configurator.exe**, change the style and click "Apply" and then and only then it changes,

**Comment by cursednebulous** [comment]
It does not work for me even if I manually open taskbar X configurator, make changes in "Style" and click apply. It does nothing.

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
