### ISSUE TITLE
TaskBarX Configurator

### ISSUE THREAD

**Issue by felipednegredo** [ChrisAnd1998/TaskbarX#607]
Bug
TaskBarX Configurator, don't open

To Reproduce
1. Go to 'TaskbarX_1.6.9.0_x64'
2. Click on 'TaskbarX Configurator.exe'
4. Don't open

Information Desktop :
 - OS: Windows 10 1909
 - Version TaskbarX 1.6.9.0

**Comment by BenQbtw** [comment]
before that open TaskbarX Configurator.application then click install and it should work

**Comment by felipednegredo** [comment]
### The problem that the installation also did not work, this is the error that appears:

INFORMATION ON PLATFORM VERSIONS
Windows: 10.0.18363.0 (Win32NT)
Common Language Runtime: 4.0.30319.42000
System.Deployment.dll: 4.8.4270.0 built by: NET48REL1LAST_C
clr.dll: 4.8.4341.0 built by: NET48REL1LAST_C
dfdll.dll: 4.8.4270.0 built by: NET48REL1LAST_C
dfshim.dll: 10.0.18362.1 (WinBuild.160101.0800)

ORIGINS
Deployment URL: file: /// C: /Program%20Files/TaskbarX_1.6.4.0_x64/TaskbarX%20Configurator.application
Application URL: file: /// C: /Program%20Files/TaskbarX_1.6.4.0_x64/TaskbarX%20Configurator.exe.manifest

IDENTITIES
Deployment Identity: TaskbarX Configurator.application, Version = 1.0.0.2, Culture = neutral, PublicKeyToken = 0000000000000000, processorArchitecture = amd64
Application Identity: TaskbarX Configurator.exe, Version = 1.0.0.2, Culture = neutral, PublicKeyToken = 0000000000000000, processorArchitecture = amd64, type = win32

APPLICATION SUMMARY
* Installable application.

SUMMARY OF ERRORS
A summary of the errors can be found below. The details of these errors are listed later in the log.
* Exception when activating C: \ Program Files \ TaskbarX_1.6.4.0_x64 \ TaskbarX Configurator.application. The following error messages have been detected:
+ File: /// C: / Program Files / TaskbarX_1.6.4.0_x64 / StoreLogo2-71.ico.deploy failed to download.
+ Could not find the file 'C: \ Program Files \ TaskbarX_1.6.4.0_x64 \ StoreLogo2-71.ico.deploy'.
+ Could not find the file 'C: \ Program Files \ TaskbarX_1.6.4.0_x64 \ StoreLogo2-71.ico.deploy'.
+ Could not find the file 'C: \ Program Files \ TaskbarX_1.6.4.0_x64 \ StoreLogo2-71.ico.deploy'.

SUMMARY OF COMPONENT STORAGE TRANSACTION FAILURE
No transaction errors were detected.

WARNINGS
* The manifest for this application does not have a signature. Validation of the hash signature will be ignored.
* The manifest for this application does not have a signature. Validation of the hash signature will be ignored.

STATUS OF THE OPERATION'S PROGRESS
* [16/04/2021 13:49:31]: The activation of C: \ Program Files \ TaskbarX_1.6.4.0_x64 \ TaskbarX Configurator.application has started.
* [16/04/2021 13:49:31]: Processing of the deployment manifest has been completed successfully.
* [16/04/2021 13:49:31]: The installation of the application has started.
* [16/04/2021 13:49:32]: Processing of the application manifest has been completed successfully.
* [16/04/2021 13:49:35]: Version 4.0.30319 of the compatible runtime was found.
* [16/04/2021 13:49:35]: The request for trust and detection of the platform has been completed.

ERROR DETAILS
The following errors were detected during this operation.
* [16/04/2021 13:49:35] System.Deployment.Application.DeploymentDownloadException (Unknown subtype)
- File: /// C: / Program Files / TaskbarX_1.6.4.0_x64 / StoreLogo2-71.ico.deploy failed to download.
- Source: System.Deployment
- Stack tracking:
in System.Deployment.Application.SystemNetDownloader.DownloadSingleFile (DownloadQueueItem next)
in System.Deployment.Application.SystemNetDownloader.DownloadAllFiles ()
in System.Deployment.Application.FileDownloader.Download (SubscriptionState subState, X509Certificate2 clientCertificate)
in System.Deployment.Application.DownloadManager.DownloadDependencies (SubscriptionState subState, AssemblyManifest deployManifest, AssemblyManifest appManifest, Uri sourceUriBase, String targetDirectory, String group, IDownloadNotification notification, DownloadOptions options)
in System.Deployment.Application.ApplicationActivator.DownloadApplication (SubscriptionState subState, ActivationDescription actDesc, Int64 transactionId, TempDirectory & downloadTemp)
in System.Deployment.Application.ApplicationActivator.InstallApplication (SubscriptionState & subState, ActivationDescription actDesc)
in System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation (Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String & errorPageUrl, Uri & deploymentUri)
in System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry (Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String & errorPageUrl)
--- End of stack trace from the previous location where the exception was raised ---
in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw ()
in System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry (Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String & errorPageUrl)
in System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker (Object state)
--- Internal exception ---
System.Net.WebException
- The file could not be found

**Comment by furquim87** [comment]
I'm facing the same issue. And whenever I try installing it using the TaskbarX Configurator.application I get the following error: "Cannot download the application. The application is missing required files. Contact application vendor for assistance.".

I was using an earlier version of the app and uninstalled it after facing some issues with it's icon being blank on the taskbar, but the configurator was working just fine.

**Comment by furquim87** [comment]
Neither the configurator nor the "TaskbarX Configurator.application" are working for me on version 1.7.0.0 either.

**Comment by Vignesh-Ganesan-008** [comment]
> ### The problem that the installation also did not work, this is the error that appears:
> INFORMATION ON PLATFORM VERSIONS
> Windows: 10.0.18363.0 (Win32NT)
> Common Language Runtime: 4.0.30319.42000
> System.Deployment.dll: 4.8.4270.0 built by: NET48REL1LAST_C
> clr.dll: 4.8.4341.0 built by: NET48REL1LAST_C
> dfdll.dll: 4.8.4270.0 built by: NET48REL1LAST_C
> dfshim.dll: 10.0.18362.1 (WinBuild.160101.0800)
> 
> ORIGINS
> Deployment URL: file: /// C: /Program%20Files/TaskbarX_1.6.4.0_x64/TaskbarX%20Configurator.application
> Application URL: file: /// C: /Program%20Files/TaskbarX_1.6.4.0_x64/TaskbarX%20Configurator.exe.manifest
> 
> IDENTITIES
> Deployment Identity: TaskbarX Configurator.application, Version = 1.0.0.2, Culture = neutral, PublicKeyToken = 0000000000000000, processorArchitecture = amd64
> Application Identity: TaskbarX Configurator.exe, Version = 1.0.0.2, Culture = neutral, PublicKeyToken = 0000000000000000, processorArchitecture = amd64, type = win32
> 
> APPLICATION SUMMARY
> 
> * Installable application.
> 
> SUMMARY OF ERRORS
> A summary of the errors can be found below. The details of these errors are listed later in the log.
> 
> * Exception when activating C: \ Program Files \ TaskbarX_1.6.4.0_x64 \ TaskbarX Configurator.application. The following error messages have been detected:
> 
> * File: /// C: / Program Files / TaskbarX_1.6.4.0_x64 / StoreLogo2-71.ico.deploy failed to download.
> * Could not find the file 'C: \ Program Files \ TaskbarX_1.6.4.0_x64 \ StoreLogo2-71.ico.deploy'.
> * Could not find the file 'C: \ Program Files \ TaskbarX_1.6.4.0_x64 \ StoreLogo2-71.ico.deploy'.
> * Could not find the file 'C: \ Program Files \ TaskbarX_1.6.4.0_x64 \ StoreLogo2-71.ico.deploy'.
> 
> SUMMARY OF COMPONENT STORAGE TRANSACTION FAILURE
> No transaction errors were detected.
> 
> WARNINGS
> 
> * The manifest for this application does not have a signature. Validation of the hash signature will be ignored.
> * The manifest for this application does not have a signature. Validation of the hash signature will be ignored.
> 
> STATUS OF THE OPERATION'S PROGRESS
> 
> * [16/04/2021 13:49:31]: The activation of C: \ Program Files \ TaskbarX_1.6.4.0_x64 \ TaskbarX Configurator.application has started.
> * [16/04/2021 13:49:31]: Processing of the deployment manifest has been completed successfully.
> * [16/04/2021 13:49:31]: The installation of the application has started.
> * [16/04/2021 13:49:32]: Processing of the application manifest has been completed successfully.
> * [16/04/2021 13:49:35]: Version 4.0.30319 of the compatible runtime was found.
> * [16/04/2021 13:49:35]: The request for trust and detection of the platform has been completed.
> 
> ERROR DETAILS
> The following errors were detected during this operation.
> 
> * [16/04/2021 13:49:35] System.Deployment.Application.DeploymentDownloadException (Unknown subtype)
> 
> * File: /// C: / Program Files / TaskbarX_1.6.4.0_x64 / StoreLogo2-71.ico.deploy failed to download.
> * Source: System.Deployment
> * Stack tracking:
>   in System.Deployment.Application.SystemNetDownloader.DownloadSingleFile (DownloadQueueItem next)
>   in System.Deployment.Application.SystemNetDownloader.DownloadAllFiles ()
>   in System.Deployment.Application.FileDownloader.Download (SubscriptionState subState, X509Certificate2 clientCertificate)
>   in System.Deployment.Application.DownloadManager.DownloadDependencies (SubscriptionState subState, AssemblyManifest deployManifest, AssemblyManifest appManifest, Uri sourceUriBase, String targetDirectory, String group, IDownloadNotification notification, DownloadOptions options)
>   in System.Deployment.Application.ApplicationActivator.DownloadApplication (SubscriptionState subState, ActivationDescription actDesc, Int64 transactionId, TempDirectory & downloadTemp)
>   in System.Deployment.Application.ApplicationActivator.InstallApplication (SubscriptionState & subState, ActivationDescription actDesc)
>   in System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation (Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String & errorPageUrl, Uri & deploymentUri)
>   in System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry (Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String & errorPageUrl)
>   --- End of stack trace from the previous location where the exception was raised ---
>   in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw ()
>   in System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry (Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String & errorPageUrl)
>   in System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker (Object state)
>   --- Internal exception ---
>   System.Net.WebException
> * The file could not be found

I'm facing the same issue.

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
