### ISSUE TITLE
cmd shows near search at startup

### ISSUE THREAD

**Issue by BenQbtw** [ChrisAnd1998/TaskbarX#608]
**Describe the bug**
cmd shows near search at startup

**To Reproduce**
download TaskbarX_1.6.9.0_x64 open TaskbarX Configurator.exe do some settings and restart the pc

**Expected behavior**
start without cmd

**Screenshots**
![image](https://user-images.githubusercontent.com/81976048/115016177-6971b800-9ebd-11eb-9b2d-707627befb71.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 20h2

**Additional context**
it isn't that important but just wanted to point that out

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
