### ISSUE TITLE
Shrink entire Taskbar

### ISSUE THREAD

**Issue by HoleInTheSeat** [ChrisAnd1998/TaskbarX#610]
I have a 32:9 monitor, I use fancy zones so that I have a 16:9 window in the middle of my screen and 4 more smaller 16:9 windows on each side of the main window. I would like to be able to shrink the entire taskbar, so that it is only as wide a the 16:9 window

Thanks for the awesome software!

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
