### ISSUE TITLE
Add option: Middle mouse click on taskbar app should close the app

### ISSUE THREAD

**Issue by MikaelPorttila** [ChrisAnd1998/TaskbarX#611]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add the option to allow middle mouse click on taskbar app icon to shut down the application like how tabs work in the browser.
This would make cut the number of clicks to close an app from the taskbar in half.

**Describe alternatives you've considered**
There could also be an option to press down CTRL + middle mouse click to close app but keep the original windows middle mouse click for a new app instance, maybe two options?

**Additional context**
After a long workday with multiple applications running in the taskbar it's quite painful to go through every app, right click and select close. A single tap on the middle mouse button should be enough. In my mind this is a killer feature that should exist in Windows itself already.

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
