### ISSUE TITLE
Ability to disable minimum width for vertical taskbar

### ISSUE THREAD

**Issue by watermarkhu** [ChrisAnd1998/TaskbarX#612]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Ability to disable minimum width for vertical taskbars. When the a vertical taskbar is set, there is a certain minimum width that can be set. As a result, there is a lot of unused space in the taskbar. 

**Describe alternatives you've considered**
I would like to see an option to disable the minimum width, similarly to [7+ taskbar tweaker](https://rammichael.com/7-taskbar-tweaker). With 7+TT, the `no_minimum_width` flag can be enabled after which the vertical taskbar can be set to the icon width, providing a much cleaner look. Screenshots are attached below. 

**Additional context**
[screenshots](https://imgur.com/a/8oCZFDt)

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
