### ISSUE TITLE
Option for unpinned applications to not re-center the whole Taskbar

### ISSUE THREAD

**Issue by Pertzell** [ChrisAnd1998/TaskbarX#613]
**Is your feature request related to a problem? Please describe.**
The best part about the default un-centered taskbar is that the pinned icons are in the same place no matter how many applications are open, since it's left-aligned and icons are added on it's right. But with Taskbar X, anytime a program that isn't pinned is opened, the whole taskbar re-centers and pinned programs shift a little bit to accommodate the unpinned programs. It's annoying to have icons be in slightly different places depending on how many unpinned programs are open.

**Describe the solution you'd like**
I'd like an option to keep pinned programs centered, but just add unpinned programs to the right of them. This way, pinned programs are in the same place no matter how many unpinned programs are opened.

**Describe alternatives you've considered**
This is actually kinda possible to achieve without TaskbarX, but it's a weird workaround. If you right click the taskbar and add a "Links" toolbar, you can put place it right next to the Start Menu, and manually resize it so the pinned programs are in the middle of the screen.

Here's what the taskbar looks like with this workaround.
![image](https://user-images.githubusercontent.com/60529987/115943411-d36dfc80-a47d-11eb-86dd-28079a927945.png) 

You can right-click the "Links" text to hide it and if the taskbar is locked, then the bars go away and it's pretty much exactly what I'm suggesting for TaskbarX. Pinned programs are (roughly) in the center of my screen and unpinned programs opened are added to the right.

**Additional context**
Here's an image showing what I'm envisoning. I hope it makes sense.
![](https://user-images.githubusercontent.com/60529987/115943587-c3a2e800-a47e-11eb-8d7a-54bb3ea692da.png)

**Comment by Mr-Anonymous75** [comment]
So basically you're asking for an option to center only pinned apps?

**Comment by Pertzell** [comment]
Yeah I think that accurately describes what I was imagining.

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
