### ISSUE TITLE
transparency issue

### ISSUE THREAD

**Issue by ggdosi** [ChrisAnd1998/TaskbarX#615]
**Describe the bug**
whenevery I try to turn the task from glossy to transparent it just blocks and doesnt change anything

**To Reproduce**
1. Go to 'Style'
2. Click on 'Transparent'
3. Select it and apply

**Expected behavior**
I expect it to become completely transparent and clear 
**Screenshots**
cant put any screenshot actually representing my problem

**Desktop (please complete the following information):**
 - OS: windows 10
 - Version 10.0.19042
**Additional context**

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
