### ISSUE TITLE
"The group or resource is not in the correct state to perform the requested operation" error message

### ISSUE THREAD

**Issue by omgitzmo** [ChrisAnd1998/TaskbarX#616]
Upon start up I receive this error message along with CMD behind it. TaskBarX still works fine but its a bit annoying to see the message everytime when starting my PC.

Screenshot:
![tempp](https://user-images.githubusercontent.com/66964415/116214480-a69c3c80-a73e-11eb-9481-4dd2ed3484f6.PNG)

**Comment by MrKevinU** [comment]
I have this issue too upon first boot.  Version 1.6.9.0

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
