### ISSUE TITLE
taskbar support issue

### ISSUE THREAD

**Issue by Punrawee** [ChrisAnd1998/TaskbarX#617]
**Describe the bug**
So am current use windows10insider preview build 21364.So it have news&interest box on taskbar but now after use use taskbar x it have a little bug i mean it sometime appear and gone appear& gone it so very anoy

if you want to know abot my pc you can see from attachment and also how news&interrest bow actually look like
![Screenshot (57)](https://user-images.githubusercontent.com/66133828/116230460-df113a00-a781-11eb-8332-0a43ffec8cdb.png)
![Screenshot (59)](https://user-images.githubusercontent.com/66133828/116230759-3e6f4a00-a782-11eb-81d6-ae1ee07daad5.png)

**Comment by ChrisAnd1998** [comment]
@Punrawee Just updated to 21370 and everything works fine here. I see you have a lot of icons in your taskbar. TaskbarX put's the icons back to the left when the icons start going behind the tray (clock, wheather..). You can disable that function inside the configurator under the Position tab. It's called "Revert to zero beyond tray".

**Comment by Punrawee** [comment]
okay

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
