### ISSUE TITLE
When I open a certain amount of apps, with some pinned to the taskbar, it reverts back to how it comes with Windows 10

### ISSUE THREAD

**Issue by AdeebShakhawat** [ChrisAnd1998/TaskbarX#618]
Here's the screenshot
![Screenshot 2021-04-29 100231](https://user-images.githubusercontent.com/83386343/116501195-0840e000-a8d2-11eb-94e9-30191329b80f.png)

**Comment by ChrisAnd1998** [comment]
@AdeebShakhawat It think because of this function. When enabled the icons should go to the left when it starts overlapping with the tray.


![dd](https://user-images.githubusercontent.com/50437199/116580779-fed86780-a913-11eb-8179-e1f8c9660648.png)

**Comment by dennisklad** [comment]
I have a similar issue but the opposite. When I have a lot of apps open it does not revert to the default and I am unable to see the lower half of tasks. I have my taksbar at the right. Even with the option enabled and disabled it does not work. Could you take a look at it. Thanks!
![image](https://user-images.githubusercontent.com/53832177/125787569-879b5795-ca67-4953-8510-bc69ee9dcd34.png)
