### ISSUE TITLE
Multiple issues

### ISSUE THREAD

**Issue by electronik54** [ChrisAnd1998/TaskbarX#619]
Thanks for the great app you have created😁, I had been looking for something like this since a long time. Unfortunately, my system keeps on running into some weird issues that I am not able to fix. Not sure if the issues are caused due to the portable version of the TaskbarX that I am using or my OS or both. 

I would like to add a suggestion to the app. I am not sure how the app works, but if its replacing or editing some of the system files, it should backup the original files along with the path so that we can manually restore them incase something is broken. I tried to run my OS without taskbarX in the startup hoping that would revert my system back to the original state till the bugs are fixed or create a system restore point. Right now I am working with a buggy taskbar, please let me know if there is a way to fix this.

----------------------------------------------------------------

**BUGS**

**1 |** My taskbar tray is always empty and filled with empty slots every time I restart my computer and TaskbarX is not running

![hidden icon tray](https://user-images.githubusercontent.com/16402142/116639307-39eb9280-a936-11eb-9d20-c66b5047461c.PNG)

Restarting the app or resting does not work either. It just reduces the empty slots
![image](https://user-images.githubusercontent.com/16402142/116639374-6b645e00-a936-11eb-85ab-1f0955b38502.png)

----------------------------------------------------------------

**2 |**  TaskSchedule does not work. I tried to change the delay to 10sec from default 6sec but it never works. Not sure if I was looking in the right place, but I checked my task scheduler library and there was no entry for the TaskbarX.

----------------------------------------------------------------

**3 |** I tried using the startup method but it looses transparency if I open my start menu. I use fullscreen start menu and not the default one. I have to either restart the app or apply the settings again to get the transparency back. The taskbar looses transparency everytime I open the start menu, but my icons stay centered.
But if I keep the console window running, the bug wont appear and the taskbar stays transparent.
----------------------------------------------------------------

**4 |**  I am not sure what the console does but keeps on showing me the following message.
![image](https://user-images.githubusercontent.com/16402142/116640837-6fde4600-a939-11eb-8fb0-1dc8722412a4.png)
The message never changes but the console window restarts every time I click apply or restart TaskbarX.

----------------------------------------------------------------

**5 |**  Taskbar and fullscreen window overlaps whenever the taskbar is transparent
![image](https://user-images.githubusercontent.com/16402142/116642436-db75e280-a93c-11eb-84f8-d02848cbc653.png)

but it fixes itself when the bug#3 happens
![image](https://user-images.githubusercontent.com/16402142/116642362-aa95ad80-a93c-11eb-829b-ee116ea46cdb.png)

----------------------------------------------------------------

**6 |**  TaskbarX wont minimize to tray, or the one of the empty slot in the second screenshot of bug#1 is for the taskbarX, the second slot would be my audio drive tray icon. I cant confirm that since I do not get any tooltip too.

----------------------------------------------------------------

**TaskbarX version** 
1.6.9.0 portable

----------------------------------------------------------------

**SETTINGS**

![image](https://user-images.githubusercontent.com/16402142/116639849-779ceb00-a937-11eb-84c7-15d9c1e0e211.png)
![image](https://user-images.githubusercontent.com/16402142/116639855-7a97db80-a937-11eb-96f4-f89e4709eb23.png)
![image](https://user-images.githubusercontent.com/16402142/116639866-7d92cc00-a937-11eb-83bd-496dc3e38825.png)
![image](https://user-images.githubusercontent.com/16402142/116639874-7ff52600-a937-11eb-9f93-8c2849c67a3c.png)
![image](https://user-images.githubusercontent.com/16402142/116639885-84214380-a937-11eb-8a55-305c72300e54.png)
![image](https://user-images.githubusercontent.com/16402142/116639891-87b4ca80-a937-11eb-89f8-dd915b065c31.png)

----------------------------------------------------------------

**SYSTEM INFO**

Processor	AMD Ryzen 5 2600X Six-Core Processor              3.60 GHz
Installed RAM	32.0 GB
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display
Edition	Windows 10 Education
Version	20H2
Installed on	‎2021-‎04-‎09
OS build	19042.906
Experience	Windows Feature Experience Pack 120.2212.551.0

**Comment by ChrisAnd1998** [comment]
@electronik54 Thanks for the details! I am working on it. For now just disable the tray icon.

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
