### ISSUE TITLE
Taskbar is "cropped"

### ISSUE THREAD

**Issue by Martin5001** [ChrisAnd1998/TaskbarX#62]
This is probably not a typical use scenario and I don´t know if it´s possible (or even needed) to fix this but I report it anyway.

**My initial setup was:**

- taskbar set to "Center between..."
- search icon shown (no textbox)
- task view icon shown
- no Cortana icon shown

**I did this:**

- show Cortana icon
- hide Cortana icon
- set search from icon to textbox
- set search from textbox to hidden
- set search back to icon only

(If you ask why I did this: I was just wondering how Falcon handles me doing all this nonsense :D AKA extensive testing)

**And this is what happened:**
![Bez názvu](https://user-images.githubusercontent.com/35201200/68026363-cec4ef80-fcaf-11e9-891c-060aedc78466.png)

**Comment by ChrisAnd1998** [comment]
Hmm, i cant seem to reproduce this behavior. Also not on my laptop.

**Comment by v-rogg** [comment]
I can confirm the bug. But I also haven't found a way yet to reproduce it consistently

**Comment by v-rogg** [comment]
For me it seems like it usually occurs when connecting another display with a higher resultion with the main taskbar switching to this new monitor.

**Comment by ChrisAnd1998** [comment]
Latest update will restart the application on Display_Change and Settings_Change so in theory this should be fixed. Feel free to reopen if not.
