### ISSUE TITLE
Configurator not working

### ISSUE THREAD

**Issue by LJINFINITY** [ChrisAnd1998/TaskbarX#620]
when i open the Configurator nothing happens ,I know that there is a post related to this but the post was closed i don't know if anymore comment will get a reply so i made a new issue.
i tried what u told in the comment but its does not work for me please help

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
