### ISSUE TITLE
how to uninstal taskbarx when your stupid

### ISSUE THREAD

**Issue by nednedsudo** [ChrisAnd1998/TaskbarX#622]
*hello i need help bc im stupid and i didnt look how to uninstal taskbarx and i delete and the othere files and the left file is the taskbarx and i cant delete it help pls!.

**Comment by EndreEndi** [comment]
Explain better please, to be able to understand your issue and help with it

**Comment by nednedsudo** [comment]
how to delete a taskbarX but i deleted the other files and only the taskbarX application remained and i can't delete it

**Comment by nednedsudo** [comment]
Ok i have new issue i delete the app taskbarX but its still staying in the same possition in the middle

**Comment by ChrisAnd1998** [comment]
_How do i uninstall TaskbarX? Open the "TaskbarX Configurator" and hit the "Stop TaskbarX" button. This will stop the TaskbarX process and put your icons back to the left. Then go to the "Taskschedule" tab and hit the "Remove" button. After that you can simply remove the files where you installed TaskbarX.

Watch on Youtube_
