### ISSUE TITLE
TaskbarX Animation Bug when i start a game in fullscreen

### ISSUE THREAD

**Issue by CaioCarneiro29** [ChrisAnd1998/TaskbarX#624]
I found a little animation bug that can occur when i open a game in fullscreen, like ROBLOX, the taskbar animation glitches and after a few seconds the taskbar disapear (and the taskbar should just disappear when you open a game in full screen)

**To Reproduce**
Just open a game or program in fullscreen (sometimes this bug happen)

**Screenshots**
i dont have any screenshot

**Desktop (please complete the following information):**
 - OS: Widows 10
 - Version Windows 10 pro 21H2.

That's it, i hope you guys could find the issue and solve it. Thanks!

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
