### ISSUE TITLE
Transparent and Transparent Gradient not working correctly

### ISSUE THREAD

**Issue by benpashiro** [ChrisAnd1998/TaskbarX#625]
normal version from github
19042.928 build of Win10
.NET framework installed
only windows defender
no 3rd party taskbar tweakers although TranslucentTB was installed at one point
Reproduce:
-move taskbar to top position on desktop
--run taskbarX
---change to settings as shown at https://imgur.com/a/rhcQ3cw
----run firefox/ms edge and maximise window

**For me this results in this ugly overlap of the taskbar on top of the firefox window as seen in https://imgur.com/a/axKE76t
full screenshot of result : https://imgur.com/a/AYQ0h3k**

**Comment by yusufekerdiker** [comment]
it happens only on firefox browser

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
