### ISSUE TITLE
The New Widget

### ISSUE THREAD

**Issue by ghost** [ChrisAnd1998/TaskbarX#626]
Ever since the update that brought the weather/news widget to Windows 10, Taskbar X simply wouldn't centre that taskbar but everything seems to work fine. That's it

**Comment by ChrisAnd1998** [comment]
@DiamonAurora Weird I just updated to 21370 and it still works fine here...

**Comment by DiamonAurora** [comment]
So I realised that the widget just made the taskbar icons go beyond the tray and therefore put the icons back to where it was with the 'revert o zero tray' setting. My bad

**Comment by Ione15** [comment]
It does not work with "Compensate Tray Clock etc...."

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
