### ISSUE TITLE
taskbar x not be run

### ISSUE THREAD

**Issue by Punrawee** [ChrisAnd1998/TaskbarX#627]
**Describe the bug**
taskbar x not run after run taskbar x.exe i mean it not center the app icon

**Expected behavior**
but taskbar x.exe and application center automatically

**Screenshots**

https://user-images.githubusercontent.com/66133828/117116705-e1464a80-adb8-11eb-8442-fc59414bad63.mp4

**Desktop (please complete the following information):**
 - OS: Windows 10 pro insider preview
 - Version dev  bulid : 21370.1

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
