### ISSUE TITLE
Request: Use the taskbar itself to show battery percentage

### ISSUE THREAD

**Issue by Mr-Anonymous75** [ChrisAnd1998/TaskbarX#629]
**Is your feature request related to a problem? Please describe.**
I'm almost done removing tray icons from my taskbar. I figured out a keyboard shortcut for the time (Win + Alt + D), I removed the action center icon altogether, and the only tray icon left on my taskbar is the battery one - I always need to know how much battery my laptop has. 

**Describe the solution you'd like**
What if part of the taskbar was a different color?

![Battery Representation Suggestion](https://user-images.githubusercontent.com/73294041/117225580-48531600-ae30-11eb-9ae3-c876c569c602.png) (this was the first time I used GIMP)

As you can see, part of the taskbar is tinted red while the rest is the original color. The red part shows that there's about 55% battery in the screenshot. 
It would be even better if the color could change depending on how much battery was there. And even better still if we could choose those colors.

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
