### ISSUE TITLE
[Feature Request] Change taskbar background while start menu is open

### ISSUE THREAD

**Issue by Mr-Anonymous75** [ChrisAnd1998/TaskbarX#630]
**Is your feature request related to a problem? Please describe.**
I use a fullscreen start menu, which shows the desktop as the background - but my acrylic taskbar still shows the window beneath, which is usually edge with some website in dark mode opened. This looks really weird.
![image](https://user-images.githubusercontent.com/73294041/117228751-4d679380-ae37-11eb-8614-819ec4cf21f8.png)

**Describe the solution you'd like**
It would be great if the taskbar background could change to the desktop when the start menu is open. 
![image](https://user-images.githubusercontent.com/73294041/117228979-c961db80-ae37-11eb-8932-8616c532356f.png)
Something like this - just tint the taskbar white like the start menu.

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
