### ISSUE TITLE
Animation delay and watch for changes

### ISSUE THREAD

**Issue by kien5436** [ChrisAnd1998/TaskbarX#631]
**Describe the bug**
* When I use multi screens, whenever I switch between them, the taskbar is back to the original settings
* also, the animation is a bit lag
* Center animation is only from left to right? I wish it could run in both directions

**To Reproduce**
1. Choose 'transparent' style and 'linear' animation
2. Taskbar is transparent
3. Switch screen
4. Taskbar is back to accent color before transparent again. Center animation causes icons jump to center and not smoothie

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10] windows 10
 - Version [e.g. 1909]1909

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
