### ISSUE TITLE
Extending to a wireless display cause taskbarx to crash and says could not find the handle of the taskbar

### ISSUE THREAD

**Issue by Saihaan06** [ChrisAnd1998/TaskbarX#632]
**Describe the bug**
whenever I extend tp a wireless display using project to this pc, taskbarx crashes, 
**To Reproduce**
1. click win+p and connect to another wireless display
2. click duplicate and then extend

**Expected behavior**
it should just center the taskbar as usual
**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 20H2

**Additional context**
the desktop is also constantly refreshing, which could either be cause by taskbarx trying to restart or cause taskbarx to crash in the first place. this also only happens when extending my display. I am using another laptop as the second display

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
