### ISSUE TITLE
"@Looper1 | Member not found" after installing Windows Update "2021-04 Cumulative Update Preview for Windows 10 Version 20H2 for x64-based Systems (KB5001391)"

### ISSUE THREAD

**Issue by jaybaldwin** [ChrisAnd1998/TaskbarX#634]
**Describe the bug**
On Windows 10 20H2, after installing "2021-04 Cumulative Update Preview for Windows 10 Version 20H2 for x64-based Systems (KB5001391)," TaskbarX does not center the icons. Seems to have no effect on the taskbar. Console reports exception: 

Waiting for Shell_TrayWnd
@Looper1 | Member not found. (Exception from HRESULT: 0x80020003 (DISP_E_MEMBERNOTFOUND))

**To Reproduce**
Using TaskbarX from the Windows Store. Confirmed most recent Store version (1.6.9.0)

1. I installed "2021-04 Cumulative Update Preview for Windows 10 Version 20H2 for x64-based Systems (KB5001391)" via Windows Updates on 5/4/2021.  
2. Run TaskbarX. It won't work.
3. Restart TaskbarX with Console to observe the following in the console after several minutes:
Waiting for Shell_TrayWnd
@Looper1 | Member not found. (Exception from HRESULT: 0x80020003 (DISP_E_MEMBERNOTFOUND))

**Expected behavior**
TaskbarX centers the icons correctly and has effect on the Taskbar

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Version 20H2 (OS Build 19042.964)

**Additional context**
I doubt it matters, because it never has before (since FalconX days), but I use my taskbar locked on the top of the primary display.

**Comment by jaybaldwin** [comment]
Additional update:

I discovered today this is due to the "News and Interests" feature added to Windows 10 that adds the weather Icon and temperature to the Taskbar.  Here's the thing: It only adds this info to the taskbar IF the Taskbar is situated on the BOTTOM of the screen.  Since mine was at the top, I did not notice the new window class on the Taskbar.  In fact, when I right-click the Taskbar on the top, the "News and Interests" context menu option is missing entirely. It ONLY shows up when on the bottom.  

My problem was caused by the TaskbarX Configurator setting "Revert to zero beyond Tray."  I have several icons pinned to the taskbar, and there's actually room for them to center if the taskbar is oriented at the bottom, even with the new "News and Interests" area ... but NOT if the Taskbar is at the top of the display, despite that feature not working correctly in this version of Windows. 

Info about the feature, complete with screenshots: 

https://www.windowscentral.com/how-use-news-and-interests-taskbar-widget-windows-10

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
