### ISSUE TITLE
High CPU Usage if you switch Windows Account

### ISSUE THREAD

**Issue by techgenius1** [ChrisAnd1998/TaskbarX#635]
If i switch between multiple windows account while an account is already logged in and running TaskBarX it starts to use High CPU and this doesnt fix without logout that second account and restart TaskbarX

Screenshots
![image](https://user-images.githubusercontent.com/10501401/117568824-4d7fc180-b0cb-11eb-8943-0708adbb3ef6.png)

Desktop :
 - OS: Windows 10
 - Version 21H2 & 21H1 & 20H2 & 2004

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
