### ISSUE TITLE
"Show Tray Icon" -setting causes TaskbarX to not launch.

### ISSUE THREAD

**Issue by ZenTunE** [ChrisAnd1998/TaskbarX#636]
**Describe the bug**
Enabling "Show tray icon" in the configurator (or placing it in a shortcut (-sti=1)) cause TaskbarX to not launch properly. When trying to Restart TaskbarX from the configurator, a command prompt pops up for a bit of time saying:

```
Waiting for Shell_TrayWnd
Arithmetic operation resulted in an overflow
```

All other settings work as expected.

**To Reproduce**

0.  Installl taskbarX on a user with a space in the username (See **"Additional context"**!)
1. Enable "Show tray icon" in configurator.
2. Try to apply and/or restart TaskbarX.
3. Will not start.
4. Disable "Show tray icon" in configurator.
5. Try to apply and/or restart TaskbarX.
6. Works again.

**Expected behavior**
For TaskbarX to restart properly, with the settings saved and the tray icon visible.

**Screenshots**
Here is a link to a recording that shows the issue: https://youtu.be/IiUc6Izzet0

CMD:
![TaskbarX Debug](https://user-images.githubusercontent.com/83918274/117582632-9b1c1e80-b10b-11eb-8334-03cd0ffb0c0c.png)
Translation:
```
Waiting for Shell_TrayWnd
Arithmetic operation resulted in an overflow
```

**Desktop (please complete the following information):**
 - Windows 10 Pro
 - 20H2
- TaskbarX version: 1.6.9.0, most recent at the time of writing

**Additional context**
I started to suspect that on reason for this could be that my windows username (as seen in the video in the command prompt) has a space in it (Alvar Palander). When creating a taskchedule from the configurator and checking it manually, the path to TaskbarX .exe has no quotation around it. Usually this causes an error because the path has a space in it, quotations prevent the error. 

I'm not sure whether this affects anything related to this issue but thought I'd mention this just in case.

**Comment by TheSpartaPT** [comment]
I have a similar problem to yours, mine actually launches with Show tray icon enabled, but the console window stays opened (maybe permanently I haven't seen it close automatically with the option enabled) with the message "Waiting for Shell_TrayWnd", the TaskbarX tray icon isn't displayed like this:
![image](https://user-images.githubusercontent.com/8343238/128596897-62ca9d1a-4542-4d9a-aa8d-efcfdc9f9e2f.png)

and the right click menu doesn't open too. but the actual taskbar settings apply:
![image](https://user-images.githubusercontent.com/8343238/128596992-3735f1b8-ea25-4cf5-bf48-e3c207d9a0f6.png)

#### Desktop (please complete the following information):

- Windows 10 Pro
- 20H2
- TaskbarX version: 1.7.1.0

PS: my windows username has no spaces in it so I guess it's not related

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
