### ISSUE TITLE
Taskbarx wont open

### ISSUE THREAD

**Issue by jhnprc** [ChrisAnd1998/TaskbarX#637]
Whenever I launch the taskbar, it only puts my taskbar icons in the middle but do not launch the app. I want to make it transparent but as I've mentioned, it doesnt launch. Already tried to reboot many times but no luck. Please help

**Comment by ChrisAnd1998** [comment]
Have you tried to open the Configurator exe?
The main application (TaskbarX.exe) has no GUI. To configure it you need the (TaskbarX Configurator.exe)

**Comment by jhnprc** [comment]
where can I get a TaskbarX Configurator.exe from the store? thanks

**Comment by jhnprc** [comment]
nvm. found it. thanks a lot <3

**Comment by ChrisAnd1998** [comment]
Ok 😁👍
