### ISSUE TITLE
Export Settings

### ISSUE THREAD

**Issue by merlin555** [ChrisAnd1998/TaskbarX#639]
Hi,

I would like to know where the settings are saved by the tool.
Or an option to export the settings.

Greetings..

  Merlin

**Comment by ChrisAnd1998** [comment]
Hi @merlin555 The settings are saved as parameters inside the Taskschedule.

![Untitled22](https://user-images.githubusercontent.com/50437199/117830189-af7b2b00-b273-11eb-8a97-567f8882ab5d.png)

There is no option to export them yet... You can just copy the parameters and paste them back on the machine you want to import them for now.

**Comment by merlin555** [comment]
Great !
Thank you.
