### ISSUE TITLE
Falcon logo animation in Settings

### ISSUE THREAD

**Issue by Martin5001** [ChrisAnd1998/TaskbarX#64]
Animating the logo when Falcon Settings window is opened might add a nice touch. (GIF has slightly lower framerate than the original video but good enough for a concept illustration.)
![animation](https://user-images.githubusercontent.com/35201200/68037596-63d3e280-fcc8-11e9-978e-1ec46570a813.gif)

**Comment by ChrisAnd1998** [comment]
Looks nice 😁🔥, and again thanks for putting so much time in this!

**Comment by Martin5001** [comment]
You're welcome :)

**Comment by ChrisAnd1998** [comment]
I like this but, is no longer relevant to the new configurator.
