### ISSUE TITLE
TaskbarX messing up my taskbar

### ISSUE THREAD

**Issue by mikwee** [ChrisAnd1998/TaskbarX#640]
**Describe the bug**
I opened TaskbarX, and immediately, something was wrong. I had a feeling it had to do something with my computer being set to Hebrew, an RTL language, which means my entire UI is flipped. I looked at the configurations, but I couldn't find anything related to flipping the UI. I stopped TaskbarX, yet my taskbar was still messed up, and still is as I'm writing this.

**To Reproduce**
1. Setm your language to Hebrew
2. Open TaskbarX

**Expected behavior**
I expected TaskbarX to only center my software icons when I opened it, like a tutorial showed me.

**Screenshots**
![lqkyWM6now](https://user-images.githubusercontent.com/8478516/117845425-32f34700-b289-11eb-8188-0a01f18ce7ad.png)
My taskbar, currently
P.S.: The taskbar has changed a bit since I screenshot this, the software icons are now aligned to the right, they come right after the up arrow.

**Desktop:**
 - OS: Windows 10 Pro
 - Versione 1909

**Additional context**
I feel like adding RTL compatibility is the solution.

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
