### ISSUE TITLE
TaskbarX settings reset after every restart.

### ISSUE THREAD

**Issue by AayushBoliya** [ChrisAnd1998/TaskbarX#641]
**Describe the bug**
I customize taskbar, and after I restart my PC everytime, TaskbarX settings reset.
Also it doesn't start on start up.

**Expected behavior**
It should save the settings and load them on every startup.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 20H2

**Comment by NOMVD** [comment]
I am sort of having the same issue except in my case its only one setting that resets every time I restart. The transparency always resets and I have to fix it each time I restart.

**Comment by ChrisAnd1998** [comment]
@AayushBoliya Can you open "Task Scheduler" from your start menu? Just start typing and it will pop up.
Look for an entry that is called TaskbarX... 

I assume it's only forgetting it's settings but it does run at start-up?. So it could be stuck. Right click the TaskbarX entry and hit delete. Now just configure TaskbarX again using the Configurator and it should work fine.

**Comment by AayushBoliya** [comment]
Actually it doesn't even start at startup. I've reinstalled it multiple times.
It only started after I created a Task in Windows Task Scheduler.

When Taskbar.exe (blue icon) starts, it only pushes the icons on the middle, but forgets the other settings.
So I have to open up Taskbar Configurator (grey icon) and select the settings again and apply

And it never saves, so the cycle repeats.

**Comment by ChrisAnd1998** [comment]
The TaskbarX.exe needs the parameters from the Configurator in order to work with your settings. If it's run without parameters it will run with default settings. Can you still try to manually delete the TaskbarX task schedule. The Taskschedule could be stuck. Also don't run TaskbarX or the Configurator as Administrator.

**Comment by NOMVD** [comment]
i deleted it from task scheduler and restarted and still, it forgets the transparent parameter and to remove the start button and tray. When i open taskbarx it still shows my settings though, it just doesn't acknowledge them on start up.

**Comment by n33rj** [comment]
TaskScheduler doesn't work for me too on 20H2, but here's a workaround i got it working.

1. TaskbarX --> Startup --> Remove Taskscheduler --> Generate Shortcut link and copy
2. Go to "C:\Users\USER-NAME-HERE\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup"
3. Right click --> New --> shortcut --> Paste what you copied --> Type a name after clicking next --> you are done!

It should work as expected on next startup....

**Comment by HobbesKo** [comment]
@n33rj 
That works for me, many thanks.

**Comment by AayushBoliya** [comment]
@ChrisAnd1998 How can I change the default settings for the (Blue icon taskbar)? 
Yes I can manually delete TaskbarX Schedule. And I don't run it as Admin.

@n33rj your method works, thanks. It starts on startup, but it the settings still get reset to default.

**Comment by Ziffer-yan** [comment]
@n33rj  Much thanks! That also works for me when I have updated my win10 to 20H2.

**Comment by mbero2125** [comment]
To get it to save your settings at startup, Install the app then launch the TasbarX Configurator set it up the way you want it then hit apply, then create the task scheduler. that seemed to work for me.
