### ISSUE TITLE
@looper2 error

### ISSUE THREAD

**Issue by Nerxxy** [ChrisAnd1998/TaskbarX#642]
**Describe the bug**
Error pop up "@looper2 | External component has thrown an exception"

**To Reproduce**
i did nothing, just loaded my pc and it popped up

**Expected behavior**
The error nor show up i guess? otherwise N/A

**Screenshots**
![Screenshot_1](https://user-images.githubusercontent.com/37718547/118031302-4cb28e00-b35e-11eb-86cb-cf83d07bf197.png)

**Desktop (please complete the following information):**
- OS Build: 19042.928
- OS: Windows 10
- Version 20H2

**Additional context**
N/A

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
