### ISSUE TITLE
TaskbarX simply won't open

### ISSUE THREAD

**Issue by jeremyrenerischill** [ChrisAnd1998/TaskbarX#643]
*Describe the bug*
It will not open whatsoever when I try to. I downloaded it from the Microsoft Store. 

1. Type Taskbar X on search
2. Click on Taskbar X 
3. It doesn't open
4. See nothing, because it gives no error.

Expected behavior:
To open when I payed $1.59 on the Microsoft Store

**Screenshots**
I would, 'show screenshots' but no error comes up, just my blank screen.

**Desktop**
 - OS:  Windows 10
 - Version Latest version?

**Additional context**
Installed, reinstalled, restarted.  Nothing works to get it to open no matter how much I try it. Been two hours wasted to get it to work to no avail. Look, I am not really 'well versed' in computers, that is why I bought it on the Microsoft Store and not extracted the files via GitHub, etc.

**Comment by ChrisAnd1998** [comment]
@jeremyrenerischill I'm sorry you have to go through this hassle. Please try to extract the **x64** or **neutral** zip from GitHub. And run **TaskbarX.exe** or **TaskbarX Configurator.exe**. If that works there's a problem with the Microsoft Store.

For the Zip file just download it.
Open it.
And put the contents inside a folder where you like.
For example a folder desktop called **taskbarx**.
Then go inside the folder and run the **TaskbarX.exe** file.

If that works.. Then there is an issue with the store and I can't fix that. Mostly it's a matter of time.

**Comment by jeremyrenerischill** [comment]
@ChrisAnd1998 I am not very versed in computers, is there a link of some sorts that I can easily download it from?

**Comment by jeremyrenerischill** [comment]
![Screenshot (9)](https://user-images.githubusercontent.com/84182208/118358921-952ca000-b546-11eb-8364-6b6ca50e6b72.png)

Here is an example of it just centering the taskbar and nothing else.

**Comment by ChrisAnd1998** [comment]
Ok, and have you opened the Configurator exe file?

**Comment by jeremyrenerischill** [comment]
Do you mean the 6 lines of code here? https://github.com/ChrisAnd1998/TaskbarX/blob/master/TaskbarX%20Configurator/TaskbarX%20Configurator/TaskbarX%20Configurator.exe.config

**Comment by ChrisAnd1998** [comment]
No.. **TaskbarX Configurator.exe**

![f2](https://user-images.githubusercontent.com/50437199/118360399-992ce200-b587-11eb-832a-56654b945249.png)

**Comment by jeremyrenerischill** [comment]
Can you link me the download to add this file to the TaskbarX file?

**Comment by jeremyrenerischill** [comment]
Look man, I am completely new at extracting zip files and GitHub. In fact, I am so new, I cannot even find the TaskbarX file on my computer to even drop the file into the folder.

**Comment by ChrisAnd1998** [comment]
https://github.com/ChrisAnd1998/TaskbarX/releases/tag/1.6.9.0

![f1](https://user-images.githubusercontent.com/50437199/118361300-0ee67d00-b58b-11eb-9c28-4b4d3f3d4129.png)

**Comment by ChrisAnd1998** [comment]
Just double click the zip file to open it.
Then copy all the files in there to a folder anywhere you like.

**Comment by ChrisAnd1998** [comment]
But how are your taskbar icons centered when you have not used the zip file yet?

**Comment by jeremyrenerischill** [comment]
Well, I tried opening the TaskbarX Application and it just centers it. Then I tried opening the TaskbarX Configurator and IT WORKS GREAT! Also, what do you mean by "Configurator inside your startmenu."

**Comment by ChrisAnd1998** [comment]
:) Well this confused me a bit.. In your screenshot your taskbar is centered. So all you had to do to change it's appearance is search for the **TaskbarX Configurator** inside you start menu.

![f3](https://user-images.githubusercontent.com/50437199/118361794-39393a00-b58d-11eb-9bc2-9fde9c415839.png)

**Comment by jeremyrenerischill** [comment]
OMG, I am sooo sorry. I was just uneducated in how it was to work at first, but now I realize I should've just looked up TaskbarX Configurator first and it would've simply worked fine :/
I have one more tiny question. How do I enable TaskbarX to work on startup?
After that last question is answered. I just want to thank you for taking your precious time in helping me and I will definitely give you a five-star-rating for your troubles and a more than great review :'))))

**Comment by ChrisAnd1998** [comment]
Thank you I really appreciate that 😁😁. After hitting the Apply button inside the Configurator it should run at start-up automatically.

**Comment by jeremyrenerischill** [comment]
Btw it looks AMAZING! Many thanks for your contribution.

**Comment by GPatricks** [comment]
Ok, grabbed the x64 version and it shows it is running in task manager. Configurator starts fine but changes have 0 effect. Stop/Restart has no effect. I am running Win11 Pro using Nvidia Surround on Triples. 
![TaskbarX](https://user-images.githubusercontent.com/88084475/159003705-4bb7b312-bc39-4114-a415-6cdc89dfd9a1.jpg)

**Comment by ac-denton** [comment]
End it in Task Manager then try again. I noticed the Stop and Restart buttons done nothing too. A reinstall of it could work.
I have the Win Store version and for me I had to go onto the store and update the app for it to run again.
