### ISSUE TITLE
TaskbarX stop centering icons after user switch

### ISSUE THREAD

**Issue by sergeypugachov** [ChrisAnd1998/TaskbarX#645]
Hello.

Standalone portable version. Taskschedule enabled.

I have multiple local (micrososft) accounts on laptop. On first account i use Taskbasrx, and on another i do not. After switching to second account, and switching back taskbarx stopped centering icons (but process is started)   

1. Create two accounts
2. Configure taskbarx on first. Enable taskschedule.
3. Do not configure taskbarx on second account.
4. Switch to second user
5. Switch back to first user
6. TaskbarX is running (in task manager), but icons not centered

**Expected behavior**
I assume, icons should be centered in souch scenario.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - 20H2 (19042.985)

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
