### ISSUE TITLE
UI Doesn't appera

### ISSUE THREAD

**Issue by finallight1** [ChrisAnd1998/TaskbarX#647]
I cant customize my taskbar because the configuration window does not appear, i tried opening Configurator with and without admin rights. Why even release smthing if it doesn't work

**Comment by finallight1** [comment]
And now I cant move my Icons back, and I am stuck with those ugly centered icons and cannot do anything about it.

**Comment by finallight1** [comment]
Oh ok nevermind i restarted my pc and my icons are back to normal, can't recommend using this fake software

**Comment by ChrisAnd1998** [comment]
@finallight1 It might be a bug.. Shouting doesn't solve any issues 😞.
