### ISSUE TITLE
TaskbarX actually works on Windows 8, but with minor issues

### ISSUE THREAD

**Issue by HanS985** [ChrisAnd1998/TaskbarX#648]
**Is your feature request related to a problem? Please describe.**
I do remember that in the Readme file, it says that Windows 8 is not officially supported. However, I still installed it anyway on Windows 8 (more specifically the 8.1 variant) and found that it generally still works. That's right, the app icons in the taskbar became centered and I got better transparency effects normally unavailable on Aero. However, this also leads to minor issues such as the taskbar color customizations resetting to the theme color after switching from a Metro app or the emojis displaying wrongly, but other than that, it just works. 

**Describe the solution you'd like**
The solutions I'd want is 
- The readme file saying that it works. 
- to retain the color customizations made through TaskbarX after a Metro app was closed
- to not show the emojis when Windows 8 or 8.1 is detected

**Describe alternatives you've considered**
There isn't really any alternatives I've considered since _it just works_ and it is in the application itself. 

**Additional context**
I don't have any screenshots, but trust me: it actually works, and that was the truth.

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
