### ISSUE TITLE
Taskbar Artifacts & FIX (Windows 21H1 with Weather Widget Update) 

### ISSUE THREAD

**Issue by Cassiedee** [ChrisAnd1998/TaskbarX#649]
There are taskbar artifacts now present when TaskbarX is launched and running. I believe that the Weather Widget that was implemented in the latest update would be the cause for the Taskbar acting weird and not being where it should be. Sometimes it wouldn't even be there and the Taskbar doesn't re-center. I have tried disabling the weather widget itself but to no avail did that fix anything.

1.  Update Windows to the 21H1 Build through the Windows Insider Program
2.  Set Taskbar position to the Top or Bottom of the screen
3.  Launch TaskbarX

![image](https://user-images.githubusercontent.com/65631988/119214189-be36be80-ba79-11eb-8e81-f4779d34aa59.png)

 - OS: Windows 10 Enterprise
 - Version: 10.0.19043 Build 19043 (Windows 21H1 May Update | Windows Insider Build)

EDIT: A temporary fix is to position the taskbar to the right or left hand side of the screen. This isn't preferable tho. The top and bottom positions are problematic. 

EDIT 2: Try reinstalling TaskBarX, apply the latest Windows Cumulative Update for the build (if and when avaliable), and restart. That magically fixed it for me. Nothing is actually wrong with TaskbarX. It solely seems to be a Windows taskbar optimization problem due to that new weather widget.

**Comment by JoBilert** [comment]
Having the same problem here. Also getting some weird "ghost"-icons when opening the Systemtray.

**Comment by Skyline404** [comment]
Same here

**Comment by Cassiedee** [comment]
@JoBilert @Skyline404 I found a fix. Try reinstalling TaskBarX, apply the latest Windows Cumulative Update for the build, and restart. That fixed it for me. Nothing is wrong with TaskbarX. It solely seems to be a Windows taskbar optimization problem due to that new weather widget.

**Comment by Skyline404** [comment]
> @JoBilert @Skyline404 I found a fix. Try reinstalling TaskBarX, apply the latest Windows Cumulative Update (if and when available) for the build, and restart. That magically fixed it for me. Nothing is actually wrong with TaskbarX. It solely seems to be a Windows taskbar optimization problem due to that new weather widget.

Didnt help, still glitching

**Comment by eXcalpius** [comment]
I was able to get around this bug between 21H1, News and Interests, and Taskbar X by using the 1.7.0.0 pre-released and selecting "Show Icon Only" for the News and Interest toolbar. If either of the other options (Hidden or Show Icon and Text) is selected, everything gets jumbled up on the right and often even the entire system tray disappears entirely.

This approach even works after reboots, etc. so I thought I'd share my findings with everyone. I hope it helps while we await a bug fix. :)

Note that my OS build is x64 21H1 19043.1023. YMMV.

**Comment by snaildos** [comment]
Can confirm.

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
