### ISSUE TITLE
Restarting GPU dependant software after TaskbarX launch or restart 

### ISSUE THREAD

**Issue by fsdgshda** [ChrisAnd1998/TaskbarX#650]
Every time Windows boots up whatever launched before TaskbarX disappears from the icon tray, like the Nvidia Control panel.
or whenever the screen turns off and then it turned on again, all the programs that are using GPU crash and close, like the MSI afterburner or the 3dmodeling software like Rhino. It is not something new, it is at least here from the first day of Taskbar X 1.6.9.0 update.

Windows 10 Pro Version	21H1 OS build	19043.985

Nvidia Studio Driver Version 462.59

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
