### ISSUE TITLE
Style resets itself at every reboot/shutdown

### ISSUE THREAD

**Issue by Tw3ak3rz** [ChrisAnd1998/TaskbarX#651]
I tried to locate this in case it has been posted but didn't see this exact issue though it is very possible I simply missed it.

**Describe the bug**

At every restart of the PC Blur or any other choice is reset to Transparent making it difficult to see icons and such in the taskbar (esp with my poor vision).

**To Reproduce**

No error shown, it just resets itself.

**Expected behavior**

I expect to make a choice and it is remembered between restarts.

**Screenshots**

Not required.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]

Windows 10 Pro x64

 - Version [e.g. 1909]

21H1 OS Build 19043.985

**Additional context**

Best I recall it was NOT the store version, download it via web browser, and states it is the latest version.

I also use TaskBarGroups found here on GitHub.

Thank you!

**Comment by maaanuuuuu** [comment]
Yeah same here

**Comment by Tw3ak3rz** [comment]
> Yeah same here

At least I'm not the only one, otherwise, it is a really great program. I hope when you click it'll offer ToolTips one day since some icons look similar.

**Comment by ebdonato** [comment]
The same error for me, but I want transparent setup and always get blur after system restart.

**Comment by Tw3ak3rz** [comment]
> The same error for me, but I want transparent setup and always get blur after system restart.

I fixed my problem, in Task Schedular is a TaskbarX task that you can edit. Open Task Scheduler and locate the task "TaskbarX" and open/edit that task. Once opened click the Actions Tab then click Edit at the bottom. In the Arguments section you will change the number -tbs=2 which is Blur. Replace with whatever you prefer for the desired style you want. 2=Blur, 5=OpaqueNow it remains as desired between restarts or shutdown.
In the event you want to change things, these are the settings.
-tbs=0 Default
-tbs=1 Transparent
-tbs=4 Transparent Gradient
-tbs=5 Opaque
-tbs=2 Blur
-tbs=3 Acrylic (can flicker)

**Comment by ebdonato** [comment]
> 
> 
> > The same error for me, but I want transparent setup and always get blur after system restart.
> 
> I fixed my problem, in Task Schedular is a TaskbarX task that you can edit. Open Task Scheduler and locate the task "TaskbarX" and open/edit that task. Once opened click the Actions Tab then click Edit at the bottom. In the Arguments section you will change the number -tbs=2 which is Blur. Replace with whatever you prefer for the desired style you want. 2=Blur, 5=OpaqueNow it remains as desired between restarts or shutdown.
> In the event you want to change things, these are the settings.
> -tbs=0 Default
> -tbs=1 Transparent
> -tbs=4 Transparent Gradient
> -tbs=5 Opaque
> -tbs=2 Blur
> -tbs=3 Acrylic (can flicker)

Thank you for your reply.

I find the Task Scheduler and there was two task scheduled for TaskbarX, one using the current PC name and other using the prior PC name. I think I changed the PC name after installing TaskbarX, and then change my setup to transparent.

**Comment by Tw3ak3rz** [comment]
> > > The same error for me, but I want transparent setup and always get blur after system restart.
> > 
> > 
> > I fixed my problem, in Task Schedular is a TaskbarX task that you can edit. Open Task Scheduler and locate the task "TaskbarX" and open/edit that task. Once opened click the Actions Tab then click Edit at the bottom. In the Arguments section you will change the number -tbs=2 which is Blur. Replace with whatever you prefer for the desired style you want. 2=Blur, 5=OpaqueNow it remains as desired between restarts or shutdown.
> > In the event you want to change things, these are the settings.
> > -tbs=0 Default
> > -tbs=1 Transparent
> > -tbs=4 Transparent Gradient
> > -tbs=5 Opaque
> > -tbs=2 Blur
> > -tbs=3 Acrylic (can flicker)
> 
> Thank you for your reply. Problem solved.
> 
> I find the Task Scheduler and there was two task scheduled for TaskbarX, one using the current PC name and other using the prior PC name. I think I changed the PC name after installing TaskbarX, and then change my setup to transparent.

You're welcome and I'm glad you got it resolved. So you deleted one of them or edited as I described above? I only have one entry in Task Scheduler but also have not changed the PC name since I built the system years ago.

**Comment by ebdonato** [comment]
I deleted one, that one with -tbs=2, and leave the other one with -tbs=1. It was not necessary edit.

**Comment by Tw3ak3rz** [comment]
> I deleted one, that one with -tbs=2, and leave the other one with -tbs=1. It was not necessary edit.

Right on, since you wanted Transparent it did make it easy. Since I fixed my problem (and luckily was able to help you too) I am going to close this so it will be considered Resolved.
