### ISSUE TITLE
Blur style bug when using multiple monitors with hiding of taskbar

### ISSUE THREAD

**Issue by nitramleo** [ChrisAnd1998/TaskbarX#652]
On my PC I use the automatic hide of my taskbar, when I use this and try to use the blur style the blur only shows on my main monitor, the other look like they have the transparent style. I have noticed that if I set my taskbar to show at all time it works on all monitors, but I would love to use this and still be able to hide my taskbar. Thank you.

I have tried reinstalling multiple times just as a precaution but no positive result came as of the 4th time reinstalling.

https://i.imgur.com/KZ2d9Hb.png how it looks (taken from my 2nd monitor)
https://i.imgur.com/NaYOMmE.png how it is supposed to look (taken from my main monitor)

OS: Windows 10
Ver: 19042

**Comment by BijornCoote** [comment]
Me too.

**Comment by BijornCoote** [comment]
I think it happens when you press apply more than once.

**Comment by Wizard-Anorak** [comment]
I suffer from the same mistake

**Comment by maties22** [comment]
I noticed that too.

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
