### ISSUE TITLE
if I can propose some small features 

### ISSUE THREAD

**Issue by Nickyg001** [ChrisAnd1998/TaskbarX#656]
I would like to propose these small features, partly already feasible in windows but really badly done and managed, I think it would take your implementation of the windows taskbar to a higher level.

As you can see from the small preview in the attachment, the idea would be to be able to position the icons of the open software always in the standard way from left to right, but alternatively to be able to pin fixed icons on the bar, which can be positioned in 3 points of the bar, left (normal method), center or right.
So for example, having in pin the icons of your favorite software positioned on the right and additional software open if necessary on the left.
Currently you have to create a new folder with linked icons to put them on the right, but it's a mess when this thing could be done natively on the taskbar.

Another feature would be to be able to put folders on the right, and going up in mouse hover, the subfolders are cascaded so as to have for example a general folder where you can quickly access other subfolders without these being opened in the explorer . This is already half doable with add to toolbar, but it works poorly.
I would like the icon of the general folder on the bar and going above to open the subfolders menu ... a bit like what happens on Apple's OSX.

![106583142-0ec6f200-6545-11eb-8fd1-bcef4fc9a4ff](https://user-images.githubusercontent.com/33684734/121020456-aad96200-c7a0-11eb-882b-9191fff31f81.png)
![106794591-5b9bed00-6659-11eb-9b08-1dceb7b8fdf7](https://user-images.githubusercontent.com/33684734/121020470-ad3bbc00-c7a0-11eb-8521-863bd5515aba.png)

**Comment by markOteams** [comment]
@Nickyg001 
How did you make left and right group of icons?  I want to group my icons left and right of the center of the taskbar, and want the center to be blank and not have any icons be placed there.
thank you

**Comment by Nickyg001** [comment]
@markOteams  Simply with Photoshop :)

I created this graphic preview, to ask the developer to implement this function in order to put the icons on the right and left in addition I asked for a reinterpretation of the toolbar function which, as it is natively done in windows 10, works halfway , it is not very optimal and usable, even if at 80% it already natively does what I ask, only it does it in the wrong way.

Read the description of the post.

**Comment by markOteams** [comment]
@Nickyg001 thank you.  wanted to double double check as it looked like you'd actually done what I wanted.  Thank you for getting back.

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
