### ISSUE TITLE
taskbarX not working correctly on multi row taskbar

### ISSUE THREAD

**Issue by mahdy-asady** [ChrisAnd1998/TaskbarX#658]
it will center based on end of task items that has sit on next row
![Screenshot (8)](https://user-images.githubusercontent.com/60986124/121140154-c69b4180-c84e-11eb-9ec4-4caaa22f6f0f.png)

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
