### ISSUE TITLE
Configurator Wont Open

### ISSUE THREAD

**Issue by DannyRepublica** [ChrisAnd1998/TaskbarX#661]
Ive Download every possible free version and almost all work by centering the apps but none of them open the configurator. Im running Windows 2h21. Please help, thanks in advance

**Comment by LukoFoks** [comment]
@DannyRepublica I will try to assist you.
It can be somewhat missleading, but the actual "Taskbar.exe" file does not include configuration. A seperate file exists for this.

Therefore please follow these instructions:
1. Open Windows search (`Win + S`)
2. You're looking for file called "TaskbarX Configurator.exe"

If it doesn't show up check your installation folder. It has to contain "TaskbarX.exe" and "TaskbarX Configurator.exe". If this is not the case, download the latest version and unzip it again.

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
