### ISSUE TITLE
Taskbar acting funny post Win 10 update to ver 20H2

### ISSUE THREAD

**Issue by onlytanmoy** [ChrisAnd1998/TaskbarX#662]
Hiya @ChrisAnd1998 trust you are doing well.
Yesterday my Win 10 got updated to version 20H2 (OS Build19042.1052)
ever since that my Taskbar is acting all funny as you can see in the screenshot
![image](https://user-images.githubusercontent.com/48493659/121493027-523bdc00-c9cf-11eb-90da-fe3a493adfd8.png)
when I hover my mouse over, it gets normal somehow, not fully, see screenshot below AM/PM & year truncated
![image](https://user-images.githubusercontent.com/48493659/121493475-c8404300-c9cf-11eb-8766-91833e8d71aa.png)
And after some time, all icons disappear from the system tray and the task bar icons are no longer centered 😒

**Comment by AntonioLansang** [comment]
Yep. Same issue here. Taskbar is no longer centered.

**Comment by grumpydev** [comment]
The 1.7.0.0 pre release build sorted the issues I was having with 20H2:

https://github.com/ChrisAnd1998/TaskbarX/releases/tag/1.7.0.0

![image](https://user-images.githubusercontent.com/527013/121636147-5de6db80-ca7f-11eb-8735-f989c3e02ef4.png)

**Comment by onlytanmoy** [comment]
@grumpydev That's good to know, please can you tell me how to install? I downloaded the Release.zip file from that location you gave and unzipped that, don't see any installer file 🙄

**Comment by greatleapingcrab** [comment]
Good to know! Looking forward to the official releases

**Comment by yashpalgoyal1304** [comment]
this is a regression right?

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
