### ISSUE TITLE
The taskbarX was not changing configuration so I uninstalled it and cleared all the files. But after reinstalling, it is on the same configuration and does not change the congfiguration upon applying the settings .

### ISSUE THREAD

**Issue by Xitiz5775** [ChrisAnd1998/TaskbarX#663]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Version [e.g. 1909]

**Additional context**

**Comment by LukoFoks** [comment]
This issue happened to me too. It is a duplicate of #344 posted in 2020.
Please follow these steps:

1. Open your command prompt at TaskbarX.exe location
2. Run `taskbarx <command>`
3. You will find the right command [here](https://github.com/ChrisAnd1998/TaskbarX/issues/344) in the documentation

Did this resolve your issue?

**Comment by Xitiz5775** [comment]
I made another user account as the TaskbarX was not clearing it previous data , it is working properly now. But wait what if it happens again 😲.

**Comment by Xitiz5775** [comment]
Well @LukoFoks , thanks for your help.

**Comment by LukoFoks** [comment]
> I made another user account as the TaskbarX was not clearing it previous data , it is working properly now.

This is somewhat interesting. I searched for already closed issues like #657. It could help someone. I solved it with running a .bat file on startup with the right command.

**Comment by LukoFoks** [comment]
I found a great thread #641 that solves this issue very quickly [here](https://github.com/ChrisAnd1998/TaskbarX/issues/641#issuecomment-842329968). You don't have to create any .bat files, but it's actually the same.

**Comment by Xitiz5775** [comment]
> I found a great thread #641 that solves this issue very quickly [here](https://github.com/ChrisAnd1998/TaskbarX/issues/641#issuecomment-842329968). You don't have to create any .bat files, but it's actually the same.
> There are so many threads on this already, wow.

I have already done that but it does not work (sad emoji)

**Comment by Xitiz5775** [comment]
Update : I changed my microsoft login account to a local account and taskbar configurator started working properly.
