### ISSUE TITLE
Memory usage increasing over time

### ISSUE THREAD

**Issue by puchm** [ChrisAnd1998/TaskbarX#664]
I looked at the memory usage of the process in the task manager and it seems like usage is rising over time.
I tracked it over a minute and it rose by about 2000kB within that time so it seems like it is around 32kB per second.

When I open/close a program and the taskbar recenters, it drops back to around 3000kB.
It also doesn't seem to stop anywhere - I left it running for a few minutes and it's now at 24000kB.

Can you look into this?

**Comment by grumpydev** [comment]
I've checked this locally and have the same issue (running the latest pre release build) - I might have to stop running it and go back to a stupid and boring non-centered toolbar like a normal person 😱😱😱😁

**Comment by sxnch** [comment]
I've also been noticing this issue, and tried various fixes to no avail (even tried finding an old version of FalconX and it seemed to have the problem too, but to a slightly lesser extent). Hopefully it gets patched soon!

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
