### ISSUE TITLE
Taskbarx on rainmeter flicks to the left and back to the center when exiting fullscreen applications

### ISSUE THREAD

**Issue by Nagamakii** [ChrisAnd1998/TaskbarX#665]
**Describe the bug**
Taskbarx on rainmeter flicks to the left and back to the center when exiting fullscreen applications

**To Reproduce**
1. Go to a fullscreen application
2. Tab out
3. The taskbar will flick from the center to the left and back

**Expected behavior**
The taskbar will not move from the center when exiting an application

**Screenshots**
https://gfycat.com/illegalthoughtfuljoey

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Version 10.0.19042 Build 19042

**Additional context**
rzbt is set to 1, and cfsa is set to 0

Any tips on what to do?

**Comment by thomasthebear** [comment]
You may have the option to suspend **TaskbarX** when Full-Screen Applications are running and what you are seeing is it adjusting back to what it should be using the animations selected in the Options upon exiting the applications. 

_Just my thoughts of what could be causing it, so take it with a grain of salt..._

**Comment by Nagamakii** [comment]
> 
> 
> You may have the option to suspend **TaskbarX** when Full-Screen Applications are running and what you are seeing is it adjusting back to what it should be using the animations selected in the Options upon exiting the applications.
> 
> _Just my thoughts of what could be causing it, so take it with a grain of salt..._

Appreciate the response, cfsa is the setting that suspends taskbarx when fullscreen applications are open but ive got it set to disable (0). I will experiment more with it to see if it's that setting or something else!

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
