### ISSUE TITLE
Taskbar X Waiting for Shell_TrayWnd @Looper1 Error

### ISSUE THREAD

**Issue by shseah601** [ChrisAnd1998/TaskbarX#666]
**Describe the bug**
The app suddenly auto restart every few seconds.

**To Reproduce**
1. Start TaskbarX
2. Wait for few seconds
4. TaskbarX auto restarted

**Expected behavior**
It won't restart every few seconds.

**Screenshots**
-

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 20H2

**Additional context**
After trying to look into the console given by TaskbarX Configurator.

The following error log is recorded before the restart happens:
Waiting for Shell_TrayWnd @Looper1 | Error: Missing method 'instance object [TaskbarX] Accessibility.IAccessible::get_accRole(object)' from class 'System.Int32'.

Sometimes it appears once and restarts, Sometimes it appears twice before the console and the app auto restarted.

**Comment by shseah601** [comment]
Seems to be duplicated of #406 

The restart seems to appear randomly.

Is it possible to not restart the console when TaskbarX restarted? Or save the error log into some log file within the app, so that we are able to keep track of the error and easier for developers to debug the errors I think.

**Comment by phatakp** [comment]
I have the same issue. Waiting for a resolution

**Comment by shayvt** [comment]
Answered here #406

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
