### ISSUE TITLE
Micro gaps?

### ISSUE THREAD

**Issue by Haxorzz** [ChrisAnd1998/TaskbarX#667]
Noticed some tiny gaps between the taskbar and my screen, this also prevents me from clicking the "show desktop" button if I move my mouse to the bottom right corner or press the windows button with my mouse at the bottom edge as well etc...
![bGNywnCaUJ](https://user-images.githubusercontent.com/20832273/121790798-a4008400-cbd2-11eb-8b4f-ef97403de0a9.jpg)
![ULkwSCCRyA](https://user-images.githubusercontent.com/20832273/121790799-a4991a80-cbd2-11eb-90c1-1e1ec4cb1066.jpg)

**Comment by sunZHUcs** [comment]
I'm having the same issue, was just about to make my own thread. This is really annoying for me and I have the corner radius set to 0 in settings.

**Comment by tjpricey** [comment]
I have the same isssue also. Tiny gap below bottom of taskbar. The desktop is clickable within it. I've tried latest stable release & 1.7 beta. Both exhibit same problem.

Windows Version 10.0.19042 Build 19042

Desktop resolution: 5120x1440
Display Scaling: 110%
![image](https://user-images.githubusercontent.com/64754398/122123312-c0e0c580-ce25-11eb-8b4a-315d2ed929bf.png)

**Comment by MathLeoCodes** [comment]
some progress on this bug? I have it, and a need a solution :/

**Comment by Nuzair46** [comment]
Is there a way to remove this?
I think it did a permanent damage on my system. Uninstalling taskbarx doesn't solve this issue.

**Comment by MathLeoCodes** [comment]
So, I have a "half-solution", using the RoundedTB (you can download it from Microsoft Store) you can set the "Margin" to "-1"

**Comment by MathLeoCodes** [comment]
And another solution, uninstall the 1.7.0.0 version and use the 1.6.9.0

**Comment by f-batiri** [comment]
> 
> 
> Is there a way to remove this?
> I think it did a permanent damage on my system. Uninstalling taskbarx doesn't solve this issue.

After Uninstalling TaskbarX, find windows explorer in processes of task manager and right click, then restart.

> 
> 
> And another solution, uninstall the 1.7.0.0 version and use the 1.6.9.0

Thank you very much. Version 1.6.9 works fine. I was going to give up on TaskbarX for this issue.

**Comment by auraanyway** [comment]
same issue on latest, 1080p resolution, on both monitors

**Comment by Shibbyz** [comment]
How do you guys download the 1.6.9.0 version? I can only find the source code for that version but not a .zip with exe files. This micro gap is driving me crazy..

**Comment by f-batiri** [comment]
@Shibbyz 
> How do you guys download the 1.6.9.0 version? I can only find the source code for that version but not a .zip with exe files. This micro gap is driving me crazy..

[https://github.com/ChrisAnd1998/TaskbarX/releases/tag/1.6.9.0](https://github.com/ChrisAnd1998/TaskbarX/releases/tag/1.6.9.0)
Extract ( _TaskbarX_1.6.9.0_x64.zip_ if on 64bit windows) and run TaskbarX.exe.

**Comment by Shibbyz** [comment]
@f-batiri Thank you!

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
