### ISSUE TITLE
A way for windows to "flow" behind the taskbar

### ISSUE THREAD

**Issue by Haxorzz** [ChrisAnd1998/TaskbarX#668]
The blur effect is nice and all but maximizing windows obviously doesn't go past the task bar, but I feel this under-utilizes the opacity/blur settings since I'd love windows to go behind it
For example maximizing past the taskbar all the way to the edge of the screen would be more immersive and look nicer whilst the taskbar is still shown
Hiding the taskbar and revealing it kinda works but I like to see my taskbar at all times.

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
