### ISSUE TITLE
Not working all time. 

### ISSUE THREAD

**Issue by starkexpo42** [ChrisAnd1998/TaskbarX#670]
When I restart my pc it's goes to left side. it's stop working after restart. it's is more irritating. solve this issue as soon as possible. 
use the command and patched to fix it at center.

**Comment by ThijmenGThN** [comment]
I can vouch for this, its so annoying having to manually start it on each boot.

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
