### ISSUE TITLE
Windows 11 Leak 

### ISSUE THREAD

**Issue by designgears** [ChrisAnd1998/TaskbarX#671]
Is it possible this is a fake and using your app?!

https://www.theverge.com/2021/6/15/22535123/microsoft-windows-11-leak-screenshots-start-menu

**Comment by designgears** [comment]
Maybe it's real; https://twitter.com/roadrasher7/status/1404839052579250177

Did you just create the Windows 11 start bar without realizing it?! LOL

**Comment by Picoseconds** [comment]
It seems real, official screenshots of Windows 10X have this behaviour too and I wouldn't be surprised at all
