### ISSUE TITLE
Not working on Windows 11 Beta, does not launch.

### ISSUE THREAD

**Issue by amogosgaming** [ChrisAnd1998/TaskbarX#673]
**Describe the bug**
Does not launch on Windows 11 Beta.

**To Reproduce**
Launch the program on the Windows 11 Beta.

**Expected behavior**
Expected it either to keep restarting (crashing) explorer.exe, or an error message

**Desktop:**
 - OS: Windows 11
 - Version Dev
 - Build 21996.1

**Comment by shayvt** [comment]
In windows 11 the taskbar is centered. 
Why do you need TaskbarX ?

**Comment by amogosgaming** [comment]
Just wanted to note, and yes I do know that the taskbar can be swapped to either left, or middle.
