### ISSUE TITLE
Option to center start button with other icons 

### ISSUE THREAD

**Issue by eliotexe** [ChrisAnd1998/TaskbarX#674]
**Is your feature request related to a problem? Please describe.**
Cannot center start button

**Describe the solution you'd like**
An option to center the start button and animate it like all the other icons. Similar to how Windows 11 seems to be. 

**Describe alternatives you've considered**
I have looked for other solutions with no luck.

**Comment by rlaphoenix** [comment]
Duplicate of https://github.com/ChrisAnd1998/TaskbarX/issues/529

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
