### ISSUE TITLE
future of taskbarx

### ISSUE THREAD

**Issue by Fefedu973** [ChrisAnd1998/TaskbarX#675]
is taskbar x is going to be stopped with the new windows 11 ?

**Comment by ChrisAnd1998** [comment]
The main feature TaskbarX was all about is centering the taskbar and thats not needed anymore. I think I'll just continue adding different modifications to the taskbar on Win 11.  And also focus on the desktop.

**Comment by Fefedu973** [comment]
is it possible to add the feature blur (blur without acrylic) and apply it not only for taskbar but for tray icon list notification center and new windows start menu ?

**Comment by Kazlehoff** [comment]
If you could allow for centering icons with the start button on the left, that would be awesome. my only gripe about win11.

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
