### ISSUE TITLE
Unable to click taskbar buttons

### ISSUE THREAD

**Issue by theFireProject** [ChrisAnd1998/TaskbarX#676]
### Short description of the bug
The taskbar is cut off by 1 pixel at the bottom while TaskbarX is running. This means that I cannot click any buttons on the taskbar when I move the mouse pointer to the bottom of the screen.

### Steps to reproduce

Steps to reproduce the bug:
1. Start TaskbarX (just downloaded and extracted, default settings)

Steps to restore the taskbar to its normal state (without TaskbarX):
1. Stop TaskbarX
2. Restart Windows Explorer

### Screenshots and Detailed Description

These are two full resolution screenshots of my 1920*1080 screen. You have to closely inspect the bottom of the taskbar. Ideally, you have to use an image viewer that clearly displays every pixel and doesn't blur the edges of pixels when you zoom in very far:

![image](https://user-images.githubusercontent.com/61639215/122587964-cb39d400-d05e-11eb-8d17-7e1016b3ddd1.png)
![image](https://user-images.githubusercontent.com/61639215/122587967-cc6b0100-d05e-11eb-91b8-f2a6197d811b.png)

Usually the taskbar is 30 pixels high on my screen. I use small taskbar icons, 100% scale and a 1920*1080 screen. When TaskbarX is running, it is only 29 pixels high, because one row of pixels is cut off at the bottom of the taskbar. This becomes clear when you look at the taskbar icons of my open windows. You can see that the thin grey line below each icon becomes even smaller (from 2 pixels to 1 pixel high). In the single row of pixels where the taskbar is cut off you can instead see the bottom of the desktop background. If you right click at the bottom of the screen, the desktop context menu opens.

![image](https://user-images.githubusercontent.com/61639215/122588898-ebb65e00-d05f-11eb-83da-1328379d2ec1.png)
![image](https://user-images.githubusercontent.com/61639215/122588954-f83ab680-d05f-11eb-844f-7edd63ff5218.png)

![image](https://user-images.githubusercontent.com/61639215/122590133-692e9e00-d061-11eb-8ccc-bbff2c8d0d69.png)
![image](https://user-images.githubusercontent.com/61639215/122590028-48fedf00-d061-11eb-9a2a-8a8b6c41b42f.png)

### Desktop:
 - OS: Windows 10 Home
 - Version: 21H1
 - Build: 19043.1052
 - TaskbarX: 1.7.0.0

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
