### ISSUE TITLE
The TaskbarX configurator Doesn't save settings and TaskbarX crashes when you apply them

### ISSUE THREAD

**Issue by Leofergz** [ChrisAnd1998/TaskbarX#677]
I've used it for about a week now and out of nowhere the configuration on the taskbar went back to default, I checked task manager and I see that the taskbar x process isn't even running. and when I open taskbarX again and the configurator and try to make a change and apply it crashes the TaskbarX process.

I have tried re-installing it many times but the same thing happens and I can't make any changes to my taskbar because when I try to apply the changes it crashes TaskbarX. It's very annoying and I don't know what to do now.

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
