### ISSUE TITLE
Tray icon disappears

### ISSUE THREAD

**Issue by theFireProject** [ChrisAnd1998/TaskbarX#678]
### Short description
Multiple tray icons disappear after left clicking the TaskbarX tray icon. This problem persists after restarting TaskbarX.

### Steps to reproduce

Steps to reproduce the bug:
1. Start up the computer
2. TaskbarX starts automatically
3. Left click the TaskbarX tray icon

Steps to restore the taskbar and system tray to its original state (without TaskbarX):
1. Stop TaskbarX
2. Restart Windows Explorer

### Screenshots and Detailed Description

Usually the tray icon looks like this:

![image](https://user-images.githubusercontent.com/61639215/122595240-71d6a280-d068-11eb-82e7-2faa0481177e.png)
[Complete screen](https://user-images.githubusercontent.com/61639215/122595234-70a57580-d068-11eb-9cbe-409c8805a353.png)

The system tray seems to be broken once I left click the TaskbarX tray icon. It disappears together with all other icons after the TaskbarX tray icon. Only one *empty* icon remains. In the screenshot, you cannot see the mouse pointer but I'm pointing at this empty tray icon. It doesn't have an icon (small image), it doesn't have a tooltip and it doesn't do anything when it is clicked:

![image](https://user-images.githubusercontent.com/61639215/122595250-7602c000-d068-11eb-91fd-8728e19932e0.png)
[Complete screen](https://user-images.githubusercontent.com/61639215/122595247-756a2980-d068-11eb-9113-f3e512e97d73.png)

There are no icons after that one empty icon. When I reopen the tray, it becomes smaller:

![image](https://user-images.githubusercontent.com/61639215/122595256-77cc8380-d068-11eb-8ff8-4ff1d5665e91.png)
[Complete screen](https://user-images.githubusercontent.com/61639215/122595253-769b5680-d068-11eb-92ea-1e5dcc947e79.png)

If you stop TaskbarX, the empty tray icon will disappear, but the other tray icons will still be missing. To fix this problem, you have to restart Windows Explorer. All missing tray icons will reappear.

But as soon as you start TaskbarX again, the same icons as before will disappear once more and the empty icon will be there again, too.

It is possible to fix the empty tray icon and display the TaskbarX tray icon correctly again. But this won't fix the other missing tray icons. To do that, you have to disable the TaskbarX tray icon in the Configurator, click *Apply*, enable the tray icon and click *Apply* once more. Now the empty tray icon is gone and the TaskbarX tray icon is displayed and working, but the other tray icons that disappeared before are still missing.

### Desktop:
 - OS: Windows 10 Home
 - Version: 21H1
 - Build: 19043.1052
 - TaskbarX: 1.6.9.0

**Comment by knxrb** [comment]
Yeah, I have this same issue after recently purchasing and using TaskbarX myself. Once TaskbarX starts, some of my icons disappear entirely, one goes blank with no icon but still has its place, and others move from their place on the visible task tray into the little "more icons" pop out area instead; for example, the icons from HWiNFO64 for CPU and GPU temperature move from their position.

OS: Windows 10 Pro (Version	10.0.19043 Build 19043)
TaskBarX: 1.7.1.0
Purchased and installed via Windows Store.

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
