### ISSUE TITLE
Left and right taskbar is broken

### ISSUE THREAD

**Issue by theFireProject** [ChrisAnd1998/TaskbarX#679]
### Description
The taskbar is broken when it is displayed at the left or right side of the screen. This might be connected to a problem that occurs when the taskbar is positioned at the bottom: #676. All in all it only seems to work perfectly fine at the top.

### Steps to reproduce

1. Start TaskbarX (just downloaded and extracted, default settings)
2. Change the position of the taskbar

### Screenshots

![image](https://user-images.githubusercontent.com/61639215/122596836-c0853c00-d06a-11eb-92ee-ed3222350161.png)

![image](https://user-images.githubusercontent.com/61639215/122596837-c1b66900-d06a-11eb-924e-71299008841a.png)

![image](https://user-images.githubusercontent.com/61639215/122596839-c24eff80-d06a-11eb-806f-083d8a4c2a99.png)

![image](https://user-images.githubusercontent.com/61639215/122596842-c2e79600-d06a-11eb-8355-95497a7ebb30.png)

### Desktop:
 - OS: Windows 10 Home
 - Version: 21H1
 - Build: 19043.1052
 - TaskbarX: 1.7.0.0

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
