### ISSUE TITLE
Windows 10 system dark theme

### ISSUE THREAD

**Issue by Martin5001** [ChrisAnd1998/TaskbarX#68]
Would it be possible to change app controls colour to black/grey shades depending on Windows set to light/dark mode? The current system setting can be retrieved from the registry at 
`HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize`
where the `AppsUseLightTheme` and `SystemUsesLightTheme` values are the ones to look for.
(Also notice that older versions of Windows 10 used only one of these options when dark mode was first introduced and the ability to change theme for apps and system independently was added later on, so this might cause some compatibility issues if not handled.)

I know that controls colours can be changed in Winforms, but I don´t know if it goes for all of them (Some people say Combobox cannot be styled). This is a minor feature anyway, but it would be pretty neat, I think.

**Comment by ChrisAnd1998** [comment]
Update 1.5.4.0 ;)
