### ISSUE TITLE
Primary screen icons not centering.

### ISSUE THREAD

**Issue by Slash1y** [ChrisAnd1998/TaskbarX#680]
Hello,

Idk if this is a known issue for the latest version of TaskbarX, but seems like primary screen won't center for some reason. Using the Rainmeter version of TaskbarX.

No idea as to why this happens at all. I tried setting `cpo` to 1 in the config, and it doesn't seem to do it(refreshed loads of times. And that doesn't do it either.

**Comment by Slash1y** [comment]
I seem to have fixed the issue by going down to a lower version. I was running on version 1.7.0.0 and that seemed to be causing the problem, as version 1.6.9.0 works just fine. I wanted to see if there was a difference.

**Comment by meiaihara06** [comment]
I have same problem. i just updated after a month (or two? i don't remember) but 1.7.0.0 only centers second display.
I also tried cpo=0 and playing with screen modes (extended, duplicate, etc.) and they didn't work.

![image](https://user-images.githubusercontent.com/46371349/122643663-4dd99680-d126-11eb-9156-0b83a870927b.png)

![tmp](https://user-images.githubusercontent.com/46371349/122643825-3949ce00-d127-11eb-89bd-4d0f4fd20b35.png)

**Comment by meiaihara06** [comment]
I also tried TaskbarX with Configurator instead of Rainmeter Skin
The problem still exists.

**Comment by meiaihara06** [comment]
I tried pre-release 1.7.1 to see if it is fixed. it wasn't.
then I Enabled "Show Console"
and this was the output
![image](https://user-images.githubusercontent.com/46371349/122665160-dace2f80-d1ba-11eb-82b0-fa8daf995663.png)

and everytime i open or close an app, this error appears again.

**Comment by Slash1y** [comment]
> I tried pre-release 1.7.1 to see if it is fixed. it wasn't.
> then I Enabled "Show Console"
> and this was the output
> ![image](https://user-images.githubusercontent.com/46371349/122665160-dace2f80-d1ba-11eb-82b0-fa8daf995663.png)
> 
> and everytime i open or close an app, this error appears again.

To solve this issue, downgrade to 1.6.9.0. Seems to fix it.
