### ISSUE TITLE
Application creates a space between taskbar and the bottom of the screen

### ISSUE THREAD

**Issue by TheSpiffyOne** [ChrisAnd1998/TaskbarX#682]
**Describe the bug**
When using taskbarx it creates a noticeable crease between the bottom the screen and the taskbar which is very annoying

**To Reproduce**
Use Taskbarx

**Expected behavior**
I expect to see no space between the bottom of the screen and the taskbar, like on my second screen, but on my primary one it creates this line.

**Screenshots**
![image](https://user-images.githubusercontent.com/86152662/122640935-cb8fa900-d10a-11eb-98f4-3f82c1f10d09.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 1.7.0.0

**Comment by Dekamir** [comment]
Can reproduce. Happens on 1.7.0.0. Doesn't happen on version 1.6.9.0. 

To fix the issue temporarily, one can disable TaskbarX and restart Windows Explorer (and revert one version if you want to continue using).

**Comment by ChrisAnd1998** [comment]
Fixed in the pre-release ;) https://github.com/ChrisAnd1998/TaskbarX/releases/tag/1.7.1.0

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
