### ISSUE TITLE
Taskbar does not end with the lower edge of the screen

### ISSUE THREAD

**Issue by Perrin11a** [ChrisAnd1998/TaskbarX#683]
The taskbar does not end with the lower edge of the screen - there remains an ugly 1-2mm gap (ultrawide monitor 49 ", resolution 5120x1440). It doesn't matter whether the symbols are in the middle or on the left. Nor does" light "or" dark "play Role. Scaling also not (100% or 125% - regardless).

Regards
Michael

**Comment by meiaihara06** [comment]
fixed in [1.7.1.0](https://github.com/ChrisAnd1998/TaskbarX/releases/tag/1.7.1.0)

check out #682

**Comment by SeriousHoax** [comment]
> fixed in [1.7.1.0](https://github.com/ChrisAnd1998/TaskbarX/releases/tag/1.7.1.0)
> 
> check out #682

It fixed the bug for the left side but not the right side for the show desktop button.

**Comment by Perrin11a** [comment]
It helps, Thanks! But:

 

1. Another mistake:

If I select the theme "Windows 11" after a reboot, as indicated during the installation, the font in Windows Explorer is only light gray and therefore very difficult to see against the white background.

 

 

2. Another error with the Windows 11 dark skin pack, which I also bought today:

The background image is missing and is "replaced" by an orange thumbnail from Windows 10.

The "dark colors" also seem to be wrong. They are more brown than black. I am not satisfied with that.

 

Regards

Michael Cronbach

 

 

 

Von: SeriousHoax ***@***.***> 
Gesendet: Sonntag, 20. Juni 2021 16:37
An: ChrisAnd1998/TaskbarX ***@***.***>
Cc: Perrin11a ***@***.***>; Author ***@***.***>
Betreff: Re: [ChrisAnd1998/TaskbarX] Taskbar does not end with the lower edge of the screen (#683)

 

fixed in 1.7.1.0 <https://github.com/ChrisAnd1998/TaskbarX/releases/tag/1.7.1.0> 

check out #682 <https://github.com/ChrisAnd1998/TaskbarX/issues/682> 

It fixed the bug for the left side but not the right side for the show desktop button.

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
