### ISSUE TITLE
Allowing window to sweep down to edge!

### ISSUE THREAD

**Issue by Rish704** [ChrisAnd1998/TaskbarX#684]
I'd like the taskbar to allow any window or application on the screen to reach or sweep down right till the bottom of the screen rather than stopping it at the taskbar and taskbar showing the background wallpaper instead.
![image](https://user-images.githubusercontent.com/72202747/122667837-8fc01680-d1d2-11eb-86fb-6977b9df7a51.png)
One could always hide the taskbar but I'd like to keep it on the screen.

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
