### ISSUE TITLE
Doesn't even work.

### ISSUE THREAD

**Issue by jonatanelgstrom** [ChrisAnd1998/TaskbarX#686]
TaskbarX refuses to center icons and undoes any changes I have made in the configuration program whenever I try to launch it.

**Comment by Slash1y** [comment]
@jonatanelgstrom I would suggest going down to version 1.6.9.0. And try and see if it does anything. I had an issue with 1.7.0.0, where it did not center icons.

**Comment by mgroover** [comment]
Same thing here with 1.7.0, on a Dell XPS13 2020 4k screen + Samsung Oddyssey G9 49" 5120*1440 screen. 1.6.9 works just fine!

**Comment by ResolvedSpice6** [comment]
In the 1.7.0.0 it does not iven center the icons, any solution?
![imagen_2021-06-23_155725](https://user-images.githubusercontent.com/86378058/123160021-b3d26080-d43b-11eb-96c7-9e58d46b82a1.png)

**Comment by Slash1y** [comment]
> In the 1.7.0.0 it does not iven center the icons, any solution?
> ![imagen_2021-06-23_155725](https://user-images.githubusercontent.com/86378058/123160021-b3d26080-d43b-11eb-96c7-9e58d46b82a1.png)

@ResolvedSpice6 I would suggest using 1.6.9.0 to fix this. No idea if Chris has released a new version fixing the bug.

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
