### ISSUE TITLE
TaskbarX 1.7.0.0 

### ISSUE THREAD

**Issue by gabri25ele** [ChrisAnd1998/TaskbarX#687]
I have updated to 1.7 version and a empty line under the taskbar is present:

![Immagine](https://user-images.githubusercontent.com/33927879/122721130-9735fd00-d270-11eb-8da5-257548a64d14.png)

back to version 1.6.9.0, the empty line is gone

![Immagine2](https://user-images.githubusercontent.com/33927879/122721244-b6cd2580-d270-11eb-905b-537df4d145b4.png)

**Comment by colenh** [comment]
I also have this issue.

**Comment by TitanBlast** [comment]
For some reason even if I downgrade to 1.6.9.0 it also happens for me. 
![Icmu9](https://user-images.githubusercontent.com/54638868/122980858-74ebce80-d399-11eb-80b8-fea0ed9f909c.png)

**Comment by ResolvedSpice6** [comment]
In the version 1.7.0.0 the task does not center. Any kind of solution? 
![imagen_2021-06-23_155130](https://user-images.githubusercontent.com/86378058/123159309-e0d24380-d43a-11eb-9c63-20b06aa2b4a0.png)

**Comment by gabri25ele** [comment]
> 
> 
> For some reason even if I downgrade to 1.6.9.0 it also happens for me.
> ![Icmu9](https://user-images.githubusercontent.com/54638868/122980858-74ebce80-d399-11eb-80b8-fea0ed9f909c.png)

try uninstall completely and reainstall

**Comment by ChrisAnd1998** [comment]
Fixed
