### ISSUE TITLE
disabling small taskbar makes a line

### ISSUE THREAD

**Issue by guizinhomartinez** [ChrisAnd1998/TaskbarX#692]
**Describe the bug**
i like a clean small taskbar but my friend like big icons so he changed on settings to make icons bigger on taskbar but for no reason it appeared a giant space between the taskbar and the final piece of the screen

**To Reproduce**
1. Go to 'taskbar on the appereance tab'
2. Click on 'use smal buttons'

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/81656897/123299300-c017f580-d4ef-11eb-8838-6c183c55e5f7.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Version 1909]

**Additional context**

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
