### ISSUE TITLE
taskbar appears when clicked on other monitor

### ISSUE THREAD

**Issue by YaBoiHarry** [ChrisAnd1998/TaskbarX#693]
I have 2 monitors. If I'm watching a YouTube video on monitor 1 in fullscreen, the taskbar on monitor 1 disappears as it should, but if I click on the taskbar on monitor 2, the taskbar in monitor 1 shows up over the YouTube video. Is this a known issue and how can I fix it?
![taskbar_issue](https://user-images.githubusercontent.com/74841807/123381965-3ba49180-d546-11eb-8051-71e5e97b9c9b.png)

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
