### ISSUE TITLE
Startup problem

### ISSUE THREAD

**Issue by AldosSenpai** [ChrisAnd1998/TaskbarX#694]
I uninstalled TaskbarX to update it to the latest one so I use the configurator and after deleted the TaskbarX folder. But when I reinstalled and made a shortcut link it doesnt work. In the startup menu, it still has the startup for the old version. How do I fix this?

**Comment by m0hith** [comment]
I recommend removing the existing files in startup menu and also delete all the shortcuts you have created (if any). Uninstall the current version using TaskbarX configurator and delete the folder. Place the folder with new version files in the required directory and re-install.

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
