### ISSUE TITLE
A normal sized bottom taskbar has an empty line below it when on maximized window when switch back to Default on maximized window is turned on.

### ISSUE THREAD

**Issue by Tranken587** [ChrisAnd1998/TaskbarX#695]
**Describe the bug**
A normal sized bottom taskbar has an empty line below it when on maximized window when switch back to Default on maximized window is turned on.
**To Reproduce**
1. Use a regular size taskbar (not small)
2. Go to TaskbarX Configurator
3. Click on Style
4. Choose Transparent style
5. turn on "Switch back to Default on maximized window
6. go to a maximized window
7. See a slim transparent line below the taskbar

**Expected behavior**
No transparent line below the taskbar
**Screenshots**
![xbxpc4jtug771](https://user-images.githubusercontent.com/86501027/123494076-7274b900-d5d3-11eb-84ec-2cf77b391aff.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 21H1

**Additional context**
I was using a laptop.

**Comment by lolguyXDDD** [comment]
Update to 1.7.1.0, this is patched there.

**Comment by Joe-Joi** [comment]
this was fixed in v1.71. try it

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
