### ISSUE TITLE
Glitches in the Right-Side of the Taskbar

### ISSUE THREAD

**Issue by jon-spec** [ChrisAnd1998/TaskbarX#696]
**Describe the bug**
The right-side taskbar glitches when you click anything on it.

**Screenshots**
![image](https://user-images.githubusercontent.com/83124057/123510010-a49b1f00-d696-11eb-9a28-4674105507c8.png)

 - OS: Windows 10 Home
 - Version 21H1

**Additional context**
If I hover the mouse over the affected area after it glitches it goes back to normal but still glitches if you click something on it.

**Comment by johanCloud** [comment]
I have the same issue, stopping Taskbarx "solves" it.

**Comment by jon-spec** [comment]
> I have the same issue, stopping Taskbarx "solves" it.

Thanks, but that temporarily solves the issue. But I can live with that.

**Comment by johanCloud** [comment]
The issue came back to me so I deleted the IconCache.db file in appdata\local\ directory and restarted the pc. Now the issue is gone.

**Comment by jon-spec** [comment]
> 
> 
> The issue came back to me so I deleted the IconCache.db file in appdata\local\ directory and restarted the pc. Now the issue is gone.

I did the same and haven't got a glitch yet. You're a life saver.

I'm going to close this issue with this comment. I'll make a new one if I have any more issues.

Thanks again @johanCloud .
