### ISSUE TITLE
Uninstalled still getting taskbarx window on each boot

### ISSUE THREAD

**Issue by shyim** [ChrisAnd1998/TaskbarX#697]
**Describe the bug**
![image](https://user-images.githubusercontent.com/6224096/123545222-4bdf8b00-d757-11eb-8cb5-b547e57a948e.png)

**To Reproduce**
- Install from Microsoft Store
- Uninstall
- Getting that error on each boot

**Expected behavior**
A clear uninstall without annoying window on each boot

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 21390.2025

**Additional context**

**Comment by shyim** [comment]
Deleted the following regedit keys and popup is now gone:
```
HKEY_CLASSES_ROOT\taskbarx
HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\ApplicationAssociationToasts\AppXawa9afd499jcr7q33jw4avavgazw8dvm_taskbarx
HKEY_CURRENT_USER\Software\Microsoft\Windows\Shell\Associations\UrlAssociations\taskbarx
HKEY_CURRENT_USER\Software\Microsoft\Windows NT\CurrentVersion\HostActivityManager\CommitHistory\40210ChrisAndriessen.FalconX_y1dazs5f5wq00!TaskbarX
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Schedule\TaskCache\Tasks\{9028F20F-13A8-49A1-AE9D-FDDAABEA8B59}
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Schedule\TaskCache\Tree\TaskbarX DESKTOP-PGUGN2Fshyim
```

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
