### ISSUE TITLE
 virus notification

### ISSUE THREAD

**Issue by Str7xx** [ChrisAnd1998/TaskbarX#698]
hi. could i help someone? when I download taskbarx I get a notification from the antivirus that the taskbarx.exe file contains a Trojan. is it false-positive can the program really transmit the virus?

**Comment by KrunoSaho** [comment]
Is this similar to what you get?
https://www.virustotal.com/gui/file/a81796e13173dcc5db5bc578cd40df0c15d6487fff43b06019952f7558745489/detection

**Comment by Str7xx** [comment]
Yes

**Comment by KrunoSaho** [comment]
False positive.

**Comment by Str7xx** [comment]
Thank you for help.

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
