### ISSUE TITLE
Highlight to display open apps is thinner when large icons are used

### ISSUE THREAD

**Issue by stephen147** [ChrisAnd1998/TaskbarX#700]
**Describe the bug**
When large icons are used the highlight shown here is very thin.

Possibly related: https://github.com/ChrisAnd1998/TaskbarX/issues/683

**To Reproduce**
1. Change the tray icons to large.

**Expected behavior, this is what is suppose to show.**
![image](https://user-images.githubusercontent.com/14054664/123560493-66872380-d79a-11eb-9c0c-1836ab7fede8.png)

**Screenshots Problem**
![image](https://user-images.githubusercontent.com/14054664/123560514-8f0f1d80-d79a-11eb-9724-acb4ba6564ba.png)

**Desktop (please complete the following information):**
 - Microsoft Windows 10 Pro (Build 19042)

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
