### ISSUE TITLE
"Show Desktop Button" can't be clicked fully

### ISSUE THREAD

**Issue by ethnjnr** [ChrisAnd1998/TaskbarX#701]
**Describe the bug**
When trying to click the show desktop button on the lower right, it can't be clicked. Only the upper and middle part of the small rectangle is functional, not the lower part.

**To Reproduce**
Use Taskbarx

**Expected behavior**
I expect to fix this bug by clicking the show desktop button in the lower portion of the small rectangle

**Screenshots**
none

**Desktop (please complete the following information):**

OS: Windows 10
Version 1.7.1.0

**Comment by Double-A-92** [comment]
Same bug as #717 which seems more active.

**Comment by yashpalgoyal1304** [comment]
it's sad that ppl here are opening soo many duplicates :(

**Comment by yashpalgoyal1304** [comment]
even though #717 seems more active, but taking a bird eye skimming through that, the discussion there didnt seem to go into much else depth other than mentioning the older working version.

**Comment by juninholiveira** [comment]
I'm havind this problem too! It's really annoying. The "Show Desktop Button" can't be clicked on the extreme lower right corner. And the problem persists after unninstalling.

**Comment by yashpalgoyal1304** [comment]
@juninholiveira i have moved over the input from other issue which contains the fixing step. try those :)

**Comment by juninholiveira** [comment]
@yashpalgoyal1304 Yes, your steps indeed solved the problem for now! I'll stay in 1.6.9 for now, but I'll wait for a proper fix on 1.7.3 cause I really don't like using out of date software :S But thank you!

**Comment by Falki-git** [comment]
> it's sad that ppl here are opening soo many duplicates :(
> #785
> #782
> 
> even though #717 seems more active, but taking a bird eye skimming through that, the discussion there didnt seem to go into much else depth other than mentioning the older working version.

That was my bad, I opened #717, although I did search through existing issues and at that time didn't find a similar one. Apologies

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
