### ISSUE TITLE
Flickering on second monitor or application open full screen on the primary monitor

### ISSUE THREAD

**Issue by CherriBearxx** [ChrisAnd1998/TaskbarX#702]
**Describe the bug**

When I have an application open on my primary monitor and nothing open on the second monitor the bar flickers on the second monitor.

![image](https://user-images.githubusercontent.com/78436268/123602459-aa0c7c80-d7f0-11eb-9718-0a7b9a825df6.png)
These are my settings and regardless of the style this bug occurs.

The bug only occurs when the application is open to full screen on the primary monitor and there is nothing open on the second monitor. When a full screen application is open on the second monitor the flickering stops regardless of what happens with the primary monitor.

**To Reproduce**

1. Open an application only on the primary screen
2. Make sure it is ful;l screen
3. See error on secondary monitor as taskbar flickers

**Expected behavior**

I was hoping that if I have nothing open on my second monitor and something fullscreen on my primary monitor 

**Screenshots**

**Desktop (please complete the following information):**

Windows 10 
version 10.0.19042 

**Additional context**

I cannot find an error code but I can see the flickering of the taskbar regardless of the 'Style' I have it set to transparent at this point.

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
