### ISSUE TITLE
Search bar glitching after uninstalling TaskbarX

### ISSUE THREAD

**Issue by m0hith** [ChrisAnd1998/TaskbarX#703]
**Describe the bug**
Even after uninstallation and completely removing all the files, Taskbar glitches on the search box on startup, and every time I restart windows explorer (to reset taskbar functioning), and glitching stops when I hover my cursor on that search box.

**To Reproduce**
1. Go to Taskmanager
2. Enable search box in the taskbar (if not enabled)
3. Find Windows Explorer and Restart it
4. See an error

**Expected behavior**
Normal search box without a glitch

**Screenshots**
![image](https://user-images.githubusercontent.com/53620651/123629095-7aca2f80-d831-11eb-9471-1fb4de13c37b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home Single Language
 - Version 21H1

**Additional context**
While glitching:
- the pinned icons don't appear yet
- Also while glitching, the text inside the search box "Type here to search" keeps moving to the left and center.
- The magnifying glass icon in the search box doesn't appear until I hover my cursor on it and the glitch disappears.

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
