### ISSUE TITLE
Chopped-up Taskbar

### ISSUE THREAD

**Issue by Merz26** [ChrisAnd1998/TaskbarX#704]
**Problem?**
The whole taskbar is lost a few pixels, showing the wallpaper and and context menu of the desktop on right click.
Cause: switching to small taskbar icon (and then switch back!?)
The taskbar is still functional within its area.

**To Reproduce**
Switching to small "taskbar icon"
Switch back
Done =))

**Expected behavior**
The desktop is shown underneath the taskbar, after switching back, taskbar was chopped (↓↓↓↓↓↓)
**Screenshots**
![image](https://user-images.githubusercontent.com/85775157/123645344-74977b80-d850-11eb-9b48-b02963172242.png)

**Desktop :**
 - Version 1.7.something

**Comment by rzkalqdr** [comment]
can confirm this happens to me too -- except that i don't have to do extra steps, it's just chopped up for me by default upon installing.

**Comment by Merz26** [comment]
idk, only happen if i switch to that thing

**Comment by Li-An** [comment]
Same problem here.

**Comment by noxusdev** [comment]
i have same problem..

**Comment by Joe-Joi** [comment]
yeah same problem.. v1.7

**Comment by Asad-13** [comment]
> guys, uninstall the 1.7 and try 1.71. It worked for me

I do want to try that, but some people on other issues are saying that the chop off will be retained on the right end of the taskbar.

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
