### ISSUE TITLE
unable to find any setup/configurator file

### ISSUE THREAD

**Issue by SvaiskiS** [ChrisAnd1998/TaskbarX#707]
**Describe the bug**
i cannot find any file to open to setup the taskbarx

**To Reproduce**
i downloaded the latest .zip through github and i cannot find any .exe file that i'm told i will find.

**Desktop **
OS: windows 10 home
![unnamed](https://user-images.githubusercontent.com/69459800/124016542-7139f680-d9ee-11eb-82ec-1ea6e8e12744.png)

**Comment by GameBoyYeet** [comment]
go inside TaskbarX Configuator

**Comment by GameBoyYeet** [comment]
it seems like you downloaded the source code, try downloading a release instead
