### ISSUE TITLE
maybe make an option for the direction of the icons centering.

### ISSUE THREAD

**Issue by Skulcrusherr** [ChrisAnd1998/TaskbarX#708]
I have a problem where my icons go to the right not the left... I know why that is but I would like a fix for it:

just add an option to where people would want their icons to center, to the right or to the left...

**Comment by Skulcrusherr** [comment]
this happens to me because my icons are already centered from the windows method.... and this confuses taskbarX making it shift my icons to the right instead of the left, if you can fix that/ make it have an option to where I can make my icons shift that would be amazing

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
