### ISSUE TITLE
thin line appeared on transparent taskbar on Windows 11

### ISSUE THREAD

**Issue by pb29** [ChrisAnd1998/TaskbarX#710]
**Describe the bug**
A thin line appeared on taskbar when you set taskbar style to transparent on windows 11.

**To Reproduce**
Set style to Transparent on Windows 11

**Expected behavior**
A thin line appeared on taskbar.

**Screenshots**
![explorer_2021-07-01-22-24-20](https://user-images.githubusercontent.com/26969207/124132147-787b0600-dabb-11eb-91fa-f9bb3009cb1f.png)
full res screenshot below
![%pn_2021-07-01-22-23-48](https://user-images.githubusercontent.com/26969207/124132150-7a44c980-dabb-11eb-9706-95debaef9b90.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 21H2 (22000.51)

**Comment by Settordici** [comment]
Happens the same thing on my computer

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️

**Comment by vulGUN** [comment]
You can remove the line by installing the RoundedTV application from the MS Store. In the settings, you need to set the margin to 1 px.
 I'm sure there is a better way, but this is the only one that has worked for me so far.
