### ISSUE TITLE
The centering on the taskbar won't work its magic on my main monitor, but my second is working as intended.

### ISSUE THREAD

**Issue by probablytacolol** [ChrisAnd1998/TaskbarX#711]
I downloaded TaskbarX, everything is working as intending for being transparent on both of my monitors. However, the centering is only affecting my second monitor. I've tried to fix it, but it won't do anything. What should I do?

**Comment by patstg** [comment]
I have exactly the same problem. Everything worked fine, but some time ago (about 1-2 weeks ago) the "Compensate Tray Clock etc ..." option on the main screen stopped working. On the second monitor it's ok. 
I wonder if the problem isn't the recent Windows update that added weather and news next to the tray?
After entering the TaskbarX configurator, unchecking the "Compensate ..." option and turning it on again and restarting TaskbarX starts working properly again, but only for some time. Randomly crashes and icons are centered without compensate the tray.

**Comment by probablytacolol** [comment]
I clicked the Tray Clock thing, and it started working. Thank you so much!
