### ISSUE TITLE
works only on the second monitor

### ISSUE THREAD

**Issue by VolfVi** [ChrisAnd1998/TaskbarX#712]
Please help
Primari monitor
![image](https://user-images.githubusercontent.com/86832503/124264544-e6174880-db34-11eb-92cb-c32fdc2797f1.png)
secondary monitor
![image](https://user-images.githubusercontent.com/86832503/124264602-f92a1880-db34-11eb-83ad-c8c0c4fce4a5.png)

**Comment by Aftonone** [comment]
I'm having the same issue. It works on my second and third monitors but not the main monitor. I have an error in the console saying "Object reference not set to an instance of an object"

**Comment by BryceStandley** [comment]
Same here on a fresh install of windows as of 14/7/21. cant seem to get any change based on settings.

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
