### ISSUE TITLE
Bugs persist after uninstalling

### ISSUE THREAD

**Issue by leon-sm** [ChrisAnd1998/TaskbarX#713]
**Describe the bug**
Had these two problems after installing the arm version of the rainmeter skin: https://github.com/ChrisAnd1998/TaskbarX/issues/710
https://github.com/ChrisAnd1998/TaskbarX/issues/701
After disabling the skin and deleting the files in the skin folder, both the Taskbar and the Aero Peek button didn't return to normal.
Installing the prerelease 1.7.1.0 version fixed the problem with the line on the taskbar, not the aero peek problem tho, not even after uninstalling the 1.7.1.0 version.
**My guess is that there are still files left from the rainmeter skin installation, i just don't know where.**
Releasing a version where the aero peek problem is being fixed would probably also fix my issue.

**To Reproduce**
1. Install TaskbarX_1.7.0.0_arm.rmskin
2. Enable and Disable rainmeter skin
3. Delete TaskBarX files

**Expected behavior**
Thin line on taskbar disappears and Aero peak works again after uninstalling

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 20H2

**Additional context**

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
