### ISSUE TITLE
Increasing the refresh rate even more.

### ISSUE THREAD

**Issue by Battler624** [ChrisAnd1998/TaskbarX#714]
**Is your feature request related to a problem? Please describe.**
Its kinda related to a problem, I just notice the delay in icons moving after an application is opened, I wish to decrease that delay as much as possible.

**Describe the solution you'd like**
I wish to be able to increase the refresh rate beyond 100ms.

**Describe alternatives you've considered**
I have no idea of any alternatives.

**Additional context**
I haven't tested the rainmeter skin but i will do so later.

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
