### ISSUE TITLE
2 monitor problem

### ISSUE THREAD

**Issue by BirdHazBeenFlown** [ChrisAnd1998/TaskbarX#715]
When I was setting up TaskbarX It didn't work on the Main Monitor and I realized it only worked on my 2nd monitor
Specs:
1st monitor: Optiplex 9010
2nd monitor: LG Flatron E1600
Intel 15 vPro
Windows 10

**Comment by BruskBoy78** [comment]
I have this problem as well. The main monitor taskbar still goes transparent but the icons only go to the center on my second monitor.

**Comment by diniamo** [comment]
+1

**Comment by BirdHazBeenFlown** [comment]
> I have this problem as well. The main monitor taskbar still goes transparent but the icons only go to the center on my second monitor.

Yea same I could see my wallpaper in the taskbar

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
