### ISSUE TITLE
After uninstall Taskbarx - microphone output stopped working

### ISSUE THREAD

**Issue by MeierDGft** [ChrisAnd1998/TaskbarX#718]
Hey,
I had Taskbarx and deleted it. After uninstall it my headphone output immediately stopped working. It doesn't make sound anymore. I used the newest version on my Windows 10 laptop.
I hope you can help me.
Also, the right side of the taskbar sometimes disappears. (See the photo)
![16253454944395999587848491046775](https://user-images.githubusercontent.com/86894064/124366598-400d3080-dc51-11eb-99ad-1c61980f1b57.jpg)

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
