### ISSUE TITLE
A dekstop line after the taskbar...

### ISSUE THREAD

**Issue by GexerGex** [ChrisAnd1998/TaskbarX#719]
You can click on the taskbar and right-click as you can on the desktop. This does not happen when I use the default taskbar
Picture of the issue:
https://user-images.githubusercontent.com/86916114/124385056-d470a500-dcdc-11eb-89f2-7c05e2d46571.png

Operating System:
Windows 10
Version:
 21H1
Hope you can help me, thanks.

**Comment by gokhancvs** [comment]
This issue seems to be fixed in the 1.7.1.0 version. Here's [the link](https://github.com/ChrisAnd1998/TaskbarX/releases/tag/1.7.1.0).

**Comment by Dorus** [comment]
Please release this version 💪

**Comment by ChrisAnd1998** [comment]
Fixed.
