### ISSUE TITLE
 [Windows 11] Mac/Ubuntu like top par to where we can move all our System Tray Icon as well as WIFI , battery , sound ..

### ISSUE THREAD

**Issue by iAmBipinPaul** [ChrisAnd1998/TaskbarX#720]
As Windows 11 support now Center taskbar , It will be better to have all System Try Icons on top bar like Mac/Ubuntu. 

Thank you !

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
