### ISSUE TITLE
NOT CENTERING ICONS

### ISSUE THREAD

**Issue by Xitiz5775** [ChrisAnd1998/TaskbarX#721]
I uninstalled the old version of TaskbarX and installed the latest version , but it is not centering icons. Even I have not selected *Do not center the icons*.

**Comment by Karonpa** [comment]
Same problem here, was working in the older versions, but now it won't center.

**Comment by octrhiumlofera** [comment]
Having the same issue on mine. I had to downgrade the app (v1.7.0.0 → v1.6.9.0) to make icons centering work again.

**Comment by 0neEyed** [comment]
how to downgrade the app? my version is v.1.7.1.0

**Comment by SpecterGames** [comment]
@0neEyed you have to uninstall your TaskbarX and go to the releases and download v1.6.90. I hope it helps!

**Comment by ChrisAnd1998** [comment]
Please try the pre-release 1.7.4.0
