### ISSUE TITLE
Show labels in Windows 11 taskbar

### ISSUE THREAD

**Issue by idiliev18** [ChrisAnd1998/TaskbarX#722]
**Is your feature request related to a problem? Please describe.**
In the new version of Windows, the customization option for labels is missing.
![image](https://user-images.githubusercontent.com/50216485/124399853-fc84f600-dd26-11eb-8db6-7ed4c3dd5bb7.png)

**Describe the solution you'd like**
I think it will be a very good enhancement to add this option to the app.

**Describe alternatives you've considered**
For now I'm just waiting for this feature

**Additional context**
The extra menu could be great place for this option
![image](https://user-images.githubusercontent.com/50216485/124399909-6d2c1280-dd27-11eb-9d08-2ad3cbfbbb39.png)

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
