### ISSUE TITLE
TaskbarX - taskbar icons being hidden

### ISSUE THREAD

**Issue by ghost** [ChrisAnd1998/TaskbarX#723]
**Describe the bug**
Hi . i use taskbarx all the time . but sometimes the icons in the taskbar will be hidden . so at that times i have to kill the taskbarx proccess, please help

**Expected behavior**
taskbar icons being hidden

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 20H2

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
