### ISSUE TITLE
only half taskbar vissible

### ISSUE THREAD

**Issue by vishnumoorthi30** [ChrisAnd1998/TaskbarX#725]
<img width="960" alt="Screenshot (21)" src="https://user-images.githubusercontent.com/87019802/124602285-505a2100-de86-11eb-91ee-a642d459e9ae.png">
When i close the taskbar configurator app i can see only half my taskbar vissible pls fix this problem as fast as you can

![Screenshot (21)](https://user-images.githubusercontent.com/87019802/124602058-1ab53800-de86-11eb-8247-eb8b55393c4e.png)

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
