### ISSUE TITLE
Make the taskbar even further from the bottom of the screen and adjust its width

### ISSUE THREAD

**Issue by Mr-Anonymous75** [ChrisAnd1998/TaskbarX#726]
**Is your feature request related to a problem? Please describe.**
You know how there's a one-pixel gap between the the screen and the taskbar in 1.7.0.0? Well, what if instead of trying to fix that, you embrace that problem?

**Describe the solution you'd like**
Let the user decide how large the gap between the taskbar and the screen is. And with 1.7.0.0 already having rounded corners, maybe even let the user decide the width (or height, depending on the alignment) of the taskbar - or even better, make it dynamic, and make the taskbar just large enough to fit all the icons?

**Comment by Karonpa** [comment]
This a genius idea, not only centering the icons but being able to adjust the width so that it become a floating taskbar.

**Comment by Mr-Anonymous75** [comment]
Oh, and another thing - I just realized that if you drag the outside of the taskbar outward - that's what would usually make the taskbar wider - it changes the position of the taskbar, and keeps the thickness the same instead in 1.7.0.0. That should make implementing this even easier - I'd like to try implementing it myself, but I know only C#, not VB.

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
