### ISSUE TITLE
Windows 11: Centered start button

### ISSUE THREAD

**Issue by foersterp** [ChrisAnd1998/TaskbarX#727]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when the taskbar icons are centered in Windows 11 Insider Preview but the start button, too.

**Describe the solution you'd like**
I would like if you could center the taskbar icons but not the start button, the taskview button and widgets button.

**Describe alternatives you've considered**
There are no alternatives.

**Additional context**
No other context and no screenshots.

**Comment by ItzzBluee** [comment]
Agreed. I would love this feature in TBX or even stock, vanilla Windows.

**Comment by BakoBitz** [comment]
Please! We really want this.

**Comment by BraINstinct0** [comment]
Yep, currently it's possible to either center all or move all to the left, but both are annoying.

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
