### ISSUE TITLE
Doesn't centre on both monitors

### ISSUE THREAD

**Issue by innux420** [ChrisAnd1998/TaskbarX#728]
I've tried everything and it still will not centre on my main monitor but does it on my second monitor and I do not know why.

**Comment by lorrding** [comment]
I have the same thing happening on 1.7, tried 1.6.9, works fine.

**Comment by alexandeoliveira** [comment]
O programa estava funcionando normalmente, e de uma hora para outra parou de funcionar, não centraliza mais os ícones

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
