### ISSUE TITLE
TaskbarX messes with additional toolbars sometimes

### ISSUE THREAD

**Issue by detlefs** [ChrisAnd1998/TaskbarX#729]
**Describe the bug**
Having additional toolbars visible, in my case the Desktop folder and the languages bar, when using TaskbarX, they get overlapped and the Desktop folder cannot be clicked anymore

**To Reproduce**
1. Enable both a folder and the languages bar as additional toolbars
2. Arrange the folder to the right as far as possible
4. Start TaskbarX and enable centering the icons
5. Open and close some apps that add and remove icons
6. The arrangement of the toolbars becomes corrupted. See screenshot

It happens regardless of Lock all taskbars is enabled or not

**Expected behavior**
Additional toolbars should remain properly arrannged

**Screenshots**
![image](https://user-images.githubusercontent.com/303976/125053869-def8b900-e0a5-11eb-8db3-b930c631523b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 2004
 - Version: 1.7.1.0 (but also seen in 1.6.9)

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
