### ISSUE TITLE
TaskbarX leaves a gap to the left and bottom of the taskbar, and cuts-off the taskbar when turned off.

### ISSUE THREAD

**Issue by Asad-13** [ChrisAnd1998/TaskbarX#730]
The taskbar has a gap of a single pixel left out on the right end. It has actually cut-off the right end. This makes it difficult to use the 'Show Desktop' button. As for the bottom end, it has already been posted as an issue, and I have the same bug, so I'm not elaborating it again. When I turn off TaskbarX, my taskbar gets greatly cut-off from the bottom as well as the right end and I cannot access the tool buttons (Network, battery, quick settings, etc.) due to that.

1. I power on my computer, TaskBarX starts off alright (auto-start).
2. The icons get centered, and then I notice the gap in the taskbar.
3. I go to TaskbarX configurator and turn it off.
4. There's the bug that cuts-off the taskbar.
![Screenshot 2021-07-09 185901](https://user-images.githubusercontent.com/87184327/125085232-f8baf000-e0e7-11eb-8631-9dc92be8bf27.png)
![Screenshot 2021-07-09 190235](https://user-images.githubusercontent.com/87184327/125085597-636c2b80-e0e8-11eb-9961-3dd618fc178e.png)
![Screenshot 2021-07-09 190305](https://user-images.githubusercontent.com/87184327/125085757-90b8d980-e0e8-11eb-946a-ded89bc5f1f6.png)

Expected behavior:
The taskbarX effect should turn off and the icons should return to their default places. There should not be any other effects on the Windows default taskbar, but there is.

Desktop:
 - OS: Windows 10
 - Version 21H1

Additional context
I have experienced this problem since the install of TaskbarX version 1.7 from here, GitHub. I have a 64-bit device. I have previously used OpenShell to alter the Windows Start. I had uninstalled it before updating TaskbarX. To be precise, I noticed this problem one day after I installed TaskbarX v1.7 and played around with the 'Corner Radius'.

Something else I want to say:
I just uninstalled TaskbarX and rebooted my PC. It's back to normal now. I'm gonna stay at 1.6 for now, see that it doesn't bring the problem now. Please update me when there's a fix. Good Luck!

**Comment by CheeryLee** [comment]
Confirmed too, but when the taskbar is on the left, the gap will be between panel and full-screen window.

![image](https://user-images.githubusercontent.com/11297752/125256065-bde1d380-e304-11eb-96b7-944456364c3f.png)

**Comment by thenicholashenry** [comment]
This also happens to me.. I came here hoping to find a fix. please update. I have to go back to 16.9

**Comment by ChrisAnd1998** [comment]
Fixed ;)

**Comment by thenicholashenry** [comment]
> Fixed ;)

Hey Chris, just got mine updated again and it definitely helped BUT there is still a small 1 - 2 pixel gap to the bottom right (which means it is shifted to the top left).

You can reproduce this by trying to show desktop using the button on the bottom right and moving your mouse on the VERY edge/vortex of your screen on the bottom right and it wouldn't click like before.
