### ISSUE TITLE
taskbarx cant center icons

### ISSUE THREAD

**Issue by ericdelea** [ChrisAnd1998/TaskbarX#731]
i cant center the taskbar icons using taskbarx for more info i have windows 10 21h1 it is a custom version link here: https://sites.google.com/view/meetrevision i tried enable and disable uac but nothing

the rainmeter skin dosent work too and one more detail when i run taskbarx  i see a little clear area in the taskbar and when i close taskbarx it remains there i need to restart explorer to get rid of it

i will provide more information soon!

**Comment by Asad-13** [comment]
You might want to edit this issue and provide more information.

**Comment by bluishmatt** [comment]
I have the same problem. I'm running windows 10 home - build 19043. Newly installed. The taskbar icons don't center on my primary screen (haven't tried rainmeter). The icons do center on my secondary screen. Ive also noticed the system tray doesn't show on my secondary screen (only icons and the time), but am not sure if this is expected.

**Comment by gestudio** [comment]
Duplicated issue, same here on a 2570px wide monitor. Single monitor.

![image](https://user-images.githubusercontent.com/1157693/125867159-64fa076a-122a-4ade-aae4-5ef78a96fe39.png)

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
