### ISSUE TITLE
Software becomes unusable after setting change.

### ISSUE THREAD

**Issue by Alexciao** [ChrisAnd1998/TaskbarX#732]
**Describe the bug**
The software becomes unusable and crashes after "show in tray" option is enabled and requires re-install. It becomes impossible to change other settings after this because when the "Apply" button is clicked on the configurator it crashes both apps.

**To Reproduce**
1. Go to 'Extra' in the configurator
2. Click on 'Show tray icon’
4. Software breaks

**Expected behavior**
The software icon shows in the Windows tray.

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Version 20H2
 - Website Build
 - No other taskbar mods

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
