### ISSUE TITLE
Taskbar update event should pause when mouse is on taskbar

### ISSUE THREAD

**Issue by SpeedK** [ChrisAnd1998/TaskbarX#733]
**Is your feature request related to a problem? Please describe.**
Yes: Let's say we have 2 applications (A and B). Both are unpinned from taskbar and at least A is running. If I close application A and want to swap to/open application B using taskbar, I have to click on it. Sadly, everytime I try to do it, the polling (RefreshRate) hits and i have to retry to open the application B. 

**Describe the solution you'd like**
A perfect solution would be refreshing the taskbar only if refreshrate hits while cursor is not on top of taskbar.

**Describe alternatives you've considered**
A possible half solution is decreasing refresh rate but will be heavier for pc, without solving completely the problem, since minimum refreshrate is 100ms. 

**Additional context**
Not something really necessary but may help

**Comment by v1tesse** [comment]
I was just thinking about this the other day. I also 7+ Taskbar Tweaker, which allows me to close open apps with middle click on the corresponding icon on the taskbar, so I end up doing this often. Normally, I would close one app and move my mouse to close another, but before I can click it, everything shifts.
I like the minimum refresh rate of 100ms (although I wouldn't object to having an option of lowering it even more), but it would be really nice if there was an option to pause refreshing/recentering of the icons when the mouse is over the middle (icon area) of the taskbar. The best example of a practical way this is implemented is in web browsers, when closing multiple tabs - they all stay in the same position until the mouse is moved away and then they resize to fill the available space.

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
