### ISSUE TITLE
The original Windows 10 Start Menu is changed like Windows 7.

### ISSUE THREAD

**Issue by AnonymousPESPro** [ChrisAnd1998/TaskbarX#734]
**Describe the bug**
The original Windows 10 Start Menu is changed like Windows 7.

**To Reproduce**
On Windows 10, click on start button.

**Expected behavior**
I expected the start menu to be untouched.

**Screenshots**
![image](https://user-images.githubusercontent.com/87350719/125385259-cc3cf780-e3b7-11eb-938d-5f90bac22c5e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Version 21H1
**Additional context**

**Comment by ChrisAnd1998** [comment]
@AnonymousPESPro Hi, TaskbarX does not have a startmenu replacement... This is not TaskbarX.

**Comment by aor2021** [comment]
THIS IS NOT TASKBARX
