### ISSUE TITLE
Primary taskbar not being centered

### ISSUE THREAD

**Issue by wwhiteeee** [ChrisAnd1998/TaskbarX#735]
Having an issue where the primary taskbar isn't being centered, while the secondary is. Swapping my primary and secondary monitors doesn't seem to help either.

**Comment by gestudio** [comment]
Same here, on 2570px wide screen.

![image](https://user-images.githubusercontent.com/1157693/125867045-61d175eb-bff7-494a-a5ac-907ea0046f9c.png)

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
