### ISSUE TITLE
I get this popup on startup after uninstalling TaskbarX

### ISSUE THREAD

**Issue by Zare01** [ChrisAnd1998/TaskbarX#736]
**Describe the bug**
After installing the dev build of Windows 11 I have no use for TaskbarX anymore so I uninstalled it. Before uninstalling I made sure to stop the service and remove the task scheduler from the TaskbarX configurator. Even though I removed every trace of TaskbarX and the task scheduler windows still tries to start it on startup and I get this popup. I got TaskbarX from the Microsoft Store but I made sure to check the Task Scheduler app and TaskbarX wasn't in the Task Scheduler Library. 

**To Reproduce**
Install TaskbarX Microsoft Store version.
Create Task Scheduler with the TaskbarX configurator.
Uninstall TaskbarX.
Restart PC.

**Expected behavior**
You get a popup asking what app to use to open TaskbarX link.

**Screenshots**
![Screenshot 2021-07-14 233126](https://user-images.githubusercontent.com/79867565/125696956-489b1aa1-eaa4-4f8f-8111-95bcd65c1a2a.png)

**Desktop (please complete the following information):**
 - OS: [Windows 11 Pro]
 - Version [22000.65]

**Additional context**

**Comment by ghost-mk** [comment]
Let me second this on Windows 11 Home too.

**Comment by mrgoodwin** [comment]
I ran into this as well on Windows 10 Pro. The problem is that if you uninstall it by right-clicking the icon and choosing Uninstall, the scheduled task that refreshes it periodically gets left behind. If you go into Task Scheduler you should see the scheduled task for TaskbarX. Delete it and this message will go away.

There is an uninstall option in the TaskbarX Configurator that uninstalls the app correctly.

**Comment by Zare01** [comment]
> I ran into this as well on Windows 10 Pro. The problem is that if you uninstall it by right-clicking the icon and choosing Uninstall, the scheduled task that refreshes it periodically gets left behind. If you go into Task Scheduler you should see the scheduled task for TaskbarX. Delete it and this message will go away.
> 
> There is an uninstall option in the TaskbarX Configurator that uninstalls the app correctly.
I didn't know about the uninstall. Thanks for the help.

**Comment by mrgoodwin** [comment]
You're welcome! It's really not obvious at all that you're supposed to use the configurator to do the uninstall.

**Comment by robcee** [comment]
> I ran into this as well on Windows 10 Pro. The problem is that if you uninstall it by right-clicking the icon and choosing Uninstall, the scheduled task that refreshes it periodically gets left behind. If you go into Task Scheduler you should see the scheduled task for TaskbarX. Delete it and this message will go away.
> 
> There is an uninstall option in the TaskbarX Configurator that uninstalls the app correctly.

do you (or @ChrisAnd1998) happen to know what this service is called? I don't see anything obviously TaskbarX related in my list of services.

Super annoying to have this popup on restarts.

**Comment by mrgoodwin** [comment]
It's not a service, it's in the Windows Task Scheduler. I don't remember the name of it and unfortunately don't use TaskbarX anymore so can't check, but it wasn't hard to locate once you're in Task Scheduler. IIRC it was at the root Task Scheduler Library level. Just look for the task that has an Action set to run TaskbarX.

**Comment by robcee** [comment]
> It's not a service, it's in the Windows Task Scheduler. I don't remember the name of it and unfortunately don't use TaskbarX anymore so can't check, but it wasn't hard to locate once you're in Task Scheduler. IIRC it was at the root Task Scheduler Library level. Just look for the task that has an Action set to run TaskbarX.

Found it, thank you!

It is literally just `Taskbar X on COMPUTER\name`.

![taskbar x scheduler](https://user-images.githubusercontent.com/27976/143033166-920098ce-e182-4ddf-a779-29ac139b59f8.png)

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
