### ISSUE TITLE
Taskbarx doesn't work

### ISSUE THREAD

**Issue by Alonzzzo2** [ChrisAnd1998/TaskbarX#737]
**Describe the bug**
the icons aren't in the center of the taskbar

**To Reproduce**
start taskbarx

**Expected behavior**
icons should be at the center of the taskbar

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 2004

**Additional context**
Restarted, reset all the settings back to default, restarted, uninstalled, restarted, installed, restarted, reset settings - nothing helps
changing other settings such as style (transparent) does work
also tried uninstalling via taskbarx and not via the control panel, then reinstalled - didn't help

**Comment by Alonzzzo2** [comment]
btw, changing other settings such as style (transparent) does work

**Comment by piecemealcranky** [comment]
Having the same issue!

**Comment by navidmafi** [comment]
You should provide what version of TaskbarX you are using when reporting issue
Uninstall any previous release and try 1.6.9 release and see if it works.
(https://github.com/ChrisAnd1998/TaskbarX/releases/tag/1.6.9.0)

**Comment by Alonzzzo2** [comment]
Thanks, it was version 1.7.1.0
version 1.6.9.0 works :)
