### ISSUE TITLE
With version 1.7.1.0 (console screenshot) and HotFix by me 😄 

### ISSUE THREAD

**Issue by ZypsohNode** [ChrisAnd1998/TaskbarX#738]
1. Start TaskBarx

**Expected behavior**
Go to the middle

**Screenshots**
https://prnt.sc/1bj9g8r (console)

**Desktop (please complete the following information):**
- OS: Windows 10
- Version: 21H1

**Additional context**
Well this just happens with 1.7.1.0 and i dont want that annoying gap 

(FIX) I downloaded 1.6.9.0 and 1.7.1.0 and changed all .dll, .xml, .pdb, .config, .manifest, not (.exe) and now i dont have the gap, it goes to the middle and its fully working :)

**Comment by Akarshit7** [comment]
How

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
