### ISSUE TITLE
Won't apply settings when going back from sleep

### ISSUE THREAD

**Issue by majstudio** [ChrisAnd1998/TaskbarX#739]
Version : 1.7.1 and lower

Hello ! I really enjoy TaskbarX and purchased it on MS Store for seemless updates.

However, a thing that always frustrated me was the fact I use this on my laptop, and I regularly close the lid to put my computer to sleep.

When, I want to use my laptop again I open the lid and the PC wakes up naturally and when resuming my session, I always find TaskbarX applying default settings (not applying my custom settings) : aka the taskbar isn't centered anymore, is not transparent, etc.

I have to open the configurator and click Apply button each darn time and it's really annoying.

Please note that it works as intended on reboot but not when waking up from sleep.

Thank you, hope we can fix this.

**Comment by majstudio** [comment]
A quick workaround I discovered solve this problem is the shortcut : Win + CTRL + SHIFT + B which resets the graphical adapter and effectively resets up TaskbarX & other stuff as f.lux !

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
