### ISSUE TITLE
Taskbar on Main Display Won't Center Itself

### ISSUE THREAD

**Issue by JamesF0X** [ChrisAnd1998/TaskbarX#740]
I've been using TaskbarX for a while, and I recently encountered an issue after installing a windows update. For some reason, ever since the update, the taskbar on my main display refuses to center itself. I've tried reinstalling the software and messing with the configurator, but nothing has worked. The only way to get around it is by making one of my secondary monitors the main display in the windows settings.

**Comment by achza** [comment]
I am having the same issue as well

**Comment by gabrielbsb** [comment]
I'm having the same issue, started a couple of days ago.

**Comment by ProviceUnify** [comment]
Same

**Comment by MaxSqui** [comment]
Same, after check on "Show console" and applied changes showed this exception.
![image](https://user-images.githubusercontent.com/50052211/126384518-02af3a2a-131b-48aa-80f3-dc4f0d978b46.png)

**Comment by matliprah** [comment]
I have the exact same issue I just installed Windows 10 Pro Version 1909 (OS Build 18363.592) on my new pc build and haven't been able to center main taskbar. Console also displays same error as for MaxSqui.

**Comment by Varachack** [comment]
I am currently experiencing the same issue as everyone else.

**Comment by JamesF0X** [comment]
Ok, so I just updated Windows 10 to version 21H1, and TaskbarX is suddenly working correctly again.

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
