### ISSUE TITLE
Taskbar will not remember settings

### ISSUE THREAD

**Issue by harrys719** [ChrisAnd1998/TaskbarX#741]
**Describe the bug**
The taskbar will not remember settings like transparency.
**To Reproduce**
1. Install version 1.7.1.0
2. Change option to transparent/trans gradient
3. Create a task

**Expected behavior**
Option saves and applies on startup

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 
 - Version 20H2

**Additional context**
AMD PC

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
