### ISSUE TITLE
Taskbar is shifted up and to the left

### ISSUE THREAD

**Issue by nekoamaa** [ChrisAnd1998/TaskbarX#743]
**Describe the bug**
The taskbar is shifted up and to the left, and you could see bits of the desktop

**To Reproduce**
I don't know f there are any steps, but I've reinstalled TaskbarX multiple times and it occurs every single time

**Expected behavior**
Well, I expect it to be not shifted.

**Screenshots**
The screenshot is hard to take, but you could see bits of the taskbar at the bottom. You cant see bits on the far right of the taskbar because the screenshot doesn't show, but the taskbar is shifted to the left. 

[Screenshots](https://cdn.discordapp.com/attachments/677679611760345112/866721397045067847/unknown.png)

**Desktop:**
 - OS: Windows 10 Home
 - Version: 2004

**Additional context**
I have not seen anyone else with this problem yet, and I wondering if the problem lies with my computer. This is my first issue and I hope I did it right. Thanks in advance.

**Comment by rodrigotlc** [comment]
it's happening with me too, there should be a bug fix soon, i hope so

**Comment by thenicholashenry** [comment]
Hey Chris, just got mine updated again and it definitely helped BUT there is still a small 1 - 2 pixel gap to the bottom right (which means it is shifted to the top left).

You can reproduce this by trying to show desktop using the button on the bottom right and moving your mouse on the VERY edge/vortex of your screen on the bottom right and it wouldn't click like before.

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
