### ISSUE TITLE
Rounded taskbar support.

### ISSUE THREAD

**Issue by 1van0** [ChrisAnd1998/TaskbarX#744]
Hey Chris Andriessen,

I love TaskbarX and it made my pc look so much cleaner.
But I would really like a rounded taskbar setting, just like - [RoundedTB](https://github.com/torchgm/RoundedTB)
I think it would look really nice.

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
