### ISSUE TITLE
Bug Visual

### ISSUE THREAD

**Issue by Guicsr** [ChrisAnd1998/TaskbarX#745]
when you hover over the taskbar it stays on even though you don't click on the icon
![Captura de tela 2021-07-21 213754](https://user-images.githubusercontent.com/87788795/126576426-93765b67-2b8e-45fa-9435-989566058662.png)

**Comment by lofity3** [comment]
Isn't that like, _default_ on Windows or am I just confused?

**Comment by Guicsr** [comment]
Sorry, was a Windows bug, I restart and come back to normal.

Enviado do Email<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

De: ***@***.***>
Enviado:terça-feira, 27 de julho de 2021 21:00
Para: ***@***.***>
***@***.***>; ***@***.***>
Assunto: Re: [ChrisAnd1998/TaskbarX] Bug Visual (#745)


Isn't that like, default on Windows or am I just confused?

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
