### ISSUE TITLE
Transparent taskbar glitches 

### ISSUE THREAD

**Issue by Dandalicious** [ChrisAnd1998/TaskbarX#746]
**Describe the bug**
Transparency of taskbar only glitches on second monitor when main monitor is being used/has tabs open. Transparency seems like it is constantly activating and deactivating very quickly

**Desktop**
 - OS: [e.g. Windows 10]
 - Applications also used: Wallpaper Engine

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
