### ISSUE TITLE
Tray icon 

### ISSUE THREAD

**Issue by ChinmayMR** [ChrisAnd1998/TaskbarX#747]
The settings are being applied when turning on show tray icon

1. Go to TaskbarX configurator
2. Click on 'Extras'
3. Scroll down to 'Tray icon'
4. Enable it.
5. Click apply

**Expected behavior**
The tray icon should appear and the settings should work properly

**Desktop:**
 - OS: Windows 10
 - Version 21H1

**Comment by JustDesoroxxx** [comment]
If you already didn't, can you look here:
![image](https://user-images.githubusercontent.com/82710983/127082002-5e2bba1a-9d5b-4065-9d8e-ea3e8e5808fb.png)

Also, what version are you using?

**Comment by ChinmayMR** [comment]
I am using TaskbarX_1.7.1.0_x86. As said when I enable the option for tray icon the customization settings that I applied will not work

**Comment by ChinmayMR** [comment]
I will try to uninstall and reinstall. Then I will provide feedback.

**Comment by ChinmayMR** [comment]
I tried to reinstall but nothing seems to happen. And when I tried to look at the console with tray icon on then the console just closes automatically

**Comment by ItzzBluee** [comment]
This happened to me as well, and I opened an issue. For me though the software just breaks after enabling and no other options work until I reinstall.

**Comment by ChinmayMR** [comment]
> This happened to me as well, and I opened an issue. For me though the software just breaks after enabling and no other options work until I reinstall.

This is the same thing that happens to me I just described it wrongly. Sorry for my bad English.

**Comment by ItzzBluee** [comment]
No problem :)

**Comment by ItzzBluee** [comment]
> > This happened to me as well, and I opened an issue. For me though the software just breaks after enabling and no other options work until I reinstall.
> 
> This is the same thing that happens to me I just described it wrongly. Sorry for my bad English.

No problem

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
