### ISSUE TITLE
TaskBar wont center

### ISSUE THREAD

**Issue by kkanekii** [ChrisAnd1998/TaskbarX#748]
**Describe the bug**
Okay so......... i re installed taskbarx on my computer anddddddd.................. it wont center!
I used the exact same settings i used yesterday..and day before.. and yea 

**To Reproduce**
i dont think this is reproducable
**Expected behavior**
It should center the icons

**Screenshots**
![image](https://user-images.githubusercontent.com/86641210/126791778-e9dfdc5b-035d-4975-9ae0-062d8a63a92d.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 1609
 - Arch: x64

**Additional context**
idk man pretty straightforward

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
