### ISSUE TITLE
Taskbarx not centring apps

### ISSUE THREAD

**Issue by Akarshit7** [ChrisAnd1998/TaskbarX#749]
**Describe the bug**
The taskbarx is working(showing in task manager) but not actually centring the icons on opening the .exe
 And also not able to configure anything in config application
Windows defender is enabled 
Window:21h1
Yes .net framework is there 

Do i need to disable windows defender
Do i need activated windows or without activation it will also work

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
