### ISSUE TITLE
TaskbarX only centering secondary monitor

### ISSUE THREAD

**Issue by MoistTortilla** [ChrisAnd1998/TaskbarX#750]
Taskbarx only centers my secondary monitor. If I switch my monitor. It will still only center the second monitor. Anyone know a fix?

**Comment by BearTS** [comment]
i get the same issue

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
