### ISSUE TITLE
Primary Taskbar not centering

### ISSUE THREAD

**Issue by Chlebebebek** [ChrisAnd1998/TaskbarX#751]
primary taskbar not centering and i dont know what i can do in this situation

![Przechwytywanie](https://user-images.githubusercontent.com/87916444/126882323-180c0776-241e-4498-a78d-cbc1a1ff649a.PNG)

**Comment by thenicholashenry** [comment]
Might be stupid but did you try clicking apply? If yes, my bad.. Try either of these:

1. Right-click the taskbar and toggle "Lock the taskbar" to unlock it.
2. Disable Links. Right Click Taskbar > Toolbars > Links
3. Create a task schedule and/or restart TaskbarX.
4. I have the x84 version downloaded straight from the website.. Try redownloading and extracting the entire folder to ensure you aren't missing any files.

**Comment by AM2i9** [comment]
I am also having this issue, but it seems like its something happening in release 1.7.0.0 and up. I went and installed 1.6.9.0, and it worked fine.

**Comment by bmayrink** [comment]
I have the same problem, and I bought it through the microsoft store there is no way for me to download the previous version

**Comment by Akarshit7** [comment]
> I have the same problem, and I bought it through the microsoft store there is no way for me to download the previous version

Uninstall the ms version 
Dl the 1.6.9.0
Extract and enjoy

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
