### ISSUE TITLE
TASKBARX not centering my main monitor. 

### ISSUE THREAD

**Issue by mylaken** [ChrisAnd1998/TaskbarX#754]
Hi.

OS: Windows 10

TLDR taskbarx has stopped centering my main monitor. My side monitors still work. Ran the program through the Debugger but no errors in the code i guess.

In the screen shot I have the console open to show the issue that is happening for me. 

@Calculator | Object reference not set to an instance of an object.
@Looper1 | Member not found. (Exception from HRESULT: 0x80020003 (DISP_E_MEMBERNOTFOUND))
![taskbar problem](https://user-images.githubusercontent.com/88047546/127184668-32dd2fad-f447-4489-8297-ea93598a504e.jpg)

**Comment by JustDen1234** [comment]
same here:

Waiting for Shell_TrayWnd
!0
@Calculator | Object reference not set to an instance of an object.

**Comment by Traxero** [comment]
Same

**Comment by Snede** [comment]
Same for me

**Comment by Zayde05** [comment]
Same here for me, it will only center my second monitor but not my main.

**Comment by BrunoAquiCob** [comment]
Same here

**Comment by Zayde05** [comment]
> Same here for me, it will only center my second monitor but not my main.

I turned on my computer this morning and some how both taskbars on both monitors were centred.

**Comment by msturma** [comment]
Same problem for me :(

**Comment by addicteda2** [comment]
I have encountered similar problems

**Comment by Fang546** [comment]
I have the same issue

**Comment by PhilipKrauss** [comment]
Same problem for me - display 1 and 2 are displayed correctly, but display 3 (which is my main monitor) doesn't work

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
