### ISSUE TITLE
TaskbarX not working well with vertical taskbars(it somehow solved itself??)

### ISSUE THREAD

**Issue by lofity3** [ChrisAnd1998/TaskbarX#755]
Basically, the bug is that, well, you read the title, it's not working well with vertical taskbars.
No taskbar button are visible, except for the start button.
Also, the taskbar here was supposed to be _"Transparent Gradient"_ but as you can see:
![image](https://user-images.githubusercontent.com/88064144/127242869-79f5639c-d56b-45ea-a91f-d7f7b1e4922f.png)
Please fix this, thank you for reading this issue.

My system: Acer Aspire 5, x64 based processor: Intel Core i5 10th gen, 8 GB RAM, 64-bit system: Windows 10 21H1 Build 19043.1110, 15"6 Inch Screen.
Update: I somehow solved this, my cursor became invisible, I restarted the computer and everything was working, no idea how that happened but it just did, I am genuinely confused.

**Comment by lofity3** [comment]
can someone tell me how to delete this issue

**Comment by pc-v2** [comment]
i got this issue too, restarting explorer,exe solves this
