### ISSUE TITLE
TaskbarX not support windows 10 version 20H2?

### ISSUE THREAD

**Issue by namndt** [ChrisAnd1998/TaskbarX#758]
**I did  download new release Taskbar, run TaskbarX.exe and not thing change.**
My taskbar wont center.

**Comment by CrewMaster** [comment]
Same problem here. It still kinda works but autostart doesn't work anymore. You have to kill the application with the taskmanager because it gets stuck and restart it in oder to work. Also the "TaskbarX configurator" crashes if you press "Restart TaskbarX".

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
