### ISSUE TITLE
[v1.7.1.0 x64] - Icons don't center on Windows 10 Pro x64 19043.28

### ISSUE THREAD

**Issue by pluchinetti** [ChrisAnd1998/TaskbarX#759]
### Description:
The taskbar icons don't get center.

### Steps to reproduce:
1. Download and extract [TaskbarX_1.7.1.0_x64](https://github.com/ChrisAnd1998/TaskbarX/releases/download/1.7.1.0/TaskbarX_1.7.1.0_x64.zip).
2. Open "TaskbarX Configurator.exe" and select a style (I tried with Default, Transparent and Transparent Gradient).
3. Make sure that the checkbox "Don't center Taskbar" is not checked.
4. Click on "Apply".
5. The taskbar blinks and the current style is applied, however the icon are still placed to the left.

### Expected behavior
In addition to the style change, the icons should be centered after clicking on "Apply".

### Screenshots
- Without TaskbarX
![WithoutTaskbarX](https://user-images.githubusercontent.com/40801333/127749787-3477d695-4a57-4b58-a796-86d5843db83e.png)

- With TaskbarX
![WithTaskbarX](https://user-images.githubusercontent.com/40801333/127749790-67cc2200-e75c-4351-a417-7ac515d8baec.png)

### Specifications
 - OS: Windows 10 Pro x64
 - Version: 21H1
 - Build: 19043.28
 - No antivirus software installed
 - Single monitor
 - Feel free to ask for more information if needed.

**Comment by pluchinetti** [comment]
**Update:** Icons get centered when using [TaskbarX_1.6.9.0_x64](https://github.com/ChrisAnd1998/TaskbarX/releases/download/1.6.9.0/TaskbarX_1.6.9.0_x64.zip)

**Comment by SmookeyDev** [comment]
Same situation, TaskbarX 1.7.1.0 dont working on Windows 10 21H1, but 1.6.9.0 work.

**Comment by imgladnotu** [comment]
> **Update:** Icons get centered when using [TaskbarX_1.6.9.0_x64](https://github.com/ChrisAnd1998/TaskbarX/releases/download/1.6.9.0/TaskbarX_1.6.9.0_x64.zip)
> 
> ![Sjs8f9vXS0](https://user-images.githubusercontent.com/40801333/127749895-cd46e079-d97f-4b20-8aef-9153b3331a5e.png)

huh, same issue. tested out it out 1.7.0.0 and centering still doesn't work, but on 1.6.9.0 it works fine. (W10 1709 LTSC)

**Comment by mekkkwiz** [comment]
same

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
