### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by tangyyt912** [ChrisAnd1998/TaskbarX#760]
So, whenever i'm launching taskbarx, the center taskbar isn't working. when, checking the console, i'm seeing the following error :-

**@Calculator | Object reference not set to an instance of an object.**

 - OS: Windows 10
 - Version 19042

**Comment by OgulcanCelik** [comment]
I'm having the same issue.

Fresh install
Version: 19043.928

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
