### ISSUE TITLE
Duplicate icon for Edge appears and looks like folder

### ISSUE THREAD

**Issue by SuperTempAccount** [ChrisAnd1998/TaskbarX#761]
**Describe the bug**
A folder icon appears on the taskbar when Edge is minimised and virtual desktops are switched using keyboard shortcuts.

**To Reproduce**
1. Open Edge
2. Minimise Edge
3. Click anywhere on the desktop
4. Switch to another virtual desktop (important! use CTRL+WIN+left/right)
5. Switch back to the virtual desktop with Edge
6. A folder icon has appeared (which links to the Edge tab)

**Expected behavior**
Only the Edge icon is present.

**Screenshots**
![image](https://user-images.githubusercontent.com/83566267/127787557-676ca625-e177-40a5-8c72-64a4aba9fca4.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise
 - Version: 20H2

**Additional context**
Seems to only occur when using the keyboard shortcut to switch virtual desktops.
Opening the screenshot menu (CRTL+SHIFT+S) and escaping out of it (ESC) seems to remove the folder icon.

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
