### ISSUE TITLE
What exactly is the "secondary taskbar" that is referred to in some settings?

### ISSUE THREAD

**Issue by trwnh** [ChrisAnd1998/TaskbarX#762]
I can't seem to figure out what all those settings that refer to a "secondary taskbar" actually do. It doesn't seem to be the Windows setting to show a taskbar on all monitors. I'm at a loss as to what it could be.

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
