### ISSUE TITLE
Win11 Insider - TaskbarX causes Windows 11 File Explorer and mouse cursor to slow

### ISSUE THREAD

**Issue by XeroraYT** [ChrisAnd1998/TaskbarX#764]
As title suggest, I'm a windows 11 insider and am assisting with feedback where I can. 

letting the file explorer window touch the taskbar while TaskBarX is running causes the window and mouse cursor to slow down, and it almost feels like I'm watching a 10,000 FPS slow-mo clip from the slowmoguys. Mouse also becomes completely unresponsive.

1. Have Windows 11 with TaskBarX installed, and running.
2. Open file explorer
3. Move the window towards the taskbar

 - OS: Windows 11 21H2
 - Version: Insider Build 22000.100

**Additional context**
I don't expect an immediate fix, as I AM running an OS that isnt OFFICIALLY supported, but I did at the very least, want to make you aware.

**Comment by Gaaraly** [comment]
All software that makes the status bar transparent will cause this.

**Comment by XeroraYT** [comment]
> All software that makes the status bar transparent will cause this.

So it's more of a windows 11 issue then, it sounds like.

**Comment by pc-v2** [comment]
this app is supposed to be run in Windows 10, not 11

**Comment by XeroraYT** [comment]
Thank you, you're irrelevant input helped me so much!

(Next time read what you're responding to, then you'd know I'm submitting
feedback/bug report, and not looking for assistance, dimwit.)

**Comment by pc-v2** [comment]
this is Windows 11 problem, I assume DWM really broken in 11 (or could be the display driver), I got slo-mo even without this app

**Comment by DigitalNXZ** [comment]
same here.. and it crashes non stop.. I restart it.. 10 minutes later it kills itself again :(

**Comment by ryuu27** [comment]
I also had this problem a few months back but ever since I switched from the TaskbarX software to the github release
I stopped having the problem mentioned above 
Hope this helps

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
