### ISSUE TITLE
[Bug] Taskbar Only Shows Top Part (Windows Start Menu Button)

### ISSUE THREAD

**Issue by pc-v2** [ChrisAnd1998/TaskbarX#766]
**Describe the bug**
The bug appear when taskbar is moved to Right/Left of the screen
**To Reproduce**
1. Start TaskbarX
2. Move the taskbar to the left/right of the screen
3. See error

**Expected behavior**
Taskbar shows all part of it

**Screenshots**
![image](https://user-images.githubusercontent.com/58063311/128807570-76ea032a-78c0-442a-a776-1c5b2efc8abb.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Version [21H1]
 - TaskbarX 1.7.1.0 Microsoft Store

**Additional context**

**Comment by pc-v2** [comment]
#755 
this issue seems to be the same as this one

**Comment by subash017** [comment]
i too got this now

**Comment by N0t-Br0ken** [comment]
Restart Windows explorer using task manager, The issue should be fixed

**Comment by pc-v2** [comment]
> Restart Windows explorer using task manager, The issue should be fixed

yeah but it's irritating to me if I want to move the taskbar again

**Comment by N0t-Br0ken** [comment]
> > Restart Windows explorer using task manager, The issue should be fixed
> 
> yeah but it's irritating to me if I want to move the taskbar again

You can contact the developer about the issue.

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
