### ISSUE TITLE
Taskbar X only working on second screen

### ISSUE THREAD

**Issue by LVarelaG** [ChrisAnd1998/TaskbarX#767]
The icons only center on the second screen

I downloaded the program, start it and all the icons in the second screen move to the center of the taskbar, but in the primary screen nothing happened

I've used it before with two screens and it worked perfectly

OS: Windows 10 Education
Version: 21H1

EDIT:
I just tried with older versions, 1.6.9.0 and olders work perfectly, the problem is with 1.7 and newer.

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
