### ISSUE TITLE
doesnt show the back of the screen when a app is in full screen 

### ISSUE THREAD

**Issue by DyingDice** [ChrisAnd1998/TaskbarX#768]
hey mods when I fullscreen/full-re an app like GTA 5 or zoom  I can't see my background/wallpaper please help me fix it
![image](https://user-images.githubusercontent.com/88765122/128983140-f633093b-4761-4524-bcdc-3417ac4dea51.png)
![image](https://user-images.githubusercontent.com/88765122/128983222-c8105383-97f9-46fa-b10e-7cd64aaedb42.png)
here its showing the rest of the app under the taskbar and not leting me see my perfect wallpaper how do i stop this from happening.

**Comment by DyingDice** [comment]
its showing the rest under the taskbar

**Comment by DyingDice** [comment]
anyone there

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
