### ISSUE TITLE
TaskbarX doesn't center the taskbar

### ISSUE THREAD

**Issue by CaneMandarinesco** [ChrisAnd1998/TaskbarX#769]
**TaskbarX doesn't center the taskbar!!!**
nothing to explain. however downgrading to 1.6.8.0 solved the problem

**To Reproduce**
1. Download, extract and run TaskbarX 1.7.1.0 on my computer

**Expected behavior**
...

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 1903

**Comment by CaneMandarinesco** [comment]
Same things is happening on my laptop HP 15s-eq0xxx with Windows 10 Home 20H2. tried this time with 1.6.9.0 and now works

**Comment by dinhtrung3997** [comment]
Oh, the same on Windows 10 LTSC 1809.

**Comment by sjain882** [comment]
Same issue Windows 10 Enterprise 20H2, laptop, single monitor, 1440p, 125% DPI, no toolbars enabled

**Comment by yashpalgoyal1304** [comment]
duplicates:
#787 
#774

**Comment by yashpalgoyal1304** [comment]
hi, can this issue be pinned, and labelled as duplicate target (idea of this label: gimp tracker)??

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
