### ISSUE TITLE
[Feature request] System tray with the same style as the taskbar.

### ISSUE THREAD

**Issue by Dhyfer1** [ChrisAnd1998/TaskbarX#770]
Hi Chris.

I've been using TaskbarX for a while now and I really like it, from the available styles inside the TaskbarX settings I always use Acrylic, it's my favorite style.

I have a suggestion, could you make TaskbarX also apply the selected style to the system tray? As you can see in this image...

![Animation13](https://user-images.githubusercontent.com/50301201/129119372-dbac05f9-141f-4964-a04a-9a36a39dc7f8.gif)

...the taskbar adopts the Acrylic style, but the system tray doesn't. The system tray always appears with an emphasis color that is automatically chosen by Windows according to the wallpaper and can be configured in Windows Settings>Personalization>Colors.

As the system tray is part of the taskbar, can you have TaskbarX also apply the same style to the system tray? It's something that would look great, don't you think?

I look forward to your reply.

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
