### ISSUE TITLE
Microsoft PowerToys does not work correctly when the Store version of Taskbar X is installed

### ISSUE THREAD

**Issue by tre4b** [ChrisAnd1998/TaskbarX#771]
**Describe the bug**
I decided to buy the Store version of Taskbar X.

Some time after installation I went to use a feature of PowerToys and found the icon was missing.  I took a fair while trying to resolve this then I uninstalled TaskbarX and PowerToys went back to normal.   I have since re-installed TaskbarX from the Zip and with this method both programs function correctly

**To Reproduce**
Install Microsoft PowerToys.  
Install Taskbar X from the Windows Store

**Expected behavior**
Both programs work correctly, both programs display tray icons.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10  21H1     
 - 19043.1110         
 - Feature Pack Experience: 120.2212.3530.0
 - 
**Additional context**
Currently not a hot issue the zip installed version of TaskbarX works fine.  This issue is logged to ensure the Author is aware of it.  A fix would be good as this would enable me to use the auto update feature of windows store however it is not urgent.  I will happily unload and reload to assist in any debugging if required.

**Comment by tre4b** [comment]
Having worked with this I now know that both the store app and the downloaded app have the same issue.

It is related to mechanism used for startup of taskbarx.

I resolved this for myself by going into the configurator, setting it up and then removing the startartup.   When booted the PowerToys icon is there and works.  Running TaskbarX then also works and both programs work together.   To restore startup I added the Taskbarx application into my startup folder.   now I have both applications working correctly.

**Comment by rtorchia** [comment]
@tre4b came here to support your findings. I've had the same issue with the system icon of PowerToys (and others ones I"ve now discovered) with TaskBarX starting automatically from the Task Scheduler.

**Comment by mrgoodwin** [comment]
Do you have the systray icon enabled?
ModernFlyouts?
I had this issue as well and some combination of disabling the TaskbarX systray icon and uninstalling ModernFlyouts finally seems to have fixed it.

**Comment by stevemagruder** [comment]
In my own testing, it's not the startup method that's the issue, it's the Extra setting "Show Tray icon". As long as I have that _not_ checked, PowerToys runs fine and shows in the system tray. This has also been bugging me for a while, and I thought it was a PowerToys issue - now, maybe not. At any rate, these apps aren't getting along when it comes to the system tray.

**Comment by stevemagruder** [comment]
I also have reason to at least speculate that TaskbarX's tray icon was interfering with other tray icons as well, such as CCleaner. That and some others weren't showing up in the tray from time to time while I had the "Show Tray icon" Extra setting checked. Now everything I expect to show up in the tray is there and has been for hours.

**Comment by tre4b** [comment]
Mine has been working fine since my above post.   Seeing your post I went into configurator and turned on the task bar icon.   It appeared fine, so I clicked on it and taskbar crashed sending my icons back to the left.  It does seem like something to do with the task bar button is not healthy.

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
