### ISSUE TITLE
Make the taskbar blend in with the other apps.

### ISSUE THREAD

**Issue by Nevskjij** [ChrisAnd1998/TaskbarX#772]
Make the taskbar blend in with the other apps. An example is when I have chrome open and most of the colors on the bottom is white then make the taskbar blend in by changing its color to white, but when I change over to look at my default windows 10 background it will change to blue. To give you an idea of why I want this then look at this. 
![image](https://user-images.githubusercontent.com/57047360/129481145-85ec0748-6813-47ee-a2e9-c9c9b542c269.png)
That just looks terrible.

**Comment by yashpalgoyal1304** [comment]
one way this can be done is that the apps whole of screen bleeds into the taskbar area - but only the visuals, not the actual working area - sort of like tile+stretch effect. So, setting alpha = opaqueness < 50 or so will effectively give what u want. 

Ofc even if it's implementable, then too it will still have one hiccup - contrast with the color theme of system. Like when the white bg came in following video.

Simulated mockup:



https://user-images.githubusercontent.com/19423063/132123985-b7ea0554-414d-4af9-92a7-1110c2a9b0a9.mp4

**Comment by Nevskjij** [comment]
Thats exactly what I wanted. Could you send me a screenshot of your settings?

Also do you know how I can fix the Win + M btton in the corner? It isnt always working. ![image](https://user-images.githubusercontent.com/57047360/132125007-ff562030-fd8e-410e-adf6-7b3ca5422f65.png)

**Comment by yashpalgoyal1304** [comment]
> Could you send me a screenshot of your settings?

a screenshot wont be enough 😅 . I'll send u the instructions in some days. WIll get back later :)

for win + m - go to https://github.com/ChrisAnd1998/TaskbarX/issues/701

**Comment by Nevskjij** [comment]
> > Could you send me a screenshot of your settings?
> 
> a screenshot wont be enough 😅 . I'll send u the instructions in some days. WIll get back later :)
> 
> for win + m - go to [#701 (comment)](https://github.com/ChrisAnd1998/TaskbarX/issues/701#issuecomment-913021091)

I will wait untill you patch that. I dont want to lose my 2 week spree of gpu mining.

**Comment by Nevskjij** [comment]
Another small bug I noticed is that on my laptop is that because it has a small screen the apps start going under the weather update thing. Pls fix that and make sure its more central on smaller screens.

**Comment by Nevskjij** [comment]
Another small bug I noticed on my laptop is that because it has a small screen the apps start going under the weather update thing. Pls fix that and make sure its more central on smaller screens.

**Comment by yashpalgoyal1304** [comment]
screenshot?? also, please search if somebody has already filed that issue. if yes, then enter ur input there as comment, otherwise, open a new issue - remember: **only one issue ticket per problem and only one problem per issue**

**Comment by Nevskjij** [comment]
Sorry, but I cant screenshot that and it doesnt look like someone has that problem.
It looks like this, but its under the weather and the other icons are next to it. 
![image](https://user-images.githubusercontent.com/57047360/132237692-2042593f-70ee-46cb-b813-cdc7cfec4d25.png)
It happens if the taskbar run out of space on the right side. Instead of moving all the icons to the left to centralize them they start going under the weather thing.

**Comment by yashpalgoyal1304** [comment]
i dont know what weather thing - where's it, with start icon (on left in ur case) or with other system tray icons (on the right)?

**Comment by Nevskjij** [comment]
This is the weather icon btw
![image](https://user-images.githubusercontent.com/57047360/132251450-1beeb5be-a2c5-4dbc-9a2c-845bc2e7e23c.png)

**Comment by Nevskjij** [comment]
Are you coming back to me any soon?

**Comment by yashpalgoyal1304** [comment]
Err… wanted to, but no. lots of stuff going on.

**Comment by yashpalgoyal1304** [comment]
ohkay, so, the not so polished instruction set:
1. Enable "Automatically hide the taskbar in desktop mode" (< taskbar settings < right click on taskbar) AND,
2. Set TaskbarX's style to anything with transparency i.e. opacity or alpha less than ~65%
     - styles with transparency: transparent, trans gradient, blur, acrylic
     - in the above shared screen capture, i chose transparency with blur to give some distinction to taskbar.


I am not using TaskbarX anymore, so, cant recall if there were any other thing that i adjusted or not. Hope it helps, and be sure to let me know how it went (u didnt for the above given solution for clipping 😉)


![image](https://user-images.githubusercontent.com/19423063/132116725-a3b73ef9-8f0f-4065-856d-3cac4ca8ab13.png)

**Comment by Nevskjij** [comment]
Hmm not quite what I wanted or it just dont work. I want to be able to see the taskbar at all times btw exept when I am in a fullscreen game.
![image](https://user-images.githubusercontent.com/57047360/133829547-a1a7aa96-2c35-485a-87fc-e62f5eb331e8.png)

**Comment by yashpalgoyal1304** [comment]
> or it just dont work

are u saying with respect to the dark color of taskbar? if so, then try increasing alpha, it's a bit buggy.

> I want to be able to see the taskbar at all times

yep, i am aware that the method i shared doesnt work for this, that's why i mentioned it as "simulated mockup" in my prev comment (https://github.com/ChrisAnd1998/TaskbarX/issues/772#issuecomment-913128677)

**Comment by Nevskjij** [comment]
> are u saying with respect to the dark color of taskbar? if so, then try increasing alpha, it's a bit buggy.
There is like no difference if I use 100% or 65 or 30 or 0% alpha.

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
