### ISSUE TITLE
Visual Glitch after uninstalling TaskbarX

### ISSUE THREAD

**Issue by SterDN** [ChrisAnd1998/TaskbarX#773]
my pc became unresponsive and taskbar is glitching after uninstalling taskbarx for hours now,

I only uninstalled it and it starts glitching idk what happened

its glitching out, the desktop background turns black, i cant click using my mouse cursor

https://user-images.githubusercontent.com/88993668/129499791-0bde3ea9-af5c-47bd-a08b-017a9f86c1e2.mp4

 windows 10]
 versikn 21h1

**Comment by mingyewfoo1** [comment]
did u remove taskshd?

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
