### ISSUE TITLE
Icons wont centre

### ISSUE THREAD

**Issue by Kaization** [ChrisAnd1998/TaskbarX#774]
**Describe the bug**

TaskbarX is loading but the icons won't Centre
**To Reproduce**
1. Go to 'TaskbarX folder'
2. Click on 'TaskbarX Configurator'
3. Scroll down to 'Click apply'
Will not Centre icons
**Expected behavior**
I expect the icons to be centered but they wont Centre
**Screenshots**
![image](https://user-images.githubusercontent.com/88996167/129504740-13cd154f-a0ba-4deb-8ff2-1d4848f9c3f6.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Version [e.g. 1909]

I am using windows 10 build 2004 (20H1)
**Additional context**

**Comment by Kaization** [comment]
Until this is fixed, I have to manually centre the icons

**Comment by Kaization** [comment]
now it wont stay open in the background

**Comment by Kaization** [comment]
fixed by using a year old version

**Comment by subash017** [comment]
@Kaization can u mention which version you used to solve

**Comment by Kaization** [comment]
taskbarx 1.6.0.0

**Comment by Kaization** [comment]
everything is the exact same
basically

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
