### ISSUE TITLE
Application will not open on startup and other issues.

### ISSUE THREAD

**Issue by SeaSaltStar** [ChrisAnd1998/TaskbarX#775]
No matter what I seem to put in the startup settings I cannot seem to get the app to open on startup. I've tried running various versions of the app x86/x64 and the Microsoft store version. It's been a lot of troubleshooting to get my taskbar transparent as well. I have to press the reset all setting button multiple times in order to get any of my applied settings to work. I've tried deleting various associated files then reinstalling the app, multiple power cycles as well.

**Comment by SeaSaltStar** [comment]
I've also noticed that when I have "Show Tray Icon" enabled it just refuses to make my taskbar transparent,
Incase my specs are in question I have an ROG Strix 3070 5600x and am running Windoes 21h1

**Comment by rebin12** [comment]
I used a program that helped me to make it auto-start at startup its a program that lets you make any application start at startup, its called startup delayer it works well for me.

**Comment by SeaSaltStar** [comment]
Thanks for the recommendation, it seemingly works well for startup opening. However I'm still having issues pertaining to transparency and the configurator.

**Comment by rebin12** [comment]
are you using the Microsoft store version? if so try to download the portable version from Github or the official website and try other ones if the one you downloaded is not working.

**Comment by SeaSaltStar** [comment]
I've tried various versions as stated in OP

**Comment by rebin12** [comment]
Sorry i don't have any other ways to help but I am glad that the startup issue fixed

**Comment by UrielTapia** [comment]
Same issue here, I'm glad someone pointed it out. I've also tried deleting and creating the taskschedule to no avail.
I've found mine rarely launches normally during startup, but fails to start again after an hibernation. As for the transparency issues, I just disable it and use another tool instead (not sure I can name it here).

**Comment by SeaSaltStar** [comment]
My theory is that there's a weird config interaction occurring, hence why when I "reset" my settings I can get the program to behave appropriately. Maybe there's a file that's made outside of the ones I've tried deleting that is screwed up

**Comment by SeaSaltStar** [comment]
As an update to help someone maybe. I manually went into task scheduler and deleted the automatically made one. Made my own to run the script provided by the program and added a 30 second delay after log in. Not sure why when the program made it with nearly the same settings it refused to work but when I created my own it is working flawlessly.
