### ISSUE TITLE
TaskBarX will not continue working after going to sleep or after computer is restarted.

### ISSUE THREAD

**Issue by JMoney607** [ChrisAnd1998/TaskbarX#776]
Every time my computer goes to sleep or I turn it off I have to re open taskbarx and click apply again. Ive played around with the startup delay and it has changed nothing.
**To Reproduce**
Let computer go to sleep or turn computer off or restart computer. 

**Expected behavior**
Taskbarx would begin working again however is does not. 

**Desktop :**
 - OS: [Windows 10]
 - Version 21H1 
 - Taskbarx version 1.7.1.0

**Additional context**
for some reason it has a better chance of working on startup if I manually put my computer to sleep or shut it down than it does if i just let my computer go to sleep.

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
