### ISSUE TITLE
TaskbarX doesn‘t adapt the WIN11 taskbar

### ISSUE THREAD

**Issue by assassinliujie** [ChrisAnd1998/TaskbarX#777]
When I have a software icon in the tray area of the taskbar,It will leave a residual icon when I change the length of the tray area (e.g. switching input method)

1.open a Software that has taskbar tray icon
2.using alt+shift to switch the input method(you need at least to input methods
3.switch back the input method,then It will leave a residual icon

![image](https://user-images.githubusercontent.com/68693675/129819279-847557e5-b821-4d8d-b469-ea813e4d11ea.png)
![image](https://user-images.githubusercontent.com/68693675/129819292-72cf0450-cce2-4226-803a-b76f5b12eb26.png)

Windows11
22000.132
TaskbarX1.7.1.0

**Comment by yashpalgoyal1304** [comment]
hi, does it seem similar to https://github.com/ChrisAnd1998/TaskbarX/issues/662 ??

**Comment by assassinliujie** [comment]
> hi, does it seem similar to #662 ??

yes

**Comment by yashpalgoyal1304** [comment]
@assassinliujie then i'd suggest that u paste ur input (description) there, and close this issue 😃😃

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
