### ISSUE TITLE
my taskbar broke after uninstalling latest version of taskbarx, icons wont centre either

### ISSUE THREAD

**Issue by ericmeister0** [ChrisAnd1998/TaskbarX#778]
**Describe the bug**
Icons do not centre, taskbar is broken after uninstalling taskbarx
(version is 1.7.1.0)
**Screenshots**

![Screenshot (2203)](https://user-images.githubusercontent.com/89142534/129905357-7372d849-ea3c-4f32-bdb7-1ad850b6e832.png)

**Comment by N0t-Br0ken** [comment]
Just restart the whole windows explorer and the issue should be fixed

**Comment by N0t-Br0ken** [comment]
I meant by using task manager

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
