### ISSUE TITLE
"Cannot Start Application" Error

### ISSUE THREAD

**Issue by Tech72** [ChrisAnd1998/TaskbarX#779]
I have a windows 10 64 bit desktop
When opening the taskbar x configurator manifest I get past the install button but then get prompted of the message displayed bellow. The detail log is also attached.
[7P5RS3U0.log](https://github.com/ChrisAnd1998/TaskbarX/files/7017638/7P5RS3U0.log)
![image](https://user-images.githubusercontent.com/70978388/130142179-12b21d29-0b31-429a-94a6-1f10df58d204.png)

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
