### ISSUE TITLE
Right Click box behind Taskbar

### ISSUE THREAD

**Issue by mingyewfoo1** [ChrisAnd1998/TaskbarX#780]
When we go to the task view (Win + Tab)
then we right click on the TaskBar,
the "Taskbar Settings" option will be behind the Taskbar

**To Reproduce**
1. Press Win + Tab
2. Right-Click on Taskbar
*Expected behavior**
The "Taskbar Settings" option will be behind the TB

**Screenshots**
<img width="577" alt="Untitled" src="https://user-images.githubusercontent.com/89394347/130447440-b01e55f8-ef95-48cd-bd82-b5afacc0f1cf.png">

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 21H1
 - OS Build: 19043.1165

**Comment by mingyewfoo1** [comment]
I changed TB to taskbar

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
