### ISSUE TITLE
I'd like the start menu to be same style as TB

### ISSUE THREAD

**Issue by mingyewfoo1** [ChrisAnd1998/TaskbarX#781]
I'd like the start menu to be same style as TB
Thanks In Advance

**Comment by yashpalgoyal1304** [comment]
whats tb?

**Comment by mingyewfoo1** [comment]
taskbar

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by yashpalgoyal1304** [comment]
oh, so u mean the style of the start menu right?? 'cz other than that i dont think other stuff is relevant regarding start menu.

![image](https://user-images.githubusercontent.com/19423063/132116725-a3b73ef9-8f0f-4065-856d-3cac4ca8ab13.png)

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
