### ISSUE TITLE
Blank space below the taskbar.

### ISSUE THREAD

**Issue by rahatpaudel** [ChrisAnd1998/TaskbarX#782]
There is a blank space below the taskbar. So, we can not position our mouse to the very bottom left to open start, and more importantly, we can not show the desktop from the bottom right. This is really annoying for me as I am used to doing that.

**Comment by rahatpaudel** [comment]
The start button and all other icons are fixed, but the show desktop button still can't be clicked from the very bottom right.

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
