### ISSUE TITLE
Aero Peek doesn't work while TaskbarX is installed.

### ISSUE THREAD

**Issue by CAOSUnleashed** [ChrisAnd1998/TaskbarX#785]
I want to try Aero Peek while TaskbarX is on but it doesn't let me on the bottom-right corner of my screen.

1. I hover my mouse on the bottom-right corner.
2. Aero Peek doesn't work.
3. If I move my mouse a little higher, Aero Peek works.

I expect Aero Peek to work always.

**Screenshots**
![0l2ktQStj7 - copia](https://user-images.githubusercontent.com/23172040/131190729-6f0f1575-591b-41d7-96d6-771dcd95de32.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 21H1

**Comment by BlacklightYT** [comment]
i have the same problem

**Comment by deepydarkness** [comment]
This is the only issue that's keeping me from updating to 1.7+. 1.6.9.0 doesn't have this problem.

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
