### ISSUE TITLE
Added a 2nd display and taskbar centering doesnt work anymore.

### ISSUE THREAD

**Issue by PyroUniKORN** [ChrisAnd1998/TaskbarX#786]
**Describe the bug**
I added a second display to my system and now only the taskbar on the secondary monitor will center. The main display will not move from the default {left} side of the taskbar no matter what settings I choose in TBX.

![Screenshot 2021-08-28 192312](https://user-images.githubusercontent.com/89713417/131234220-084a134c-f79f-4589-9d3a-a85bde47d147.jpg)
![Screenshot 2021-08-28 192300](https://user-images.githubusercontent.com/89713417/131234221-992171f3-9bb3-4e19-a21c-cff65a36450b.jpg)

**Comment by mdohrn** [comment]
I'm running into the same issue. 

**Versions:** 1.7.2.0, 1.7.1.0 and 1.7.0.0 (Using TaskbarX_x.x.x.x_x64.zip release)

1.6.9.0 works fine for me.

**Comment by yashpalgoyal1304** [comment]
related regression: #769

**Comment by legoraystudios** [comment]
> #783 there is a PR with a fix but yes the 1.6.9.0 has no Problems ^^

> I'm running into the same issue.
> 
> **Versions:** 1.7.2.0, 1.7.1.0 and 1.7.0.0 (Using TaskbarX_x.x.x.x_x64.zip release)
> 
> 1.6.9.0 works fine for me.

Yeeeah, I'm having the same issue and I downgraded to version 1.6.9.0. That's worked to me

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
