### ISSUE TITLE
Picking accent color from system

### ISSUE THREAD

**Issue by yashpalgoyal1304** [ChrisAnd1998/TaskbarX#790]
**Is your feature request related to a problem? Please describe.**
- The color of taskbar X doesnt sync with system's other elements' accent color when in non-default styled mode
- So, the taskbarX doesnt blend in with system - it feels like a different aloof part.

**Describe the solution you'd like**
- an option to use system's accent color₁ since it₁
    - can already be applied to sytem's elements (title bar, start menu, action center), and 
    - has ability to blend with wallpaper as well,
- so, if TaskbarX can use that₁ then it would become able to automatically blend in with all those things even in styled mode

**Additional context**

Color Picker < Styles < Taskbar X | Accent Color < Colors < Personalization < System
-- | --
![Styles] | ![Accent Color]

**Describe alternatives you've considered**
Nothing

[Styles]: https://user-images.githubusercontent.com/19423063/132116725-a3b73ef9-8f0f-4065-856d-3cac4ca8ab13.png
[Accent Color]: https://user-images.githubusercontent.com/19423063/132118063-54b0172b-c648-4384-a2ab-9908f206f6ff.png

---
Duplicate search: 🔍 [accent color](https://github.com/ChrisAnd1998/TaskbarX/issues?q=is:issue++accent+color)

**Comment by yashpalgoyal1304** [comment]
it can help in:
- Making the taskbar look similar as start menu (reverse case of #781) even in non-default style (i.e. even when no window is maximised)
- Making the taskbar look similar to title bar (verrry limited cases of #772) 
   - saying again, it wont achieve that completely, but in some user settings - it can. 
   - For example: if title bar and taskbar come in contact (i.e. when taskbar position ≠ bottom), then they'll have same color, so, will feel blended and not so "terrible".

![image](https://user-images.githubusercontent.com/19423063/132119078-587d01d6-1446-407d-8907-4dfd84f2bc19.png)

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
