### ISSUE TITLE
Scope of expansion?

### ISSUE THREAD

**Issue by yashpalgoyal1304** [ChrisAnd1998/TaskbarX#791]
- This issue is a bit of offtrack/out of scope issue and mingle of several thoughts which - software-wise pin on different aspects ig, but overall contribute to same thing - a nice and smooth UI/UX flow for 4 of the windows elements - taskbar, start, system tray, and action center. 
- This issue also consist of questions on suggestion for customising other elements than taskbar.
- This can be considered as overexpansion of https://github.com/ChrisAnd1998/TaskbarX/issues/781
- i know such issues are generally not welcome, but thought to discuss it since it's appeal felt huge to me.

Ohkay now, on with it:

1. #781 itself - ability to style the start menu - that will be so nice. I am pretty content with organisability side of Start Menu of Windows 10 specifically, but theming wise it lacks. So, this will cover that thing.
2. Can the styling part be extended to action center too? Can means 
    1. is it possible/doable in a clean way? and 
    2. can it be in TaskbarX's scope/roadmap?
3. _~And title bar too? So, effectively like superseding "Accent Color" system wide?~_ This is bit too much, and not my wish item either.

^

4. Any way, or recommended software with which i can modify system tray? 
     1. Specifically, i wanna remove/change the action center icon so that it doesnt occupy sooo much space. This will make it Win 11 like as well.
     2. As a totally overkill bonus, making the systray widgets' color and start button color to auto change between black and white based on bg will be cool too. t'll help when the taskbar is set to transparent/similar (Re: in the hack mentioned for accomplishing https://github.com/ChrisAnd1998/TaskbarX/issues/772#issuecomment-913128677 )

^

5. Any way to modify action center? 
It is implemented sooo poorly. it is thing of an utter disgrace in my opinion. Considering all the following points, i'd really like a way to tweak/replace windows action center. Similar to how i wanted to do to Taskbar before finding TaskbarX.

    1. it doesnt show the time and date - which becomes crucial soo many times when giving online exams - which are often held in full screen that is taskbar and systray is inaccessible.
    2. there's no way to go to dedicated setting of wifi/bluetooth etc. so, to change them, it requires going to system tray again. - although this aspect is _on its way_ to getting fixed in windows 11 - but ugh, let's not touch "windows 11" wormcan.
    3. It doesnt stick with taskbar location - always appears on right.
    4. the all settings tile is just wasting space there. 
    5. it can be potentially made more aligned with system tray - both things have soo much potential to be unified. giving an awesome clean look AND better UX. 
    6. W.r.t. point 1, 4, 5, 2 take android ≥ 9 for example - showing time/battery status, and settings icon besides it. Tap and hold opens dedicated settings. smooth UX flow.

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️

**Comment by yashpalgoyal1304** [comment]
**Update:** 2022.05.29

* That kind of thing is called an alternative "windows shell' 
* ... which is essentially a replacement for explorer.exe - [source] 
* Other alternative shells: [windows-alternative-shell]
* Found this whole trail via: [cairo shell]
* ... which is alternativeto: [modernflyouts] which was listed on [ms-store-app-awards]

[cairo shell]: https://github.com/cairoshell/cairoshell
[source]: https://www.youtube.com/watch?v=SYc2kEJH4qs&t=16s
[windows-alternative-shell]: https://www.online-tech-tips.com/software-reviews/7-best-windows-alternative-shell-replacement-programs/


[modernflyouts]: https://alternativeto.net/software/modernflyouts/
[ms-store-app-awards]: https://blogs.windows.com/windowsdeveloper/2022/05/27/announcing-the-microsoft-store-app-awards-winners/
