### ISSUE TITLE
Configurator is broken

### ISSUE THREAD

**Issue by Artaherzadeh** [ChrisAnd1998/TaskbarX#793]
If I apply the configurator crashes and I cant apply custom color it goes back to default black color after OS restart. Stop the app works but restart is not working we have to manually click on the app exe file.

**Comment by Artaherzadeh** [comment]
Went back to version 1.6.8. It was ok and never had a problem with it.

**Comment by Indomie-glitch** [comment]
Yes, I also have a similar problem. None of the settings in the configurator is getting applied.

**Comment by Artaherzadeh** [comment]
I tested version 1.6.8. It was ok before but after installing 1.7.1 I can't set color even on this version. I don't know what the problem is but 1.7.1 broke everything. But the configurator is more stable on 1.6.8

**Comment by jcjbocs4** [comment]
how did you went back to version 1.6.8?

**Comment by Artaherzadeh** [comment]
You can download the previous version on github page. It's more stable but still has some problems that I didn't have before this latest update.

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
