### ISSUE TITLE
The configurator is not working 

### ISSUE THREAD

**Issue by Indomie-glitch** [ChrisAnd1998/TaskbarX#795]
**Describe the bug**
Whenever I want to change the setting in the configurator it never gets applied even after I pressed apply. 
**To Reproduce**
Open TaskbarX Configurator
Change the settings to Transparent
Press Apply
Nothing happens

**Expected behavior**
The taskbar should be transparent
**Screenshots**
![image](https://user-images.githubusercontent.com/80404578/132616606-b8564184-8471-4df5-8ac2-4992b2aff096.png)

**Desktop (please complete the following information):**
 Windows 10
20H2

**Additional context**
None

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
