### ISSUE TITLE
TaskbarX will not open

### ISSUE THREAD

**Issue by wellsyzac** [ChrisAnd1998/TaskbarX#796]
TaskbarX will not open, no matter what I have tried so far. 

I downloaded “TaskbarX_1.7.2.0_neutral.zip” 

I unzipped the file to a folder in my downloads labeled ‘TaskbarX’

I opened to “TaskbarX” application, which centred the task bar, perfect, as I thought it may have done. But didn’t open the configurator. 

That’s when I noticed “TaskbarX Configurator” so naturally went to open that. But to no luck nothing opened. 

I got the spinning blue loading circle for about 10 secs, to which it then disappeared. 

The configurator would not open at all. 

I tried force closing it in task manager, to reopen the applications but it still did not work. 

I cannot uninstall it to try reinstall, as you uninstall via the configurator. From what I have seen in the video you posted. 

 I am on windows 10, unsure of what version. But can get that info if required. 
 
I love, love, love the design and functionality that TaskbarX can provide, of course from what I have seen. Really cannot wait to try this out properly!

**Comment by kevisguy346** [comment]
you have to open "TaskbarX.exe" first, then use the configurator.

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
