### ISSUE TITLE
TaskbarX Not Working

### ISSUE THREAD

**Issue by RareMaker50** [ChrisAnd1998/TaskbarX#797]
**Describe the bug**
When running TaskbarX and using the configurator, it does not change the taskbar and it stays as default. It is open is task manager

**To Reproduce**
1. Open TaskBarX
2. Use Configurator
3. Change anything
4. Make sure TaskBarX is open in task manager
4. Toggle Show Console

**Expected behavior**
It is supposed to blur (due to my settings) and centre, but it isn't

**Screenshots**
https://imgur.com/a/NXkm7Fh <- Here is console error that comes

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Version 21H1

**Additional context**

**Comment by snjyr123** [comment]
Ditto
Works for me when running as admin but then that breaks the startup task.

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
