### ISSUE TITLE
UI Automation is gray out

### ISSUE THREAD

**Issue by chriskoups** [ChrisAnd1998/TaskbarX#798]
I am on the latest version of Windows 10.

I have notices that from 1.6.x-1.7.x the UIAutomation is grey out.

Is a specific way to enable it?
Is it a future expansion?

**Comment by ChrisAnd1998** [comment]
@chriskoups It's something I may add later… UI Automation is the newer replacement for Microsoft Active Accessibility (MSAA). However MSAA is more plain. It just does what TaskbarX needs. UI Automation does not provide a better way of retrieving the taskbar(s) information or give better performance. MSAA even seems to have slightly better performance. If people are having problems with MSAA I will add the option to switch between them.

**Comment by shogerr** [comment]
That is confusing UX -- what about a hardcoded link to an issue in this issue tracker?
