### ISSUE TITLE
TaskbarX just working on one Monitor

### ISSUE THREAD

**Issue by BuildTrainer** [ChrisAnd1998/TaskbarX#799]
When i start TX my Taskbar will only center on one of my two monitors, i already reinstalled it and tried a few settings

I use Windows 10 and version 21H1

**Comment by BuildTrainer** [comment]
i needed to downgrade a version, then it fixed idk why but it did.
But i still wanna use the microsoft version and not the "website" version, i paid 2€ for it xDD

**Comment by excludes** [comment]
> 
> 
> i needed to downgrade a version, then it fixed idk why but it did.
> But i still wanna use the microsoft version and not the "website" version, i paid 2€ for it xDD

i get that, but there is no difference between microsoft store version and github version, other then microsoft store version supports Chris.

**Comment by valinet** [comment]
It's probably because of TaskbarX not taking into account when the "News and interests" panel is not displayed. Described [here](https://github.com/ChrisAnd1998/TaskbarX/pull/820).

An archive with fixed binaries according to the PR I made: [TaskbarX.zip](https://github.com/valinet/ExplorerPatcher/files/7271525/TaskbarX.zip).

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
