### ISSUE TITLE
the default taskbar feature for showing the desktop is not working properly

### ISSUE THREAD

**Issue by Styralix** [ChrisAnd1998/TaskbarX#800]
When taskbarx is on the feature for showing the desktop is not working properly (the right most box).
![01](https://user-images.githubusercontent.com/85453697/132951658-e1c05257-be73-4a04-abe1-61c17370d0a5.png)
my mouse is on the right down corner of my screen but i cannot click on the square that will show my desktop.
i can move my mouse a bit for the square to flash white meaning that i can press it.
exiting taskbarx and restarting windows explorer from the taks manager fixes the issue as long as you don't open the taskbarx again

**Comment by Murtsiboi** [comment]
I have the same issue. Downloaded from microsoft store. Windows 10 Pro N 21H1 build 19043.

It seems like it's the one pixel right at the corner that it somehow outside the click area. And if you flick your mouse there, that's the pixel you will click.

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
