### ISSUE TITLE
umm i m here to tell about the fix

### ISSUE THREAD

**Issue by littlooo** [ChrisAnd1998/TaskbarX#801]
listen everyone there is a glitch in taskbar x 1.07 so you can install taskbar x 1.06 here's the link
https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqbWp3UHM1SlhwSjFCbndRSndxMHh3anpaclRpZ3xBQ3Jtc0trYzJBTXNRTnBfSHVfWDdBSktlWXhkcjE5anluNGtKendQNFo2eW9BSmtjTm5LbTdsTEkyY05xTGFHM0Jvb3JOQzg2NW45dUt5bWk2bnhEODd4UFdIYzBrMVlOZjJxa1psMkRpUG9RZEQ4b1RPYzQtMA&q=https%3A%2F%2Fgithub.com%2FChrisAnd1998%2FTaskbarX%2Freleases%2Fdownload%2F1.6.2.0%2FTaskbarX_1.6.2.0.zip

![image_2021-09-15_182756](https://user-images.githubusercontent.com/90773371/133437532-56bf57f9-bad4-41de-b9d7-9ef967a211ec.png)
i found this link from here

**Comment by aor2021** [comment]
Taskbarx 1.7.2.0 for me now works perfectly

**Comment by Nydid** [comment]
Or you know, use the Github releases like a normal person. Why risk getting a virus on a random channel's link...

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
