### ISSUE TITLE
Windows Server 2022 Support

### ISSUE THREAD

**Issue by alextof** [ChrisAnd1998/TaskbarX#802]
I'm trying to center the bar in windows server 2022 and I'm not able to do that as it shows incompatibility.

`Waiting for Shell_TrayWnd
@Calculator | Object reference not set to an instance of an object.`

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️

**Comment by alextof** [comment]
Fixed in the latest releases.
