### ISSUE TITLE
The notification area icon increases or decreases, causing a restart

### ISSUE THREAD

**Issue by AsimovGod** [ChrisAnd1998/TaskbarX#803]
OS: [Windows 10]
Version [21H1]  

[#190](https://github.com/ChrisAnd1998/TaskbarX/issues/190)    
The problem recurs and should be caused by a software called TrafficMonitor.   

https://user-images.githubusercontent.com/75630897/134220617-1e0b6e36-4ab4-4644-99d8-4a7c7699bb7f.mp4

I don't know which party to turn to for help, but to bother you. Could you tell me if there is a solution?   
I've turned to TrafficMonitor, which is also open source software.  [TrafficMonitor](https://github.com/zhongyang219/TrafficMonitor)     
  
  
One more thing, please ask if you have any plans to update Chinese translations.

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
