### ISSUE TITLE
Not running in Windows 10, 21H1.

### ISSUE THREAD

**Issue by NityaNandaDPG** [ChrisAnd1998/TaskbarX#804]
<h3>The Application won't open in my desktop. I tried to Run as Administrator, but same result. Please help sir.</h3>

**My Device Specifications:**
Windows 10 Pro Edition
Version: 21H1

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
