### ISSUE TITLE
TaskbarX not restarting after hiding the second monitor taskbar

### ISSUE THREAD

**Issue by NGGiovanni** [ChrisAnd1998/TaskbarX#805]
Store or Regular version? Regular.
What's your Build of Windows 10? 20H2 19042.1237
.NET Framework 4.8 installed? Yes
Any Antivirus software? Bitdefender
Any other third-party taskbar tweakers? Wallpaper Engine and Rainmeter
What are your taskbar settings? Basically centralizing two monitors taskbar and keeping it translucent, also with taskschedule.
What says the error message if you got any? No error message

How to reproduce it:
1. Go to Windows Settings - Personalization - Taskbar - Multiple displays
2. Turn Off "Show taskbar on all displays" and turn it on again

That's not really a big problem and don't necessarily need a fix, i'm just keeping this here so it's a known issue. When you hide windows taskbar on the second monitor and turn it on again TaskbarX doesn't set it up again and it keeps the Windows default one.

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
