### ISSUE TITLE
Taskbar X just sraight up not working at all

### ISSUE THREAD

**Issue by Danny33452** [ChrisAnd1998/TaskbarX#806]
i have it downloaded from the microsoft store and when i start it nothing happens and when i open the configurator and try to just apply the default settings and any sort of customizations the console spits out this:
 @Calculator | Object reference not set to an instance of an object.
![image](https://user-images.githubusercontent.com/48798559/134606016-37dd8f24-27d4-4da0-b595-955bb358011c.png)
![image](https://user-images.githubusercontent.com/48798559/134606051-0a959f28-5b60-4240-884a-1493cd907c18.png)

**Comment by jerrydmoss** [comment]
I'm having a similar issue.

TaskbarX stopped centering on my primary display, but works on my 2nd and 3rd displays:

![Screenshot 2021-09-24 103742](https://user-images.githubusercontent.com/26930586/134702693-7df508a4-aeb0-4d08-bb32-fe0f107028b7.png)

![Screenshot 2021-09-24 104352](https://user-images.githubusercontent.com/26930586/134703390-e213607d-dd1b-4dbf-b9a6-5c5b16d650d8.png)

**Comment by Danny33452** [comment]
I don’t have a secondary display but does your console output the same error as mine?

**Comment by jerrydmoss** [comment]
I am seeing that calculator object reference not set error in the console.

**Comment by jerrydmoss** [comment]
Windows Update just fixed the issue for me? Weird?

**Comment by valinet** [comment]
It's probably because of TaskbarX not taking into account when the "News and interests" panel is not displayed. Described [here](https://github.com/ChrisAnd1998/TaskbarX/pull/820).

An archive with fixed binaries according to the PR I made: [TaskbarX.zip](https://github.com/valinet/ExplorerPatcher/files/7271525/TaskbarX.zip).

**Comment by Danny33452** [comment]
Oh i see i was gonna say it randomly started working again but i now realized thats cause this computer has 1909 installed which has no such news and interested tab but i digress thanks replying

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
