### ISSUE TITLE
How to Fix 1.7.2.0 Not Working (STOP CREATING ISSUES)

### ISSUE THREAD

**Issue by fun840** [ChrisAnd1998/TaskbarX#807]
I'm seeing so many people spamming issues on this repository when there are clearly so many already there. I'm making this issue to show people who are new to Github how to download an earlier version that still works, and I'll close the issue once 1.7.3.0 comes out.
To download an earlier version, go to [this link: https://github.com/ChrisAnd1998/TaskbarX/releases/tag/1.7.1.0](https://github.com/ChrisAnd1998/TaskbarX/releases/tag/1.7.1.0) and download the version which is right for you. This is just version 1.7.1.0, which still works. 
If you see this, please, you DO NOT need to create another issue with the same information. If you have an actual issue unrelated to 1.7.2.0 not working, search the issues to make sure it hasn't already been posted. Hopefully this helps the people having the same problem.

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
