### ISSUE TITLE
BUG: TaskbarX creating a small gap between windows peek button

### ISSUE THREAD

**Issue by zhyph** [ChrisAnd1998/TaskbarX#808]
**Describe the bug**

**To Reproduce**
1. Go to down right where Windows Peek should be
2. Hover over the extreme down right
3. Windows Peek does not work, and it's possible to click in the desktop “though” taskbar.

**Expected behavior**
In earlier versions it doesn't have this problem(1.6.9 I believe), if the cursor is on the extreme edge of the screen in the desktop it was still not clickable.
![Working](https://user-images.githubusercontent.com/68618179/134730474-40b09d5b-a9f9-46ec-9773-4b6daeff57e3.gif)

**Screenshots**
As you can see the desktop is clickable though and when I hover until the end the “hover” animation disappears, meaning that it is not fixed to the bottom of the screen
![Bug](https://user-images.githubusercontent.com/68618179/134730489-82814769-6d97-4cf7-a2d9-4112a8ce4495.gif)

**Desktop (please complete the following information):**
 — OS: [Windows 10]
 — Version: [21H1]
 — Build: [19043.1237]

**Additional context**
PS: To stop this problem, the only thing I've noticed working is uninstalling Taskbar via his configurator, deleting its files and then restarting the pc.

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
