### ISSUE TITLE
taskbarx config not work after changing settings

### ISSUE THREAD

**Issue by aor2021** [ChrisAnd1998/TaskbarX#810]
**Describe the bug**
After changing taskbarx 1.7.2.0 settings. it will work fine once, but if i want to change settings again. it wont work and i have to reinstall.

**To Reproduce**
1. Go to 'Taskbarx Configurator'
2. Click on 'settings that i want to change..'

**Expected behavior**
taskbarx configurator still works after changing settings

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 21h1]
 

**Additional context**

**Comment by aor2021** [comment]
and yeah this is a re upload i cant find the old one

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
