### ISSUE TITLE
when i try it in my windows 11 the taskbar appreeance feature works but the iwndows icon dozent shifts to the left and apps to not go to center it says like the default taskbar icon arrangement and when i open console it says 

### ISSUE THREAD

**Issue by TheOnlyPixelOne** [ChrisAnd1998/TaskbarX#812]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Version [e.g. 1909]

**Additional context**

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
