### ISSUE TITLE
It dozent work in windows 11

### ISSUE THREAD

**Issue by TheOnlyPixelOne** [ChrisAnd1998/TaskbarX#814]
I troed it in qindows 11 and it dozent work the colour, blur, etx feature does work but the felt alinged start button and center app icons dozent works so please update it for windows 11

**Comment by ashergz** [comment]
Well windows 11 has centered icons by default but i was actually curious the skinning. Good to know I can still have transparent taskbar.

**Comment by nectoar** [comment]
Yeah has some odd errors for me in Windows 11 - most if it worked but I was unable to open the Windows 11 Display Settings windows (one you change your resolution, etc). After uninstalling this the window would open normally

**Comment by 0ibaba** [comment]
> 
> I want the start button in left and apps in center i like apps in centre but start button in centre is a bit annoying so it would be great if u managed to slide the start button to the left in center taskbar mode
>
Yeah, that's what I'd like too

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
