### ISSUE TITLE
Primary Taskbar doesn't centre, but others do

### ISSUE THREAD

**Issue by benwornes** [ChrisAnd1998/TaskbarX#816]
**Describe the bug**
The taskbar on my main monitor doesn't seem to centre, but the rest of my settings (remove tray, remove windows button, transparentness) seem to work fine.

Even without changing any settings at all, when taskbarX first opened, the taskbar on my primary monitor was not centred.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open TaskBarX
2. Set Translucent
3. Add Extras shown in the photo
4. See an error

**Expected behaviour**
Both taskbars should be centred.

**Screenshots**
![image](https://user-images.githubusercontent.com/67489093/135374490-29f4c6b8-04f5-44b2-92a7-6d469ef16cbd.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 21H1

**Additional context**
I just reinstalled windows, it worked fine on my previous install. Not sure what, but something's broken in this install.

**Comment by valinet** [comment]
It's probably because of TaskbarX not taking into account when the "News and interests" panel is not displayed. Described [here](https://github.com/ChrisAnd1998/TaskbarX/pull/820).

**Comment by valinet** [comment]
It's probably because of TaskbarX not taking into account when the "News and interests" panel is not displayed. Described [here](https://github.com/ChrisAnd1998/TaskbarX/pull/820).

An archive with fixed binaries according to the PR I made: [TaskbarX.zip](https://github.com/valinet/ExplorerPatcher/files/7271525/TaskbarX.zip).

**Comment by benwornes** [comment]
This might be right. Randomly today it started working. I noticed that even though the tray area was hidden, the weather bit "News and interests", was displayed, even though I had never enabled it and had never seen it before. Not sure why it randomly enabled itself, but that seem to have fixed it. Will the fix you posted work even if the news and interests panel goes away again?

**Comment by valinet** [comment]
Yeah, that’s what the fix is, otherwise it would be the same as the publicly available version. You can also disable “News and interests” right away by right clicking on its taskbar button and choosing “Turn off” or something like that; it’s there in the options, look for it.

**Comment by benwornes** [comment]
Yeah, I disabled it. Your fix seems to work.

Thanks.

**Comment by valinet** [comment]
You’re welcome. I hope all is well with the developer, and hopefully he/she will be back online soon.
