### ISSUE TITLE
Restart TaskbarX - Command Line

### ISSUE THREAD

**Issue by 101AustinTech** [ChrisAnd1998/TaskbarX#817]
Hi there,
Is it possible to restart the TaskbarX app from the command line as this would be useful for a script I have made that restarts explorer, then restarts TaskbarX, so the transparency still works after restarting explorer.
Thanks, Austin :)

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
