### ISSUE TITLE
Opening and closing an application

### ISSUE THREAD

**Issue by TankArgie** [ChrisAnd1998/TaskbarX#821]
When opening and closing an application repeatedly, this is what I get. I was trying to test if it can handle it or not.
Note: It's my first time using this software, and this is my first issue I made on Github, if there is a duplicate of this, please kindly direct me there thank you.

https://user-images.githubusercontent.com/60542682/135727620-1fd6d31e-090b-4ea3-bdf0-226f5ac9f8ba.mp4

Windows 10
21H1 - 19043.1263

**Comment by aor2021** [comment]
The same taskbar glitching happend to me, where sometimes if i close a app it just glitches, but it recovered and seemed normal after

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
