### ISSUE TITLE
Arrows of Toolbars are not highlighted on mouseover

### ISSUE THREAD

**Issue by nexusV2** [ChrisAnd1998/TaskbarX#824]
The arrow-icons of the toolbars are not highlighted when moving the cursor over them.
![Unbenannt](https://user-images.githubusercontent.com/24851823/136708736-1da78142-24df-4d8d-b7b6-e856f16e23fd.PNG)
![Unbenannt](https://user-images.githubusercontent.com/24851823/136709343-bc738867-9721-49d2-9c05-72ecd6f1b04d.PNG)

Win 10 [21H1/build 19043.1266], TaskbarX version 1.7.2.0

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
