### ISSUE TITLE
Transparancy effects disappears after a reboot - Windows 10

### ISSUE THREAD

**Issue by HenrikRaakil** [ChrisAnd1998/TaskbarX#825]
**Describe the bug**
Transparancy effects disappears after a reboot.

**To Reproduce**
1. Start Windows with TaskbarX set to autostart.
![desktop](https://user-images.githubusercontent.com/89202778/136811875-750dfaf6-021d-437a-9c42-6bca6cf0b9f2.PNG)

**Expected behavior**
Transparancy effects being active, like other features like centering.

**Desktop (please complete the following information):**
 - OS: Windows 10
 -  Version 21H1 OS Build: 19043.1165

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
