### ISSUE TITLE
failure to center on 1.7.2 x64 portable

### ISSUE THREAD

**Issue by Gunnthorian** [ChrisAnd1998/TaskbarX#826]
**Describe the bug**
after a fresh win10 install taskbarx was one of the first installs i did (as usual) and to my surprise my icons didn't center. after messing with it I couldn't fix it, uninstalled, pulled 1.5.6.0 off of my old system drive and it works.

**To Reproduce**
ofc this one probably wont be reproducible, however i do remember opening the configurator before the application. whether this is the reason or not i have no idea.

**Expected behavior**
center

**Screenshots**
no need, just looked like default taskbar, however i was able to change the blur style and every now and then my side monitor taskbar would center

**Desktop (please complete the following information):**
fresh win 10
Version	10.0.19043 Build 19043

**Additional context**
none, if digging into this causes a headache, ignore it.

**Comment by ChrisAnd1998** [comment]
Please try the pre-release 1.7.4.0
