### ISSUE TITLE
TaskbarX Unresponsive

### ISSUE THREAD

**Issue by falsonerd** [ChrisAnd1998/TaskbarX#827]
**Describe the bug**
TaskbarX stops working whenever an app on something else restart windows explorer.
Restartubg TaskbarX through Configurator will cause it to crash.

**To Reproduce**
1. Open Task Manager and restart windows explorer
or
1. Check switch back to default...
2. Start something in fullscreen.

**Expected behavior**
Taskbar continue working.
Clicking Restart

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 21h1 (19043.1266)

**Workaround for unresponsible taskbar**

1.Open Taskbarx configurator
2.Click Unninstall and wait it to finish
3.Start  TaskbarX again and set all your configs once more.
You have to do that every time it stops working.

**Additional context**
Event Viewer Log: 
![image](https://user-images.githubusercontent.com/50148645/136957104-7c25d11e-b13e-4be1-9756-80dd338b3711.png)

**Issue 2**
Small gap beside windows peek.

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
