### ISSUE TITLE
file explorer dragged behind taskbar causes system freeze 

### ISSUE THREAD

**Issue by winkface1** [ChrisAnd1998/TaskbarX#828]
**Describe the bug**
when the file explorer window is moved behind the taskbar once transparency is enabled the whole operating system lags and freezes, this only happens when file explorer is hovered underneath the taskbar other windows such as firefox do not cause the system to lag. this is on windows 11 latest version btw.

**To Reproduce**
1. Go to file explorer
2. Click on file explorer 
3. Drag file explorer window behind taskbar 
4. See error which is whole windows 11 operating system lag and freeze 

**Expected behavior**
for the file explorer to go behind the taskbar without issue or freezing of the os 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows 11 pro
 - Version : Version	10.0.22000 Build 22000

**Additional context**

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
