### ISSUE TITLE
A few options for taskbar Icon customizability

### ISSUE THREAD

**Issue by GanerCodes** [ChrisAnd1998/TaskbarX#829]
Basically, there's a few features that StartIsBack has that I would love to exist in an open source program like this one, as well as a few Taskbar Tweaker options that would well suited here

1. Change spacing between taskbar icons, SIB+ has various margin sizes to choose between that would be nice to enable here
2. Large taskbar icons; this is something 7+ Taskbar Tweaker has that's really nice
3. Remove little line under opened programs icons. I know some custom themes remove it but for the life of me I cannot figure out what they are doing so if anyone figures out how please let me know

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
