### ISSUE TITLE
TaskbarX not working on Windows 10 Build 19043.928

### ISSUE THREAD

**Issue by Kaization** [ChrisAnd1998/TaskbarX#830]
Hi, I am currently reinstalling Windows on my PC, when I load TaskbarX everything works fine but when I click apply or Restart TaskbarX it no longer works

**Comment by Kaization** [comment]
nope nevermind didnt change anything still doesnt work

**Comment by Kaization** [comment]
![image](https://user-images.githubusercontent.com/88996167/137237721-8b3b91a9-be90-4214-aab6-b105a627bbd6.png)

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
