### ISSUE TITLE
TaskbarX not making the icons centered

### ISSUE THREAD

**Issue by MichaelJordanss** [ChrisAnd1998/TaskbarX#831]
pls help me. i downloaded the 64bit version. i can use the configurator for transparency etc, but i cant seem to make it centered. how to fix it?

**Comment by atharizky13** [comment]
i have the same problem here can you guys help ?

**Comment by Striveflash** [comment]
Had the same issue.
i fixed it by using the release 1.6.9.0

**Comment by sorryjack** [comment]
thanks, 1.6.9.0 works on my win 11

**Comment by ChrisAnd1998** [comment]
Please try the pre-release 1.7.4.0
