### ISSUE TITLE
Transfer Area stopping work

### ISSUE THREAD

**Issue by HugoPFe** [ChrisAnd1998/TaskbarX#833]
There is a lot of weeks that I have notice this behavior. I use my computer normally and suddenly the Ctrl + C, Ctrl + X, Ctrl + V and even PrintScreen commands stop work. And checking the transfer area by pressing Win + V, I can see the oldest things that I have copied, but I can't paste it. I've been made some tests and this behavior don't happens if I don't open the TaskbarX. I've tried to reinstall and even reinstall windows already.

**To Reproduce**
Unfortunately, I have no idea how reproduce it. It's completly suddenly.

**Expected behavior**
Copy and paste items without problems.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 21H1 19043.1288

**Additional context**
By rebooting pc the behavior stops, but it returns later.

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
