### ISSUE TITLE
An obvious line when the taskbar is on a white background in Windows 11

### ISSUE THREAD

**Issue by EPICGAMER521** [ChrisAnd1998/TaskbarX#834]
**Describe the bug**

**To Reproduce**
1. Put a white background and observe a line on the top of the taskbar

**Expected behavior**
There is a obvious line on the top of the taskbar

**Screenshots**

![v0pih17slst71](https://user-images.githubusercontent.com/92638182/137591512-77c465f5-3b4c-4e74-9595-e5557066b679.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version: 22000.258

**Additional context**

**Comment by EchoSphere-Chara** [comment]
I am also having this issue, it's a very obvious line, doesn't have transparency, looks grey.

**Comment by ChrisAnd1998** [comment]
@EPICGAMER521 This is some sort of shadow of the taskbar. Sadly this is unfixable.
