### ISSUE TITLE
添加语言支持

### ISSUE THREAD

**Issue by MYXXTS** [ChrisAnd1998/TaskbarX#836]
可以添加中文语言支持吗？

**Comment by zedd-0** [comment]
it will be asked for a support of the chinese language *
---
at the moment there is probably no developer who could cultivate the chinese language. 
没有支持中文的开发者。*

( * Google Translator )

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
