### ISSUE TITLE
making it hide the start button for windows 11 and the very obvious line when it is transperent

### ISSUE THREAD

**Issue by Skulcrusherr** [ChrisAnd1998/TaskbarX#839]
hello, i recently updated to windows 11 and it came with a start button that also moves with the icons... i was wondering if you can add a setting to be able to hide the start button.

and also there is a very obvious seem that connects the taskbar and the desktop when it is transparent, i was wondering if you can edit that out.
![image](https://user-images.githubusercontent.com/73060680/139375934-e7d9c417-676d-4974-863d-cbca9c5f2a43.png)

**Comment by 0ibaba** [comment]
@Skulcrusherr iirc this was also present in translucent tb, so it probably has something to do with windows. 
I'm currently using rounded tb, and it doesn't seem to have this problem

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
