### ISSUE TITLE
TaskbarX x64 multiple versions is broken, also on 2 different Rainmeter versions

### ISSUE THREAD

**Issue by GalGreenfield** [ChrisAnd1998/TaskbarX#840]
**Describe the bug**
• No centering of the icons
• Right-aligning the icons
• With News and Interests  Show icons and text option on, some of the right-most icons are hidden by it (they go "under" it)

**To Reproduce**
Steps to reproduce the behavior: get the Windows in the version listed below
1. Install Rainmeter's latest version (4.5.2)
2. Use SkinInstaller to install the skin
3. See error

**Expected behavior**
Centering of the icons in the vertical center of the taskbar, as shown screenshots and pictures.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10, version 20H2, build 19042.1319
 - TaskbarX Versions: TaskbarX_1.7.2.0_x64, TaskbarX_1.7.1.0_x64, TaskbarX_1.6.9.0_x64

**Additional context**

It stopped working suddenly one day. I had TaskbarX of version (IIRC) 1.6.1 (or 1.6.9, probably 1.6.1) and it worked with Rainmeter v4.4 RC 3404 beta. When it suddenly stopped working it was on that version. I tried doing a clean install of the latest version - Rainmeter v4.5.4 and it continued being broken.

After performing a clean install of Rainmeter v4.5.2, all 3 versions I tested behaved the same.
I don't remember what changed between the day I noticed it stopped working and after it. I _assume_ that it was due to a Windows Update but I really don't know. It's the only variable that was the most likely to changed compared to the other ones (as I didn't apply any changes to neither Rainmeter nor TaskbarX).

I also bought the app from the Microsoft Store. It said no refunds, which I was okay with, but that version doesn't work, either (it behaves the same). Since it doesn't do as advertised it's false advertisement, so I want a refund. I bought it only in the hope that the paid version that's in the Microsoft store might work.

**Comment by GalGreenfield** [comment]
Hi, there's still no reply on this - the app **doesn't work as intended**. Please at least reply!

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
