### ISSUE TITLE
Taskbar on 'higher' display only blurred halfway

### ISSUE THREAD

**Issue by lua-P** [ChrisAnd1998/TaskbarX#841]
**Describe the bug**
When adding a second monitor to my system and tweaking the height in system settings in order for them to line up,
the upper display refuses to blur the taskbar in its' entirety.

**To Reproduce**
1. Set high-contrast wallpaper
2. Set taskbar style to 'Blur'
3. Set different vertical alignment for monitors (see app. 1)
4. ???
5. Pro... errrr Issue (see app. 2)

**Expected behavior**
Taskbar blurs completely

**Screenshots**
![Appendix 1](https://user-images.githubusercontent.com/93545247/139719455-0a7a6b47-b5bd-42e7-a17a-8bf1b6394302.png)

![Appendix 2](https://user-images.githubusercontent.com/93545247/139719311-805d8ade-679e-4483-9bc7-0836588d3c2e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 21H1
 - TaskbarX Version: 1.7.2.0

**Comment by ChrisAnd1998** [comment]
@lua-P Sadly this is the behaviour of the blur effect in Windows. This is unfixable.
