### ISSUE TITLE
Taskbar stuttering when dragging a higher resolution window

### ISSUE THREAD

**Issue by XSSMOKEONE** [ChrisAnd1998/TaskbarX#843]
So basically I have a 19 inch 1440x900 second monitor and if I drag a 1600x900 window to the top of the display(that isn't maximizable)the taskbar starts to stutter. This happens when you try to maximize the League Of Legends Client
Windows Version:21h1
TaskBar X Version:1.7.2.0

I don't mind it, just so that you know about the issue

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
