### ISSUE TITLE
Not centering on second screen and decentered on primary screen

### ISSUE THREAD

**Issue by pacmac34** [ChrisAnd1998/TaskbarX#844]
Hello,

My secondary screen is the one on the left.

It's not centering the icons on my secondary screen taskbar.
On my primary screen, it seems that the centering is taking the first icon on the left as the reference.

<img src="https://i.imgur.com/9xjwQlL.png" width="1000"/>

Thanks.

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
