### ISSUE TITLE
TaskbarX dont center. Older version also not fix the Problem.

### ISSUE THREAD

**Issue by VxMisc** [ChrisAnd1998/TaskbarX#846]
**Describe the bug**
TaskbarX dont center anymore and the suggestions to install older version also not fix the problem.
Installing .NET Framework 4.8 didnt fix it too.

Nothing i tried works.

Can anyone help me?

**Desktop:**
 - OS: Windows 10 Pro
 - Version: 20H2

**Comment by ChrisAnd1998** [comment]
What version did you use in the first place?

**Comment by VxMisc** [comment]
I used the version 1.7.2.0. Suddently it doesnt center anymore. Did not change any setting.

So i tried also the latest version 1.7.3.0. Unfortunately didnt work for me.

After i read here, that many people has the same issue and they said use older version that will fix it.
So i tried older version from 1.6.0.0 to 1.7.1.0. too. But nothing helped.

**Comment by ChrisAnd1998** [comment]
For some a Windows update will do the trick.

**Comment by VxMisc** [comment]
I did it yesterday. Now i am fully updated, but it still not center

**Comment by yorkeJohn** [comment]
Can also confirm that centring is not working anymore. Downgrading to an older version does not fix the issue either. Icons are pushed about 75% to the right instead of 50% centre.

**Comment by Shurikensenpai** [comment]
> Can also confirm that centring is not working anymore. Downgrading to an older version does not fix the issue either. Icons are pushed about 75% to the right instead of 50% centre.

yes thats exactly what is going on here
and its like 75% to the right and since i use a secondary monitor the icons in the secondary monitor are not centred

**Comment by Shurikensenpai** [comment]
![image_2021-11-25_195343](https://user-images.githubusercontent.com/95030459/143458321-819836e4-e4d5-4070-a9c3-34c4658d69f6.png)

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
