### ISSUE TITLE
not working on windows 11

### ISSUE THREAD

**Issue by XPower7125** [ChrisAnd1998/TaskbarX#847]
I wanted to center only taskar icons (not start menu...) but the latest taskbarX version, doesn't work.

how to Reproduce this problem
1. open taskbarx configurator.exe
2. Click on apply
3. look at your taskbar (I had taskbar on the left)

i expected the taskbarbar to center

 - OS: Windows 11
 - Version 21H2 22000.258 stable channel

I used taskbarx on windows 10 2004 and it worked very well

SCREENSHOT
![image](https://user-images.githubusercontent.com/64551044/140912502-2c13a20a-2a52-43af-8163-43cf8b088390.png)

**Comment by ChrisAnd1998** [comment]
@XPower7125 TaskbarX does not work with the new taskbar from Windows 11. In Windows 11 there is an option to center the taskbar icons now. However if you don't like the new taskbar you can bring back the old taskbar with ExplorerPatcher
https://github.com/valinet/ExplorerPatcher

Doing this will make TaskbarX work again.
