### ISSUE TITLE
transperent option not working

### ISSUE THREAD

**Issue by Ninjarexxx** [ChrisAnd1998/TaskbarX#849]
so when i click on transperent in style option and click apply it dosent change anything it just moves my icon somehwere and returns it back. i dont know if this is a bug
Also i have a theme enabled from this video: https://www.youtube.com/watch?v=gjLm_g-FJMg
i just put the link so that u can see if the problem is coming from the theme

**Comment by ChrisAnd1998** [comment]
@Ninjarexxx Does this happen without the theme installed? UXThemePatcher might be the cause here..
