### ISSUE TITLE
Centering Issue with Multiple Monitors

### ISSUE THREAD

**Issue by eblaxton** [ChrisAnd1998/TaskbarX#850]
After updating Windows 10 and TaskbarX my taskbars on my left two monitors won't center and the taskbar on my right monitor won't even show.
![Desktop](https://user-images.githubusercontent.com/18471718/142624105-04f75e68-00a6-4a40-85ab-27a1ad78aa67.png)

When I reset to default settings I have the same issue.
![Desktop_Default](https://user-images.githubusercontent.com/18471718/142624474-7b07a6af-cf74-4348-8d23-b01f6a8496a1.png)

I did have to purchase the app in the Microsoft store in order to actually run the application and here is an image of my TaskbarX Configurator About page.

![TaskbarX Config](https://user-images.githubusercontent.com/18471718/142624709-b7b35aa1-8127-4cf8-b4a1-b72de366bc69.png)

Before purchasing and updating the app, I had version 1.7.1.0 and had the same issues.

Sorry for the large images, the taskbar may be had to find/see.

**Comment by eblaxton** [comment]
I also just tested each previous version until 1.6.9.0. Each version had the same issue except 1.6.9.0 which moved every taskbar off screen.

**Comment by yorkeJohn** [comment]
Can confirm this issue is happening.

**Comment by Shurikensenpai** [comment]
yes even i can confirm this happening
for me the icons on the main monitor are offset from the center and in the secondory monitors it not even centred

**Comment by rafaelgsilveira** [comment]
Yes, I'm also having this issue.
The icons on the main monitor are not centered and in the secondory monitors it not even showing

**Comment by mcwidg3t** [comment]
Similar problem for me. Icons on primary monitor not centring, they are a little off to the right. Items on secondary monitor don't move at all. Playing about with the taskbar offset does move the icon locations on primary but not secondary.

WIndows OS Build: Windows 10 Ent, 19041.1348
TaskbarX Build: 1.7.3.0

Started happening a couple of weeks ago, similar time to the other reports in this thread.

**Comment by Geekays** [comment]
I also see the same issue.

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
