### ISSUE TITLE
Desktop Peek button bottom edge broken after using TaskbarX (persists after closing)

### ISSUE THREAD

**Issue by CraggyX** [ChrisAnd1998/TaskbarX#851]
The Peek button to the right of the Tray, on the taskbar doesn't quite work right after Taskbar X has been launched. 
Under normal conditions, the mouse can be 'whacked' into the very corner of the screen and a mouse click will show the desktop. Importantly, the cursor can be on the very edge of the monitor and the button still works.
After launching TaskbarX, however, it seems that the very bottom row of pixels no longer can be clicked on to show the desktop; instead, one must 'whack' the mouse into the corner, then raise it upwards fraction to enable the Peek button to be clicked (it changes colour when the cursor is over it and clickable). 
This issue persists even _after_ stopping TaskbarX from the configurator, and so far the only way I have found to restore normal Peek behaviour is to disable TaskbarX from launching on startup and rebooting the PC. 
The issue goes away in Safe Mode, but then is _immediately_ back again after manually running TaskbarX.exe, and does not return to normal after stopping the program. 
The version of TaskbarX I am using is 1.7.3.0.

**Comment by xolboy** [comment]
i was having the same issue too, so i tried installing different versions and 1.6.4.0 works fine for me atm

**Comment by Sharlentouane** [comment]
Same thing for me here. Peek button seems to be broken in newer versions. Just tried 1.6.4.0 and it works fine here too. Thanks for the info!

**Comment by xolboy** [comment]
ur welcome lol

**Comment by deepydarkness** [comment]
I'm also facing the same issue. Going to stick to 1.6.4.0 until this bug gets fixed!

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
