### ISSUE TITLE
TaskbarX 1.7.3.0 x64 - Does not launch on system start

### ISSUE THREAD

**Issue by Filip134** [ChrisAnd1998/TaskbarX#852]
I upgraded from 1.6.8 I think? Now on the most recent version it doesn't launch on system start and I need to open it up manually. Tried increasing the delay in seconds even to a minute but that does nothing.
Avast doesn't hold any files hostage.
I use no other taskbar tools.
I do have .NET 4.8.
My only setting is blur at 10% and of course centered items.
I have Windows 10 20H2 19042.1348

**Comment by ChrisAnd1998** [comment]
In your startmenu search for "Task Scheduler". On the left menu click on "Task Scheduler Library". In the middle a list will appear.
Look for a TaskbarX entry. Then delete that entry. After that close the Task scheduler app and and let the configurator create a new one by clicking the Apply button inside the configurator.

**Comment by Filip134** [comment]
That did it, thank you!
