### ISSUE TITLE
the taskbar flashes when you open the start menu

### ISSUE THREAD

**Issue by Fefedu973** [ChrisAnd1998/TaskbarX#853]
the taskbar flashes when you open the start menu

**To Reproduce**
set taskbat to blur
It happens some time
1.press windows button
2.taskbar flashes
Or (It happens all the time)
1.drag a window
2.press windows button
3. the taskbar flashes

**Expected behavior**
stop the taskbar flashes

**Screenshots**
video

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Version [22000.348]

**Additional context**
an other small bug when the tackbar is set blur and the rounded corner are enable we must press windows button to show the rounded corne

https://user-images.githubusercontent.com/80718477/143676656-fe554d20-1dc0-472f-8a65-c37aff9de685.mp4

rs

**Comment by RaveVR** [comment]
I have Windows 10 and version (I don't know if you meant OS Build) 19043.1348 is it. My taskbar flashing when open Start Menu, how can I fix it?

**Comment by ChrisAnd1998** [comment]
@Fefedu973 This should only happen with the Acrylic effect.. but you are having it with blur too! The Taskbar refreshes itself when the start button is hit. Sadly i can't make it stop doing that :/
