### ISSUE TITLE
It is not hiding the secondary start button in Windows 11

### ISSUE THREAD

**Issue by fernandoccandidoo** [ChrisAnd1998/TaskbarX#855]
![image](https://user-images.githubusercontent.com/61832398/143810756-4142d8e7-281b-4bcd-a426-81f4d2c141d8.png)

The option to hide the menu start on the 2nd screen is not working on windows 11.

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
