### ISSUE TITLE
A thin line appears in the newer build (22504.1010) of win11

### ISSUE THREAD

**Issue by symeen** [ChrisAnd1998/TaskbarX#856]
A thin line appears at the top end of the taskbar when applying a transparent setting.  
For reference, a screenshot is attached with this issue.

**To Reproduce**
1. Go to extracted folder of 'TaskbarX_1.7.3.0_x64.zip'
2. Click on 'TaskbarX Configurator.exe'
3. Hover to 'Style'
4. Select 'Transparent'
5. Click on 'Apply'
6. Click on 'Restart TaskbarX'
4. See the error
![Screenshot (1)](https://user-images.githubusercontent.com/83005417/143824670-5e43d31b-2377-47f0-a119-58a451ee88b4.png)

**Expected behavior**
Taskbar becomes transparent immediately but the upper portion displays shows a thin line 
in the newer build 22504.1010 of Windows 11

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Version [22504.1010]

**Comment by ChrisAnd1998** [comment]
@symeen Sadly this is unfixable it's some sort of shadow of the taskbar itself.
