### ISSUE TITLE
Changing Virtual Desktop causes TaskbarX to reload

### ISSUE THREAD

**Issue by isayakmondal** [ChrisAnd1998/TaskbarX#857]
**Describe the bug**

While changing virtual desktops on windows 10 feels like it is being reloaded. I don't know if it's a windows 10 issue or not. I've linked a video below.

**Screenshots**

https://user-images.githubusercontent.com/51121313/144092897-00d71559-8a83-4dbd-b805-896b60ca256b.mp4

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 21H2 (OS Build 19044.1348)

**Comment by ChrisAnd1998** [comment]
@isayakmondal This happens because the amount of icons on your desktop(s) are different. It's just centering them again.
