### ISSUE TITLE
TaskbarX resetting taskbar centering when the system is under load.

### ISSUE THREAD

**Issue by KittenCat180** [ChrisAnd1998/TaskbarX#858]
Description:
When the system is under load, the taskbar moves to the left of the screen, as per default behavior, and if the load is not removed, the taskbar begins to become inconsistent, and the centering of the icons are wildly different from second to second. On rare occasions, the icons disappear entirely, and it takes a few seconds to return.

1. Load a demanding application 
2. Taskbar resets to the left of the screen, and then returns to the center, if the load is sustained, the taskbar becomes unusably inconsistent.

Expected behavior:
The taskbar, even if it lags, should remain centered, under any system load, icons should remain.

Screenshots:
I was unable to get a screenshot of the behavior, I might be able to later.

 - OS: Windows 10 21H1 19043.1348

**Comment by ChrisAnd1998** [comment]
@KittenCat180 Can you check if the "Pause looper when fullscreen app is running" option is disabled? It's under the Extra tab.

**Comment by KittenCat180** [comment]
@ChrisAnd1998 I did, That setting is disabled.
