### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by EgorZverev** [ChrisAnd1998/TaskbarX#859]
I trying to start TaskbarX.exe but nothing going on. But TaskbarX.exe appears at processes in Task Manager

**Comment by L0garithmic** [comment]
Same issue

**Comment by ChrisAnd1998** [comment]
@EgorZverev Can you try an older version like 1.6.9.0 ?

**Comment by L0garithmic** [comment]
> @EgorZverev Can you try an older version like 1.6.9.0 ?

That functions. Any idea the issue?
