### ISSUE TITLE
taskbarx: could not fint the handle of the taskbar. Your current OS may not be supported.

### ISSUE THREAD

**Issue by Redwesty** [ChrisAnd1998/TaskbarX#860]
Every time i start my pc the app doesnt start and give this error
taskbarx: could not fint the handle of the taskbar. Your current OS may not be supported.

Windows 10 Pro 21H1 19043.1387

**Comment by ChrisAnd1998** [comment]
Can you try an older version of TaskbarX? Like 1.6.9.0

**Comment by 1rom11** [comment]
I am having the same problem but I keep on staying on a black screen (I am on my mom's laptop)
I came on here by doing Ctrl + Alt + Del > task manager > new task > chrome
Windows 11 Home 22H2 OS build 22623.1028

**Comment by 1rom11** [comment]
![image](https://user-images.githubusercontent.com/76579908/206577710-b6fb2c5b-993d-4771-91e8-6d7e7fa0fb46.png)
This is a screenshot

**Comment by LandlordTT** [comment]
im having this problem too, i try all defferent metods it all ends up the same way

**Comment by LandlordTT** [comment]
im having the same problem but i got it on win 10, i tought upgrade to win 11 will be the solution then i have the same problem and worse. and i found the solution on my problem, first download taskbar xi for win 11 and go to relase then download 2 aplication one for the taskbar and one for the configurator, then i start the taskbar xi and i click apply. then i open the config again and i uncheck run on startup and stop taskbar xi then i close it and restart my computer. it boot up as fine as new.
my windows version is windows 11 22H2 

![Screenshot 2023-01-26 235739](https://user-images.githubusercontent.com/114121231/214884740-f39b6d87-57bd-41c9-a5d4-13b9babd92e8.jpg)
![Screenshot 2023-01-26 235819](https://user-images.githubusercontent.com/114121231/214884750-a72b84a4-376f-4761-9aba-96dfa830d9ae.jpg)

the screenshot i shown is how my config i setup and work
