### ISSUE TITLE
"You'll need a new app to open this taskbarx link" pop-up on startup

### ISSUE THREAD

**Issue by onlytanmoy** [ChrisAnd1998/TaskbarX#861]
Hiya @ChrisAnd1998 hope you are doing well.
Yesterday I updated to Win 11 and uninstalled TaskbarX, now whenever I start the laptop I get this pop-up.
I checked under Task Manager - Startup, nothing related to TaskbarX there. How do I get rid of this?
![image](https://user-images.githubusercontent.com/48493659/144704942-67a879b1-56ce-42a7-b098-198fa2e031f0.png)

**Comment by ChrisAnd1998** [comment]
@onlytanmoy Here watch this ;) https://www.youtube.com/watch?v=QtvxF1S7Dsw

**Comment by onlytanmoy** [comment]
Thanks mate, that did the trick :)
