### ISSUE TITLE
Multiple Keyboard Input Bug

### ISSUE THREAD

**Issue by ever-blogger** [ChrisAnd1998/TaskbarX#862]
**Describe the bug**
Notification Tray is overlap when you have Multiple Keyboard Input

**To Reproduce**
Keyboard Layout with multiple keyboard input

**Screenshots**
![image](https://user-images.githubusercontent.com/63139255/144717197-a2978d51-daf2-42fc-9916-13197b3315c1.png)

**Desktop (please complete the following information):**
 - OS:  Windows 11
 - Version [e.g. 1909]

**Additional context**

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
