### ISSUE TITLE
Explorer lags whenever using TaskbarX with Rainmeter

### ISSUE THREAD

**Issue by MeowKing5** [ChrisAnd1998/TaskbarX#863]
**The Bug**
Explorer lags whenever using it with rainmeter.

**Steps to reproduce the behavior:**
1. Use the .rmskin file to install the skin
2. Drag windows and notice the choppy dragging lag.
3. Sometimes explorer will freeze for 5-10 seconds

**Expected behavior**
Windows will move normally without the .rmskin

**Operating System**
 - Windows 10 (Build 21H1)

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
