### ISSUE TITLE
When using 'light' system theme, using any style other than default renders the clock and tray icons invisible

### ISSUE THREAD

**Issue by pbakes** [ChrisAnd1998/TaskbarX#866]
**Describe the bug**
Invisible isn't the right word, but when using the light theme, the clock and tray icons are black, so when taskbarx is setting the taskbar to a dark color, those items become close to unreadable. The option to change the tray icon color within taskbarx would be an ideal workaround.

**To Reproduce**
1. Set Windows 10/11 to light mode
2. Set taskbarx to any style besides default (transparent, opaque, blur)
3. Set to any darker color or any opacity

**Expected behavior**
Things seem to behave as expected in light mode, but currently no other option to change tray icon color
![Screenshot 2021-12-11 135532](https://user-images.githubusercontent.com/38716120/145692874-406a6b48-3ef3-4c15-b591-3c95d84ba822.png)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 21H2

**Additional context**
n/a

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
