### ISSUE TITLE
Transparent Gradient style gets kicked down to Default after switching users and then switching back

### ISSUE THREAD

**Issue by stevemagruder** [ChrisAnd1998/TaskbarX#867]
**Describe the bug**
I have the TaskBarX style set to Transparent Gradient. When I switch to another Windows account and come back to the one running TaskBarX (the admin account), the style has been somehow kicked down to Default. I go into the Configurator and see the style is still set to Transparent Gradient, so I "Restart TaskBarX" and this style gets restored.

**To Reproduce**
Steps to reproduce the behavior (assuming you've already been running TaskBarX with the style set to Transparent Gradient):
1. Switch to another user in Windows and sign into their account.
2. Sign off and sign back in to your regular account running TaskBarX.
3. You'll see the TaskBarX showing with the Default style.
4. Open TaskBarX Configurator - you'll see the style still set to Transparent Gradient.
5. Click the Restart TaskBarX button and the style becomes Transparent Gradient again.

**Expected behavior**
I expected that when I switched back to my regular account, TaskBarX would be showing with the Transparent Gradient style instead of having been kicked down to Default.

**Screenshots**
I think the above covers it but if a screenshot would help, please ask for it.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 21H2 Build 19044.1387 (was happening with earlier versions too)

**Additional context**
This problem has been happening for some time, not just with the current version 1.7.3.

**Comment by stevemagruder** [comment]
Note this isn't the Restart issue separately reported. TaskBarX loads with the Transparent Gradient style I've set after every restart.

**Comment by ChrisAnd1998** [comment]
Please try the pre-release 1.7.4.0
