### ISSUE TITLE
TaskbarX is not saving the changes on features done on Configuration.exe, "extra" & "Style" features specifically.

### ISSUE THREAD

**Issue by Narendhiran13** [ChrisAnd1998/TaskbarX#869]
I have modified the features in "TaskbarX Configuration" but the changes are not reflecting after restarting the computer, that means the changes are stored in the "TaskbarX Configuration" file but it is not reflecting when I execute "TaskbarX.exe".

Update the changes to the "TaskbarX" automatically so that I don't have to open "Taskbar X.exe" unnecessarily.
![image](https://user-images.githubusercontent.com/43815101/147378290-414f38a0-3423-4932-a1a1-fb95d5922da2.png)
The "extra" & "Style" features specifically are not reflecting unless I click "Restart TaskbarX/ Apply" in the COnfiguration.exe. 
![image](https://user-images.githubusercontent.com/43815101/147378301-e7ff5565-2e5b-404b-b9c9-3a4a199b475d.png)

Windows 10

**Comment by ChrisAnd1998** [comment]
@Narendhiran13 TaskbarX should be run with parameters. The configurator creates a taskschedule automatically but if that does not work use the generate button. Then create a manual shortcut using the text in the big textbox.
![Untitled](https://user-images.githubusercontent.com/50437199/147380749-4869411b-9e51-4d22-9aa9-08690d82689f.png)
.
