### ISSUE TITLE
💡| Possible feature requests

### ISSUE THREAD

**Issue by ChrisAnd1998** [ChrisAnd1998/TaskbarX#870]
#25 Move Start Button, Search, Cortana, and Task View to center too Feature Request
#33 Add a Recycling Bin to the taskbar with the right-click menu options of the desktop icon
#41 Only show taskbar background on icon/menus Feature Request (segments)

**Comment by Mr-Anonymous75** [comment]
You forgot #726. And #629.

**Comment by Droyk** [comment]
I mean yeah less clutter but those purple tickmarks aren't helping user need to clearly see if they features they suggested got implemented or not so I think adding a checkbox 

- [ ] right before the said feature would do it!

**Comment by Droyk** [comment]
I mean yeah less clutter but those purple tick marks aren't helping. users need to clearly see if the features they suggested got implemented. so I think adding a checkbox 

- [ ] right before the said feature would do it! 

and I don't know if putting all the feature requests here and closing all of their respective issues is a great Idea I mean it seems counterproductive. users will start discussing every kind of feature request on here wouldn't it make more of a mess it will be hard to separate which request they are talking about!  
I think while making a feature request list is a good productive idea but closing the request threads will be making it counterproductive!

**Comment by Droyk** [comment]
I mean yeah less clutter but those purple tick marks aren't helping. users need to clearly see if the features they suggested got implemented. so I think adding a checkbox 
- [ ] right before the said feature would do it! 

and I don't know if putting all the feature requests here and closing all of their respective issues is a great Idea. I mean it seems counterproductive. users will start discussing every kind of feature request on here wouldn't it make more of a mess it will be hard to separate which request they are talking about!  
I think while making a feature request list is a good productive idea but closing the request threads will be making it counterproductive!

**Comment by ChrisAnd1998** [comment]
@Mr-Anonymous75 Added 😉

**Comment by ChrisAnd1998** [comment]
@Droyk Thank you for your suggestions. I will definitely do a better markup here. There is also a discussion section/tab. Maybe that's even better.. Have to look into that.
