### ISSUE TITLE
small gap in the lower right corner

### ISSUE THREAD

**Issue by jogang0304** [ChrisAnd1998/TaskbarX#871]
**Describe the bug**
There is a small gap (1 -2 pixels) in the lower right corner of taskbar.

Click right bottom pixel. Nothing happens

**Expected behavior**
desktop is shown

 - OS: Windows 10 Home 21H2
 - TaskbarX: 1.7.3.0 Microsoft store

**Comment by Double-A-92** [comment]
This was already reported in several old issues, that were just closed for clean-up reasons.
I can also confirm that the issue still persists in 1.7.4.0.

The old issues:
- #717
- #701

**Comment by ChrisAnd1998** [comment]
This will now be closed. #717 is now open.
