### ISSUE TITLE
TaskbarX configurator locks up after first edit

### ISSUE THREAD

**Issue by JuanMa-78** [ChrisAnd1998/TaskbarX#872]
**Describe the bug**

When opening taskbarX configurator for the second time and attempting to apply any changes, the app softlocks and resets to default settings. I am then no longer able to change any settings whatsoever unless I uninstall and reinstall taskbarX

**To Reproduce**
Open taskbarx manager and change any setting
Close
Reopen and apply new changes

**Expected behavior**
Changes should apply and not reset to default

**Desktop (please complete the following information):**
 Windows 10
Version 21H2

I've uninstalled and reinstalled a couple times now (resetting the PC between installs); no deviation from previously mentioned behaviour

**Comment by ChrisAnd1998** [comment]
@JuanMa-78 I can't reproduce this issue.. Can you export the Task Schedule for me? So I can import it.
![Untitled](https://user-images.githubusercontent.com/50437199/147401422-54141857-7617-441f-8f53-9438ef4a8155.png)
