### ISSUE TITLE
All the animation styles other than "none" take multiple steps to center automatically

### ISSUE THREAD

**Issue by volo34** [ChrisAnd1998/TaskbarX#875]
**Describe the bug**
From the latest update, when the bar centers automatically it goes too much to the left and then takes multiple steps to center.
If the animation is set to none this doesn't happen

**To Reproduce**
Every time TaskbarX starts, I restart it manually or when a new app is opened this happens.

**Expected behavior**
It should center with one step, like all the previous updates

**Screenshots**
GIF: https://imgur.com/a/HqHjwJe

**Desktop:**
 - OS: Windows 10
 - Version: 21H2 (build SO 19044.1415)
 - Monitor: 2560x1080 (21:9 Aspect Ratio)

**Comment by ChrisAnd1998** [comment]
@volo34 What version are you using now? 1.7.4.0 or 1.7.5.0.
Which version did work for you? Then I can go through the change logs.

**Comment by volo34** [comment]
@ChrisAnd1998 I'm currently using 1.7.4.0, updated yesterday through MS Store. I don't know what was the previous version, It never gave me this problem, so any previous MS Store release works

**Comment by volo34** [comment]
> @ChrisAnd1998 I'm currently using 1.7.4.0, updated yesterday through MS Store. I don't know what was the previous version, It never gave me this problem, so any previous MS Store release works

The update 1.7.5.0 just arrived and the problem is still present

**Comment by ChrisAnd1998** [comment]
How about this? I was able to reproduce it when I only use 1 monitor. Pretty sure it's fixed now.
https://github.com/ChrisAnd1998/TaskbarX/releases/tag/1.7.6.0

**Comment by volo34** [comment]
> How about this? I was able to reproduce it when I only use 1 monitor. Pretty sure it's fixed now. https://github.com/ChrisAnd1998/TaskbarX/releases/tag/1.7.6.0

It's fixed, thanks for the immediate response!
