### ISSUE TITLE
Wont Fully Uninstall from Windows

### ISSUE THREAD

**Issue by CriminalSword30** [ChrisAnd1998/TaskbarX#876]
Hello, i have had taskbarx for a little bit and i found that i actually preferred using the standard windows version. when i try uninstal it, whenever i restart and after fully uninstalling everything and using any way possible (including through the config app) it will remind me to "you will need a new app to open "TaskbarX"" and then tells me that i have to install it through windows. what should i do to get it FULLY uninstalled so that it wont keep popping up.

![image](https://user-images.githubusercontent.com/96760979/147530325-a4d0e9b5-490d-40e2-9244-f8f1d6c64b3f.png)

**Comment by ChrisAnd1998** [comment]
@CriminalSword30 Here please follow this video 😉
https://www.youtube.com/watch?v=QtvxF1S7Dsw
