### ISSUE TITLE
How to Update the Rainmeter version of TaskbarX ?

### ISSUE THREAD

**Issue by PhoenixCODE2322** [ChrisAnd1998/TaskbarX#877]
Other than installing the rainmeter version everytime a update comes and reconfiguring the .ini file is there other way ?

**Comment by ChrisAnd1998** [comment]
@PhoenixCODE2322 Instead of reinstalling you can also only replace the Release folder. Keeping the ini.
Or make a copy of your settings and paste them back when updated.
