### ISSUE TITLE
Tray icon cannot be hidden in Windows 11

### ISSUE THREAD

**Issue by dror-sullam** [ChrisAnd1998/TaskbarX#878]
I really like the style of macOS/Gnome, so I tried to hide the whole right area of the taskbar, but it was not possible with other programs, so I tried it with this one. Although it seems that there are options to turn off the right area, the tray icon won't hide, no matter what I do.
Also, I really hope that some program would implement a way to hide the right area temporarily (hopefully with a smooth on/off animation), and show it on hover, because it is pretty essential in my opinion, and I only wanted to hide it temporarily, in order to make Windows a little cooler.

1. Go to 'Extra'
2. Click on 'Hide Primary Tray Area'/'Hide Secondary Tray Area'
3. Tray icon (the up arrow icon) stays on the taskbar

I expected the whole right area to be hidden (including the tray icon)

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/38787352/147705108-9cd87497-e995-4659-ae4c-8c42eca2a640.png">

 - OS: Windows 11
 - Version: 21H2

**Comment by ChrisAnd1998** [comment]
I'll look into this. Maybe this is something for you ;)
https://github.com/ChrisAnd1998/TaskbarXI

**Comment by dror-sullam** [comment]
Ok thanks, I'll try that...
