### ISSUE TITLE
Fake TaskbarX Website

### ISSUE THREAD

**Issue by Sergij-SApcPro** [ChrisAnd1998/TaskbarX#879]
Hi, 

This may not be an issue, but I like to inform you that there's a fake TaskbarX site: https://taskbarx.net/.
It comes first on DuckDuckGo's search results so that might be a problem...
Can you do something about this, maybe somehow inform people about this?

Thanks in Advance.

**Comment by ChrisAnd1998** [comment]
@Sergij-SApcPro I am aware of this website and sadly it ranks better on DuckDuckGo. I have already reported this website but no response.. The only thing I can do is do some SEO so my website will rank first on DuckDuckGo.

Thank you!
