### ISSUE TITLE
"Line" in taskbar when using blur style

### ISSUE THREAD

**Issue by def-init** [ChrisAnd1998/TaskbarX#880]
**Describe the bug**
Whenever I use the blur style, it leaves an obnoxious "Line" in the bottom of the taskbar. This does not happen with any of the other styles. Picture for reference:
![afbeelding](https://user-images.githubusercontent.com/70064551/147851120-a571610b-818d-44e2-a972-647e2338b80d.png)

**To Reproduce**
1. Go to 'TaskbarX Configurator'
2. Click on 'Blur'
3. You will see it.

**Expected behavior**
I expected the taskbar to not show the "Line" it's really annoying and kinda ruins the clean style of the taskbar.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Version: 21H2

**Comment by ChrisAnd1998** [comment]
@def-init What line?! I don't see it.. Do you have a better screenshot?
