### ISSUE TITLE
Cant find TaskbarX Configurator.exe anywhere

### ISSUE THREAD

**Issue by TheFrantikOne** [ChrisAnd1998/TaskbarX#881]
Hello there,

So I downloaded TaskbarX about a year ago and everything was perfect up to, I believe a few months ago(not entirely sure when it was)
Anyways, I can't find the TaskbarX configurator any longer. I've gone into the zip file and cannot find any .exe files, I've even tried downloading and reinstalling the program, nothing has worked.

It might be a small and easy issue to fix but I haven't been able to find anything similar, I'm kinda lost, hope someone's got a solution.

**Comment by Droyk** [comment]
maybe the antivirus has quarantined it thinking it's a virus. turn off the antivirus real-time protection and redownload the file.

**Comment by Kobe3koningen** [comment]
i have the same problem, i already tried putting of my anti virus and stuff.
