### ISSUE TITLE
TaskbarX windows 11 not working when turned off

### ISSUE THREAD

**Issue by KK-Designs** [ChrisAnd1998/TaskbarX#882]
**Describe the bug**
Whenever I stop TaskbarX it shows this half-filled half high taskbar. I can't turn this application off now. See the screenshot below.

**To Reproduce**
1. Use Windows 11
2. Open the configurator
3. Click on 'Stop TaskbarX'
4. See the error

**Expected behavior**
It should revert to the normal default taskbar.

**Screenshots**
Running TaskbarX (look at taskbar): 
![image](https://user-images.githubusercontent.com/71038229/148140461-22ee870c-eb97-4918-9fdf-001b2360f4ee.png)

Stopped running TaskbarX: 
![image](https://user-images.githubusercontent.com/71038229/148140525-30c962d2-68bb-4a67-98d2-b7bf7e8e68c4.png)

**Desktop**
 - OS: Windows 11
 - Version: 21H2

**Additional context**

**Comment by ChrisAnd1998** [comment]
@KK-Designs TaskbarX is not supposed to be used on Windows 11. Stop TaskbarX and remove it's files.
I am working on TaskbarXI which is build for Windows 11. It is very early though..
https://github.com/ChrisAnd1998/TaskbarXI

**Comment by KK-Designs** [comment]
This issue occurs when i uninstall TaskbarX

**Comment by ChrisAnd1998** [comment]
Please restart your PC or Restart Explorer.exe using task manager.
![Untitled](https://user-images.githubusercontent.com/50437199/148263735-02d5fb6e-2fd2-47ff-8eea-46a582aa6ab2.jpg)
r

**Comment by KK-Designs** [comment]
Thanks, it works now!

**Comment by ChrisAnd1998** [comment]
Great!!
