### ISSUE TITLE
Request: enable multiple columns for running application icons if possible

### ISSUE THREAD

**Issue by me21** [ChrisAnd1998/TaskbarX#883]
When the taskbar is horizontally oriented, e.g. at the top or bottom of the screen, Windows can add extra rows of icons when there are too many running applications. But if the taskbar is at the left or right side, there's only a scrollbar no matter how wide the taskbar is.
Is it possible to alter this behavior somehow, to add extra columns for running applications in vertical taskbars?

![example](https://user-images.githubusercontent.com/807120/148730124-78b369e6-dd05-4342-98f6-0c25d3d988ee.png)

As you can see, running applications are displayed in single column only.

**Comment by Droyk** [comment]
How did you make your running icons look so small just like quick launch Icons 
Mine looks like this
![image](https://user-images.githubusercontent.com/15848350/149010725-a89c0cad-5ee3-4551-84bb-f92b3ea0cad1.png)
As you can see quick launch icons are much smaller than the running icons! 
so how did yours get so small?

**Comment by me21** [comment]
There's an option in Windows taskbar settings for this.
