### ISSUE TITLE
Doesn't play nice with RoundedTB anymore

### ISSUE THREAD

**Issue by privacyguy123** [ChrisAnd1998/TaskbarX#884]
**Describe the bug**
TaskbarX and RoundedTB won't run together anymore 

**To Reproduce**
Open both programs together

**Expected behavior**
I expect to see rounded edges on my TaskbarX

**Screenshots**
Sorry I uninstalled.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Version 21H2

**Comment by CrazySaft** [comment]
Why don't you just set the corner radius in taskbar x Settings?
