### ISSUE TITLE
doesnt center properly.

### ISSUE THREAD

**Issue by breddd** [ChrisAnd1998/TaskbarX#886]
**Describe the bug**

the bug is that when i click on taskbar x to start it up it doesnt center properly and goes all the way to the right side and goes underneath the icons on right side (wifi, battery, bluetooth, etc..) and it can also just go the right side randomly without me doing anything, BUT when i opened the configurator and actually fixed the position allignment to my liking (-300 px on primary display) and clicked "apply"  IT WORKS IN THE CONFIGURATOR WHEN I CLICK APPLY but not when i execute the normal taskbar x app.

**To Reproduce**
1. Go to 'TaskbarX.exe'
2. Click on it
3. it wont center properly 
**Expected behavior**

its just supposed to center the taskbar normally in the middle not all the way to the right side.

**Screenshots**
![bug](https://user-images.githubusercontent.com/90939027/149465909-9edfb928-ac61-480c-a3d3-ac6e6fe23619.png) (bad)

this is what its supposed to look like
![image](https://user-images.githubusercontent.com/90939027/149466227-ec8f5e09-1382-4fb9-9c41-fd3ff68e505c.png) (good)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Version {21H2}

**Additional context**
i dont have secondary display.

**Comment by ArranPlayz** [comment]
Go to the TaskbarX configuration startup menu and click generate and copy the link
![image](https://user-images.githubusercontent.com/88970661/149563284-dd895fe6-663e-4e91-ab61-f38e134c0de8.png)

Wherever you want the shortcut to be, (even the windows startup folder if you want) Right click and hover over "New" then "New Shortcut".
![image](https://user-images.githubusercontent.com/88970661/149563686-a5b43a73-ae75-488f-8822-52d91ff92f63.png)

Then paste the link you copied earlier into the text box and apply
![image](https://user-images.githubusercontent.com/88970661/149563939-9953bb7a-13f4-4818-b1a5-3c3ff15958cd.png)

Now open the shortcut - Problem solved
