### ISSUE TITLE
The arrow-icons of the toolbars are not highlighted, when moving the cursor over them.

### ISSUE THREAD

**Issue by nexusV2** [ChrisAnd1998/TaskbarX#887]
**Describe the bug**
The arrow-icons of the toolbars are not highlighted, when moving the cursor over them.

**To Reproduce**

1. Go to taskbar
2. Mouseover on arrow-icons of the toolbars
3. See error
![grafik](https://user-images.githubusercontent.com/24851823/149615127-5967ca26-c5dc-4195-a05c-dd17064ec306.png)

**Expected behavior**

Highlight Arrows on mouseover
![grafik](https://user-images.githubusercontent.com/24851823/149615159-8c328cf8-bfa2-4658-8cdd-87be0b6ecd0e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version [21H1]
 - Build [19043.1466]

**Additional context**
#824

**Comment by ChrisAnd1998** [comment]
I am sorry to tell you that I cant fix this. TaskbarX disables the redraw of the taskbar to prevent the taskbar from flickering. This can only be fixed by enabling the redraw for the taskbar but that will open up a lot of bugs...
