### ISSUE TITLE
TaskbarX not properly uninstalled because improper update

### ISSUE THREAD

**Issue by bagiosw** [ChrisAnd1998/TaskbarX#891]
So I've been using this for months (not the store version) and decided to update a few days ago. And I did wrong when I updated the TaskbarX, I didn't stop it first, I think I deleted the files and re-extract the files, and then re-run it. So the default state (when I click "Stop TaskbarX" or when I click default style) is the blur style. Now I decided to uninstall it, and it stuck with the blur transparency. How to fix this issue?

Screenshots
![Screenshot_24](https://user-images.githubusercontent.com/15670237/149894599-b1a8824b-535e-43e1-9ed7-b3aea415ff4a.png)

 - OS: Windows 10 20H2
 - Version 19042

**Comment by ChrisAnd1998** [comment]
Please follow this: https://www.youtube.com/watch?v=Fj-gSF_nEyo
