### ISSUE TITLE
TaskbarX configurator crashing no matter what version

### ISSUE THREAD

**Issue by EvenMasait** [ChrisAnd1998/TaskbarX#892]
so I've been trying to make my taskbar transparent for a long time and no matter what I did it did not work I was happy to find out my brother using this application and he suggested it for me to use so the problem is explained in the title but to be sure I will explain it here every time i try to open the taskbarx configurator it crashes i have tried to install various versions of the same app and none of them seem to work any help would be appreciated.

**Comment by ChrisAnd1998** [comment]
Make sure you have .NET Framework 4.8 installed. If it still does not work i don't know what could cause this issue.
