### ISSUE TITLE
Move start button to middle too

### ISSUE THREAD

**Issue by github2099** [ChrisAnd1998/TaskbarX#907]
With current configuration, only the icons can be moved to the middle. I'd like to have the start button be in the middle too.

**Comment by Kazlehoff** [comment]
You can do this. Kind of.

Use the start button tab in the configurator to make a start button icon and place it on the task bar. then use the option under extras to hide the start button on your main and secondary monitors.

![image](https://user-images.githubusercontent.com/52207847/154184981-a8e47c5f-6c6f-48c4-9c80-13dcd39d1857.png)

**Comment by fsnhljz** [comment]
how to find stat button icon？i want default icon

**Comment by Kazlehoff** [comment]
https://github.com/ChrisAnd1998/TaskbarX

Scroll down

![image](https://user-images.githubusercontent.com/52207847/155232666-2543e4ef-bd77-4800-9f68-5aa323092384.png)

**Comment by Kazlehoff** [comment]
or if you must have the EXACT SAME ICON (why? makes no sense lol) do a google image search for it, then use a png to ico converter. none of this is hard my dude.

**Comment by Kazlehoff** [comment]
Here, Maximum hand-holding
https://mega.nz/file/Cc0FjKYJ#c5Rma1QsB5zKFQojKQLn5mgpKfuVRVGlzEeE7Tl5LNc

**Comment by Necrowerx** [comment]
On multiple monitor setups however, the custom Start button shortcut trick will only open the Start Menu on the primary display, regardless of which display/taskbar it was clicked in.

**Comment by Kazlehoff** [comment]
> 

all i can suggest is upgrade to 11 if you want 11's featureset *shrug*

Like im not the author, but their non-response here makes it seem like this may be a non-issue.

(who clicks the start button... theres a keyboard button for that)

**Comment by ChrisAnd1998** [comment]
The start button constantly wants to move back to its origin. This makes the taskbar flicker / bug a lot. That's why there is a work around as @Kazlehoff explained.

**Comment by Bozic421** [comment]
> The author provides some icons on the main page.
> 
> https://github.com/ChrisAnd1998/TaskbarX
> 
> Scroll down
> 
> ![image](https://user-images.githubusercontent.com/52207847/155232666-2543e4ef-bd77-4800-9f68-5aa323092384.png)
> 
> Ive also made my own icon (as i did not realize the author supplied) and have uploaded it here: https://mega.nz/file/Cc0FjKYJ#c5Rma1QsB5zKFQojKQLn5mgpKfuVRVGlzEeE7Tl5LNc

Hey I've done this but after I restart my pc the icon just goes away instead I have this 
![image](https://user-images.githubusercontent.com/81369341/172521047-6533b76a-2be8-4ada-b09f-cae56a5555ba.png)
a white box can you help?

**Comment by Kazlehoff** [comment]
Did you delete or move the icon file?
