### ISSUE TITLE
FalconX doesn't recognize apps on their start

### ISSUE THREAD

**Issue by peterreibel** [ChrisAnd1998/TaskbarX#91]
When starting an app FalconX doesn't center the taskbar activities on my 2 monitor setup.

It rearranges them on both screens when moving a window from one screens to another.

**Comment by peterreibel** [comment]
> When starting an app FalconX doesn't center the taskbar activities on my 2 monitor setup.
> 
> It rearranges them on both screens when moving a window from one screens to another.

v1.3.4.0
It always happens on my secondary screen*. The main screen works flawlessly.
*I have a laptop setup with 2 identical external monitors and the laptop screen turned off.

![FalconX error](https://user-images.githubusercontent.com/42697505/70722272-43e80380-1cf7-11ea-8d01-8b7bf4a82218.gif)

**Comment by ChrisAnd1998** [comment]
The issue here is that you have setup the taskbar to only show the windows on that particular screen.
FalconX doesn't seem to work with that setting and i have not found a way to fix that yet.

**Comment by peterreibel** [comment]
Chris, thanks for clarifying!

FalconX rocks!
