### ISSUE TITLE
Is it possible to add the ability to set the height (width) of the taskbar？

### ISSUE THREAD

**Issue by chwt163** [ChrisAnd1998/TaskbarX#917]
I like a narrower taskbar, but Microsoft's own narrow taskbar setting will make the icons smaller. There is a small software called "7+ Taskbar Tweaker" that can set a narrow taskbar without making the icons smaller. I hope TaskbarX This function can also be achieved. 
![屏幕截图 2022-02-27 092515](https://user-images.githubusercontent.com/70951194/155864868-5cc03e97-c898-43a1-a699-e7476d124d21.png)

**Comment by ChrisAnd1998** [comment]
Sadly TaskbarX does not have that kind of access to the taskbar. So this wont be possible.
