### ISSUE TITLE
Taskbar Segments not working as intended

### ISSUE THREAD

**Issue by HideOnFluff** [ChrisAnd1998/TaskbarX#926]
**Description**
Taskbar Segments is cutting the taskbar in weird spots, first it cut off the start menu logo and half of the explorer icon, and now when I tried to capture that behaviour on video it went even worse.

**To Reproduce**
1. Open Taskbar X configurator
2. Click on 'Style'
3. Check ' Taskbar Segments'
4. Press Apply
5. See error

**Expected behavior**
Get my taskbar to show my taskbar pinned apps on a cropped version of itself, similar to MacOS' dock.

**Screenshots**
![First attempt](https://i.imgur.com/oBTJKu7.png)

[second attempt (Video)](https://i.imgur.com/WE8cnfE.mp4)

**Desktop:**
 - OS: Windows 11 Beta Channel
 - Version: 21H2 (Build 22000.556)

**Additional context**
I've tried this app some months ago and it worked just fine, I'm not sure what's wrong, I don't have any other app modifying the taskbar behaviour so I don't see any reason for this to happen.

**Comment by ChrisAnd1998** [comment]
TaskbarX is not made for Windows 11. Please try TaskbarXI ;)
