### ISSUE TITLE
Windows 11 Beta latest 22h2 breaks taskbarx

### ISSUE THREAD

**Issue by anirudh-pixel** [ChrisAnd1998/TaskbarX#931]
Same as title, before update everything was fine, now even manually starting and changing values and applying doesn't do anything in build version below
Edition	Windows 11 Enterprise
Version	22H2
Installed on	‎24-‎03-‎2022
OS build	22581.1
Experience	Windows Feature Experience Pack 1000.22581.1.0
Please fix ASAP

**Comment by obsessedlady** [comment]
Can confirm, not working in the last update

**Comment by fluoroom** [comment]
Can confirm too, build 22581 of Win 11 Pro makes the taskbar solid and TaskbarX won't work.

**Comment by anirudh-pixel** [comment]
> Can confirm too, build 22581 of Win 11 Pro makes the taskbar solid and TaskbarX won't work. A similar app, TranslucentTB also breaks.

TranslucentTB has been broken since 22563 (about from a month back). Taskbarx broke only now. his is all due to the new tablet-optimized taskbar

**Comment by failurejunky** [comment]
not working in 22581.1 OS build

**Comment by cingicanga** [comment]
same issue

**Comment by sylveon** [comment]
> TranslucentTB has been broken since 22563 (about from a month back). Taskbarx broke only now. This is all due to the new tablet-optimized taskbar

To be clear, both have been broken since build 22563. It's just that the new taskbar was A/B'd to tablets only until build 22581, which enabled it for everybody

**Comment by ChrisAnd1998** [comment]
TaskbarX is not made for Windows 11. TaskbarXI will be but does not support taskbar styling yet.
