### ISSUE TITLE
TaskbarX not working in window 11 after upgraded to version 22H2

### ISSUE THREAD

**Issue by MMAH17** [ChrisAnd1998/TaskbarX#932]
**I wanted to make my taskbar transparent, but the latest version of taskbarX not compatible with Window 11 version 22H2
P/S: TaskbarX version is 1.7.6.0 ( purchase from microsoft store )**

**To Reproduce**
1. Upgrade to Window 11 22H2 version
2. Open TaskbarX
3. Apply changes of any setting
4. Not applying changes to the taskbar

**Expected behavior**
TaskbarX to take effective of setting preference on the window taskbar

**Screenshots**
Please refer to attachment
![issue](https://user-images.githubusercontent.com/102423033/160244340-c57a6a35-89ce-428d-ad90-f778b911fde3.png)
![taskbarX](https://user-images.githubusercontent.com/102423033/160244342-2a52374c-29b8-468d-bece-1ba714668d24.png)
![WindowVer](https://user-images.githubusercontent.com/102423033/160244343-5641a697-4715-49bf-99ee-174a95b77ff0.png)

**Desktop (please complete the following information):**
 - OS: Window 11 Pro
 - OS build: 22581.00
 - Version: 22H2

**Additional context**
I have a second laptop which is Window 11 version 21H2, taskbarX is working fine ( ver 1.6.9.0 )

**Comment by themoonmeetsthesun** [comment]
Afaik, TaskbarX doesn't work on windows 11 because of the new taskbar. I would recommend you to use translucent tb for now.

**Comment by MMAH17** [comment]
> Afaik, TaskbarX doesn't work on windows 11 because of the new taskbar. I would recommend you to use translucent tb for now.

Have try trans tb. Unfortunetly, it also not able to compatible with the newest window version

**Comment by themoonmeetsthesun** [comment]
> > Afaik, TaskbarX doesn't work on windows 11 because of the new taskbar. I would recommend you to use translucent tb for now.
> 
> Have try trans tb. Unfortunetly, it also not able to compatible with the newest window version

That means that it's a windows' specific issue and Microsoft needs to fix it soon.

**Comment by ChrisAnd1998** [comment]
TaskbarX is not made for Windows 11.. TaskbarXI is but does not support styling yet.

**Comment by themoonmeetsthesun** [comment]
> TaskbarX is not made for Windows 11.. TaskbarXI is but does not support styling yet.

Do you have any idea why multiple apps like translucent tb are also broken?
