### ISSUE TITLE
TaskbarX is not working from last few days, Might be after latest Windows 11 update.

### ISSUE THREAD

**Issue by rjgm774** [ChrisAnd1998/TaskbarX#936]
TaskbarX is not working from last few days, Might be after latest Windows 11 update.

I have tried unloading , Loading Skin and even tried uninstalling-installing. I also tried restarting the Machine it didn't help too. 
So Writing issue over here, you can work on fix.

My Machine:
Windows 11 Pro (Beta Channel)
Version: 22H2
Evaluation Copy. 
Build 22581.100 ni_release.220318-1623

**Comment by junesties** [comment]
Yes, it seems that this update screws a lot of taskbar tweekings like translucenttb or TaskbarX. WE'll have to wait for the Devs. MS won't change anything.

**Comment by rjgm774** [comment]
> Yes, it seems that this update screws a lot of taskbar tweekings like translucenttb or TaskbarX. WE'll have to wait for the Devs. MS won't change anything.

Thanks for your comment

**Comment by ChrisAnd1998** [comment]
TaskbarX is not made for Windows 11. Please try my other project TaskbarXI.

**Comment by junesties** [comment]
> > TaskbarX is not made for Windows 11. Please try my other project TaskbarXI.
> 
> Could you please provide link of that ? I have googled and visited your site and not found TaskbarXI .

Just go up in his github (or use this: https://github.com/ChrisAnd1998/TaskbarXI)
