### ISSUE TITLE
Icons not centered after updating windows

### ISSUE THREAD

**Issue by getBoolean** [ChrisAnd1998/TaskbarX#940]
**Describe the bug**
After updating windows 10 today, the task bar icons are not centered, and opening TaskbarX Configurator and pressing restart does not fix it (sometimes icons were not centered on startup for me in the past, and that fixed it)

**To Reproduce**
1. Login to windows
2. See that icons are not centered
3. Open taskbarX configurator
4. Press "Restart TaskbarX" button
5. See that icons are still not centered

**Expected behavior**
Icons should be centered

**Screenshots**
![NVIDIA_Share_ZtVkv2RP92](https://user-images.githubusercontent.com/19920697/163289322-2c4a30a2-ef77-43d9-bcfc-10eab118f871.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version [21H2 build 19044.1645](https://support.microsoft.com/en-us/topic/april-12-2022-kb5012599-os-builds-19042-1645-19043-1645-and-19044-1645-548cc67c-7f12-46fd-878e-589ba81ac2f5)

**Additional context**
These two updates were installed today right before I started having this problem:
- https://support.microsoft.com/en-us/topic/april-12-2022-kb5012117-cumulative-update-for-net-framework-3-5-and-4-8-for-windows-10-version-20h2-windows-server-version-20h2-windows-10-version-21h1-and-windows-10-version-21h2-7214b844-c002-49e4-9962-773e964ff737
- https://support.microsoft.com/en-us/topic/april-12-2022-kb5012599-os-builds-19042-1645-19043-1645-and-19044-1645-548cc67c-7f12-46fd-878e-589ba81ac2f5

**Comment by breggman** [comment]
I'm having the same issues after installing the identical updates (KB5012117 & KB5012599) on the same Windows 10 21H2 build 19044.1645.

Only difference is that I am on a laptop, Acer Aspire 5.

**Comment by parnavh** [comment]
I was having the same issue, updated TaskbarX to the latest version and it's fixed

**Comment by getBoolean** [comment]
I can confirm that updating to prerelease 1.7.7.0  fixed the issue

**Comment by sergeypugachov** [comment]
I have the same issue after update on 1.7.2. Update to 1.7.6 fixed the issue.

**Comment by getBoolean** [comment]
I'm closing this issue as it seems to have been fixed in >=1.7.6
