### ISSUE TITLE
RDC bug

### ISSUE THREAD

**Issue by bubufofo** [ChrisAnd1998/TaskbarX#99]
When using remote desktop connection the bastard becomes unusable after the resolution changes to match phone resolution.

**Comment by bubufofo** [comment]
https://imgur.com/a/nCkL0NC

**Comment by Martin5001** [comment]
Calling such a piece of software "the bastard"... :D

**Comment by ChrisAnd1998** [comment]
Does this still happen in TaskbarX 1.5.1.0?
