### ISSUE TITLE
Unable to run TaskbarX with ExplorerPatcher

### ISSUE THREAD

**Issue by aagha** [ChrisAnd1998/TaskbarX#997]
**Describe the bug**
I have ExplorerPatcher running and have the Taskbar style set to Win11.

I'm trying to maintain the look of Win11, but have opened apps centered in the task bar.

When I run TaskbarX (Configurator), setting up my taskbar style settings (Blur) works fine, but the task bar does not center.

**To Reproduce**
1. Install Win11
2. Install ExplorerPatcher and set the Taskbar style to Win11
3. Open TaskbarX Configurator and set the Style to Blur and the Position to check only "Revert to zero beyond Tray"
4. Click Apply

**Expected behavior**
The Win11 styled task-bar items look as follws:
- Start button on left hand side
- Open window icons are centered

**Screenshots**
![image](https://user-images.githubusercontent.com/5522103/189756016-8cc314c0-e099-4a79-bce2-2608865e5156.png)

**Desktop (please complete the following information):**
 - OS: Win 11
 - Version 21H2 (Build 22000.918)

**Additional context**

**Comment by ChrisAnd1998** [comment]
@aagha The position features don't work with the Windows 11 taskbar. If you have Explorer Patcher installed you can right click on the taskbar and hit Properties. This will open the Expolorer Patcher settings window. In the settings window you can change the Taskbar style option to Windows 10. After that hit Restart File Explorer. Now TaskbarX should work again.

![image](https://user-images.githubusercontent.com/50437199/194021674-053a5558-76a9-41a5-af5f-9c672cec2dc0.png)
